cfengine/core

tests/load/lastseen_threaded_load.c

To avoid stale processes when test fails, relevant ticket is Redmine#6907.

Child should exit if parent is dead.

---

libpromises/generic_agent.c

Fixes from a branch I was working months back - centered around internal directory checks.
Best to review each commit.

Tightened logic

---

cf-monitord/mon_temp.c

Most important is the added support for current Linux distributions.

Improvements and fixes for monitoring of CPU temperature

---

cf-agent/verify_interfaces.c
cf-agent/verify_networks.c
libenv/sysinfo.c
libutils/buffer.c

This is a first bunch of fixes for some real errors which were reported by the static code analyser cppcheck.

Fix some errors (all reported by cppcheck)

---

cf-agent/verify_files.c
tests/acceptance/10_files/10_links/delete_dangling_symlink.cf

Redmine #6582: Fix deletion of dangling symlinks

---

tests/acceptance/dcs.cf.sub
tests/acceptance/testall

Right now all the fields form test_meta bundle are parsed and added to the test results xml file. This file is then accessible while Jenkins is done with building and new test related fields are included in QA dashboard.

testall and friends updates

---

libpromises/dbm_lmdb.c

This has been a problem in the past that often goes unnoticed and can
lead to database corruption or hangs.

Implement assertion when mixing cursors with other transactions.

---

tests/acceptance/dcs.cf.sub
tests/acceptance/testall

Qa testall 3 6

---

tests/acceptance/10_files/10_links/select_file_by_symlink_target.cf
tests/acceptance/10_files/10_links/select_file_by_type.cf

These tests test that files can be selected by type and by link target.
Ref: https://dev.cfengine.com/issues/6878

Add: File selection acceptance tests

---

tests/acceptance/README

I always have to hunt down the recommendation. This makes it easier to find for everyone.

Add: Rule of thumb for test skipping/suppression/failing

---

cf-agent/files_editline.c

MatchRegion no longer relies on a 4k buffer

---

libpromises/storage_tools.c

Caused by overflow if there is more than 2GB available. off_t is
verified to be only 32 bits on HPUX. There is way more than 2GB
available on our test server, so most likely this passed earlier only
because it wrapped around multiple times and got back to the positive
side.

Fix intermittent test failure in filesystem tests on HPUX.

---

Makefile.am
m4/tar.m4
tests/acceptance/Makefile.am

Accompanies [buildscripts pull request 50](https://github.com/cfengine/buildscripts/pull/50).

Gnu tar issues redmine6626

---

tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/app_based_inputs.cf
tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/app_based_inputs.cf.sub
tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/apps/app00_zero.cf.sub
tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/apps/app_one.cf.sub
tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/apps/app_two.cf.sub
tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/apps/app_zero.cf.sub
tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/classification_bundles_not_in_sequence.cf
tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/classification_bundles_not_in_sequence.cf.sub
tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/classification_bundles_not_in_sequence2.cf
tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/classification_bundles_not_in_sequence2.cf.sub
tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/classification_bundles_not_in_sequence3.cf
tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/classification_bundles_not_in_sequence3.cf.sub
tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/dynamic_inputs_based_on_class_set_using_variable_file_control_extends_inputs.cf
tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/dynamic_inputs_based_on_class_set_using_variable_file_control_extends_inputs.cf.sub
tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/inputs/read_classes.cf.sub
tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/inputs/test_bundle_common.cf.sub
tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/read_inputs.cf.sub
tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/simple.cf
tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/simple.cf.sub
tests/acceptance/01_vars/01_basic/nested_expansion_namespaced_variables.cf
tests/acceptance/14_reports/00_output/report_nested_variable.cf
tests/acceptance/14_reports/00_output/report_nested_variable.cf.sub

Includes:
* https://github.com/cfengine/core/pull/1386
* https://github.com/cfengine/core/pull/1842
* https://github.com/cfengine/core/pull/2062
Combined simply for more efficient building and testing.

Combined acceptance tests pull requests.

---

cf-agent/verify_methods.c
tests/acceptance/21_methods/usebundle_with_or_without.cf

It's more intuitive that the name matches the bundle exactly.

Redmine #6446: Remove "method_" prefix from methods promises.

---

cf-agent/files_editline.c
tests/acceptance/10_files/09_insert_lines/preserve_block_blank_lines.cf

https://github.com/cfengine/core/pull/2169 plus one optimization.

Fix Redmine #7094 and add acceptance test

---

tests/acceptance/10_files/copy_local_file.cf

Ref: https://dev.cfengine.com/issues/5576

Add: Test that copying files locally works

---

libpromises/evalfunction.c
libpromises/files_copy.c
libpromises/files_copy.h
tests/acceptance/01_vars/02_functions/filestat_xattr.cf

Redmine#7098: let filestat() support xattr

---

libpromises/mod_services.c

Trivial change.  See https://dev.cfengine.com/issues/5646

Redmine#5646: add "enable" to service_policy menu

---

libpromises/cf3parse.y
libpromises/policy.c
tests/acceptance/01_vars/04_containers/inline_json.cf
tests/acceptance/01_vars/04_containers/inline_json.cf.expected.json
tests/acceptance/01_vars/04_containers/inline_json_parse.cf
tests/acceptance/01_vars/04_containers/inline_json_parse.cf.sub

Fixed https://github.com/cfengine/core/pull/2156

Redmine#3660: inlined JSON

---

libpromises/files_hashes.c

Add check for EVP_DigestInit status,

Fix segfault while executing cf-agent -x.

---

cf-serverd/server_transform.c

Previous fix of server promises evaluation order didn't include
promises in common bundles which are obviously evaluated by cf-serverd.
This fix adds explicit evaluation of promises from common bundles.

Redmine#7211 Fix common bundles evaluation in server.

---

cf-agent/verify_processes.c

Killing is changing the system, setting a class is not.

Redmine #7216: Don't report repaired status unless we change the system

---

ChangeLog

ChangeLog: tzz updates for 3.7

---

libenv/sysinfo.c

Redmine #7297: Make sure systemd is detected if PID 1 is a symlink

---

libpromises/files_lib.c

This simplifies code and gives more informative messages. It's needed for fixing Redmine#7358.

simplify code

---

libpromises/policy.c
tests/acceptance/00_basics/01_compiler/string_contexts.cf
tests/acceptance/00_basics/01_compiler/string_contexts_rval.cf

@nickanderson @kacfengine 
This fixes bug exposed by https://github.com/cfengine/masterfiles/pull/503#issuecomment-118873667
With acceptance test.

Redmine#2504: merge ifvarclass/if FnCall and scalar correctly

---

cf-agent/verify_users_pam.c

https://dev.cfengine.com/issues/6734

User promise fixes for HP-UX

---

examples/packagesmatching.cf

Ref: https://dev.cfengine.com/issues/7380

Add: packagesmatching() example

---

libpromises/generic_agent.c
misc/systemd/cfengine3.service.in
tests/acceptance/00_basics/04_bundles/duplicate_promise_handles.cf
tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/app_based_inputs.cf
tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/app_based_inputs.cf.sub
tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/dynamic_inputs_based_on_class_set_using_variable_file_control_extends_inputs.cf
tests/acceptance/00_basics/04_bundles/dynamic_bundlesequence/dynamic_inputs_based_on_class_set_using_variable_file_control_extends_inputs.cf.sub
tests/acceptance/01_vars/01_basic/long_string_from_embedded.cf
tests/acceptance/01_vars/02_functions/long_string_from_module.cf
tests/acceptance/01_vars/02_functions/long_string_from_text_file.cf
tests/acceptance/10_files/zendesk_1776/zendesk_1776.cf.sub
tests/acceptance/10_files/zendesk_1779/zendesk_1779.cf.sub

Fix typos found by codespell

---

examples/symlink.cf
examples/symlink_children.cf

Intended to be included in the documentation

Add: Symlink examples

---

libutils/string_lib.c
libutils/string_lib.h

Add SafeStringNDuplicate utility function to string_lib

---

autogen.sh
tests/acceptance/testall
tests/unit/dynamic_dependency_test.sh

The old approach has been found not to work under some circumstances,
however this approach has been tested and found to work.

Fix POSIX shell detection on Solaris.

---

misc/changelog-generator/changelog-generator
misc/changelog-generator/test-changelog-generator

Not putting the test in tests/unit, because it depends on Git. It
should not need to be run very often anyway.

Redmine #7381: Add changelog generator script.

---

examples/processes_define_class_based_on_process_runtime.cf

(cherry picked from commit 9d3121ebf30294ce51eca1cfa2c39f386f9b03e9)

Add: Improved processes promise example

---

tests/unit/passopenfile_test.c

The registered atexit() call was being called for each test, at the
exit() of the child process, and was removing the Unix domain socket at
/tmp. This happened on every child, no matter if it had setup a socket
or not, because DIALEDUP was being turned on around the beginning of the
parent process and never turned off, despite the file being deleted by
the child.
The solution is to clean up the Unix domain socket file after every
test, both for child (via atexit()) and parent (manually) processes. The
cleanup is accompanied by setting DIALEDUP=false, thus the next spawned
child has correct state and won't try to remove a file that hasn't
created itself.

Fix passopenfile_test that was failing on HP-UX.

---

HACKING.md

* Modified a bit the criteria for accepting pull requests
* Improved order and formatting
* Added new "Coding style" guidelines.

Configurable pull request guide

---

libutils/logging.c

Changelog: Reduce malloc() thread contention on heavily loaded
cf-serverd, by not exiting early in the logging function, if no message
is to be printed. (Redmine #7624)

Redmine#7624: Reduce malloc() thread contention

---

ChangeLog
HACKING.md
examples/processes_define_class_based_on_process_runtime.cf
examples/symlink.cf
examples/users_type.cf
libpromises/failsafe.cf
tests/acceptance/00_basics/01_compiler/710.x.cf
tests/acceptance/10_files/04_match/008.cf
tests/acceptance/10_files/04_match/008.cf.sub
tests/acceptance/10_files/04_match/directory_can_not_readlink.cf
tests/acceptance/10_files/templating/missing_template_file.cf
tests/unit/data/constraint_lval_invalid.cf

The 2nd patch changes code and I am not sure whether it does not break something, so please review it carefully.

Fix several typos (mostly found by codespell)

---

tests/acceptance/10_files/09_insert_lines/same_text_in_two_regions.cf

Redmine #7460. Currently failing.

Add acceptance test for adding the same text to different two regions.

---

libcfnet/classic.c
libcfnet/client_code.c
libcfnet/net.c
libcfnet/tls_generic.c

A small change that makes the transaction protocol stricter, plus lots of comments.

stricter transaction protocol

---

cf-serverd/server_common.c

This is a quick'n'dirty fix for the performance problems that thousands
of getpwnam() calls per second are causing.
Changelog: Improve cf-serverd's lock contention because of getpwnam()
call. (Redmine #7643)

Redmine#7643: Hard-code root uid to 0.

---

cf-agent/verify_files_utils.c
libcfnet/client_code.c
libcfnet/connection_info.c
libcfnet/connection_info.h
libcfnet/net.c
libcfnet/net.h

Check out for example:
* tests/acceptance/10_files/01_create/copy_and_purge.cf

Revert #6027 fixes due to segfaults in CI

---

tests/acceptance/21_methods/method_outcomes.cf

- Test that methods have kept/repaired/not_kept outcomes
- Test that worst promise outcome in bundle is bundle outcome

Add: Acceptance test for method outcomes

---

tests/acceptance/01_vars/02_functions/network/url_get.cf
tests/acceptance/01_vars/02_functions/url_get_local.cf

Redmine#6480: skip url_get acceptance tests when !feature_curl

---

examples/regex_replace.cf

@jimis this example will be used in the docs

Redmine#7346: add regex_replace example

---

configure.ac
libcompat/fchmodat.c
libcompat/readlinkat.c
libutils/file_lib.c
libutils/platform.h
m4/fchmodat.m4
tests/acceptance/10_files/02_maintain/fifos.cf
tests/acceptance/dcs.cf.sub
tests/unit/file_lib_test.c

Supersedes https://github.com/cfengine/core/pull/2276.

Redmine #7030: No longer hang when changing permissions/ownership on fifos

---

cf-agent/verify_packages.c

Ref: https://dev.cfengine.com/issues/7603

Change: Soften legacy package promise implementation warning

---

libpromises/locks.c

The motivation is to try to track down really hard-to-find bugs where
CFEngine hangs on a lock.
The reason for not putting the code directly in the DB operations
themselves is that we want the cleartext keys for the locks, and they
are only available higher up in the callstack.

Add extensive debugging output to cf_lock operations.

---

libpromises/generic_agent.c

Add YAML, JSON, Mustache extensions to dir checksum

---

cf-serverd/server_common.c
tests/acceptance/22_cf-runagent/serial/cfruncommand_argv0_quoted.22014.srv
tests/acceptance/22_cf-runagent/serial/cfruncommand_argv0_quoted.cf

Redmine#7409: cfruncommand is not executed under shell.

---

tests/acceptance/14_reports/failed_reports_are_not_kept.cf

Ref: https://dev.cfengine.com/issues/7833

Add: Test that failure to report to file does not have kept outcome

---

tests/acceptance/10_files/templating/mustache_does_not_try_to_render_when_provided_datacontainer_via_direct_data_is_undefined.cf
tests/acceptance/10_files/templating/mustache_does_not_try_to_render_when_provided_datacontainer_via_direct_data_is_undefined.cf.mustache
tests/acceptance/10_files/templating/mustache_does_not_try_to_render_when_provided_datacontainer_via_mergedata_is_undefined.cf
tests/acceptance/10_files/templating/mustache_does_not_try_to_render_when_provided_datacontainer_via_mergedata_is_undefined.cf.mustache
tests/acceptance/10_files/templating/mustache_does_not_try_to_render_when_provided_datacontainer_via_parsejson_storejson_is_undefined.cf
tests/acceptance/10_files/templating/mustache_does_not_try_to_render_when_provided_datacontainer_via_parsejson_storejson_is_undefined.cf.mustache

Ref: https://dev.cfengine.com/issues/7699

Add: Tests for mustache not rendering with invalid data

---

tests/acceptance/00_basics/environment/workdir_correct_after_files_promise.cf
tests/acceptance/00_basics/environment/workdir_correct_after_files_promise.cf.sub

Ref: https://dev.cfengine.com/issues/7569

Add: Test to make sure workdir is restored after files promise

---

libcfnet/classic.c

The 51cad214e5ee6bc4cfdba9dcbc5a673472eba0c1 commit does not integrate
the patch correctly.

Fix integration of a fix for error handling in case of recv timeouts

---

examples/packagesmatching.cf

(cherry picked from commit ce3bfde67aec98758800c31621e2557c32dc8e48)

Change: Cleanup packagesmatching() example

---

tests/acceptance/01_vars/02_functions/ifelse_isvariable.cf

Ref:https://dev.cfengine.com/issues/7878

Add: Test that ifelse can take isvariable as param

---

cf-agent/cf-agent.c
cf-promises/cf-promises.c

Provide new -w argument to override the workdir for testing

---

cf-key/cf-key-functions.c
cf-key/cf-key-functions.h
cf-key/cf-key.c

Add '-n' flag to cf-key to avoid host name lookups.

---

libpromises/failsafe.cf

* https://dev.cfengine.com/issues/7954

Failsafe bodies/bundles must be unique due to def.json problem

---

libpromises/failsafe.cf

* https://dev.cfengine.com/issues/7954
(cherry picked from commit e514aa341013e1c5b2f6fd934ad60f56810a5036)

Failsafe bodies/bundles must be unique due to def.json problem:

---

examples/mergedata.cf

add merge daya ezample that shows inline json with variable expansion

---

tests/acceptance/10_files/files_with_spaces.cf

Ref: http://dev.cfengine.com/issues/7934

Add: Test that files with spaces can be created

---

cf-agent/cf-agent.c

redmine#7137: log variable definitions in verbose output.

---

cf-agent/cf-agent.c
cf-agent/files_editline.c
cf-agent/verify_files.c
cf-agent/verify_files_utils.c
cf-execd/cf-execd.c
cf-promises/cf-promises.c
cf-runagent/cf-runagent.c
cf-serverd/cf-serverd-functions.c
cf-serverd/server.c
configure.ac
libcompat/fchmodat.c
libcompat/readlinkat.c
libcompat/setlinebuf.c
libenv/sysinfo.c
libpromises/evalfunction.c
libpromises/generic_agent.c
libpromises/systype.c
libutils/file_lib.c
libutils/platform.h
libutils/set.c
libutils/set.h
m4/fchmodat.m4
tests/unit/file_lib_test.c
tests/unit/set_test.c

continues @kacf 's work from https://github.com/cfengine/core/pull/2528. The commits removed are from @jimis and @pasinskim:
769f1633ed3f2262d31bc7026e1485690701af88 \
b4ff4bc121f22a5b6ea2aa4e7504808616642be6 \
ef2c963c87f163c51cb3952401cc35af9461c42f \
597289a48ac4142e359f0c2819ad6cb324bbf67c \
a0097056c427beab8335bfaa39ec44af9ffd863c \
a852b9025d4a47c0ba41723d3207b4328c894f29 \
c9bd115570749313f43df46373665609b88e0966 \
7262d3e0be0fc35fbb55ae4c79f2a0370f5fd7d6 \
05c7e6a1887105d2b3eb5517e63f4b4909f49693

36x cherry-picks

---

libpromises/failsafe.cf

Refactor the builtin failsafe/bootstrap policy to make it more readable and
easier to maintain.

Refactor builtin failsafe

---

examples/peers.cf

(cherry picked from commit b35d60a06480ace1c67268e181164817299ec8e2)

Change: Improve the comment regex for peers

---

examples/peerleader.cf
examples/peerleaders.cf

(cherry picked from commit 18a9482825dda2fdcad770d8356e55e6f0f02ba2)

Change: Improve peerleader and peerleaders examples

---

examples/readintrealstringlist.cf

(cherry picked from commit 41375731369cfb2bd62b1568ba3bec6813e5d3a2)

Change: Use multiline regex for readintrealstringlist example

---

contrib/enterprise/report.pl

Fix: Switch report.pl back to using hostnames in queries instead of ip

---

cf-agent/cf-agent.c
cf-agent/verify_processes.c
cf-execd/cf-execd.c
libpromises/cf3.extern.h
libpromises/cf3globals.c
libpromises/evalfunction.c
libpromises/processes_select.c
libpromises/processes_select.h
libpromises/systype.c
tests/acceptance/05_processes/01_matching/promiser_match_is_correct.cf
tests/acceptance/05_processes/01_matching/promiser_match_is_correct.cf.sub
tests/acceptance/05_processes/01_matching/stime_range.cf
tests/acceptance/05_processes/02_functions/findprocesses.cf
tests/acceptance/05_processes/02_functions/processexists.cf
tests/unit/split_process_line_test.c

I recommend viewing commit by commit, and preferably locally with the `--histogram` option, it becomes much more readable then.

CFE-2161: Lots of ps parsing fixes.

---

ChangeLog

(cherry picked from commit 570247324a692c0adb741f3e5141c0e81a2896f0)

Change: Adjust changelog markup to work with doc builds

---

libenv/unix_iface.c

CFE-1995: Be less verbose if a network interface doesn't have a MAC address.

---

cf-execd/cf-execd-runner.c
tests/acceptance/25_cf-execd/timed/mailfilter_repeated_runs.cf

ENT-2739: Don't send empty emails for logs where everything is filtered.

---

cf-agent/files_links.c
cf-runagent/cf-runagent.c
cf-serverd/server_classic.c
libcfnet/cfnet.h
libcfnet/misc.c
libenv/sysinfo.c
libenv/unix_iface.c
libpromises/addr_lib.c
libpromises/cf3globals.c
libpromises/evalfunction.c
libpromises/files_names.c
libpromises/files_names.h
libpromises/lastseen.c
libpromises/locks.c
libpromises/matching.c
libpromises/policy.c
libpromises/scope.c
libpromises/scope.h
libpromises/sort.c
libutils/buffer.c
libutils/buffer.h
libutils/string_lib.c
libutils/unix_dir.c
tests/unit/domainname_test.c
tests/unit/scope_test.c

Cherry-picked the undisputable ones and the ones not conflicting with Enterprise from pull request #2609.

Potential overflows cherry-picks by estenberg

---

cf-agent/cf-agent.c
examples/returnszero.cf
libpromises/generic_agent.c
libpromises/loading.c
tests/acceptance/10_files/04_match/kept_promise.cf

cf-promises: Do not verify constraint syntax for expanded slists

---

libpromises/evalfunction.c
tests/acceptance/02_classes/02_functions/isipinsubnet.cf
tests/acceptance/02_classes/02_functions/isipinsubnet.cf.expected.json

Supersedes pull request #2529.

Iprange refactor

---

examples/services.cf

(cherry picked from commit 05ef5dd5968562817bd016145669308992bffba2)

Add: Simple services promise example

---

tests/acceptance/01_vars/02_functions/ifelse.cf
tests/acceptance/01_vars/02_functions/ifelse.cf.expected.json

this is partly for https://tracker.mender.io/browse/CFE-2357 but also just to clean up the test

Improve ifelse() test

---

libutils/json.c

Change: Log level for keeping verbatim JSON to DEBUG

---

cf-agent/verify_files_utils.c
libpromises/cf3.defs.h
tests/acceptance/10_files/unsafe/multiple-group-candidates-first-found-group-perms-if-no-listed-candidate-matches.cf
tests/acceptance/10_files/unsafe/multiple-owner-candidates-first-found-user-perms-if-no-listed-candidate-matches.cf

Found while reviewing pull request #2649.

Multiple owners bug

---

libutils/man.c

Fix man pages

---

ChangeLog
LICENSE
cf-serverd/server_common.c
contrib/masterfiles-stage/README.org
contrib/masterfiles-stage/lib/optparse/README.md
examples/reports.cf
libcfnet/net.c
libpromises/failsafe.cf
tests/acceptance/00_basics/environment/workdir_correct_after_files_promise.cf
tests/acceptance/10_files/agent_control_files_single_copy_does_not_apply_to_nonmatching_files_3.cf
tests/acceptance/10_files/agent_control_files_single_copy_does_not_apply_to_nonmatching_files_4.cf
tests/acceptance/21_methods/method_outcomes.cf
tests/acceptance/README
tests/acceptance/plucked.cf.sub

Fix some typos

---

cf-serverd/cf-serverd-functions.c
libpromises/generic_agent.h

First attempt to fix this issue. @nickanderson please test.

CFE-2406: cf-serverd should reload def.json when reloading policy

---

configure.ac

Fix spurious failures caused by parallel tests on some platforms.

---

tests/unit/mon_processes_test.c

Fix mon_processes_test on linux, skip on HP-UX.

---

examples/variablesmatching_as_data.cf

needed for documentation.
Required by https://github.com/cfengine/documentation/pull/1570

Redmine#7885: add example of variablesmatching_as_data() function

---

tests/acceptance/00_basics/03_bodies/report_error_when_body_missing.cf
tests/acceptance/00_basics/03_bodies/report_error_when_body_missing.cf.sub

Add: Test sensible error message when body undefined

---

cf-agent/verify_environments.c
cf-key/cf-key-functions.c
libcfnet/tls_generic.c
tests/unit/tls_generic_test.c

Just fix some spelling errors.

Fix some spelling errors

---

tests/acceptance/09_services/custom.cf
tests/acceptance/09_services/disable.cf
tests/acceptance/09_services/enable.cf

CFE-2402: fix issue reference in acceptance tests

---

tests/acceptance/01_vars/01_basic/vars_comments_emitted_in_verbose.cf
tests/acceptance/01_vars/01_basic/vars_comments_emitted_in_verbose.cf.sub

Add: Test that comments on vars promises are emitted in verbose output

---

tests/acceptance/02_classes/01_basic/classes_comments_emitted_in_verbose.cf
tests/acceptance/02_classes/01_basic/classes_comments_emitted_in_verbose.cf.sub

Add: Test comments on classes promsies are emitted in verbose logs

---

examples/getclassmetatags.cf
examples/getvariablemetatags.cf

Example for the changes in https://github.com/cfengine/core/pull/2647 @nickanderson

Example using getvariablemetatags() and getclassmetatags()

---

misc/changelog-generator/changelog-generator
misc/changelog-generator/test-changelog-generator

changelog-generator: Omit signed-off-by entries in changelog output.

---

cf-agent/cf-agent.c
cf-execd/cf-execd-runner.c
cf-execd/cf-execd.c
cf-serverd/cf-serverd-functions.c
libpromises/bootstrap.c
libpromises/bootstrap.h
libpromises/failsafe.cf
libpromises/generic_agent.c
libpromises/generic_agent.h

@jimis Would like you to review and test this. I am also doing some more tests.
Also, the issue of what to do with cf-serverd remains: https://tracker.mender.io/browse/CFE-953

CFE-953 Custom ports for cf-agent bootstrap.

---

Makefile.am
cf-agent/agent-diagnostics.c
cf-agent/cf-agent.c
cf-execd/cf-execd-runner.c
cf-execd/cf-execd.c
cf-serverd/cf-serverd-functions.c
contrib/masterfiles/git-failsafe.cf
examples/server_callback.cf
examples/simple_ssh_key_distribution.cf
examples/software_dist.cf
libcfnet/cfnet.h
libpromises/Makefile.am
libpromises/addr_lib.c
libpromises/addr_lib.h
libpromises/bootstrap.c
libpromises/bootstrap.h
libpromises/cf3.extern.h
libpromises/cf3globals.c
libpromises/enterprise_stubs.c
libpromises/evalfunction.c
libpromises/failsafe.cf
libpromises/generic_agent.c
libpromises/generic_agent.h
libpromises/policy_server.c
libpromises/policy_server.h
libpromises/prototypes3.h
tests/unit/Makefile.am
tests/unit/policy_server_test.c

This is a bigger pull request which addresses multiple issues with the hostname and custom port features (CFE-953 CFE-546).
Previous PR for reference: cfengine/core#2699
Must be merged together with Pull Requests in masterfiles and enterprise.

Fix/improve how hostname, ip and port are handled ( CFE-953 CFE-721 CFE-385 CFE-2481 )

---

libpromises/bootstrap.c
libpromises/policy_server.c

Removed policy_hub_ip and reverted policy_hub to old behavior ( CFE-721 )

---

libcfnet/Makefile.am
libcfnet/addr_lib.c
libcfnet/addr_lib.h
libpromises/Makefile.am
libpromises/item_lib.c
libpromises/item_lib.h

Moved addr_lib to libcfnet

---

libpromises/bootstrap.c

I'm working on fixing some memory leaks. This is not ready to merge yet.

Fixing various memory leaks

---

cf-agent/verify_exec.c

CFE-2561 Change: Don't error during dry run for proposed execution.

---

.gitignore
.travis.yml
configure.ac
libcompat/strchrnul.c
tests/unit/Makefile.am
travis-scripts/after_script.sh
travis-scripts/before_deploy.sh
travis-scripts/before_install.sh
travis-scripts/script.sh

Travis improvements (folder structure, mac support etc.)

---

travis-scripts/script.sh

Fixed syntax in travis shell scripts

---

tests/acceptance/02_classes/02_functions/empty_list_or_data_doesnt_return_true_for_filesexist.cf

CFE-2631: Acceptance test for filesexist()

---

cf-net/cf-net.c

@jimis @Lex-2008 Please cherry pick this to 3.11 branch

Fixed cf-net STAT to use correct argument

---

ChangeLog

Fix 3.11.0b1 changelog

---

libenv/sysinfo.c

Location of cf-net binary stored in sys.cf-net

---

cf-agent/package_module.c
configure.ac
contrib/katepart-cfengine.highlight.xml
libpromises/pipes.c
misc/determine-version.py
splint-check.sh
travis-scripts/script.sh

Brought the 3.11.x branch up to date with master, most commits are minor and shouldn't affect build status, but the `determine-version.py` commits are important for correct version detection.

Cherry-picks for 3.11.0b1-build2

---

examples/readenvfile.cf

Added example for readenvfile() (CFE-2650)

---

tests/acceptance/26_cf-net/serial/cf-net_connect.cf
tests/acceptance/26_cf-net/serial/cf-net_connect.cf.expected
tests/acceptance/26_cf-net/serial/cf-net_get.cf
tests/acceptance/26_cf-net/serial/cf-net_help.cf
tests/acceptance/26_cf-net/serial/cf-net_help.cf.expected
tests/acceptance/26_cf-net/serial/cf-net_stat.cf
tests/acceptance/26_cf-net/serial/cf-net_stat_deny.cf
tests/acceptance/26_cf-net/serial/cf-net_stat_dir.cf
tests/acceptance/26_cf-net/serial/serverd_admit_localhost_15000.cf.srv
tests/acceptance/Makefile.am
tests/acceptance/testall

Added acceptance tests for commands:
help, connect, stat, get

cf-net acceptance tests

---

cf-net/cf-net.c

@jimis This should be cherry-picked to 3.11

cf-net: Fix windows issues (ENT-3216 & ENT-3225)

---

tests/acceptance/testall

Added printing of CF_NET env variable in testall

---

contrib/enterprise/detect_duplicate_keys/README
contrib/enterprise/detect_duplicate_keys/detect_duplicate_keys.pl
contrib/enterprise/detect_duplicate_keys/detect_duplicate_keys.sh

See [README](https://raw.githubusercontent.com/atsaloli/core/2287f2ace54c1b29e5386fc570597dcfbfbb56d8/contrib/enterprise/detect_duplicate_keys/README)

Add script to detect duplicate keys

---

.travis.yml
travis-scripts/after_script.sh
travis-scripts/before_deploy.sh
travis-scripts/before_install.sh
travis-scripts/script.sh

PR will be updated with more commits

Fixes to travis (test failures, shebangs, mac etc.)

---

libenv/sysinfo.c

CFE-2203: Enable Xen hypervisor detection on all x86 platforms

---

tests/acceptance/01_vars/04_containers/iterate_over_data_array.cf
tests/acceptance/01_vars/04_containers/iterate_over_data_array.cf.expected

(cherry picked from commit b81a281952a9422a4a7354e75bd90eb6211ad109)

Test iteration over array inside data container

---

contrib/cf-profile/cf-profile.pl

This integrates pull requests to the original cf-profile repository from
@svamberg that were never merged.

Integrate unmerged fixes to original cf-profile repository

---

examples/mustache_comments.cf
examples/mustache_extension_compact_json.cf
examples/mustache_extension_expand_key.cf
examples/mustache_extension_multiline_json.cf
examples/mustache_extension_top.cf
examples/mustache_sections_empty_list.cf
examples/mustache_sections_inverted.cf
examples/mustache_sections_non_empty_list.cf
examples/mustache_sections_non_false_value.cf
examples/mustache_set_delimiters.cf
examples/mustache_variables.cf

(cherry picked from commit a8bf6f7f3d089e37b2f252e9fc82af330395d49c)

Add examples for mustache docs

---

tests/acceptance/01_vars/02_functions/mustach_doesnt_render_null.cf

CFE-2077: Test

---

cf-execd/cf-execd.c

CFE-2406: cf-execd now re-parses augments on policy reload

---

examples/peerleader.cf
examples/peers.cf

(cherry picked from commit 895a0203b3d58858940b4f45fbcbb134f6a061b1)

Fix peers and peerleader examples like peerleaders

---

examples/peerleader.cf
examples/peerleaders.cf
examples/peers.cf

(cherry picked from commit f00ced5ea98f005307e0c592765ef73786e3830e)

Get the hostname from hostname -f

---

cf-agent/files_edit.c
cf-agent/verify_files.c
libpromises/attributes.c
libpromises/cf3.defs.h
libpromises/mod_files.c
tests/acceptance/10_files/templating/inline_demo.expected
tests/acceptance/10_files/templating/mustache_inline_demo.cf

CFE-1846: Added inline_mustache template method

---

.travis.yml
travis-scripts/after_script.sh
travis-scripts/before_deploy.sh
travis-scripts/before_install.sh
travis-scripts/script.sh

I noticed that 3.10.x was very outdated compared to master, builds were failing because of issues fixed in master.

3.10.x: Update travis files to master

---

cf-agent/acl_posix.c

ENT-3455: Improve logging of ACL errors

---

cf-agent/files_links.c
tests/acceptance/10_files/move_obstruction_respects_warn_only.cf

https://tracker.mender.io/browse/CFE-2740

CFE-2740: Do not move obstructions in warn policy mode

---

travis-scripts/before_install.sh

Travis: Overwrite OSX system gcc link

---

libpromises/cf3lex.l
libpromises/cf3parse.y
tests/unit/parser_test.c

CFE-1886: parser  can handle large input buffers

---

libpromises/dbm_migration.c
libutils/json.c
libutils/string_lib.c
libutils/string_lib.h
tests/unit/Makefile.am
tests/unit/ring_buffer_test.c
tests/unit/rlist_test.c
tests/unit/string_lib_test.c

Must be merged together:
https://github.com/cfengine/core/pull/2990
https://github.com/cfengine/enterprise/pull/359
https://github.com/cfengine/nova/pull/1073

ENT-3562: New StringToLong functions

---

ChangeLog

Signed-off-by: Aleksei Shpakovskii <aleksei.shpakovskii@cfengine.com>

Add changelog for 3.10.3

---

.mailmap
cf-agent/cf-agent.c
cf-execd/cf-execd.c
cf-key/cf-key.c
cf-monitord/cf-monitord.c
cf-promises/cf-promises.c
cf-runagent/cf-runagent.c
cf-serverd/cf-serverd-functions.c
cf-serverd/server_tls.c
libenv/sysinfo.c
libpromises/evalfunction.c
misc/determine-version.py

MUST pass jenkins before merge.

Cherry-picks for 3.7.x

---

ChangeLog

Signed-off-by: Aleksei Shpakovskii <aleksei.shpakovskii@cfengine.com>

Add 3.7.7 changelog

---

.travis.yml
travis-scripts/after_script.sh
travis-scripts/before_deploy.sh
travis-scripts/before_install.sh
travis-scripts/script.sh

See: 
https://github.com/travis-ci/travis-ci/issues/6307
#2985

Travis: Don't do set -e in .travis.yml

---

cf-net/cf-net.c

The first few commits are just minor fix-ups and refactoring for *cf-net*. The last two ones add support for getting files in parallel (in threads). I tried playing with the number of threads and everything up to ~250 was working fine for me.

Improvements and parallelism for cf-net

---

cf-serverd/cf-serverd-functions.c
cf-serverd/server_tls.c
cf-serverd/server_tls.h
cf-upgrade/Makefile.am
libcfnet/Makefile.am
libcfnet/server_code.c
libcfnet/server_code.h
libcompat/Makefile.am
libenv/Makefile.am

Server code preparation for cf-testd

---

HACKING.md

Also fixed some markdown syntax.

Added note about error codes in return values to HACKING.md

---

autogen.sh
cf-monitord/Makefile.am
cf-monitord/env_monitor.c
cf-monitord/history.c
cf-monitord/history.h
cf-monitord/mon_cumulative.c
cf-monitord/mon_cumulative.h
cf-monitord/mon_io_linux.c
cf-monitord/mon_io_stub.c
cf-monitord/mon_mem_linux.c
cf-monitord/mon_mem_solaris.c
cf-monitord/mon_mem_stub.c
cf-monitord/monitoring.c
cf-monitord/monitoring.h
cf-monitord/probes.c
cf-monitord/probes.h
cf-monitord/shared_kstat.c
cf-monitord/shared_kstat.h
cf-monitord/verify_measurements.c
libenv/sysinfo.c
libpromises/Makefile.am
libpromises/cf3.defs.h
libpromises/enterprise_stubs.c
libpromises/monitoring_read.c
libpromises/monitoring_read.h
libpromises/prototypes3.h

To be merged together with cfengine/enterprise#328

Open custom measurements in cf-monitord

---

.gitignore
Makefile.am
cf-serverd/cf-serverd-enterprise-stubs.c
cf-serverd/cf-serverd-enterprise-stubs.h
cf-testd/Makefile.am
cf-testd/cf-testd.c
configure.ac

Must be merged with the enterprise functions:
https://github.com/cfengine/enterprise/pull/374

ENT-3476: cf-testd, a mock version of cf-serverd

---

libpromises/evalfunction.c
tests/acceptance/01_vars/02_functions/filesexist-can-detect-files-containing-hash-character.cf
tests/acceptance/01_vars/02_functions/filesexist-is-collecting.cf
tests/acceptance/02_classes/02_functions/empty_list_or_data_doesnt_return_true_for_filesexist.cf

Collecting filesexist() for 3.10.x

---

libutils/logging.c
libutils/logging.h

Merge with: https://github.com/cfengine/nova/pull/1116

Moved byte printing to logging in core

---

cf-agent/cf-agent.c
cf-serverd/server_transform.c
cf-testd/cf-testd.c
libcfnet/cfnet.h
libcfnet/client_code.c
libcfnet/client_code.h
libcfnet/net.c
libcfnet/server_code.c

A few minor enhancements for *cf-testd* and the related code. At the same time these are the first steps to make *cf-testd* better prepared to be used for testing at scale.

Scale cf-testd (Part 1)

---

libutils/sequence.c
libutils/sequence.h
tests/unit/sequence_test.c

Renamed this function from ENT.

Added SeqStringLength function from ent

---

cf-key/cf-key-functions.c
cf-key/cf-key-functions.h
cf-key/cf-key.c
cf-runagent/cf-runagent.c

First draft of a new option to set the size of the key generated by cf-key. Do you think "-b" is ok for this?

Add an option to specify RSA key size to cf-key

---

tests/acceptance/01_vars/02_functions/CFE-954.cf

(cherry picked from commit 501688137dd468e92f538bf8a450e7f6fb19be07)

CFE-954: Add test for lsdir

---

libpromises/verify_vars.c
tests/acceptance/01_vars/01_basic/can_not_define_variables_in_remote_bundles.cf
tests/acceptance/21_methods/array_reset.cf

As described in [[CFE-1915]](https://tracker.mender.io/browse/CFE-1915).

CFE-1915: Disallow modifications of foreign variables

---

libpromises/dbm_quick.c

Since commit 1eb3f171e (Add support for new packages promises in dbm.,
2015-05-20), the function `DBPrivOpenCursor` was completely broken.
Ignoring the fact that the function is recursively calling itself until
the stack overflows and cfengine segfaults, the only thing it would do
if it succeeded in opening a cursor would be to delete the complete
database. This code cannot have ever been executed by anyone, as there
is clearly no constellation where it could possibly work.
I can only assume that this was an unintentional change to
`DBPrivOpenCursor`. Thus, this commit reverts all changes made in that
commit to `DBPrivOpenCursor`.

libpromise: qdbm: fix DBPrivOpenCursor function

---

libpromises/evalfunction.c

(cherry picked from commit 4d04fe5f5b7eee603a375afa30fab213ac3975ad)

Add a debug log for computed class in splayclass

---

tests/unit/lastseen_migration_test.c

[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=408)](https://ci.cfengine.com/view/all/job/pr-pipeline/408/)

Silence warnings about unused code in skipped migration test

---

cf-key/cf-key-functions.c
cf-key/cf-key-functions.h
cf-serverd/cf-serverd-enterprise-stubs.c
cf-serverd/cf-serverd-enterprise-stubs.h
cf-serverd/cf-serverd-functions.c
cf-serverd/cf-serverd-functions.h
cf-testd/cf-testd.c
libcfnet/server_code.c
libcfnet/server_code.h
libpromises/crypto.c
libpromises/crypto.h
tests/acceptance/01_vars/02_functions/shuffle-exact.cf

Tested this with 200 threads and everything seems to be working fine.

Parallel cf-testd

---

ChangeLog

and 3.11.0 which should be on master

Changelog for 3.12.0 beta

---

libpromises/generic_agent.c

These are useful for testing/debugging reporting and bootstrap.

Classes failsafe_fallback and bootstrap_mode are now reported by default

---

tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/defaults.cf
tests/acceptance/06_storage/01_local/001.cf
tests/acceptance/10_files/09_insert_lines/017.cf
tests/acceptance/10_files/unsafe/can_set_sticky_bits_with_nonroot_owner_and_group.cf

Dunno why it didn't fail before
Signed-off-by: Aleksei Shpakovskii <aleksei.shpakovskii@cfengine.com>

INF-402 fix test to work on Solaris, too

---

libpromises/cf3lex.l
tests/acceptance/00_basics/macros/if_on_first_line.cf

macros on line 1 in a file.
Ticket: CFE-2817
(cherry picked from commit 33971061d84e2a2f356489a201e3bd2fa719594a)

CFE-2817: We must start on line position is 1 instead of 0 to support the @if (3.12.x)

---

libpromises/eval_context.c
libpromises/eval_context.h
libpromises/expand.c
libpromises/loading.c
libpromises/verify_vars.c
libutils/sequence.c
libutils/sequence.h
tests/acceptance/01_vars/01_basic/can_not_define_variables_in_remote_bundles.cf
tests/acceptance/08_commands/01_modules/set-context.cf
tests/acceptance/08_commands/01_modules/set-context.cf.txt
tests/unit/sequence_test.c

CFE-1915: Allow dots in variable identifiers with no such bundle

---

HACKING.md

Reordered the content, fixed some markdown, removed some noise, added useful info on log levels.

HACKING.md improvements

---

cf-testd/cf-testd.c

Real-life reports have newlines in the CSV data rows so a more
clever approach has to be taken to store and load such
data. Length-prefixed data is a simple but powerful approach
which can easily be supported.

Support real-life reports in cf-testd

---

cf-testd/cf-testd.c

Real-life reports have newlines in the CSV data rows so a more
clever approach has to be taken to store and load such
data. Length-prefixed data is a simple but powerful approach
which can easily be supported.
(cherry picked from commit 9d9baa71fef497f37a6dd0988b31f3ea4ff6df79)

Support real-life reports in cf-testd (3.12)

---

ChangeLog

@olehermanse / @vpodzime : feel free to take commit and adapt it to your needs in case I stop responding

Add 3.12.0 changelog

---

cf-serverd/cf-serverd-functions.c

This number is used in the listen() syscall and determines the
maximum number of established connections that could be waiting
to be accepted. Any connections beyond this limit are either
refused or, worse, fed cookies (see tcp_syncookies in
man:tcp(7)).
Kernel has its own limit for this number (per socket) which is an
upper bound and it defaults to 128 [1]. So let's use this maximal
possible value as a default, there's nothing to lose for us. We
have a capability to handle many connections in threads
(specified in 'body server control' -> maxconnections), but if
too many connections are attempted at once, we need a big enough
backlog/queue to give us enough time to process them. Starting
threads may just not be fast enough, especially in combination
with our bad way of counting threads …

3.12.x - Increase the connection backlog/queue size in cf-serverd

---

cf-agent/cf-agent.c
libenv/sysinfo.c
libpromises/failsafe.cf
libpromises/generic_agent.c
libpromises/generic_agent.h
tests/acceptance/01_vars/01_basic/sysvars.cf

So that more complete data is available for the first report.

CFE-2826: Trigger promises.cf as the last step of bootstrap

---

libpromises/evalfunction.c
tests/acceptance/01_vars/02_functions/string_replace.cf
tests/acceptance/01_vars/02_functions/string_replace.cf.expected.json

Cherry-picked from https://github.com/cfengine/core/pull/3178

CFE-2850: Added function string_replace - 3.12.x

---

libpromises/evalfunction.c
tests/acceptance/01_vars/02_functions/string_replace.cf
tests/acceptance/01_vars/02_functions/string_replace.cf.expected.json

Cherry-picked from https://github.com/cfengine/core/pull/3178

CFE-2850: Added function string_replace - 3.10.x

---

examples/string_replace.cf

Tests replacing once, several and no occurences, as well as
ambiguous order.
Ticket: CFE-2850

CFE-2850: Added examples for string_replace

---

cf-upgrade/log.c

gmtime_r is thread safe.
https://lgtm.com/rules/2154840805/

Replaced gmtime with gmtime_r

---

cf-upgrade/process.c
libpromises/evalfunction.c

https://lgtm.com/rules/2154840805/

Replaced 2 more occurences of gmtime with gmtime_r

---

cf-agent/files_select.c
cf-agent/verify_files.c
libpromises/evalfunction.c
libpromises/fncall.c
libpromises/generic_agent.c
libpromises/pipes.c
libpromises/pipes_unix.c
libutils/mustache.c
libutils/regex.c

Each commit has a short explanation. Most commits should be easily cherrypicked.

Fixed string formatting of integer types in several places

---

README.md

As requested by @olehermanse in #3241 (feel free to tweak!)

Tweak LGTM.com code quality badge so it doesn't mention C++

---

cf-agent/files_repository.c
cf-agent/verify_databases.c
cf-agent/verify_storage.c
libpromises/evalfunction.c
libpromises/matching.c
libpromises/policy.c
libpromises/verify_vars.c

Improves readability/maintainability.
https://lgtm.com/rules/2154840803/

Added comments / logging to empty if blocks

---

libpromises/files_hashes.c

Don't backport. I will make custom commits for 3.10 and 3.12 where this code is slightly different.

Refactored files_hashes.c

---

contrib/masterfiles-stage/README.org

Revert "ENT-3806: Masterfiles stage readme was changed."

---

cf-agent/files_editline.c
cf-agent/files_editxml.c
cf-agent/package_module.c
cf-agent/verify_databases.c
cf-agent/verify_environments.c
cf-agent/verify_exec.c
cf-agent/verify_files.c
cf-agent/verify_files_utils.c
cf-agent/verify_methods.c
cf-agent/verify_new_packages.c
cf-agent/verify_packages.c
cf-agent/verify_processes.c
cf-agent/verify_services.c
cf-agent/verify_storage.c
cf-agent/verify_users.c
cf-monitord/env_monitor.c
cf-monitord/history.c
cf-serverd/cf-serverd-functions.c
libpromises/locks.c
libpromises/locks.h
libpromises/verify_reports.c

https://github.com/cfengine/core/pull/3269
https://github.com/cfengine/enterprise/pull/434
https://github.com/cfengine/nova/pull/1239

Changed Acquirelock() to take ints instead of a big struct

---

cf-agent/vercmp.c

RunCmpCommand improvements

---

cf-agent/vercmp.c

Make sure to return VersionCmpResult from RunCmpCommand

---

cf-agent/package_module.c

Also created some local variables to avoid excessive derefs
and unreadable code.
https://lgtm.com/rules/2156240606/

Renamed variable which shadowed param

---

cf-agent/acl_posix.c
cf-agent/acl_posix.h
cf-agent/verify_acl.c

CFE-2886: Changed functions in acl_posix to use Attributes *

---

cf-agent/files_editline.c
cf-agent/files_editline.h
cf-agent/verify_files.c

CFE-2886: Changed functions in files_editline to use Attributes *

---

cf-agent/verify_environments.c

CFE-2886: Changed static functions in verify_environments to use Attributes *

---

libutils/mustache.c

https://lgtm.com/rules/2156240606/

CFE-2886: Renamed variable which was shadowing a parameter

---

cf-agent/cf-agent-windows-functions.h
cf-agent/verify_files_utils.c
cf-agent/verify_files_utils.h
cf-agent/verify_services.c

https://github.com/cfengine/core/pull/3298
https://github.com/cfengine/enterprise/pull/436

CFE-2886: Updated verify_services to use Attributes *

---

tests/acceptance/10_files/templating/edit_template_string/mustache_edit_template_string_vs_edit_template.cf
tests/acceptance/10_files/templating/edit_template_string/mustache_edit_template_string_vs_string_mustache.cf
tests/acceptance/10_files/templating/edit_template_string/pghba.conf.mustache

CFE-2910 Test that edit_template_string works identically to edit_template and string_mustache

---

cf-agent/cf-agent-enterprise-stubs.c
cf-agent/cf-agent-enterprise-stubs.h
cf-agent/files_editxml.c
cf-agent/verify_files.c
cf-agent/verify_files.h
cf-agent/verify_files_utils.c
cf-agent/verify_files_utils.h

https://github.com/cfengine/core/pull/3303
https://github.com/cfengine/enterprise/pull/437

CFE-2886: Changed more functions to use Attributes *

---

libpromises/generic_agent.c

CFE-2913: Fixed a memory leak which occured while loading augments files (3.12)

---

libpromises/generic_agent.c

CFE-2913: Fixed a memory leak which occured while loading augments files (3.10)

---

libpromises/generic_agent.c

Revert "CFE-2913: Fixed a memory leak which occured while loading augments files"

---

libpromises/generic_agent.c

Revert "Revert "CFE-2913: Fixed a memory leak which occured while loading augments files""

---

tests/unit/csv_writer_test.c

Revert "Revert "ENT-4136: Fixed memory leak in csv_writer_test""

---

libpromises/processes_select.c
tests/unit/split_process_line_test.c

Revert "Revert "ENT-4136: Prevent OOB read in ApplyPlatformExtraTable and free in unit test""

---

tests/acceptance/00_basics/01_compiler/classes_without_constraints.cf

(cherry picked from commit 0f56fcd1a9e2d1fad61c5a0c94a3a2d3b1177591)

CFE-2000 Test that classes can be defined without constraints

---

contrib/pgsql_RA

For the HA setup we need a resource agent that supports
PostgreSQL 10 on RHEL 6. The upstream [1] only provides versions
that are either compatible with RHEL 6 or supporting PostgreSQL
10. Hence adding our combined RA to contrib.
[1] https://github.com/ClusterLabs/resource-agents/

The pgsql resource agent that supports our HA setup

---

libutils/misc_lib.c

Based on review comment from: 
https://github.com/cfengine/core/pull/3345

Removed unnecessary include in misc_lib

---

cf-execd/execd-config.c

Ticket: CFE-2931
Signed-off-by: Ole Herman Schumacher Elgesem <ole@northern.tech>
(cherry picked from commit bc7f504c31cddf96b097bfef94f3d3b249d466c3)

Fixed an issue with splay time in cf-execd (3.12)

---

contrib/masterfiles-stage/README.org
contrib/masterfiles-stage/common.sh
contrib/masterfiles-stage/example_params/PARAMS_example_git_branch.sh

merge with https://github.com/cfengine/nova/pull/1247 and https://github.com/cfengine/buildscripts/pull/449

ENT-4023 DC-to-VCS scripts

---

cf-execd/cf-execd.c
cf-net/cf-net.c
cf-serverd/cf-serverd-functions.c
libcfnet/client_code.c
libcfnet/communication.c
libcfnet/stat_cache.c
libcfnet/stat_cache.h
libpromises/crypto.c

CFE-2857: Reload persistent classes and fix related memory errors (3.12)

---

.gitignore
Makefile.am
cf-check/Makefile.am
cf-check/cf-check.c
cf-check/diagnose.c
cf-check/diagnose.h
cf-check/lmdump.c
cf-check/lmdump.h
configure.ac
libenv/sysinfo.c
tests/acceptance/Makefile.am
tests/acceptance/testall
tests/unit/dynamic_dependency_test.sh

https://github.com/cfengine/core/pull/3425
https://github.com/cfengine/masterfiles/pull/1274
https://github.com/cfengine/buildscripts/pull/492
https://github.com/cfengine/enterprise/pull/470

WIP ENT-4064: Backport cf-check diagnose to 3.12.1 

---

libpromises/processes_select.c

Also updated the comment block with new ps output.
It's a little hard to know how much of the description
there is outdated or still valid.

ENT-4295: Fixed an issue while parsing ps output on AIX (3.12)

---

examples/select_region.cf

merge with https://github.com/cfengine/documentation/pull/2007

CFE-2952 Refactor select_region docs

---

cf-execd/cf-execd.c
cf-serverd/cf-serverd-functions.c

(cherry picked from commit d3f09517202314799f99b1f7bd5332f70f28ec96)

CFE-2853 Document cf-execd and cf-serverd respond to SIGHUP in manpage

---

cf-check/Makefile.am
cf-check/backup.c
cf-check/backup.h
cf-check/cf-check.c

This command copies lmdb files to a timestamped backup directory.
```
root@dev core $ cf-check backup /var/cfengine/state/*.lmdb
Backing up to '/var/cfengine/backup/1544023142/'
Copying: '/var/cfengine/state/cf_lastseen.lmdb' -> '/var/cfengine/backup/1544023142/cf_lastseen.lmdb'
Copying: '/var/cfengine/state/cf_lock.lmdb' -> '/var/cfengine/backup/1544023142/cf_lock.lmdb'
Copying: '/var/cfengine/state/cf_observations.lmdb' -> '/var/cfengine/backup/1544023142/cf_observations.lmdb'
Copying: '/var/cfengine/state/cf_state.lmdb' -> '/var/cfengine/backup/1544023142/cf_state.lmdb'
Copying: '/var/cfengine/state/history.lmdb' -> '/var/cfengine/backup/1544023142/history.lmdb'
Copying: '/var/cfengine/state/nova_measures.lmdb' -> '/var/cfengine/backup/1544023142/nova_measures.lmdb'
Copying: …
```

ENT-4064: cf-check: Added backup command

---

tests/acceptance/21_methods/call_methods_using_array_expansion.cf
tests/acceptance/21_methods/call_methods_using_array_expansion.cf.expected.txt

(cherry picked from commit b61e3fe853f10409152bb1424b6748ffa3266734)

CFE-636 Test that methods can be called by expanding classic arrays

---

cf-check/Makefile.am
cf-check/backup.h
cf-check/cf-check.c
cf-check/diagnose.c
cf-check/diagnose.h
cf-check/repair.c
cf-check/repair.h

Example usage:
```
root@dev core $ cf-check repair
No filenames specified, defaulting to .lmdb files in /var/cfengine/state/
Status of '/var/cfengine/state/cf_state.lmdb': OK
Status of '/var/cfengine/state/history.lmdb': OK
Status of '/var/cfengine/state/packages_installed_apt_get.lmdb': OK
Status of '/var/cfengine/state/nova_measures.lmdb': OK
Status of '/var/cfengine/state/performance.lmdb': OK
Status of '/var/cfengine/state/nova_static.lmdb': OK
Status of '/var/cfengine/state/packages_updates_apt_get.lmdb': OK
Status of '/var/cfengine/state/cf_observations.lmdb': OK
Status of '/var/cfengine/state/cf_lock.lmdb': OK
Status of '/var/cfengine/state/packages_installed_$(package_module_knowledge.platform_default).lmdb': OK
All 10 databases healthy
No corruption - nothing to do.
root@dev core …
```

ENT-4064: Added repair command to cf-check

---

cf-agent/verify_exec.c
libpromises/pipes.h
libpromises/pipes_unix.c

Needed for https://github.com/cfengine/enterprise/pull/485.

Add the cf_pclose_nowait() function

---

cf-agent/package_module.c
cf-agent/package_module.h
libutils/path.c
libutils/path.h
tests/unit/Makefile.am
tests/unit/path_test.c

See commit messages for details.

ENT-4432: Quote package module path

---

contrib/cf-remote/cf_remote/commands.py
contrib/cf-remote/cf_remote/main.py
contrib/cf-remote/cf_remote/remote.py

cf-remote: Added 'scp', 'sudo', and 'run' commands 

---

libpromises/enterprise_stubs.c
libpromises/prototypes3.h

The code is returning boolean values.
Ticket: ENT-3363
Merge together: https://github.com/cfengine/enterprise/pull/489

Fix the return type of the GetRegistryValue function

---

contrib/cf-remote/cf_remote/commands.py
contrib/cf-remote/cf_remote/main.py
contrib/cf-remote/cf_remote/remote.py
contrib/cf-remote/cf_remote/ssh.py
contrib/cf-remote/cf_remote/utils.py

See the individual commits for details.

Two cf-remote fixes/enhancements

---

libpromises/enterprise_stubs.c
libpromises/evalfunction.c
libpromises/prototypes3.h

https://github.com/cfengine/enterprise/pull/490

[3.10.x] Core changes for windows detection

---

libpromises/enterprise_stubs.c
libpromises/evalfunction.c
libpromises/prototypes3.h

https://github.com/cfengine/enterprise/pull/491

[3.12.x] Core changes for windows detection

---

HACKING.md

Tried to make them more friendly and useful to new contributors:
* More friendly language
* Easier to read
* Organized into sections
* More concise/direct
* More examples
* Removed some noise

Reorganized and changed contribution and code style guidelines

---

libpromises/cf3parse.y
libpromises/syntax.c

Found using AFL:
https://github.com/olehermanse/dotfiles/blob/6498b3872a803ce89c13033375dde655fb926dd6/cfengine/fuzz.sh

ENT-4022: Fixed segfault in policy parser

---

contrib/cf-remote/README.md

https://tracker.mender.io/browse/CFE-3005

CFE-3005: Added installation and basic usage instructions to cf-remote README

---

libpromises/Makefile.am
libpromises/cf-windows-functions.h
libutils/Makefile.am
libutils/known_dirs.c
libutils/known_dirs.h
tests/unit/Makefile.am

Took over #3527 since I created a merge conflict by merging something else.

CFE-3006: Move known_dirs to libutils

---

libutils/Makefile.am
libutils/threaded_deque.c
libutils/threaded_deque.h
tests/unit/Makefile.am
tests/unit/threaded_deque_test.c

Currently WIP. Functionality is fine, but a lot of the code could be standardised a lot more.
Also needs tests.
@olehermanse or someone else, add WIP, please.

ENT-3832: Thread-safe double ended queue

---

.mailmap
misc/determine-version.py

Make determine_version compatible with python 2 or 3

---

cf-serverd/server_common.c
cf-serverd/server_common.h
libcfnet/classic.c
libcfnet/classic.h
libcfnet/client_protocol.c
libpromises/cf3.defs.h

https://lgtm.com/rules/1507386896202/

Fixed LGTM alerts: "Array argument size mismatch"

---

CONTRIBUTING.md

I think I may have accidentally deleted this part when I
reorganized the guidelines (?).

Smaller clarifications in CONTRIBUTING.md

---

cf-agent/cf-agent.c
cf-agent/verify_files_utils.c

Separated commits, and gave a short explanation to the second change, with link to PR discussion.
Replaces: #3326

CFE-2919: Ensure suid log has proper permissions

---

.lgtm/cpp-queries/function-returns-non-bool.qhelp
.lgtm/cpp-queries/function-returns-non-bool.ql

Inspired by:
https://github.com/cfengine/core/pull/3635

LGTM: Added query to detect bool functions which return non-bool values

---

libpromises/eval_context.c

Found by LGTM:
https://lgtm.com/rules/1508474826013/

Use proper enum constant for true in expressions

---

cf-agent/files_editline.c
cf-agent/files_select.c
cf-agent/files_select.h
cf-agent/retcode.c
cf-agent/retcode.h
cf-agent/verify_databases.c
cf-agent/verify_files_utils.c
cf-agent/verify_files_utils.h
cf-serverd/server_classic.c
cf-serverd/server_classic.h
cf-serverd/server_common.c
cf-serverd/server_common.h
libpromises/eval_context.c
libpromises/files_lib.c
libpromises/files_lib.h

No changes in behavior. Only improvements in readability and
maintainability.
https://lgtm.com/rules/1508524786076/

 Changed several functions to respect bool type

---

.lgtm/cpp-queries/bool-type-mismatch-return.qhelp

https://lgtm.com/projects/g/cfengine/core/queries/logs/?pack=com.lgtm.github_apps%2Fcfengine%2Fcore%2Fcpp-queries

LGTM: Removed problematic & in qhelp

---

cf-serverd/server_tls.c
configure.ac
libcfnet/tls_client.c
libcfnet/tls_generic.c
libcfnet/tls_generic.h
libpromises/feature.c

https://github.com/cfengine/buildscripts/pull/548

[3.12.x] TLS 1.3

---

cf-agent/verify_exec.c
libpromises/pipes.h
libpromises/pipes_unix.c

https://github.com/cfengine/enterprise/pull/509

[3.12.x] Add and use a new cf_pclose_nowait function

---

cf-agent/cf-agent.c
cf-agent/files_editline.c
cf-agent/files_editline.h
cf-serverd/server_tls.c
cf-serverd/server_transform.c
libutils/file_lib.c
libutils/file_lib.h
libutils/string_lib.c
libutils/string_lib.h

Using:
https://lgtm.com/rules/1508604166004/

Cleanup of functions which should return bool

---

Makefile.am

state and modules directories fixes

---

contrib/cf-remote/cf_remote/demo.py
contrib/cf-remote/cf_remote/packages.py
contrib/cf-remote/cf_remote/remote.py
contrib/cf-remote/cf_remote/ssh.py
contrib/cf-remote/cf_remote/utils.py

Install, bootstrap and agent run works with 2019 AMI and 3.12.2
MSI. The code is a little rough, needs some refactoring, and
doesn't parse all of systeminfo correctly, but I think it's a
"good enough" first step.
Install and bootstrap of Ubuntu 18 and Windows Server 2019:
```
olehermanse@OHMBP-3858 core $ cf-remote install --hub 34.242.237.40 --bootstrap 172.31.46.8 --demo --clients 52.215.207.154
ubuntu@34.242.237.40
CFEngine      : 3.12.2
Policy server : 172.31.46.8
Package already downloaded: '/Users/olehermanse/.cfengine/cf-remote/packages/cfengine-nova-hub_3.12.2-1_amd64.deb'
Copying: '/Users/olehermanse/.cfengine/cf-remote/packages/cfengine-nova-hub_3.12.2-1_amd64.deb' to '34.242.237.40'
Installing: …
```

CFE-2990: cf-remote: Initial windows support

---

cf-net/cf-net.c

Useful for testing and debugging issues with the TLS-related
aspects of our network connections.
Ticket: ENT-4617

Add options to cf-net to set minimum TLS version and ciphers

---

cf-agent/files_editline.c
cf-agent/verify_packages.c
cf-agent/verify_packages.h
libpromises/processes_select.c
libpromises/processes_select.h

https://lgtm.com/rules/1508604166004/
https://github.com/cfengine/core/pull/3686
https://github.com/cfengine/enterprise/pull/521

Changed return type of several functions to be bool

---

CONTRIBUTING.md
misc/githooks/git-commit-template

Let's try to make our changelogs nicer.

CONTRIBUTING.md: Improved instructions for commit messages

---

.lgtm/cpp-queries/missing-argument-null-check.ql

Looks to me like the LGTM build runs without debug enabled,
so the asserts are not expanded to comparisons. This commit
adds the additional check for a macro invocation where macro
name is `assert` and the "argument", the unexpanded string
inside parenthesis, matches the expected string. A little hacky,
but it gets rid of 600 false positives.

LGTM: Missing null check query now looks for asserts

---

cf-agent/verify_packages.c

https://lgtm.com/rules/1508612286000/
I want to improve this query, it has a lot of false positives.
Cleaning up verify_packages, and will test on this file to see
if I can find the problem.

Added null check assertions in verify_packages

---

cf-agent/verify_files_hashes.c
cf-agent/verify_files_hashes.h
cf-agent/verify_files_utils.c
cf-agent/verify_processes.c
cf-serverd/server_common.c
cf-serverd/server_common.h
libcfnet/client_code.c
libcfnet/client_code.h
libpromises/eval_context.c
libpromises/evalfunction.c
libpromises/loading.c
libpromises/patches.c
libpromises/prototypes3.h

https://lgtm.com/rules/1508604166004/

Changed several functions to be bool-correct

---

cf-agent/acl_posix.c
cf-agent/files_edit.c
cf-agent/files_edit.h
cf-agent/files_operators.c
cf-agent/files_operators.h
cf-agent/files_select.c
cf-agent/files_select.h
cf-agent/verify_databases.c
cf-agent/verify_environments.c
cf-agent/verify_files.c
cf-execd/cf-execd-runner.c
cf-serverd/server_classic.c
libcfnet/client_code.c
libcfnet/client_code.h
libcfnet/client_protocol.c
libcfnet/client_protocol.h
libpromises/cf-windows-functions.h
libpromises/exec_tools.h
libpromises/pipes_unix.c
libpromises/unix.c
libpromises/unix.h
libutils/hash.c
libutils/hash.h

https://lgtm.com/rules/1508604166004/
https://github.com/cfengine/core/pull/3706
https://github.com/cfengine/enterprise/pull/526

Changed several functions to use bool type correctly

---

tests/acceptance/02_classes/02_functions/isipinsubnet-valid-ip.cf

Test that isipinsubnet validates IPv4 addresses against 0.0.0.0/0

---

cf-agent/verify_users_stub.c
libenv/unix_iface.c
libpromises/evalfunction.c
travis-scripts/script.sh

Wait for: https://github.com/cfengine/core/pull/3714

Compile using -Wall and -Wextra in travis, and fixed related warnings

---

examples/reference_values_inside_data.cf

https://github.com/cfengine/documentation/pull/2164

CFE-3096: Added example showing how to reference data inside a data container

---

examples/eval.cf

(cherry picked from commit 2e9cd9a386c359e2316faac993f07c47b51b021b)

CFE-3097: Converted eval() example into example output test (3.12.x)

---

examples/eval.cf

(cherry picked from commit 2e9cd9a386c359e2316faac993f07c47b51b021b)

CFE-3097: Converted eval() example into example output test (3.10.x)

---

examples/sys_interfaces_ip_addresses_ipv4.cf

Ticket: CFE-3101
(cherry picked from commit d257930e2046c8df64d6fdb266efed0a3c7fecb0)

Added example showing iterating over sys.interfaces to show sys.ip_addresses (3.12.x)

---

examples/hostrange.cf

Merge Together:
https://github.com/cfengine/documentation/pull/2178

CFE-3104/master Improved hostrnage() function example

---

examples/hostrange.cf

Ticket: CFE-3104
(cherry picked from commit a3fb94669259609da1adcda9b82d739036f5c716)

Improved hostrnage() function example (3.12.x)

---

examples/hostrange.cf

Ticket: CFE-3104
(cherry picked from commit a3fb94669259609da1adcda9b82d739036f5c716)

Improved hostrnage() function example (3.10.x)

---

CONTRIBUTING.md

wip of changes I would like to suggest as I read carefully through CONTRIBUTING.md

CONTRIBUTING.md: proofreading changes

---

cf-agent/files_editline.c
cf-agent/verify_databases.c
cf-agent/verify_packages.c
libpromises/evalfunction.c

Also removed some FIXME's from the code regarding return values.
Decided to work down the LGTM list.

Changed some functions to be bool-correct

---

tests/acceptance/01_vars/02_functions/eval.cf

https://github.com/cfengine/core/pull/3777

CFE-2762/master Test that eval() does not round non 0 prefixed decimals to 1

---

cf-execd/Makefile.am
cf-serverd/Makefile.am
tests/acceptance/Makefile.am
tests/load/Makefile.am
tests/unit/Makefile.am

https://github.com/cfengine/core/pull/3782
https://github.com/cfengine/enterprise/pull/536

Automake: Corrected some confusion between CFLAGS and CPPFLAGS

---

.gitignore
Makefile.am
libutils/cleanup.c
tests/unit/Makefile.am

Split out from other PR to find error in mingw build.

ENT-4885: Smaller fixes in autotools / build files

---

contrib/agentsay/agentsay.py

```
$ fortune | agentsay
/-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-\
|                                                                           |
|               HOW MANY ZEN BUDDHIST DOES IT TAKE TO CHANGE A              |
|              LIGHT BULB?  TWO.  ONE TO CHANGE IT AND ONE NOT              |
|                               TO CHANGE IT.                               |
|                                                                           |
|                                   ● ● ●                                   |
|                                   ● ● ●                                   |
|                                                                           |
|                               ●   ● ● ●   ● …
```

agentsay: Accept input from stdin

---

libpromises/LMDB.md
libpromises/cf3.defs.h
libpromises/lastseen.h

I don't have time or energy to go through them all, but these
are the most important to document better. I'll revisit the
document once we have better tooling.

CFE-3125: Documented some of LMDB databases in markdown doc and comments

---

libpromises/dbm_lmdb.c

https://github.com/cfengine/core/pull/3820
https://github.com/cfengine/buildscripts/pull/614

LMDB corruption callback

---

libpromises/dbm_lmdb.c

https://github.com/cfengine/core/pull/3827
https://github.com/cfengine/buildscripts/pull/615

[3.12.x] LMDB assert callback

---

cf-check/diagnose.c

Cherry-picked from: https://github.com/cfengine/core/pull/3842

cf-check: Improve portability of --no-fork mode (3.12)

---

cf-check/Makefile.am
cf-check/db_structs.h
cf-check/dump.c
libutils/json.c
libutils/json.h
libutils/string_lib.h

Cherry-picked from: https://github.com/cfengine/core/pull/3828

CFE-2989: Human readable JSON5 dumping of LMDB databases (3.12)

---

libenv/unix_iface.c

CFE-682: IPv6 addresses are now added to policy variable sys.ip_addresses

---

tests/acceptance/00_basics/04_bundles/unless_bug.cf

See: https://github.com/cfengine/core/pull/3850

Added test_soft_fail to unless_bug.cf acceptance test

---

travis-scripts/valgrind.sh

See: https://github.com/cfengine/masterfiles/pull/1517

Travis: Adapted valgrind.sh to be usable in masterfiles repo

---

travis-scripts/valgrind.sh

See:
https://github.com/cfengine/masterfiles/commit/16598847a1910d645b73ff81a65bbfcc8aa0ff0e
https://github.com/cfengine/core/pull/3851

valgrind.sh: Fixed minor nitpick in comment

---

examples/missing_ok.cf

The docs render with some empty boxes, this change tries to fix that.

CFE-3168 Fix doc rendering

---

cf-net/cf-net.c
libcfnet/Makefile.am
libcfnet/cfnet.h
libcfnet/protocol.c
libcfnet/protocol.h

Creates a directory listing of a path on a remote host.
Ticket: CFE-3089

CFE-3089: New CFNet function OPENDIR

---

cf-agent/verify_processes.c
tests/acceptance/05_processes/process_stop.cf

https://github.com/cfengine/enterprise/pull/548

ENT-4988/master Fix process_command return code influencing promise result

---

examples/readintlist.cf
examples/readreallist.cf
examples/readstringlist.cf

https://github.com/cfengine/documentation/pull/2208

CFE-3172/master Separate examples for readstringlist(), readreallist(), and readintlist()

---

travis-scripts/after_script.sh

They seem to be a more reliable storage facility

Use file.io instead of transfer.sh

---

travis-scripts/after_script.sh

(cherry picked from commit 38e1e0c194b2b17c7d6e5a39a40f0a905051e432)

Use file.io instead of transfer.sh (3.12)

---

libenv/unix_iface.c

Previously MAC addresses would not be added to the sys.hardware_addresses
and the sys.hardware_mac variables if the interface contained only IPv6
addresses.

CFE-3164: Added MAC address to sys.hardware_(addresses,mac)

---

libcfnet/key.c

Just some smaller improvements to stack data type, alloc
header, queue, etc. Nothing which should affect behavior.
Also had to adjust one include to make the new version work.

libntech: Updated to master

---

cf-agent/tokyo_check.c
cf-check/backup.c
cf-check/dump.c
cf-check/repair.c
cf-check/utilities.c
cf-check/utilities.h
libpromises/dbm_api.c

Also fixed a bunch of includes in libntech and core.

Use StringMatchesOption() from libntech

---

cf-agent/nfs.c
cf-agent/nfs.h
cf-agent/verify_storage.c
libpromises/mod_storage.c

Forward-ported from: https://github.com/cfengine/core/pull/3893

Added support for CIFS and PanFS file systems to storage promise type

---

CONTRIBUTING.md

Follow-up from: https://github.com/cfengine/core/pull/3908

CFE-3177 - CONTRIBUTING.md: More detailed git workflow explanation

---

CONTRIBUTING.md

Follow-up from: https://github.com/cfengine/core/pull/3910

CONTRIBUTING.md: Addressed additional review comments

---

libpromises/dbm_lmdb.c

LMDB sometimes detects corruption and reports it by returning
MDB_CORRUPTED return code from its functions. We should handle
these cases just like other LMDB corruption cases.

Handle LMDB corruption when we get MDB_CORRUPTED

---

cf-agent/cf-agent.c
cf-agent/files_editline.c
cf-agent/files_editxml.c
libpromises/cf3.defs.h
libpromises/eval_context.c
libpromises/eval_context.h

3.12.x version of https://github.com/cfengine/core/pull/3922.

[3.12.x] Terminate gracefully when abortclasses are triggered

---

libcfnet/server_code.c

Using AI_NUMERICHOST for getaddrinfo() is an optimization that
allows us to avoid potential long DNS queries when doing bind()
in cf-server. However, it cannot be used if the bind address is a
host name and not an IP address.
This change makes it being used only in cases where the bind
address looks like an IPv4 address. If it doesn't, getaddrinfo()
will take care of resolving things. Please note that this flag is
just a hint for getaddrinfo(), not using it never changes the
results (using it potentiall does).
Ticket: CFE-3190
Changelog: Allow using hostname in bindtoaddress

Only use AI_NUMERICHOST for what looks like an IPv4 address

---

libcfnet/server_code.c

Using AI_NUMERICHOST for getaddrinfo() is an optimization that
allows us to avoid potential long DNS queries when doing bind()
in cf-server. However, it cannot be used if the bind address is a
host name and not an IP address.
This change makes it being used only in cases where the bind
address looks like an IPv4 address. If it doesn't, getaddrinfo()
will take care of resolving things. Please note that this flag is
just a hint for getaddrinfo(), not using it never changes the
results (using it potentiall does).
Ticket: CFE-3190
Changelog: Allow using hostname in bindtoaddress
(cherry picked from commit 1db94931400983bfcc739c0cb783e130d7c88e9f)

[3.12.x] Only use AI_NUMERICHOST for what looks like an IPv4 address

---

libenv/unix_iface.c

This reverts commit c40f502486f845f16999f9797d341faa04168107
which broke tests on AIX.

Revert "CFE-3046: Only add unique IPv4 interfaces to sys.interfaces"

---

cf-net/cf-net.c
libcfnet/protocol.c
libcfnet/protocol.h
libcfnet/stat_cache.c
libcfnet/stat_cache.h
tests/acceptance/26_cf-net/serial/cf-net_stat_deny.cf

A simpler, non-cached version of `cf_remote_stat`. Might need some more proofing, as well as maybe supporting links.

CFE-3088: New stat function, ProtocolStat

---

cf-net/cf-net.c

https://tracker.mender.io/browse/CFE-3201

CFE-3201: Removed error code from failed to connect message in cf-net

---

examples/basename.cf

https://github.com/cfengine/documentation/pull/2261
Ticket: CFE-3196

CFE-3196/master: Added example showing usage of new function basename()

---

contrib/cf-remote/cf_remote/demo.py

Makes it easier to test / demo federated reporting.

cf-remote: Added FR dependencies to --demo def.json

---

contrib/cf-remote/cf_remote/commands.py

So that there is a better chance they will be unique.

Use more info for VM names in 'cf-remote spawn'

---

configure.ac
misc/Makefile.am
misc/determine-version.py
misc/selinux/Makefile.am
misc/selinux/cfengine-enterprise.fc
misc/selinux/cfengine-enterprise.te

https://github.com/cfengine/buildscripts/pull/632
https://github.com/cfengine/core/pull/3913
https://github.com/cfengine/enterprise/pull/558
https://github.com/cfengine/nova/pull/1539

[3.12.x] RHEL 8

---

cf-agent/verify_users_pam.c
docs/BSD.md

Based on review comment:
https://github.com/cfengine/core/pull/3589#discussion_r344640531

FreeBSD: Changed ifdef guard to be OS-specific

---

cf-check/Makefile.am
cf-check/diagnose.c
cf-check/diagnose.h
cf-check/repair.c
cf-check/validate.c
cf-check/validate.h
libpromises/Makefile.am
tests/unit/Makefile.am

CFE-2988: cf-check: Added data validation for cf_lastseen.lmdb

---

cf-check/diagnose.c
cf-check/repair.c
cf-check/validate.c

Fixes:
https://tracker.mender.io/browse/ENT-5309
https://tracker.mender.io/browse/CFE-2988

cf-check: Added timestamp validation and fixed various smaller issues

---

cf-check/diagnose.c
cf-check/repair.c
cf-check/validate.c

cf-check: Added timestamp validation and fixed various smaller issues (3.12)

---

cf-check/diagnose.c
cf-check/repair.c
cf-check/validate.c

cf-check: Added timestamp validation and fixed various smaller issues (3.15)

---

libenv/unix_iface.c

The finished PR for CFE-3046. This is the same commit as in: https://github.com/cfengine/core/pull/4027

CFE-3046: Only add unique Ipv4 and MAC address to sys variables

---

libpromises/cf3lex.l
tests/acceptance/00_basics/macros/if.cf

No conflicts, just cherry-picked all the commits from the macro PRs.
Cherry-picked from:
https://github.com/cfengine/core/pull/4052
https://github.com/cfengine/core/pull/4055
https://github.com/cfengine/core/pull/4062

Added macros: maxmium_version, between_version, before_version, after_version, at_version (3.15)

---

cf-serverd/cf-serverd-functions.c
cf-serverd/server.c
cf-serverd/server.h
cf-serverd/server_transform.c
libpromises/eval_context.c
libpromises/eval_context.h

https://github.com/cfengine/core/pull/4076
https://github.com/cfengine/enterprise/pull/586

ENT-5313: Added file flag to enable reporting dumps in enterprise

---

libpromises/evalfunction.c
tests/acceptance/01_vars/02_functions/cf_version.cf
tests/acceptance/01_vars/02_functions/cf_version.cf.expected.json

CFE-3197: New version convenience functions

---

libpromises/generic_agent.c
libpromises/generic_agent.h

A logical counterpart to the WritePID() function.
https://github.com/cfengine/core/pull/4075
https://github.com/cfengine/nova/pull/1614

Add a function to read PID from a PID file

---

examples/cf_version_after.cf
examples/cf_version_at.cf
examples/cf_version_before.cf
examples/cf_version_between.cf
examples/cf_version_maximum.cf
examples/cf_version_minimum.cf

CFE-3197: Added examples for cf_version functions

---

examples/validdata.cf
examples/validjson.cf
libpromises/evalfunction.c

Also fixed wrong return type for `validjson`

CFE-2898: validdata/validjson examples

---

cf-promises/cf-promises.c
cf-serverd/server_common.c
libenv/unix_iface.c
libpromises/evalfunction.c
libpromises/fncall.c
tests/acceptance/testall

@karlhto Here is my first attempt at this. As we discussed, there are some problems with libtool, LD_PRELOAD, etc. I was able to run the tests, and find a lot of issues. 
Some rough instructions:
```
make CFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address" -j8
sudo make install
cd tests/acceptance
BINDIR="/var/cfengine/bin" PRELOAD_ASAN="/usr/lib/gcc/x86_64-linux-gnu/7/libasan.so" ./testall
```

Fixed issues found by running Acceptance tests with ASan

---

cf-agent/files_editline.c
cf-agent/verify_files.c
libpromises/evalfunction.c

Various memory leak fixes using ASan (Address Sanitizer)

---

configure.ac
examples/variablesmatching.cf
libenv/sysinfo.c

https://github.com/cfengine/core/pull/4110
https://github.com/cfengine/buildscripts/pull/707

sys.cf_version_release

---

cf-agent/verify_methods.c
libpromises/eval_context.c
libpromises/evalfunction.c
libpromises/expand.c
libpromises/generic_agent.c
libpromises/rlist.c
libpromises/rlist.h
libpromises/var_expressions.c
libpromises/variable.c
libpromises/variable.h
tests/unit/variable_test.c

https://github.com/cfengine/core/pull/4124
https://github.com/cfengine/enterprise/pull/607

CFE-3297: Make the 'Variable' struct private

---

tests/acceptance/10_files/templating/cftemplate.cf

CFE-270/master: Activated test making sure classic templates do not add extra newlines

---

contrib/masterfiles-stage/README.org
contrib/masterfiles-stage/install-masterfiles-stage.sh

Github doesn't present a name that allows you to fetch raw content:
```
ERROR: certificate common name “www.github.com” doesn’ match requested host name "raw.githubusercontent.com".
To connect to raw.githubusercontent.com insecurely, use --no-check-certificate
```

Switched to curl for masterfiles-stage install script and instructions

---

tests/acceptance/01_vars/01_basic/CFE-628.cf
tests/acceptance/01_vars/01_basic/CFE-628.cf.sub

CFE-628/master: Added test for expected output

---

tests/acceptance/01_vars/01_basic/CFE-628.cf
tests/acceptance/01_vars/01_basic/CFE-628.cf.sub

CFE-628/3.15.x: Added test for expected output

---

tests/acceptance/01_vars/01_basic/CFE-628.cf
tests/acceptance/01_vars/01_basic/CFE-628.cf.sub

CFE-628/3.12.x: Added test for expected output

---

tests/acceptance/01_vars/01_basic/CFE-2191.cf

Ticket: CFE-2191
(cherry picked from commit 14798359882789b4d0b80348ccf0a5d8da90b51b)

CFE-2191/3.15.x: Added test

---

tests/acceptance/01_vars/01_basic/CFE-2191.cf

Ticket: CFE-2191
(cherry picked from commit 14798359882789b4d0b80348ccf0a5d8da90b51b)

CFE-2191/3.12.x: Added test

---

CONTRIBUTING.md

Only in commits. Not in PR descriptions.

Added where changelog entries are discovered

---

misc/init.d/cfengine3.in

ENT-5528/3.12.x: Fixed service status cfengine3 on systemd managed hosts

---

tests/acceptance/02_classes/01_basic/if_resolving_classexpression_from_datacontainer.cf

CFE-3319/master: Test that if can check a class expression from a data container

---

INSTALL

Add some examples of how to install needed dependencies for FreeBSD and SUSE. TODO: debian, redhat, hp-ux, ???

Added dependency one-liners for various systems

---

examples/storage-cifs.cf

https://github.com/cfengine/documentation/pull/2311

CFE-3187/master: Added example illustrating use of cifs mount_type

---

examples/template_method-inline_mustache.cf

Ticket: ENT-5966
(cherry picked from commit c9192bd3339125ff4a4815a86117a76f51166992)
----
#

ENT-5966/3.15.x: Added example illustrating template_method => "inline_mustache"

---

examples/template_method-inline_mustache.cf

Ticket: ENT-5966
(cherry picked from commit c9192bd3339125ff4a4815a86117a76f51166992)
----
#

ENT-5966/3.12.x: Added example illustrating template_method => "inline_mustache"

---

examples/mustache_classes.cf

It makes the docs ugly.
----
#

Removed extra lines from test

---

examples/mustache_classes.cf

Working toward improved rendering of example.
https://docs.cfengine.com/docs/master/guide-faq-mustache-templating.html#how-do-i-use-class-expressions
----
#

Wrapped example output in backticks for improved rendering

---

libpromises/pipes.c
libpromises/pipes.h
libpromises/pipes_unix.c

https://github.com/cfengine/core/pull/4180
https://github.com/cfengine/enterprise/pull/616

Add option to use FILE * streams with cf_popen_full_duplex

---

libpromises/cf3parse_logic.h

No change in behavior. Separate PR to split up test and review.

CFE-3273: Preparations for custom promise types (SeqSplit and parser refactoring)

---

libpromises/Makefile.am
libpromises/dbm_api.c
libpromises/dbm_api.h
libpromises/dbm_api_types.h
libpromises/dbm_lmdb.c
libpromises/dbm_priv.h
libpromises/dbm_quick.c
libpromises/dbm_tokyocab.c
libpromises/locks.c
tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/defaults.cf

Remove race condition in WaitForCriticalSection()

---

libpromises/Makefile.am
libpromises/dbm_api.c
libpromises/dbm_api.h
libpromises/dbm_api_types.h
libpromises/dbm_lmdb.c
libpromises/dbm_priv.h
libpromises/dbm_quick.c
libpromises/dbm_tokyocab.c
libpromises/locks.c
tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/defaults.cf

[3.15.x] Remove race condition in WaitForCriticalSection()

---

tests/acceptance/01_vars/02_functions/ifelse_isvariable-ENT-4653.cf

Adjusted ifelse/ENT-4653 test to report properly

---

.lgtm/cpp-queries/bool-type-mismatch-return.ql

Something that is explicitly typecast to bool, should be
considered bool, and something that is typecast to something else
should not be considered bool.
There were some false positives, mainly because the CodeQL type
`CStyleCast` includes implicit casts, and actually focusing on
and checking only explicit casts proved to be quite difficult.
After some trial and error, I found a version that works, but
I don't fully understand the behavior of here.
Tested query locally, using VSCode extension and instructions:
https://help.semmle.com/codeql/codeql-for-vscode/procedures/setting-up.html
Confirmed that this removes the 5 false positives we had, while
keeping the 20 true positives.

LGTM: Fixed false positives in bool type mismatch query

---

INSTALL

Fixed typo in alpine dependency one-liner

---

cf-agent/verify_files.c
libpromises/eval_context.c
libpromises/eval_context.h
libpromises/expand.c
libpromises/expand.h
libpromises/fncall.c
libpromises/fncall.h
tests/acceptance/10_files/this_promiser.cf

Outcome classes for promiser in files promises

---

cf-agent/cf-agent.c

Reports generation only happens if there is exactly one
'cf-agent' process running (to avoid corruptions in the reporting
data). If some promise in the policy uses an action policy with
'background => true', there might still be a forked child process
evaluating the promise when the main process reaches the point
when it wants to generate reports. In such cases, it is important
that the main process waits for the forked child processes.
Ticket: ENT-6042
Changelog: Promises with 'action => bg()' no longer break reporting data
(cherry picked from commit 3d9abd5cb4a21a920d5c6c9c6e25946533e132e9)

[3.15.x] Wait for background processes before generating reports

---

cf-agent/verify_exec.c

Just a small mistake from previous PR.

CFE-3379: Stopped printing background log message on windows

---

tests/acceptance/01_vars/02_functions/findfiles-GLOB_BRACE.cf

Mergetogether:
https://github.com/cfengine/libntech/pull/64
Ticket: CFE-3292

Added test for GLOB_BRACE with findfiles()

---

tests/acceptance/17_users/unsafe/10_modify_user_with_many_attributes.cf
tests/acceptance/17_users/unsafe/10_modify_user_with_many_attributes_warn.cf

ENT-5335 Typo fix: no comma after promisee

---

libpromises/evalfunction.c
libpromises/exec_tools.c
libpromises/exec_tools.h
libpromises/pipes.h
libpromises/pipes_unix.c
tests/acceptance/01_vars/02_functions/execresult_select.cf

https://github.com/cfengine/core/pull/4261
https://github.com/cfengine/enterprise/pull/629
https://github.com/cfengine/nova/pull/1694

CFE-3108: Selecting stdout / stderr / both for execresult output

---

examples/execresult_as_data.cf
libpromises/evalfunction.c
libpromises/exec_tools.c
libpromises/exec_tools.h

https://github.com/cfengine/core/pull/4268
https://github.com/cfengine/nova/pull/1695
https://github.com/cfengine/documentation/pull/2344

CFE-3315: Added execresult_as_data()

---

.gitignore
Makefile.am
cf-agent/cf-agent.c
cf-agent/package_module.c
cf-agent/verify_environments.c
cf-monitord/history.c
configure.ac
libenv/sysinfo.c
libpromises/syntax.c
tests/static-check/Makefile.am
tests/static-check/cppcheck_suppressions.txt
tests/static-check/run.sh
tests/static-check/run_checks.sh

Also fixed the issues the checks found.

Add a simple way to run static checks on the sources

---

docs/custom_promise_types/cfengine.py
docs/custom_promise_types/git_from_scratch.py
docs/custom_promise_types/git_using_lib.py
docs/custom_promise_types/json_based.input
docs/custom_promise_types/json_based.output
docs/custom_promise_types/line_based.input
docs/custom_promise_types/line_based.output
docs/custom_promise_types/modules.md
docs/custom_promise_types/test.cf

Already reviewed by several people in other PR. Putting this in separate PR so we can get it merged, and link to it in master branch.
Moved out from:
https://github.com/cfengine/core/pull/4137
JIRA Ticket:
https://tracker.mender.io/browse/CFE-3273

CFE-3273: Custom Promise Types - Specification

---

cf-agent/files_changes.c

No need to write to the DB if there is no change.

[3.15.x]  Only write directory listing if it changes

---

tests/acceptance/01_vars/02_functions/network/selectservers.cf

(cherry picked from commit ee1d03fbd06e95062bfd295486bc923790603649)

Adjusted to more reliable list of servers (for now)

---

cf-agent/acl_posix.c
libcfnet/client_code.c
libenv/sysinfo.c
libenv/unix_iface.c
libpromises/evalfunction.c
libpromises/patches.c

CFE-3285 Various changes for termux environment.

---

contrib/enterprise/report.pl

So that it can be used with a hub using a self-signed
certificate.

Add a new '--insecure' option to report.pl

---

.gitignore
cf-monitord/Makefile.am
cf-monitord/get_socket_info.c
cf-monitord/mon_network.c
cf-monitord/proc_net_parsing.c
cf-monitord/proc_net_parsing.h
libutils/file_lib.c
libutils/file_lib.h

[3.12.x] socket info from proc net

---

configure.ac
tests/Makefile.am
tests/valgrind-check/Containerfile
tests/valgrind-check/Makefile.am
tests/valgrind-check/run.sh
tests/valgrind-check/run_checks.sh
tests/valgrind-check/valgrind.sh

Adapted from the Travis test. Community only for now,
enterprise will require some extra work.
Conflicts:
Related to static-check which is missing on 3.15.x
(cherry picked from commit 58ce156b766c5492ff8b4763c9b096abe543962c)

ENT-5553: Added valgrind test using Ubuntu 20 container (3.15)

---

cf-agent/files_changes.c
cf-agent/verify_exec.c
cf-agent/verify_packages.c
libpromises/eval_context.c
libpromises/keyring.c
libpromises/lastseen.c

Still some more warnings remaining, but this should be okay to merge as is.

CFE-3409: Fixed truncation issues / warnings

---

cf-agent/verify_databases.c
cf-agent/verify_files.c
cf-execd/cf-execd-runner.c
cf-monitord/mon_network_sniffer.c
cf-runagent/cf-runagent.c
cf-serverd/server_classic.c
cf-serverd/server_common.c
libpromises/enterprise_stubs.c
libpromises/prototypes3.h
tests/static-check/run_checks.sh

https://github.com/cfengine/core/pull/4308
https://github.com/cfengine/enterprise/pull/631
https://github.com/cfengine/nova/pull/1710

CFE-3409: Fixed format truncation warnings

---

contrib/cf-remote/cf_remote/cloud_data.py

So that it can spawn such VMs.

Add Debian 10 x86_64 as a supported platform to cf-remote

---

cf-agent/verify_users_pam.c

Found by running valgrind agent run on a demo hub.

Fixed memory leak in users promises

---

docs/cf_remote_demo.sh

I use this quite often when I want to test or demo something on a real setup.

Added demo script for testing CFEngine on a group of hosts

---

tests/acceptance/29_audit_mode/audit_safe_functions.cf
tests/acceptance/29_audit_mode/audit_safe_functions.cf.sub

Added test for unsafe functions not evaluating in --audit mode

---

libpromises/mod_custom.c

Also added a helpful debug message.

Custom promise types: Fixed memory leak

---

cf-promises/cf-promises.c
libpromises/generic_agent.c

Found by running acceptance tests with ASAN.

CFE-3461: Fixed small memory leak in cf-promises

---

cf-execd/cf-execd-runner.c
cf-execd/exec-config.c
libenv/unix_iface.c
libpromises/generic_agent.c

https://github.com/cfengine/core/pull/4352
https://github.com/cfengine/enterprise/pull/639

libntech: Changes needed for use in Mender

---

cf-agent/verify_users_pam.c
cf-execd/cf-execd-runner.c
cf-execd/exec-config.c
cf-serverd/server_common.c
libenv/unix_iface.c
libpromises/generic_agent.c

https://github.com/cfengine/core/pull/4356
https://github.com/cfengine/enterprise/pull/640

Backports: libntech, nt_static_assert, pcre, etc. (3.15)

---

.gitignore
cf-agent/Makefile.am
cf-agent/audit_mode.c
cf-agent/audit_mode.h
cf-agent/cf-agent.c
cf-agent/manifest_file.c
cf-agent/verify_files.c
cf-agent/verify_files_utils.c
libpromises/changes_chroot.c
libpromises/changes_chroot.h
libpromises/files_lib.c
libpromises/files_lib.h
libpromises/generic_agent.c
tests/acceptance/28_inform_testing/01_files/copy_from03.cf.expected

--audit=manifest mode

---

tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/defaults.cf

ENT-6200 Disable flaky test on Solaris 11, also

---

cf-agent/audit_mode.c
cf-agent/audit_mode.h
cf-agent/cf-agent.c

ENT-5294: --audit=diff mode

---

cf-check/cf-check.c
cf-execd/cf-execd.c
cf-key/cf-key.c
cf-monitord/cf-monitord.c
cf-promises/cf-promises.c
cf-runagent/cf-runagent.c
cf-secret/cf-secret.c
cf-serverd/cf-serverd.c
cf-testd/cf-testd.c

https://github.com/cfengine/core/pull/4369
https://github.com/cfengine/nova/pull/1725

Call cleanup functions in binaries' main()

---

cf-check/cf-check.c
cf-execd/cf-execd.c
cf-key/cf-key.c
cf-monitord/cf-monitord.c
cf-promises/cf-promises.c
cf-runagent/cf-runagent.c
cf-secret/cf-secret.c
cf-serverd/cf-serverd.c
cf-testd/cf-testd.c

Cherry-picked commits from #4369 
https://github.com/cfengine/core/pull/4380
https://github.com/cfengine/nova/pull/1727

[3.15.x] Call cleanup functions in binaries' main()

---

cf-check/cf-check.c
cf-execd/cf-execd.c
cf-key/cf-key.c
cf-monitord/cf-monitord.c
cf-promises/cf-promises.c
cf-runagent/cf-runagent.c
cf-serverd/cf-serverd.c
cf-testd/cf-testd.c

Backport of #4369 
https://github.com/cfengine/core/pull/4381
https://github.com/cfengine/nova/pull/1728

[3.12.x] Call cleanup functions in binaries' main()

---

contrib/cf-remote/cf_remote/commands.py
contrib/cf-remote/cf_remote/main.py
contrib/cf-remote/cf_remote/spawn.py
contrib/cf-remote/cf_remote/utils.py

Support for spawning VMs in GCP in `cf-remote spawn` and some small improvements to make things faster or at least better reported.

CFE-3477 cf-remote gcp

---

libenv/sysinfo.c

"OS type" was changed to "Kernel", "OS kernel" was changed to "Kernel Release".
Ticket: ENT-6551

ENT-6551/master: Changed sys var attribute names

---

libpromises/evalfunction.c

When I reached the Balmer peak, I found this shitty log message.
BDFN said it was ugly, so here you go.

Remove un-necessary stuff from log message

---

docs/custom_promise_types/cfengine.py
docs/custom_promise_types/git_using_lib.py
docs/custom_promise_types/test.cf
libpromises/mod_custom.c
tests/acceptance/30_custom_promise_types/01_basic_module.cf
tests/acceptance/30_custom_promise_types/example_module.sh

Support for result classes from promise modules.

Promise module result classes

---

contrib/cf-remote/cf_remote/main.py

Added possible logging levels to cf-remote --help

---

contrib/cf-remote/cf_remote/remote.py

Introduced in:
8b3f2dd1f31832980e2fa66a3cdcf94ba2e63549

ENT-6633 cf-remote: Fixed bug with package selection

---

.github/workflows/asan_unit_tests.yml
.github/workflows/macos_unit_tests.yml

Enabling ASAN on MacOS will require some more work, but this gets us halfway there.

CFE-3540: GitHub Actions: Added MacOS Unit Tests

---

contrib/vagrant-ci/centos-7-x64/Vagrantfile

Fixed vm-check libxml dependency package name

---

cf-agent/simulate_mode.c

CFE-3521: Added checks to return value from getpwuid & getgrgid

---

libpromises/mod_files.c

CFE-3541/master: Clarified description of depth_search xdev attribute behavior

---

libpromises/mod_files.c

Ticket: CFE-3541
(cherry picked from commit 7be9b3bd82ac9ebc06b375017d12bc7bebda25f5)

CFE-3541/3.15.x: Clarified description of depth_search xdev attribute behavior

---

libpromises/mod_files.c

Ticket: CFE-3541
(cherry picked from commit 7be9b3bd82ac9ebc06b375017d12bc7bebda25f5)

CFE-3541/3.12.x: Clarified description of depth_search xdev attribute behavior

---

docs/custom_promise_types/site_up.cf

ENT-6616/master: Added policy illustrating use of site_up promise type

---

cf-execd/Makefile.am
cf-execd/cf-execd-runagent.c
cf-execd/cf-execd-runagent.h
cf-execd/cf-execd.c
configure.ac
misc/selinux/cfengine-enterprise.te
tests/acceptance/25_cf-execd/mailfilter_common.cf.sub

https://github.com/cfengine/core/pull/4453
https://github.com/cfengine/masterfiles/pull/1891

Support for hailing agents with cf-runagent via cf-execd 

---

examples/inline-yaml.cf

CFE-3551/master: Added example illustrating inline yaml

---

docs/custom_promise_types/modules.md

Custom Promise Types: Added result_classes to specification

---

cf-agent/verify_files_utils.c
cf-execd/cf-execd-runagent.c
cf-execd/cf-execd.c
cf-monitord/mon_network.c
cf-monitord/mon_network_sniffer.c
cf-secret/cf-secret.c
cf-serverd/cf-serverd-functions.c
cf-serverd/server_classic.c
cf-serverd/server_tls.c
cf-serverd/server_transform.c
libpromises/dbm_lmdb.c
libpromises/dbm_priv.h

Fixed remaining sign compare warnings

---

libpromises/dbm_lmdb.c

There seems to be a race condition causing mdb_txn_begin() to
return EINVAL in very rare cases. These changes implement a retry
mechanism (5 attempts) to mitigate issues caused by the failure.
Ticket: ENT-6527

Implement retries for mdb_txn_begin() in case of EINVAL

---

examples/inline-json.cf

CFE-3551/master: Added inline json example

---

CONTRIBUTING.md

CFE-3582/master: Added note about how to cancel Changelog entries

---

libpromises/generic_agent.c

CFE-3599/master: Clarified error log message about untrusted state directory not being private

---

libpromises/generic_agent.c

Ticket: CFE-3599
(cherry picked from commit 219640670c9e7798b3693c7c0329d58607534f2b)

CFE-3599/3.15.x: Clarified error log message about untrusted state directory not being private

---

libpromises/generic_agent.c

Ticket: CFE-3599
(cherry picked from commit 219640670c9e7798b3693c7c0329d58607534f2b)

CFE-3599/3.12.x: Clarified error log message about untrusted state directory not being private

---

docs/custom_promise_types/rss.cf
docs/custom_promise_types/rss.py

CFE-3518: Added rss example promise module

---

cf-agent/retcode.c

CFE-3604/master: Improved log messages for commands promise outcomes and return codes

---

libcfnet/server_code.c
libpromises/Makefile.am
misc/systemd/cf-serverd.socket

Follow-up for #4499 to avoid torturing @peckpeck in that PR longer than necessary. :)

Polish the the systemd-based socket activation code a bit

---

libenv/sysinfo.c
tests/acceptance/01_vars/01_basic/os_name_human.cf

CFE-3569: Added policy variable sys.os_name_human

---

tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/defaults.cf
tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/package_lock.cf

ENT-6939 Skip often-failing acceptance tests

---

tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/defaults.cf
tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/package_lock.cf

ENT-6939 Skip often-failing acceptance tests - 3.12.x

---

tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/defaults.cf
tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/package_lock.cf

ENT-6939 Skip often-failing acceptance tests - 3.15.x

---

docs/custom_promise_types/groups_experimental.cf
docs/custom_promise_types/groups_experimental.py

CFE-3570: Added groups promises prototype

---

docs/custom_promise_types/modules.md

Describe how 'classes' is handled with custom promise types

---

tests/acceptance/17_users/unsafe/user_queries.cf.sub

ENT-6975 Update user/group tests for latest suse

---

CONTRIBUTING.md

Added switch-case fall through code style guideline

---

cf-runagent/cf-runagent.c
cf-serverd/server_common.c

[3.15.x] cf-runagent exit code based on remote agent runs results

---

cf-agent/cf-agent.c

https://github.com/cfengine/core/pull/4592
https://github.com/cfengine/masterfiles/pull/1961

files_single_copy body agent control attribute handling fixes

---

cf-agent/cf-agent.c
cf-agent/verify_files_utils.c
cf-agent/verify_files_utils.h

3.15.x backport of #4589 and #4592.

[3.15.x] single copy list fixes

---

cf-agent/cf-agent.c
cf-agent/verify_files_utils.c
cf-agent/verify_files_utils.h

3.12.x backport of #4589 and #4592.

[3.12.x] single copy list fixes

---

cf-serverd/server_classic.c
libcfnet/misc.c
libpromises/actuator.c
libpromises/cf3parse_logic.h
libpromises/evalfunction.c
libpromises/generic_agent.c
libpromises/item_lib.c
libpromises/rlist.c
tests/static-check/run_checks.sh

CFE-3416: Fixed implicit fallthrough compiler warnings on multiple files

---

libcfnet/misc.c

Removed commented out function in libcfnet/misc.c

---

libenv/sysinfo.c
tests/acceptance/01_vars/01_basic/os_version_major.cf
tests/unit/sysinfo_test.c

CFE-3569: Added policy variable sys.os_version_major

---

tests/acceptance/01_vars/01_basic/os_version_major.cf

Added SUSE 11 to os_version_major acceptance test

---

tests/acceptance/01_vars/01_basic/os_version_major.cf

Added RHEL 5 to os_version_major acceptance test

---

libpromises/pipes_unix.c

CFE-3625: Set Filedescriptor Limit to a more practical Size

---

libpromises/mod_custom.c
tests/acceptance/.gitignore
tests/acceptance/30_custom_promise_types/13_binary_path.cf
tests/acceptance/30_custom_promise_types/custom_promise_binary.c
tests/acceptance/Makefile.am

If interpreter provided with no path attribute then error.
Ticket: CFE-3562

CFE-3562 Changed custom promise type interpreter attribute to be optional

---

examples/inherit_from.cf
examples/inherit_from_classes.cf

CFE-3636: Added examples illustrating inherit_from (master)

---

examples/findfiles_up.cf

CFE-3577: Added example for policy function findfiles_up

---

examples/string.cf
libpromises/evalfunction.c
tests/acceptance/01_vars/02_functions/string.cf

CFE-3476: Added string() policy function

---

examples/int.cf
libpromises/evalfunction.c
tests/acceptance/01_vars/02_functions/int.cf

CFE-3616: Added int() policy function

---

examples/inherit_from.cf
examples/inherit_from_classes.cf

Ticket: CFE-3636
(cherry picked from commit 4528cbc7b5e1df1d0e15545a605bdc1e05805e1b)

CFE-3636: Added examples illustrating inherit_from (3.15)

---

examples/int.cf

Tweaked int.cf example report to be more formal

---

tests/acceptance/01_vars/01_basic/os_version_major.cf

Rework acceptance test for `sys.os_version_major` to be more dynamic
Ticket: CFE-3644

CFE-3644: Rework acceptance test for `sys.os_version_major`

---

cf-agent/verify_files.c
tests/acceptance/28_inform_testing/01_files/changes01.cf.expected
tests/acceptance/28_inform_testing/01_files/changes02.cf.expected
tests/acceptance/28_inform_testing/01_files/copy_from01.cf.expected
tests/acceptance/28_inform_testing/01_files/copy_from02.cf.expected
tests/acceptance/28_inform_testing/01_files/copy_from03.cf.expected
tests/acceptance/28_inform_testing/01_files/create.cf.expected
tests/acceptance/28_inform_testing/01_files/delete-dir.cf.expected
tests/acceptance/28_inform_testing/01_files/delete.cf.expected
tests/acceptance/28_inform_testing/01_files/edit_line01.cf.expected
tests/acceptance/28_inform_testing/01_files/edit_line02.cf.expected
tests/acceptance/28_inform_testing/01_files/edit_line03.cf.expected
tests/acceptance/28_inform_testing/01_files/edit_line04.cf.expected
tests/acceptance/28_inform_testing/01_files/edit_line05.cf.expected
tests/acceptance/28_inform_testing/01_files/edit_xml01.cf.expected
tests/acceptance/28_inform_testing/01_files/edit_xml02.cf.expected
tests/acceptance/28_inform_testing/01_files/edit_xml03.cf.expected
tests/acceptance/28_inform_testing/01_files/edit_xml04.cf.expected
tests/acceptance/28_inform_testing/01_files/edit_xml05.cf.expected
tests/acceptance/28_inform_testing/01_files/edit_xml06.cf.expected
tests/acceptance/28_inform_testing/01_files/edit_xml07.cf.expected
tests/acceptance/28_inform_testing/01_files/edit_xml08.cf.expected
tests/acceptance/28_inform_testing/01_files/edit_xml09.cf.expected
tests/acceptance/28_inform_testing/01_files/perms.cf.expected
tests/acceptance/28_inform_testing/01_files/rename_newname.cf.expected
tests/acceptance/28_inform_testing/01_files/rename_rotate.cf.expected
tests/acceptance/28_inform_testing/01_files/touch.cf.expected
tests/acceptance/28_inform_testing/01_files/transformer.cf.expected

CFE-3631: Changed files promise repaired log level to verbose

---

tests/acceptance/testall

CFE-3669: Added check to fail errorexit tests that dont report errors

---

cf-agent/verify_files.c
cf-agent/verify_files_utils.c

All identified while working on CFE-3578.

'files' promises results fixes

---

examples/parseintarray.cf
examples/parserealarray.cf
examples/parsestringarray.cf

merge together: https://github.com/cfengine/documentation/pull/2455

CFE-3673: Made separate and complete examples for parse*array functions (master)

---

examples/complicated_cpu_bound_benchmark.cf

CFE-3663: Policy for complicated CPU bound benchmarking

---

.gitignore
libpromises/mod_custom.c
tests/acceptance/30_custom_promise_types/17_early_module_failure.cf
tests/acceptance/30_custom_promise_types/17_early_module_failure.cf.sub
tests/acceptance/30_custom_promise_types/18_early_module_failure_classes.cf
tests/acceptance/30_custom_promise_types/bad_import.py

Fixes for custom promise early failures

---

cf-agent/cf-agent.c
cf-execd/cf-execd.c
cf-key/cf-key.c
cf-monitord/cf-monitord.c
cf-promises/cf-promises.c
cf-runagent/cf-runagent.c
cf-serverd/cf-serverd-functions.c
cf-serverd/cf-serverd.c
libpromises/generic_agent.c
libpromises/generic_agent.h

https://github.com/cfengine/core/pull/4693
https://github.com/cfengine/enterprise/pull/661
https://github.com/cfengine/nova/pull/1766

Make sure program name is used as identifier in syslog

---

misc/selinux/cfengine-enterprise.te

Needed for our apache process to work properly.

Two additional SELinux allow rules

---

misc/custom_promise_types/cfengine.py
tests/acceptance/30_custom_promise_types/07_python_library.cf
tests/acceptance/30_custom_promise_types/09_log_level.cf.sub
tests/acceptance/30_custom_promise_types/copy_promises.py

Copied from:
https://github.com/cfengine/modules/blob/master/libraries/python/cfengine.py
See:
https://github.com/cfengine/modules/pull/6
https://github.com/cfengine/modules/pull/7

cfengine.py: Updated from upstream

---

misc/custom_promise_types/cfengine.py

See:
https://github.com/cfengine/modules/pull/9

cfengine.py: Add support for int attributes in promise types

---

contrib/vagrant-ci/centos-7-x64/Vagrantfile

Needed to build and install lcov build packages.

Add two packages to install in vagrant-ci/centos-7-x64/Vagrantfile

---

tests/unit/process_test.c

The test forks a child process which confuses the test framework
the other tests use.
Ticket: ENT-7249

Use simple custom testing helpers in tests/unit/process_test.c

---

tests/unit/logging_test.c

Ticket: CFE-3538
Signed-off-by: Ole Herman Schumacher Elgesem <ole@northern.tech>
(cherry picked from commit f5911649440dbb7bd3219e7427efb6bbb4c74824)

CFE-3538: Fixed memory leak in logging_test (3.15)

---

INSTALL

Update INSTALL with dependencies for termux, centos 7 and raspbian

---

libpromises/cf3parse.y
libpromises/cf3parse_logic.h

CFE-3639: Moved litem logic to ParserHandleListItem function

---

misc/systemd/cf-apache.service.in
misc/systemd/cf-execd.service.in
misc/systemd/cf-hub.service.in

Reverting this commit: https://github.com/cfengine/core/commit/ce2862bfc3f8c864c5335d25dd9a6ff15cfe120a
https://github.com/cfengine/core/pull/4314
https://github.com/cfengine/masterfiles/pull/1699

ENT-5125 Reverted cf-hub systemd Requires cf-postgres in systemd unit

---

misc/systemd/cf-apache.service.in
misc/systemd/cf-execd.service.in
misc/systemd/cf-hub.service.in

merge together
https://github.com/cfengine/core/pull/4737
https://github.com/cfengine/masterfiles/pull/2017

ENT-5125 Reverted cf-hub systemd Requires cf-postgres in systemd unit (3.18.x)

---

misc/systemd/cf-apache.service.in
misc/systemd/cf-execd.service.in
misc/systemd/cf-hub.service.in

merge together
https://github.com/cfengine/core/pull/4737
https://github.com/cfengine/masterfiles/pull/2018

ENT-5125 Reverted cf-hub systemd Requires cf-postgres in systemd unit (3.15.x)

---

libpromises/evalfunction.c

CFE-2546: Extended hostsseen() policy function to return host keys

---

README.md

ENT-6713 Change travis badges to .com instead of .org

---

examples/rxdirs.cf

Ticket: CFE-3718
(cherry picked from commit 42227b172c13c3c561ae0ed1dcf63e42185e0cec)

CFE-3718: Added example illustrating rxdirs perms body attribute (3.15)

---

cf-serverd/server_access.c
libcfnet/server_code.c
tests/acceptance/16_cf-serverd/serial/simple_copy_from_admit_localhost.cf
tests/acceptance/16_cf-serverd/serial/simple_copy_from_deny_localhost.cf

https://github.com/cfengine/core/pull/4750
https://github.com/cfengine/masterfiles/pull/2041

ENT-7362: cf-serverd default bind

---

cf-serverd/server_access.c
libcfnet/server_code.c
tests/acceptance/16_cf-serverd/serial/simple_copy_from_admit_localhost.cf
tests/acceptance/16_cf-serverd/serial/simple_copy_from_deny_localhost.cf

*3.18.x* version of #4750 
https://github.com/cfengine/core/pull/4756
https://github.com/cfengine/masterfiles/pull/2046

[3.18.x] ENT-7362: cf-serverd default bind

---

libenv/sysinfo.c

Ticket: ENT-7454
(cherry picked from commit a1ac12f06235f2f03f3abe87da15ce0f945e507d)

ENT-7454: Added OpenSUSE to policy var `sys.os_name_human` (3.18.x)

---

libenv/sysinfo.c
tests/static-check/cppcheck_suppressions.txt

cherry-pick from master - https://github.com/cfengine/core/pull/4758
Ticket: ENT-7502
Signed-off-by: larsewi lars.erik.wik@northern.tech

ENT-7502: Fixed Windows version unknown in MP (3.18.x)

---

cf-key/cf-key.c

cherry-picked from master - https://github.com/cfengine/core/pull/4749

CFE-3719: Fixed some memory leaks in cf-key (3.15.x)

---

examples/mergedata-last-key-wins.cf

CFE-3733: Added example illustrating that the last key wins with mergedata()

---

examples/mergedata-last-key-wins.cf

Ticket: CFE-3733
(cherry picked from commit 62a2a95c246fd5123d56dd5999a8dc4ad25d88d6)

CFE-3733: Added example illustrating that the last key wins with mergedata() (3.18)

---

examples/mergedata-last-key-wins.cf

Ticket: CFE-3733
(cherry picked from commit 62a2a95c246fd5123d56dd5999a8dc4ad25d88d6)

CFE-3733: Added example illustrating that the last key wins with mergedata() (3.15.x)

---

tests/acceptance/10_files/11_xml_edits/CFE-3806.cf

CFE-3806: Added test for trailing newline with insert_tree not removing path end tag

---

misc/systemd/cf-apache.service.in

Ticket: ENT-7966
(cherry picked from commit 102f56d345e45794621818cde2674b5b6f4831d2)

ENT-7966: Moved httpd.pid to root of httpd workdir (3.18)

---

misc/systemd/cf-apache.service.in

Ticket: ENT-7966
(cherry picked from commit 102f56d345e45794621818cde2674b5b6f4831d2)

ENT-7966: Moved httpd.pid to root of httpd workdir (3.15)

---

misc/systemd/cf-apache.service.in

Ticket: ENT-7948
(cherry picked from commit 42358dd8953675469fde8be3ab3c5fcd849e077a)

ENT-7948: Set apache umask to 0177 (3.18)

---

misc/systemd/cf-apache.service.in

Ticket: ENT-7948
(cherry picked from commit 42358dd8953675469fde8be3ab3c5fcd849e077a)

ENT-7948: Set apache umask to 0177 (3.15)

---

misc/selinux/cfengine-enterprise.fc
misc/selinux/cfengine-enterprise.te

[3.15.x] SELinux policy fixes for report scheduling/exporting/emailing

---

misc/selinux/cfengine-enterprise.fc
misc/selinux/cfengine-enterprise.te

[3.18.x] SELinux policy fixes for report scheduling/exporting/emailing

---

Makefile.am
libpromises/iteration.c
tests/static-check/run.sh
tests/static-check/run_checks.sh

[3.18.x] Static checks using newer versions of Fedora

---

misc/selinux/cfengine-enterprise.te

[3.18.x] selinux fixes for Federated Reporting

---

misc/selinux/cfengine-enterprise.te

[3.15.x] selinux fixes for Federated Reporting

---

configure.ac
libenv/sysinfo.c
misc/Makefile.am
misc/selinux/cfengine-enterprise.fc
misc/selinux/cfengine-enterprise.te
misc/systemd/cf-reactor.service.in
misc/systemd/cfengine3.service.in

ENT-7357: Add cf-reactor as a new service

---

libpromises/locks.c
libpromises/mod_custom.c
libpromises/policy.c

[3.18.x] CFE-3434: Custom promise locking and ifelapsed

---

tests/acceptance/30_custom_promise_types/22_what_module_gets.cf
tests/acceptance/30_custom_promise_types/22_what_module_gets.cf.expected
tests/acceptance/30_custom_promise_types/cat_module.sh

Add a test which checks what custom module gets from the agent

---

contrib/agentsvg/generate_all.py

https://drive.google.com/drive/folders/0Bzl7vlusV7zcY244RGtzVTlBUGc

agentsvg: New colors and filenames

---

cf-agent/acl_posix.c
cf-agent/files_select.c
cf-agent/simulate_mode.c
cf-agent/verify_files_utils.c
cf-serverd/server_common.c
libenv/sysinfo.c
libpromises/acl_tools_posix.c
libpromises/conversion.c
libpromises/evalfunction.c
libpromises/unix.c
libpromises/unix.h

[3.18.x] CFE-3937: fallback to getent if builtin user/group info lookup fails

---

libcfnet/protocol_version.c
libpromises/mod_common.c
libpromises/mod_files.c

Merge Together:
- https://github.com/cfengine/documentation/pull/2700

ENT-8560: Added protocol 3 (cookie) to syntax description (3.18)

---

libcfnet/protocol_version.c
libpromises/mod_common.c
libpromises/mod_files.c

Merge Together:
- https://github.com/cfengine/documentation/pull/2701

ENT-8560: Added protocol 3 (cookie) to syntax description (3.15)

---

tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/package_lock.cf

ENT-6967 Increase waiting time for the package_lock.cf

---

cf-key/cf-key-functions.c
configure.ac
libpromises/crypto.c

See also https://github.com/cfengine/libntech/pull/160

Minimal changes to support OpenSSL 3

---

tests/acceptance/31_tickets/CFE-3988/1/before_test.xml.txt
tests/acceptance/31_tickets/CFE-3988/1/test.cf

This change adds a test described by the related ticket for being able to edit
after a selected region.

CFE-3988: Added test for editing after a selected region

---

tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/package_lock.cf

cherry-pick from https://github.com/cfengine/core/pull/4909

ENT-6967 Increase waiting time for the package_lock.cf  - 3.15.x

---

tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/package_lock.cf

ENT-6967 Increase waiting time for the package_lock.cf - 3.18.x

---

examples/style_PascaleCase.cf
examples/style_camelCase.cf
examples/style_hungarian.cf
examples/style_snake_case.cf

Intended for use within the Policy Style Guide

Added examples that illustrate various naming conventions

---

libpromises/mod_custom.c
libpromises/policy.c
tests/acceptance/30_custom_promise_types/05_meta_attr.cf

CFE-3440: Enable use of the 'meta' attribute with custom promises

---

cf-agent/package_module.c
cf-check/dump.c
cf-check/validate.c

Ticket: ENT-9050
(in each of two commits instead)

ENT-9050: Adjust cf-check and package module code for empty updates list

---

tests/acceptance/01_vars/01_basic/os_name_human.cf
tests/acceptance/01_vars/01_basic/os_version_major.cf
tests/acceptance/02_classes/01_basic/expected_os_classes.cf
tests/acceptance/16_cf-serverd/serial/simple_copy_from_admit_localhost.cf
tests/acceptance/16_cf-serverd/serial/simple_copy_from_deny_localhost.cf

teach acceptance tests about OPENsuse

---

tests/acceptance/02_classes/01_basic/expected_os_classes.cf
tests/acceptance/16_cf-serverd/serial/simple_copy_from_admit_localhost.cf
tests/acceptance/16_cf-serverd/serial/simple_copy_from_deny_localhost.cf

cherry-picked from https://github.com/cfengine/core/pull/5007

teach acceptance tests about OPENsuse - 3.15.x

---

tests/acceptance/01_vars/01_basic/os_name_human.cf
tests/acceptance/01_vars/01_basic/os_version_major.cf
tests/acceptance/02_classes/01_basic/expected_os_classes.cf
tests/acceptance/16_cf-serverd/serial/simple_copy_from_admit_localhost.cf
tests/acceptance/16_cf-serverd/serial/simple_copy_from_deny_localhost.cf

conflict-less cherry-picks from https://github.com/cfengine/core/pull/5007/commits

teach acceptance tests about OPENsuse - 3.18.x

---

libpromises/attributes.c
libpromises/attributes.h
libpromises/mod_custom.c
libpromises/mod_custom.h
libpromises/policy.c
tests/acceptance/30_custom_promise_types/23_action_policy/dryrun_supported.cf
tests/acceptance/30_custom_promise_types/23_action_policy/dryrun_supported.cf.sub
tests/acceptance/30_custom_promise_types/23_action_policy/dryrun_unsupported.cf
tests/acceptance/30_custom_promise_types/23_action_policy/dryrun_unsupported.cf.sub
tests/acceptance/30_custom_promise_types/23_action_policy/example_module_with_action_policy.sh
tests/acceptance/30_custom_promise_types/23_action_policy/example_module_with_fake_action_policy.sh
tests/acceptance/30_custom_promise_types/23_action_policy/example_module_without_action_policy.sh
tests/acceptance/30_custom_promise_types/23_action_policy/explicit_warn_fake_supported.cf
tests/acceptance/30_custom_promise_types/23_action_policy/explicit_warn_fake_supported.cf.sub
tests/acceptance/30_custom_promise_types/23_action_policy/explicit_warn_supported.cf
tests/acceptance/30_custom_promise_types/23_action_policy/explicit_warn_supported.cf.sub
tests/acceptance/30_custom_promise_types/23_action_policy/explicit_warn_unsupported.cf
tests/acceptance/30_custom_promise_types/23_action_policy/explicit_warn_unsupported.cf.sub
tests/acceptance/30_custom_promise_types/23_action_policy/simulate_supported.cf
tests/acceptance/30_custom_promise_types/23_action_policy/simulate_supported.cf.sub
tests/acceptance/30_custom_promise_types/23_action_policy/simulate_unsupported.cf
tests/acceptance/30_custom_promise_types/23_action_policy/simulate_unsupported.cf.sub

[3.18.x] CFE-3433: action_policy and dry-run handling with custom promise modules

---

tests/acceptance/16_cf-serverd/serial/simple_copy_from_admit_localhost.cf
tests/acceptance/16_cf-serverd/serial/simple_copy_from_deny_localhost.cf

Ticket: ENT-9055
(cherry picked from PR https://github.com/cfengine/core/pull/5037)

Disable failing tests on SLES, too - 3.18.x

---

cf-monitord/cf-monitord.c

ENT-4492: cf-monitord now honors monitorfacility in body monitor control

---

cf-monitord/cf-monitord.c

Ticket: ENT-4492
(cherry picked from commit 147b9543547b93445528256aaa1cd3048d0b6fb0)

ENT-4492: cf-monitord now honors monitorfacility in body monitor control (3.18)

---

.github/workflows/unit_tests.yml

Added github action to compile core and run unit tests

---

.github/workflows/unit_tests.yml

Ticket: ENT-9155
(cherry picked from commit 739cc23eab6a05e0d299b3b849472e5eb8885ffc)

ENT-9155: Added github action to compile core and run unit tests (3.18)

---

.github/workflows/unit_tests.yml

Ticket: ENT-9155
(cherry picked from commit 739cc23eab6a05e0d299b3b849472e5eb8885ffc)

ENT-9155: Added github action to compile core and run unit tests (3.15)

---

.github/workflows/acceptance_tests.yml

ENT-9157: Added github action to run acceptance tests

---

.github/workflows/acceptance_tests.yml

Ticket: ENT-9157
(cherry picked from commit b95aa015b8b331147b730239af7342ed4099127a)

ENT-9157: Added github action to run acceptance tests (3.15)

---

tests/acceptance/testall

ENT-9162: Refactor testall check for rpmcmpver binary (3.15)

---

tests/acceptance/testall

ENT-9162: Refactor testall check for rpmcmpver binary (3.18)

---

.github/workflows/acceptance_tests.yml
.github/workflows/asan_unit_tests.yml
.github/workflows/ci.yml
.github/workflows/cifuzz.yml
.github/workflows/macos_unit_tests.yml
.github/workflows/unit_tests.yml

No need to run acceptance tests which take a lot of
minutes if unit tests don't pass.
Ticket: ENT-9203

ENT-9203: Refactored github actions to add dependencies

---

cf-serverd/cf-serverd-functions.c
cf-serverd/cf-serverd.c
cf-serverd/server_transform.c
cf-serverd/server_transform.h
libcfnet/policy_server.c
libpromises/signals.c
libpromises/signals.h
misc/systemd/cf-serverd.service.in

https://github.com/cfengine/core/pull/5045
https://github.com/cfengine/masterfiles/pull/2485

ENT-8456: Fixes for cf-serverd starting before DNS works

---

tests/acceptance/testall

ENT-9162: Silenced rpm: command not found in testall script

---

tests/acceptance/testall

(cherry picked from commit fd737d7438a5df7725256339e18a32755c3c4586)

ENT-9162: Silenced rpm: command not found in testall script (3.18)

---

INSTALL
misc/selinux/cfengine-enterprise.te

Needed for redhat 9 but maybe will break redhat 8?
Ticket: ENT-8824

ENT-8824: Adjust selinux policy for RHEL 9

---

misc/selinux/cfengine-enterprise.te

Removed duplicate name_connect capability for tcp_socket

---

.github/workflows/macos_unit_tests.yml

Fixed missing PCRE for macos_unit_tests

---

misc/selinux/cfengine-enterprise.te

Ticket: ENT-9694
(cherry picked from commit 5593ed6bf784183b905f800a404511baf13f87e7)

ENT-9694: Added selinux ldap port access for Mission Portal (3.18)

---

misc/cf-support

This change simply added an explicit --help option and aligned output with other components.

ENT-9740: Added --help option to cf-support and aligned output with other components

---

misc/cf-support

This change simply added an explicit --help option and aligned output with other components.

ENT-9740: Added --help option to cf-support and aligned output with other components (3.21)

---

misc/cf-support

This change simply added an explicit --help option and aligned output with other components.

ENT-9740: Added --help option to cf-support and aligned output with other components (3.18)

---

misc/cf-support

See:
https://github.com/cfengine/libntech/pull/171
Ticket: ENT-9741

ENT-9741 cf-support: Aligned copyright notice with other places

---

examples/getusers.cf

Ticket: CFE-4127
(cherry picked from commit 5bf7c24fd9383bdfe12d53b5b4f505916f32f783)

CFE-4127: Updated getusers() example to illustrate the filtering capabilities (3.18)

---

misc/Makefile.am

Needed to check shellcheck command differently.
Ticket: ENT-9340

ENT-9340: Fixed cf-support shellcheck check target

---

misc/cf-support

Ticket: ENT-9804
(cherry picked from commit b3fd4d4aa2b8c9eb25de875ea950aa22db5e8223)

ENT-9804: Started checking status of all cf- prefixed systemd services in cf-support (3.21)

---

misc/cf-support

Ticket: ENT-9804
(cherry picked from commit b3fd4d4aa2b8c9eb25de875ea950aa22db5e8223)

ENT-9804: Started checking status of all cf- prefixed systemd services in cf-support (3.18)

---

INSTALL

ENT-9363: Adjusted INSTALL instructions fo MacOS

---

.github/workflows/ci.yml
.github/workflows/job-static-check.yml
.github/workflows/job-valgrind-check.yml
tests/static-check/run_checks.sh

Ticket: [ENT-9922](https://northerntech.atlassian.net/browse/ENT-9922)
[ENT-9922]: https://northerntech.atlassian.net/browse/ENT-9922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ENT-9922: move container tests to GitHub Actions

---

misc/cf-support

Ticket: ENT-9786
merge together
https://github.com/cfengine/core/pull/5198
https://github.com/cfengine/system-testing/pull/485

ENT-9786: Added native core dump handling in cf-support for solaris

---

cf-agent/verify_methods.c
cf-net/cf-net.c
libcfnet/client_code.c
libpromises/evalfunction.c
libpromises/iteration.c
libpromises/sort.c

together:
https://github.com/cfengine/libntech/pull/179
https://github.com/cfengine/core/pull/5204
https://github.com/cfengine/enterprise/pull/719
https://github.com/cfengine/nova/pull/2013

ENT-9878: Added support for building and testing MacOS

---

docs/cf_remote_demo.sh

- cf_remote_demo.sh: Commented out masterfiles deploy
- cf_remote_demo.sh: Removed CentOS 6 and RHEL 6
- cf_remote_demo.sh: Updated Debian 9 to Debian 10
- cf_remote_demo.sh: Updated hub to Ubuntu 22

cf_remote_demo.sh: Updated with new platforms and convenience changes

---

.github/workflows/job-static-check.yml
.github/workflows/job-valgrind-check.yml
.github/workflows/valgrind.yml

ENT-10190: Upgraded together javascript action

---

misc/cf-support

CFE-4160: Added classes and vars to cf-support

---

misc/selinux/cfengine-enterprise.te

Needed by rhel-9.2 linux kernel
Ticket: ENT-10206

ENT-10206: Added mctp_socket class to selinux policy

---

misc/selinux/cfengine-enterprise.te

We didn't cherry pick all the needed fixes on master for RHEL 8 to 3.18.x branch.
Ticket: ENT-10258

ENT-10258: Bring needed selinux fixes from master for RHEL 8 (3.18)

---

libpromises/evalfunction.c
tests/acceptance/08_commands/01_modules/set-tags.cf
tests/acceptance/08_commands/01_modules/vars-from-module-have-source-and-derived_from-tags.cf

Cherry-picked from https://github.com/cfengine/core/pull/5243

ENT-7725: Variables & Classes Modules automatically tagged (3.18.x)

---

libpromises/evalfunction.c
tests/acceptance/08_commands/01_modules/set-tags.cf
tests/acceptance/08_commands/01_modules/vars-from-module-have-source-and-derived_from-tags.cf

cherry-picked from https://github.com/cfengine/core/pull/5243

ENT-7725: Variables & Classes Modules automatically tagged (3.21.x)

---

README.md

(cherry picked from commit 66490d6c29fb6145e6933c46fc27f4acd95624ef)

Removed LGTM banner that no longer works (3.21)

---

libpromises/fncall.c
libpromises/policy.c
libpromises/rlist.c
libpromises/rlist.h
tests/unit/rlist_test.c

This function is needed for ticket ENT-4277.

ENT-4277: Added RvalWriteRaw function that doesn't escape quotes (3.21.x)

---

libpromises/fncall.c
libpromises/policy.c
libpromises/rlist.c
libpromises/rlist.h
tests/unit/rlist_test.c

This function is needed for ticket ENT-4277.

ENT-4277: Added RvalWriteRaw function that doesn't escape quotes (3.18.x)

---

ChangeLog

Fixed and improved postgresql server state handling in package scriptlets
Ticket: ENT-10647

ENT-10647: Added changelog entry for ENT-10647 fix (3.18)

---

ChangeLog

Fixed and improved postgresql server state handling in package scriptlets
Ticket: ENT-10647

ENT-10647: Added changelog entry for ENT-10647 fix (3.21)

---

INSTALL

Updated RedHat/CentOS source install instructions

---

cf-check/diagnose.c
cf-check/diagnose.h
cf-check/dump.c
cf-check/repair.c
cf-check/repair.h
cf-check/validate.c
libpromises/dbm_api.c
libpromises/dbm_api.h
libpromises/dbm_lmdb.c
libpromises/dbm_priv.h
libpromises/dbm_quick.c
libpromises/dbm_tokyocab.c
libpromises/locks.c

A few LMDB related fixes and improvements

---

cf-check/diagnose.c
cf-check/diagnose.h
cf-check/dump.c
cf-check/repair.c
cf-check/repair.h
cf-check/validate.c
libpromises/dbm_api.c
libpromises/dbm_api.h
libpromises/dbm_lmdb.c
libpromises/dbm_priv.h
libpromises/dbm_quick.c
libpromises/dbm_tokyocab.c
libpromises/locks.c

[3.21.x] A few LMDB related fixes and improvements

---

libpromises/matching.c

Fix an off-by-one in the comment about ovector in FirstBackReference()

---

ChangeLog

Relates to:
- https://github.com/cfengine/enterprise/pull/782
- https://github.com/cfengine/masterfiles/pull/2811

ENT-11034: Added changelog for 3.18.7

---

ChangeLog

Relates to:
- https://github.com/cfengine/masterfiles/pull/2812
- https://github.com/cfengine/enterprise/pull/783

ENT-11083: Added changelog for 3.21.4

---

.gitignore
Makefile.am
configure.ac
libpromises/Makefile.am
libpromises/dbm_api.h
libpromises/dbm_test_api.c
libpromises/dbm_test_api.h
python/Makefile.am
python/README
python/test_cfe_db.py

Remaining things:
https://github.com/cfengine/core/pull/5438
https://github.com/cfengine/buildscripts/pull/1367

CFE-4281: LMDB testbed

---

libenv/sysinfo.c

https://github.com/cfengine/core/pull/5460
https://github.com/cfengine/masterfiles/pull/2850

CFE-4342: Added warning log message when OS is not recognized

---

docs/BSD.md

removed annoying opinionated editor install ;) make this easy to use for anyone and not install software that is not completely necessary. A user will have an editor installed already most likely.

Update BSD.md, remove editor install

---

libenv/sysinfo.c

Corrected typo in warning message s/Unkown/Unknown/

---

libenv/sysinfo.c

Added sys.os_name_human for Alpine, postmarketOS, OpenBSD and NetBSD

---

README.md

There's no need to try to introduce as much syntax as possible
in this example. Hello world can and should be simple.

README.md: Simplified hello world example

---

cf-execd/cf-execd.c

This could fix issues if things are slow and agent runs end up getting skipped if cf-execd wakes up too late.
(cherry picked from commit 547f3679737b695e01d7aa26c4bc48b8c3d22c01)

ENT-11765: Changed cf-execd's sleep behavior so it attempts to wake up at the beginning of every minute (3.21)

---

ChangeLog

Introduced in 173b8a77c4ace8bdbae76f25042d2ae752c1e8fd.

Add changelog for the depth_search change

---

contrib/masterfiles-stage/common.sh

- **Adjusted local settings in masterfiles stage common script to handle more cases**
- **Add option to use /etc/locale.conf if it is present**
together
https://github.com/cfengine/core/pull/5544
https://github.com/cfengine/nova/pull/2262

ENT-11885: Adjusted masterfiles stage script to choose an available locale

---

tests/valgrind-check/valgrind.sh

Backport of https://github.com/cfengine/core/pull/5567

[3.18.x] valgrind-checks improvements

---

misc/selinux/cfengine-enterprise.te.all

It executes `git` (and maybe other commands) in a shell.
Ticket: ENT-11910

Allow cfbs to execute commands in a shell

---

contrib/masterfiles-stage/masterfiles-stage.sh

Ticket: ENT-11969
together
https://github.com/cfengine/core/pull/5575
https://github.com/cfengine/nova/pull/2281

ENT-11969: Fixed masterfiles-stage.sh -c|--check-only option parsing

---

libpromises/generic_agent.c

The "CFEngine roles" inventory attribute is now tied to the
sys.cfengine_roles variable (string list). This variable describes
what role a host has;
* On an Enterprise hub: { "Reporting hub", "Policy server" }
* On a Community policy server: { "Policy server" }
* On clients (the other hosts): { "Client" }
Similarly, the cfengine_reporting_hub and cfengine_client classes
have been added to more easily make decisions in policy based on role.
A host bootstrapped to itself is considered a "Policy server" /
policy_server (pre-existing class).
A host with the cf-hub binary (from the CFEngine Enterprise Hub
package) is considered a "Reporting hub" / cfengine_reporting_hub.
Any other host (not a reporting hub nor a policy server) is considered
a "Client" / cfengine_client.

ENT-11891: Redefined CFEngine roles inventory attribute and added related classes

---

.github/workflows/ci.yml

ENT-11734: Update branches to test against with new LTS: master, 3.24.x and 3.21.x

---

.github/workflows/ci.yml

Ticket: ENT-11734
(cherry picked from commit 41663e2a452e088570b478084a0862cefb07d520)

Update branches to test against with new LTS: master, 3.24.x and 3.21.x (3.24)

---

misc/cf-support

Added logging CFEngine component related SELinux denials in cf-support

---

misc/cf-support

Ticket: ENT-12137
(cherry picked from commit ea77c55bbf419b7862d68b361ef54da83779d480)

Added logging CFEngine component related SELinux denials in cf-support (3.24)

---

misc/selinux/cfengine-enterprise.te.all

selinux: sys_ptrace for apachectl and getattr for cf-serverd to socket file

---

ChangeLog

Added late changelog entry for SELinux fixes (3.24)

---

cf-net/cf-net.c

```
root# cf-net -H 192.168.57.29 -p latest connect
cf-net: invalid option -- 'p'
```

cf-net added -p option

---

libpromises/evalfunction.c

https://github.com/cfengine/core/pull/5692
https://github.com/cfengine/nova/pull/2392

ENT-3032: Added hostkey field to hostswithclass function

---

contrib/masterfiles-stage/README.org
contrib/masterfiles-stage/common.sh
contrib/masterfiles-stage/example_params/PARAMS_example_git_branch.sh

Added support of deployment from subdirectory to the masterfiles stage script

---

.github/workflows/job-static-check.yml
cf-check/dump.c
libpromises/locks.c
tests/static-check/run_checks.sh

- Minimized resources for static-check (package dependencies) and added cppcheck version printout
- address static-check complaints
Back ported from https://github.com/cfengine/core/pull/5706

2025 03 06 static check fixes/3.21

---

examples/getbundlemetatags.cf
libpromises/evalfunction.c
tests/acceptance/01_vars/02_functions/gettags.cf
tests/acceptance/01_vars/02_functions/gettags.cf.expected.json

https://github.com/cfengine/core/pull/5703
https://github.com/cfengine/documentation/pull/3402

CFE-4019: Added getbundlemetatags policy function

---

examples/validdata.cf
examples/validjson.cf
libpromises/evalfunction.c
tests/acceptance/01_vars/02_functions/validjson_strict.cf

https://github.com/cfengine/core/pull/5696
https://github.com/cfengine/documentation/pull/3398

Added optional parameter strict

---

libpromises/evalfunction.c
tests/acceptance/02_classes/02_functions/getindices_returns_correct_indices_from_list.cf
tests/acceptance/02_classes/02_functions/getindices_returns_positonal_indices_from_list.cf

getindices() now returns positional index from a list

---

libenv/sysinfo.c
tests/acceptance/01_vars/01_basic/cpusockets.cf
tests/acceptance/02_classes/01_basic/n_cpusockets.cf

Ticket: CFE-30
cfengine/core#5722
cfengine/documentation#3408

CFE-30: Add policy variable sys.cpusockets

---

libpromises/feature.c
tests/acceptance/00_basics/macros/if_feature_pam.cf

Ticket: CFE-3371
cfengine/core#5724
cfengine/documentation#3409

CFE-3371: Add feature class for libpam

---

configure.ac
examples/groupexists.cf
m4/cf3_platforms.m4
tests/acceptance/testall

* Fix typo
* Replace which with command -v
* Simplify platform check, replace obsolescent egrep with grep -E

Fix some minor issues

---

libpromises/attributes.c

* Add comments for better readability on what's currently checked
* Fix minor typos in error message for {file,process}_select
* Fix check for logging error on missing file_result attribute:
* Remove wrong check on min_size, it's initialized with CF_NOINT and
evaluated to true
* Add check on group
* Check entries variable for truesyness

libpromises/attributes: Fix minor issues

---

examples/isconnectable.cf
libpromises/evalfunction.c

https://github.com/cfengine/core/pull/5721
https://github.com/cfengine/documentation/pull/3407

ENT-10666: Added new policy function isconnectable()

---

cf-runagent/cf-runagent.c

ChangeLog: Title
Ticket: ENT-12712

Fixed incorrect exit code handling in cf-runagent

---

examples/hostswithgroup.cf
libpromises/cf3.defs.h
libpromises/enterprise_stubs.c
libpromises/evalfunction.c
libpromises/prototypes3.h

https://github.com/cfengine/enterprise/pull/834
https://github.com/cfengine/core/pull/5741
https://github.com/cfengine/nova/pull/2403
https://github.com/cfengine/documentation/pull/3416

ENT-11325: Added hostswithgroup policy function

---

libenv/sysinfo.c
libpromises/processes_select.c
tests/unit/Makefile.am
tests/unit/processes_select_test.c

[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=12061)](https://ci.cfengine.com/job/pr-pipeline/12061/)

ENT-12751: Fixed bug in parsing process_select for Windows

---

ChangeLog
misc/changelog-generator/changelog-generator

- **changelog-generator: Fixed syntax error in regex**
- **Updated changelogs for 3.24.2**

ENT-12842: Updated ChangeLog for 3.24.2 (3.24.x)

---

configure.ac

Ticket: ENT-12594
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=12157)](https://ci.cfengine.com/job/pr-pipeline/12157/)

Adjusted configure.ac for finding workdir, logdir and piddir on windows platform

---

tests/valgrind-check/Containerfile

- **valgrind-check: Fixed missing curl**
- **valgrind-check: fix missing archives**
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=12392)](https://ci.cfengine.com/job/pr-pipeline/12392/)

Fixed static checks (3.24.x)

---

cf-agent/verify_files_utils.c

Remote file copy with the 'copy_from' attribute now only preserves
source file permissions if the 'preserve' attribute in 'body copy_from'
is true. Otherwise it will use the permissions of the destination file
if it already exists and default permissions if it does not.
Ticket: ENT-11988

ENT-11988: Fixed bug where remote file copy always preserves source perms

---

libpromises/bootstrap.c

Fixed file descriptor leak when creating the am_policy_hub file
