cfengine/core

- cf-upgrade/Makefile.am
Building cfengine core out of the source tree fails with this error:
Making all in cf-upgrade
CC       process.o
../../../../cf-upgrade/process.c:25:22: fatal error:
platform.h: No such file or directory
#include <platform.h>
^
compilation terminated.
Makefile:513: recipe for target 'process.o' failed
After adding the missing include path to CPPFLAGS, the build
finishes successfully.
> cf-upgrade: Fix out of tree builds

- cf-agent/verify_files.c
- examples/bundlestate.cf
- libpromises/evalfunction.c
- libpromises/evalfunction.h
- tests/acceptance/01_vars/02_functions/bundlestate.cf
- tests/acceptance/01_vars/02_functions/bundlestate.cf.sub
This is not finished because I'm unable to test on Mac OS X (error: 
```
duplicate symbol _DEFAULT_CONTAINER_CAPACITY in:
../libutils/.libs/libutils.a(json.o)
../libutils/.libs/libutils.a(json-yaml.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
)
Thus the acceptance test is not finished and the code may be slightly broken, but I hope the general idea is acceptable: this function allows all the variables of a bundle to be returned in a single data container, formatted correctly (especially nested data structures).
> bundlestate: new function

- libutils/platform.h
- tests/acceptance/06_storage/01_local/001.cf
- tests/acceptance/10_files/09_insert_lines/017.cf
- tests/acceptance/17_users/unsafe/10_modify_user_with_same_password.cf
- tests/acceptance/17_users/unsafe/10_promise_outcomes.cf
- tests/unit/Makefile.am
- tests/unit/dynamic_dependency_test.sh
- tests/unit/process_test.c
Various fixes for Solaris. This was used to build the 3.6.4 package so the commit IDs should not be altered. If fixes are needed they should be put on top.
> Solaris build fixes

- libutils/platform.h
- tests/acceptance/06_storage/01_local/001.cf
- tests/acceptance/10_files/09_insert_lines/017.cf
- tests/acceptance/17_users/unsafe/10_modify_user_with_same_password.cf
- tests/acceptance/17_users/unsafe/10_promise_outcomes.cf
- tests/unit/Makefile.am
- tests/unit/dynamic_dependency_test.sh
- tests/unit/process_test.c
Various fixes for Solaris. This was used to build the 3.6.4 package so the commit IDs should not be altered. If fixes are needed they should be put on top.
> [3.6.x] Solaris build fixes

- cf-monitord/mon_network.c
Cf-monitord is not removing entries from the list containing open ports.
Once port was open and is closed later on it is reported as open.
This makes sure list is empty before open ports are collected.
> Redmine #6926 Fix cf-monitord open ports report

- tests/acceptance/10_files/zendesk_1776/zendesk_1776.cf
- tests/acceptance/10_files/zendesk_1776/zendesk_1776.cf.sub
When selecting files that are symlinks, plain files should not generate 
errors.
Ref: https://dev.cfengine.com/issues/6996
> Add: Test no errors when selecting by symlink

- libpromises/eval_context.c
If name of the class is too long we are skipping setting the class.
This prevents from writing class name outside of static buffer
of CF_MAXVARSIZE length.
> Redmine#7013 Skip setting class when name is too long.

- cf-key/cf-key-functions.c
- libpromises/crypto.c
Seeding OpenSSL's PRNG with the output of rand() isn't safe. It's better to
abort early than to continue with unsafe entropy.
Also write out a new randseed file on a deinitialization, and free our error
strings.
> Do not fallback on unsafe seed data for the PRNG

- libenv/sysinfo.c
For example if launched from /usr/lib/systemd/systemd.
> Fix systemd detection if launch path has two "systemd" substrings.

- misc/systemd/cfengine3.service
IMPORTANT: this will break rhel7 hub package so needs to be fixed
when hub package support will be added.
> Remove dependency that is not needed for community and enterprise.

- libenv/unix_iface.c
This has been used on NetBSD for quite some time.
See https://github.com/jsonn/pkgsrc/blob/trunk/sysutils/cfengine3/patches/patch-src_unix.c
Merging this will reduce the number of patches that need to be maintained for NetBSD in pkgsrc.
> Ignore HAVE_STRUCT_SOCKADDR_SA_LEN on NetBSD.

- configure.ac
Also I remove the "unknown" revision alternative, the system that runs
"autogen.sh" will ofcourse have git installed.
> Using m4_esyscmd_s is the recommended way.

- cf-key/cf-key-functions.c
- tests/unit/hash_test.c
- tests/unit/key_test.c
- tests/unit/tls_generic_test.c
Redmine 7053. Thanks to Tomáš Chvátal for submitting the patch.
> Use F4 as RSA exponent - it's common practice.

- libenv/sysinfo.c
On FreeBSD, VSYSNAME.release will look some like ’11.0-CURRENT’ 
When defining the $(sys.flavour) you read up to the ‘-‘ character so it will become freebsd-11.0
and that will also gets converted into the hard class ‘freebsd_11_0’
It would be helpful to also define a hard class that is just the major version such as freebsd_10 or
freebsd_11 so you wouldn’t have to do any additional work in an agent by calling regcmp() or
the like
> Define a hard class with just the OS major version on FreeBSD

- libpromises/mod_access.c
- libpromises/mod_common.c
- libpromises/mod_databases.c
- libpromises/mod_environ.c
- libpromises/mod_exec.c
- libpromises/mod_files.c
- libpromises/mod_interfaces.c
- libpromises/mod_knowledge.c
- libpromises/mod_measurement.c
- libpromises/mod_packages.c
- libpromises/mod_process.c
- libpromises/mod_report.c
- libpromises/mod_services.c
- libpromises/mod_storage.c
- libpromises/mod_users.c
- libpromises/syntax.h
The new global set of keys currently has only one entry (meta),
but can be extended into multiple entries later.
> Create global set of keys for bodies

- contrib/cfengine.el
Fixes error "Eager macro-expansion failure: (void-variable quote)"
and a similar one happening while byte-compiling the file
on Emacs 24.3.1 (but possibly other versions too).
> cfengine.el: Fix compilation error.

- libpromises/evalfunction.c
- tests/acceptance/01_vars/02_functions/eval_class.cf
This is a trivial change to `eval()` to add a second argument of `class` which:
* returns `any` if the result is not an error and not 0
* returns `!any` if the result is 0 or an error
I need it very often.
If it's accepted, I'll write docs and examples.
> Add new eval() option to return a class name

- examples/mergedata.cf
- libpromises/evalfunction.c
- tests/acceptance/01_vars/02_functions/mergedata.cf
This is a proposal for functionality I need often: wrapping a data container.  Here's an example of the new usage:
```
{
vars:
"ub" slist => { "b", "b2" };
"uc" slist => { };
"ud" slist => { };
"ue" slist => { "foo", "bar" };
"merge" data => mergedata('[ub]', '{ "mykey" : uc }', '{"otherkey":ue}');
"merge_s" string => format("%S", merge);
reports:
"${merge_s}";
}
```
Output:
```console
% cf-agent -KI -f ./test_mergedata_wraps.cf
R: {"mykey":[],"0":["b","b2"],"otherkey":["foo","bar"]}
```
What does this mean?
* naming a container works like usual, this is 100% backwards compatible
* the format `[ container1 ]` means "wrap `container1` in an array"
* the format `{ "mykey": container2 }` means "wrap `container2` in a map under key `mykey`"
* spaces are allowed inside, but …
> libpromises/evalfunction.c: let mergedata() wrap containers

- configure.ac
- libcompat/closefrom.c
- libutils/platform.h
- tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/defaults.cf
- tests/acceptance/Makefile.am
- tests/acceptance/dcs.cf.sub
- tests/acceptance/no_fds.c
The problem is that we don't know which file descriptors have been
opened behind our back, and most will be inherited by the new process.
The original process or its parent may then hang because some file
descriptor is still open, even though we didn't intend that. The
FD_CLOEXEC mechanism is not very helpful for descriptors we don't own,
so use the closefrom call to close all the descriptors we don't need
in the new process instead.
> Make backgrounding in tests easier by introducing no_fds command.

- examples/string_mustache.cf
- libpromises/evalfunction.c
- tests/acceptance/01_vars/02_functions/string_mustache.cf
See https://dev.cfengine.com/issues/7031
This is a very simple function that is useful when you don't want to create an external `.mustache` file.
Test policy:
```
{
vars:
"state" data => datastate();
"out" string => string_mustache(state, "sys.os = {{vars.sys.os}}");
"out2" string => string_mustache(state, "sys.os = {{vars.sys.os");
"out3" string => string_mustache(nosuchstate, "sys.os = {{vars.sys.os}}");
reports:
"mustache out: $(out)";
"mustache out: $(out2)"; # no expansion
"mustache out: $(out3)"; # no expansion
}
```
Output:
```console
% cf-agent -KI -f test_string_mustache.cf
R: mustache out: sys.os = linux
R: mustache out: $(out2)
R: mustache out: $(out3)
warning: Broken Mustache template, could not find end delimiter after reading start delimiter at 'sys.os = …
```
> Redmine#7031: string_mustache() function

- libutils/json-yaml.c
- tests/acceptance/01_vars/04_containers/parseyaml.cf
Otherwise CFEngine will assert when you try to mix key/values and
arrays inside another key/value and array.
Originally discovered and fixed approx. five min before presenting it at CfgMgmtCamp. :-)
> YAML: Make sure that key is reset when adding non-string elements.

- cf-monitord/mon_network.c
The ECGSOCKS[] array size was given by a macro that had to be updated
to stay in sync with the actual contents of the array.  Growing the
array without updating the macro would have produced a compile-time
error.  Just for once, we recently shrank it; this lead to the array
containing NULL-filled entries.  Since code accessing it used the
size, rather than a check for NULL-filled entries, cf-monitord crashed
on a strcmp(, NULL).
Change the array to unspecified size, so the compiler gets it right
reliably; and redefine the size to be derived from the actual array.
This'll avoid needing to change the size define every time we add an
entry to the array.
> Fix array-size inconsistency in mon_network.c

- examples/data_regextract.cf
- libpromises/evalfunction.c
- libutils/regex.c
- libutils/regex.h
- tests/acceptance/01_vars/02_functions/data_regextract.cf
- tests/unit/Makefile.am
- tests/unit/str_test.c
This proposed function does two things:
* adds a new `regextract` variant that creates a data container rather than "classic" array variables
* the data container is a key-value map where the keys are either the position of the match or, if the capture group was named, the name of the capture group (see the example policy below).  This is extremely nice in combination with Mustache templates, because the resulting data container can be fed directly to them.
In addition:
* the function `regex.c:StringMatchCaptures()` now returns a `Seq` of `Buffer` elements, which is nicer and removes the 4K limitation there
* the code is cleaner
* no extra variables are created
Sample policy:
```
{
vars:
"parsed" data => data_regextract("^(?<name1>...)(...)(..)-(?<name2>...)-(..).*", …
```
> data_regextract: new function like regextract, returns data container with named captures

- tests/acceptance/00_basics/02_switches/dry_run_perms_doesnt_lie.cf
- tests/acceptance/00_basics/02_switches/dry_run_perms_doesnt_lie.cf.sub
When run in dry run mode, the agent should not say that it changes any 
permissions, because in fact it does not.
Ref: https://dev.cfengine.com/issues/7082
> Add: Test dry-run mode does not assert it changes perms

- libpromises/dbm_lmdb.c
- tests/load/Makefile.am
- tests/load/run_lastseen_threaded_load.sh
- tests/unit/lastseen_test.c
On HP-UX, a unified file cache was not introduced until version 11.31.
This means that on 11.23 there are separate file caches for mmap()'ed
files and open()'ed files. When these two are mixed, changes made using
one mode won't be immediately seen by the other mode, which is an
assumption LMDB is relying on. The MDB_WRITEMAP flag causes LMDB to use
mmap() only, so that we stay within one file cache.
> Redmine #6994: Fix HPUX LMDB corruption due to non-unified file cache.

- cf-serverd/server_common.c
The algorithm first calls `lstat()`, which should bring all required
fields in the plain-file case.
Only on posix systems, and when `lstat()` indicates we have a symlink,
we need to call `stat()` again to read destination fields.
Note that the removed lines contain a bug: in the extremely rare case
that a regular file vanishes between first and second `stat()` calls,
we would be sending an uninitialized sendbuffer!
> server_common: remove double stat() of file, on non-link paths

- libpromises/cf3lex.l
- libpromises/parser_state.h
- tests/acceptance/00_basics/macros/if.cf
- tests/acceptance/00_basics/macros/if_eof_without_endif.x.cf
- tests/acceptance/00_basics/macros/if_eof_without_endif2.x.cf
- tests/acceptance/00_basics/macros/if_mismatched.x.cf
- tests/acceptance/00_basics/macros/if_multiple_endif.x.cf
- tests/acceptance/00_basics/macros/if_nested.x.cf
See https://dev.cfengine.com/issues/7111
* `@if after_version(a.b)` is hard-coded to exactly that format
* you can give multiple `@if` statements and they "stack up"
* `@endif` ends **any** `@if` state, and it's safe to give multiples
The acceptance tests should make it clear.  I'm not sure if the stacking behavior is best but I'd be OK with it as a user, since typically you'd only give one `@if` at a time.
> Redmine#7111: @if macro

- examples/file_hash.cf
Example for the `file_hash()` function.  Should be backported to 3.6.
> examples/file_hash.cf: add

- cf-serverd/cf-serverd-functions.c
Mentioning the parameter, collect_window, that controls whether to do
this gives the admin some chance of tweaking it, if that might help.
From the user's perspective, we're abandoning the call; the fact that
we're closing the socket is an implementation detail; so change
wording to say "abandon" instead of "close".
> Rephrased message when abandoning collect call attempt.

- tests/acceptance/01_vars/02_functions/getvalues_array_and_data_return_similar.cf
Getvalues should return similar results when used on a datacontainer and 
similar classic array.
Ref: https://dev.cfengine.com/issues/7116
> Add: Acceptance test for getvalues

- libenv/unix_iface.c
This has moved to policy so that undesired addresses like the local loopback
can be easily filtered out using a regular expression that is user accessible.
Ref: https://dev.cfengine.com/issues/7097
This should be merged with a change to masterfiles: https://github.com/cfengine/masterfiles/pull/444
> Remove: Inventory tag on ipv4 addresses

- cf-serverd/server_classic.c
- cf-serverd/server_tls.c
In BusyWith... functions for both TLS and classic, the comment after
ReceiveCollectCall() claimed that it had closed the connection, which
is actually done by the BusyWith...'s caller.  So correct those two
comments to tell the truth.
> Correct a pair of comments about call-collect's completion.

- cf-serverd/cf-serverd-functions.c
When CollectCallHasPending()/CollectCallGetPending() have been used to
take over ownership of the pending CC socket, their caller has a duty
to CollectCallMarkProcessed() when done with it.  That was all handled
suitably when actually using the socket; but was neglected when
discarding it due to an over-long queue.  This would leave a client
permanently failing to attempt collect calls.  Added the missing call.
> Add missing call to CollectCallMarkProcessed();

- cf-monitord/env_monitor.c
Partially reverts 756492778fb022629b19b6e370c1f9b655295ce8.
> On the first run of cf-monitord histogram data is not present, but it's not an error.

- ChangeLog
- cf-execd/cf-execd-runner.c
- cf-execd/exec-config.c
- cf-execd/exec-config.h
- libpromises/mod_common.c
- tests/unit/exec-config-test.c
Change from one week, down to two hours, see redmine#7113 for more
details.
Also changed LOG_LEVEL_ERR to LOG_LEVEL_NOTICE since this isn't some
kind of failure.
> redmine#7113: agent_expireafter

- examples/data_expand.cf
- libpromises/evalfunction.c
- tests/acceptance/01_vars/02_functions/data_expand.cf
- tests/acceptance/01_vars/02_functions/data_expand.cf.expected.json
- tests/acceptance/01_vars/02_functions/data_expand.cf.json
see https://dev.cfengine.com/issues/7166
Implements `data_expand()` as discussed, with example.  If this is acceptable I'll write docs and tests.
> Redmine#7166: data_expand() function

- libpromises/processes_select.c
No column has overflowed anything.  We *are* on the point of
overflowing the table, if there's more columns to come - except that
we side-step and don't make that mistake.  In any case, filling the
last column of the table isn't an error; the only problem would come
if there were another column to come, for which we lack space in the
table.  So stop to see if there actually *is* another column to come,
before Log()ging any error.  Also, testing > limit - 1 is just an ugly
way to test >= limit !
> redmine7219: clarify error message and condition on caring.

- libpromises/lastseen.c
cf-key -r may output a message that lastseen is not coherent, but this does not mean db-level corruption.
Running cf-key -r -x skips coherence check but this function is generic so it did not seem appropriate to mention this.
https://cfengine.zendesk.com/agent/tickets/1964
> improve error message seen from cf-key -r

- cf-agent/package_module.c
While cf-agent is run by cf-execd global promise lock is perceived
due to ifelapsed set by default to 1 minute. As global promise lock
should be available immediately for every new process it should be
set to 0.
> Redmine #7235 Fix global promise locking.

- tests/acceptance/01_vars/02_functions/sort.cf
- tests/acceptance/06_storage/01_local/001.cf
- tests/acceptance/10_files/09_insert_lines/017.cf
- tests/acceptance/17_users/unsafe/10_add_user_with_secondary_gid.cf
- tests/acceptance/README
It's not giving us useful test data to have the build contain
persistent failures. Better to save test_suppress_fail for the bad
cases and let the Jenkins build be green instead of yellow.
test_suppress_fail is still available if we need to suppress a really
bad bug.
> Reduce usage of test_suppress_fail.

- libpromises/failsafe.cf
> policy server cannot copy from masterfiles shortcut because cf-serverd is not yet up

- cf-execd/cf-execd.c
After all the sleeping we do, we need to make sure that we check if we
should terminate, otherwise the signal will simply spin the loop,
which triggers cf-agent, which spawns a new cf-execd, and we are back
where we started. At least by checking the flag, this probability is
drastically reduced.
Note that this does not fully fix the problem, since the signal
arrival is inherently a race condition, and this cannot be avoided. So
additional changes to the service scripts are still needed in order to
make sure that all daemons are stopped.
Also make sure that we do not enter yet another sleep after the first
has been interrupted. Again, this is a race condition, but it should
still improve things.
> Redmine #7193: Fix SIGTERM waking up the loop instead of ending it.

- ChangeLog
- libpromises/cf3lex.l
- tests/acceptance/00_basics/macros/if.cf
- tests/acceptance/00_basics/macros/if_eof_without_endif.x.cf
- tests/acceptance/00_basics/macros/if_eof_without_endif2.x.cf
- tests/acceptance/00_basics/macros/if_mismatched.x.cf
- tests/acceptance/00_basics/macros/if_multiple_endif.x.cf
- tests/acceptance/00_basics/macros/if_nested.x.cf
See https://dev.cfengine.com/issues/7281
> Redmine#7281: rename version_after macro to minimum_version

- contrib/cfengine.el
- libpromises/syntax.c
@ediosyncratic @leoliu please take a look.  This will be merged into Emacs as well, later.
Test case, indented correctly:
```
{
@if version_after(3.7)
reports:
any::
"any"::
'$(any)'::
'any'::
"hello 3.7!
@this should stay indented a few spaces";
vars:
"mything" data => '{
"a": 100,
"b": [
"c",
200
]
}';
@endif
}
```
Changes:
* recognize macros like `@anything`, apply the correct syntax, and indent to column 0 (unless inside a string, note `@this should stay indented` stays indented)
* when macro `@anything` is not at column 0, apply the warning face
* allow class selectors to look like `"myclass.$(myvar)"::` (but they still have string appearance, that's very hard to override)
* new interactive function `cfengine3-reformat-json-string` will, when inside a string, …
> contrib/cfengine.el: 3.7 indentation and JSON improvements

- contrib/cfengine.el
Minor fix to avoid indenting a `@(myvar)` like the below to the beginning of the line.  Safe to merge.
```
mybundle(
@(myvar)
);
```
> contrib/cfengine.el: minor regex improvement for the macro syntax

- libpromises/generic_agent.c
Now cf-promises -T is not limited to working when you are on a checked out
branch. Now you get the commit that is checked out as the release id even if
you are checked out from a specific commit or tag.
It would be really nice if this goes into 3.7.0. I also think it should be backported to 3.6.x
Ref: https://dev.cfengine.com/issues/7332
> Change: Improve git based release id

- configure.ac
- libpromises/signals.c
- libutils/Makefile.am
- libutils/passopenfile.c
- libutils/passopenfile.h
- tests/unit/Makefile.am
- tests/unit/passopenfile_test.c
<s>This is a preview, not yet a real pull request; I still need to fix some problems with the test.
I *shall* push -f a replacement branch before I'm ready to suggest merging this.
In particular, the Makefile.am changes need to move to the end, once the test is passing (and I've verified it fails before implementing the feature), so that git bisect never hits a point in the middle where tests fail.</s>
Tested on Jenkins and in our scale-test environment.  We need to test on MS-Win (but at least it compiles there, now).
> redmine7138: pass open file descriptors portably

- libpromises/processes_select.c
- tests/acceptance/05_processes/01_matching/inverse_ttime_inverse_found.cf
- tests/unit/split_process_line_test.c
This adds a `#if`-ed out unit test in which to document (and be ready for any brave soul who thinks they can fix the parser to handle) real-world ps output lines that our parser can't presently handle.
A second commit re-enables a known failing-on-Solaris test and adds a diagnostic log message in one place that shall *hopefully* shed some light on why the test fails, when it (seldom) does.
It's a single commit to make it easier to revert once that's reported the hideous ps line that causes the problem (and added it to the first commit's test), while someone thinks about how to fix it.
None of this is urgent but it would make sense to include in master at some point when you can endure a failing test on Solaris for a short while.
> Deal with perverse ps output

- configure.ac
- misc/Makefile.am
- misc/systemd/cfengine3-web.service.in
- misc/systemd/cfengine3.service.in
The paths differ, and systemd doesn't allow us to do any logic inside
its files, so we need to decide at the configure stage and then make a
replacement inside the service file.
> Redmine #7335: Fix missing environment file on Debian systems.

- m4/snprintf.m4
They were not being tested as compliant, and hence were omitted from
the build simply if they were available. We fix it not by testing for
compliance, but by reusing the result from the snprintf test, it's
almost certainly going to be the same result.
This fixes Windows builds, where this is a problem on certain MinGW
versions.
> Redmine #7362: Fix asprintf/vasprintf being misdetected as compliant.

- cf-execd/cf-execd-runner.c
- cf-serverd/cf-serverd-functions.c
- libutils/file_lib.c
- libutils/file_lib.h
- libutils/platform.h
It's quite important because Windows does not allow you to do anything
to a file that is open for writing, and if the file descriptor is
inherited by a process that is long lived, you'll never be able to
delete it.
This particular case was related to cf-execd output logs, that could
not be rotated because of cf-agent inheriting a file descriptor from
cf-execd, and cf-agent then launching an unrelated and long lived
process.
Also remove our null definition of the FD_CLOEXEC flag. Since we now
have the wrapper, we don't want people to use it by mistake.
> Redmine #7149: Make sure file desc. inheritance is honored on Windows.

- cf-agent/verify_packages.c
- tests/acceptance/07_packages/800.cf
Ticket: https://dev.cfengine.com/issues/7181
`EvalContextStackPushPromiseFrame` is always called with the first promise, whereas it should be called with the current promise.
> Fix context update when iterating on individual package actions

- examples/packagesmatching.cf
Referencing incorrect variable
> Fix: packagesmatching() example

- libcfnet/misc.c
- libpromises/item_lib.c
- tests/unit/item_test.c
I'm suspecting some CLOSE_WAIT problems, especially on windows, could be related to not properly closed sockets. So with this pull request, such failure is logged in verbose.
> Report failure to close the socket.

- libpromises/failsafe.cf
Ref: https://dev.cfengine.com/issues/7417
This message is confusing and I am unsure what value it provides at this 
point.  I believe this stems from the deconflation of updating from failsafe.
At one time exec_command in body executor control was by default set to run
failsafe.cf and then update.cf. I think that this report intended to warn
users about the usage. update.cf has been in place for some time, and this
policy is confusing new users. I think its best to just remove this report
completely unless someone can think of a good reason to keep it.
> Remove: Unnecessary and confusing report

- tests/acceptance/01_vars/01_basic/can_not_define_variables_in_remote_bundles.cf
You should not be allowed to set variables in another bundle.
Ref: https://dev.cfengine.com/issues/7145
> Add: Acceptance test for setting variables remotely

- tests/acceptance/00_basics/06_logs/disable_runlog.cf
- tests/acceptance/00_basics/06_logs/disable_runlog.cf.sub
It is disabled by symlinking it to /dev/null.
> [3.7.x] Redmine #6957: Add test to ensure runlog can be disabled.

- cf-agent/files_editline.c
- cf-serverd/server_common.c
- libpromises/cf3.defs.h
- libpromises/dbm_lmdb.c
- libpromises/known_dirs.c
- libpromises/locks.c
It contains detailed locking messages which is very developer oriented
and not useful as a separate log.
> Redmine #6957: Move /var/cfengine/cf3.<host>.runlog log to debug output.

- tests/unit/db_concurrent_test.c
Casting between pointers and int results in compiler warnings.
It is not needed here, so simply remove it.
> tests/unit: Remove non-portable unneeded type casts

- libcfnet/classic.c
- libcfnet/tls_generic.c
- libcfnet/tls_generic.h
- libutils/platform.h
Make sure a timed-out connection gets closed at the lowest level, so
that further calls of recv() do not return the delayed server reply.
Complementing pull request #2346 from @pasinskim, this pull request ensures that the socket will never be reused in case of socket timeout.
> Redmine#6027: Fix possible corruption in case of socket recv() timeout

- tests/acceptance/15_control/02_agent/abortbundle_classes.cf
- tests/acceptance/15_control/02_agent/abortbundle_classes.cf.sub
- tests/acceptance/15_control/02_agent/abortbundle_classexpression.cf
- tests/acceptance/15_control/02_agent/abortbundle_classexpression.cf.sub
- tests/acceptance/15_control/02_agent/abortbundle_nomatchclassexpression.cf
- tests/acceptance/15_control/02_agent/abortbundle_nomatchclassexpression.cf.sub
- tests/acceptance/15_control/02_agent/abortbundle_regex.cf
- tests/acceptance/15_control/02_agent/abortbundle_regex.cf.sub
Test that the agent aborts the current bundle when an exact abortclass
is matched and that the agent continues on to the next bundle.
Test that the agent aborts the current bundle when a regular expression
is matched and that the agent continues on to the next bundle.
Test that the agent aborts if a classexpression is matched and that the
agent continutes on to the next bundle.
Test that the agent does *NOT* abort if a classexpression does not
match.
Ref: https://dev.cfengine.com/issues/3611
> Add: Acceptance tests for abortbundle classes

- cf-agent/cf-agent.c
- cf-execd/cf-execd.c
- cf-serverd/cf-serverd.c
- libpromises/generic_agent.c
- libpromises/generic_agent.h
- tests/acceptance/00_basics/validation/validate_failsafe_creating.cf
- tests/acceptance/00_basics/validation/validate_failsafe_creating.cf.sub
Before setting input file to be failsafe.cf first we are checking if
file exists. If failsafe.cf is not accessible we are creating it
the same way as during bootstrap.
Changelog: failsafe.cf will be created when needed. (Redmine #7634)
> Redmine #7634: Create failsafe.cf when not exists.

- tests/unit/Makefile.am
- tests/unit/init_script_test.sh
Instead of making a separate clean target, list it in PROGRAMS
instead, which is better automake style. This implicitly invokes
libtool as well, so adapt the test to account for that.
> Fix init_script_test_helper not being cleaned properly.

- tests/unit/generic_agent_test.c
This one is causing Jenkins to fail so removing for now.
> Temporarily remove unit test creating failsafe.cf.

- tests/unit/process_test.c
They must be swapping or something, because the logs say it can take
up to ten seconds for the first process to even start.
> process_test: Try to work around slow buildslaves by giving more time.

- cf-agent/cf-agent.c
- cf-execd/cf-execd.c
- cf-promises/cf-promises.c
- cf-runagent/cf-runagent.c
- cf-serverd/cf-serverd-functions.c
- libutils/set.c
- libutils/set.h
- tests/unit/set_test.c
Currently, if multiple -D or -N flags are specified on the command-line, this causes all but the last to be ignored. These commits fixes this such that multiple flags can be used, adding more classes to be raised and lowered.
https://dev.cfengine.com/issues/7191
> Allow multiple -D or -N flags to be specified on the command line

- cf-agent/files_editline.c
- tests/acceptance/10_files/09_insert_lines/same_text_in_two_regions.cf
The issue was that even though we've been editing value in selected
region the whole file was checked to see if value was already edited.
This was broken by commit f8c7dca55ed8d99212564ea130666de4bd5e0931 when
check if line exists in region was added.
As a bonus some optimizations are added. Instead of iterating
through whole file we can now iterate only over selected region as
any operations will be done inside the region (no need to check whole
file).
Changelog: It is possible to edit the same value in multiple regions
of one file. (Redmine #7460)
> Redmine #7460: Unable to edit the same value in multiple regions.

- cf-agent/verify_files.c
- cf-agent/verify_files_utils.c
- libpromises/attributes.c
- libpromises/cf3.defs.h
- libpromises/mod_files.c
- tests/acceptance/10_files/01_create/011.cf
- tests/acceptance/10_files/01_create/012.cf
- tests/acceptance/10_files/07_delete_lines/700.cf
- tests/acceptance/10_files/09_insert_lines/400.cf
It would be nice if CFEngine could create and manage FIFOs. This functionality could be extended to include doors as well on Solaris, as well as other special files.
> Add support for adding/removing fifos in CFEngine

- libcompat/setlinebuf.c
Changelog: CFEngine on Windows no longer truncates log messages if the
program in question is killed halfway through.
> Disable block buffering on stdout on Windows.

- examples/data_readstringarray.cf
The comment regex matches multiline, and the example did not illustrate
that behaviour.
> Change: Improve example

- libpromises/policy.c
Currently line# 166 is useless in `PromiseHash()`.
`RvalHash()` in line# 167 should be using hash generated by `StringHash()` as its seed.
> bugfix PromiseHash(): RvalHash() should use hash yielded by StringHash() as its seed

- libutils/logging.c
- libutils/logging_priv.h
In that case only call log_hook if
message_level <= force_hook_level.
> Optimise performance, don't call log_hook when not printing messages

- libpromises/evalfunction.c
- tests/acceptance/01_vars/02_functions/findprocesses.cf
- tests/acceptance/01_vars/02_functions/processexists.cf
See https://dev.cfengine.com/issues/7633
Example with body extension commented out:
```
{
methods:
"test";
vars:
"test_state" data => bundlestate(test);
"test_string" string => storejson(test_state);
reports:
"$(this.bundle): state of things = $(test_string)";
}
bundle agent test
{
vars:
"procs2" data => findprocesses(".*");
}
```
Output: all the processes on that system in a data container array holding key-value maps:
```
...
{
"line": "root     31292     2     0  0.0  0.0      0   0         0    1 Oct18  3-01:49:21 00:00:00 [kworker/3:0]",
"pid": 31292
},
...
```
> Redmine#7633: processexists() and findprocesses()

- libpromises/failsafe.cf
Changelog: Fix cf-execd not starting during bootstrap with trigger_upgrade enabled in update.cf Redmine #7861
> Fix cf-execd not starting during bootstrap

- tests/acceptance/20_meta/this_bundle_meta_expands.cf
- Specifically that meta var lists can be dereferenced using this.bundle
> Add: test that meta vars can be dereferenced

- tests/acceptance/10_files/templating/mustache_does_not_fallback_to_datastate_when_provided_datacontainer_via_direct_data_is_undefined.cf
- tests/acceptance/10_files/templating/mustache_does_not_fallback_to_datastate_when_provided_datacontainer_via_direct_data_is_undefined.cf.mustache
- tests/acceptance/10_files/templating/mustache_does_not_fallback_to_datastate_when_provided_datacontainer_via_mergedata_is_undefined.cf
- tests/acceptance/10_files/templating/mustache_does_not_fallback_to_datastate_when_provided_datacontainer_via_mergedata_is_undefined.cf.mustache
- tests/acceptance/10_files/templating/mustache_does_not_fallback_to_datastate_when_provided_datacontainer_via_parsejson_storejson_is_undefined.cf
- tests/acceptance/10_files/templating/mustache_does_not_fallback_to_datastate_when_provided_datacontainer_via_parsejson_storejson_is_undefined.cf.mustache
Ref: https://dev.cfengine.com/issues/7699
> Add: Tests that mustache templates do not fallback to datastate

- tests/acceptance/01_vars/02_functions/parseyaml_with_unquoted_values_starting_with_digits.cf
Ref: https://dev.cfengine.com/issues/7372
> Add: Test that parseyaml works with naked values starting with digits

- cf-agent/cf-agent.c
- cf-serverd/server_common.c
- tests/acceptance/22_cf-runagent/serial/bundles_all_allowed_regex_disallowed_admitted.cf
- tests/acceptance/22_cf-runagent/serial/cfruncommand_argv0_quoted.cf
- tests/acceptance/22_cf-runagent/serial/cfruncommand_open.cf
- tests/acceptance/22_cf-runagent/serial/runagent_-B_bundle1_admitted_1.cf
- tests/acceptance/22_cf-runagent/serial/runagent_-B_bundle1_bundle2_admitted_1.cf
- tests/acceptance/22_cf-runagent/serial/runagent_-B_bundle2_admitted.cf
- tests/acceptance/22_cf-runagent/serial/runagent_-D_role1-B_bundle1_admitted_1.cf
- tests/acceptance/22_cf-runagent/serial/runagent_-D_role1_-D_role2_admitted.cf
- tests/acceptance/22_cf-runagent/serial/runagent_-D_role1_admitted_1.cf
- tests/acceptance/22_cf-runagent/serial/runagent_-D_role1_admitted_2.cf
- tests/acceptance/22_cf-runagent/serial/runagent_-D_role1_admitted_3.cf
- tests/acceptance/22_cf-runagent/serial/runagent_-D_role1_role2_admitted_1.cf
- tests/acceptance/22_cf-runagent/serial/runagent_-D_role1_role2_admitted_2.cf
- tests/acceptance/22_cf-runagent/serial/runagent_-D_role2_-B_bundle2_admitted.cf
- tests/acceptance/22_cf-runagent/serial/runagent_-D_role2_admitted_1.cf
- tests/acceptance/22_cf-runagent/serial/runagent_-D_role2_admitted_2.cf
cf-agent is now allowed all arguments, even when the "cfruncommand"
class is set. Additionally cf-serverd no longer appends
"-I -Dcfruncommand" to cfruncommand, this has to be done manually in
masterfiles body server control. This way configuration is fully
up to the sysadmin, as there are no hard-coded options any more.
Security is still enforced because arbitrary options can't be passed via
the EXEC command, they have to be set in policy body server control.
Changelog: cf-serverd no longer appends "-I -Dcfruncommand" to
cfruncommand, this has to be done manually in masterfiles
body server control.
> redmine#7732: cf-agent -K is now allowed even for remote execution

- libpromises/evalfunction.c
- libpromises/files_names.c
- libpromises/files_names.h
- libutils/buffer.c
- libutils/buffer.h
- libutils/string_lib.c
- libutils/string_lib.h
- tests/acceptance/01_vars/02_functions/maparray_mapdata.cf
- tests/acceptance/01_vars/02_functions/maparray_mapdata.cf.expected.json
This change includes acceptance tests, showing usage and effect.
It addresses a very common need: canonify a list without intermediate arrays.  See https://dev.cfengine.com/issues/2377 for one of many requests for it.
Syntax:
```
"canonified" data => mapdata("canonify", "any use of $(this.k) and $(this.v)", any_list_or_container_var);
```
This is 100% backwards compatible and very safe.  Please consider merging to 3.7 and 3.8 as well, even though it's a feature.
In addition to implementing the feature, this PR:
* adds a general `BufferCanonify` function to simplify code
* adds a note to `CanonifyName` (which has a `CF_BUFSIZE` limitation) that it should be replaced with `BufferCanonify` or `CanonifyNameInPlace`
* moves `CanonifyNameInPlace` to `string_lib.[ch]` because it's more …
> Add "canonify" mode to mapdata().

- libpromises/generic_agent.c
Buffered output is discarded if you switch buffering mode without
flushing the buffered output first. This will happen anyway when
switching modes, so no performance is lost.
Also move it earlier in the initialization sequence, so that we start
line buffering sooner. This can come in handy later, since if there is
an early crash in cf-agent, the log output may be truncated unless we
have switched to line buffered mode.
> Fix HP-UX specific bug that caused a lot of log output to disappear.

- tests/acceptance/testall
In testing out my changes that fail promises based on variables not expanding, I've been finding verbose output invaluable. This is *kind of* exposed through the `$VERBOSE` env var, but it's much more convenient to set this through a command-line option to `testall`.
> testall: Expose VERBOSE var through --verbose option

- tests/acceptance/01_vars/02_functions/ifelse_isvariable.cf
- tests/acceptance/testall
If the test outcome is not exactly "Pass" or "FAIL" the test script
would believe that the test had passed when it should have failed (in
the case of test_soft_fail). This is obviously wrong, it should say
that the test outcome was unknown and not expected.
Readd test that was reverted earlier because of this.
> Fix incorrect failure reason when there is a typo in test outcome.

- libcfnet/client_code.c
Avoid random errors when the encrypted string starts with a NULL character.
> Redmine #7908: Check for empty server response in RemoteDirList after decryption

- examples/reports.cf
- tests/acceptance/README
- Add skeleton for acceptance test in docs
- Cleanup whitespace (kill tabs) in reports example
> Small cleanups

- tests/acceptance/00_basics/namespaces_can_not_contain_funny_characters.cf
- tests/acceptance/00_basics/namespaces_can_not_contain_funny_characters.cf.sub
Namespaces should not be able to contain characters that are invalid in
bundle names.
> Add: Test syntax error on namespace

- cf-promises/cf-promises.c
- tests/acceptance/00_basics/def.json/show_vars_JSON.cf
- tests/acceptance/00_basics/def.json/show_vars_JSON.cf.json
Simple change, picked from #2245 
@kacf should be an easy merge, docs and acceptance tests will come if the code is OK.
> cf-promises/cf-promises.c: teach --show-vars to print JSON vars

- libutils/file_lib.c
- m4/fchmodat.m4
- tests/acceptance/10_files/02_maintain/perms_recurse.cf
- tests/unit/file_lib_test.c
The reason is that dropping privileges has some unexpected
consequences: CFEngine operates recursively on a file tree in a way
that may leave the directory being operated on last (e.g. files inside
the directory are treated before the directory itself). This means
that if we drop privileges, we may not always have the permissions to
enter the directory. This is impossible to fix for FIFOs (other than
changing the order that CFEngine does things, but that is on a
different code level and has other implications), because FIFOs will
block if we try to open a file descriptor to them, but we can fix it
for regular files by switching back to the old method of opening the
file descriptor and doing fchmod on that.
An additional level of complexity in this case is that the path may
end in a …
> Redmine #7808: Do not drop privileges when changes permissions on non fifo

- libpromises/mod_common.c
- tests/acceptance/00_basics/namespaces_can_not_contain_funny_characters.cf
namespaces that cannot be reached. Redmine #7903.
ChangeLog: Allowed namespace names made more strict, to disallow
namespaces that cannot be reached.
Modified by: Kristian Amlie <kristian.amlie@cfengine.com>
- Made regex even more strict: Don't allow starting with numbers.
> Namespaces allow some special characters which allows creation of

- cf-agent/verify_files_utils.c
* Fail on networking errors during file copy (this avoids continuing the copy when the file in error was the last evaluated in a directory)
* Free dirh in case of networking error
> Small networking errors handling improvements

- libpromises/evalfunction.c
- tests/acceptance/02_classes/01_basic/array_key_with_space_isvariable.cf
commit 3517e4833c276fcbdb4d1fc490bb0240c140bea4
Author: Nick Anderson <nick@cmdln.org>
Date:   Thu Apr 2 01:53:56 2015
Add: Test that isvariable works with array keys that have spaces
Arrays and data having spaces in a key is valid, so isvariable should be
able to test for them like any other variable.
commit c02d57bef56ba22680f001ab4fc0b257aec7076f
Author: Kristian Amlie <kristian.amlie@cfengine.com>
Date:   Fri Feb 12 09:03:56 2016
Redmine #7088: Fix isvariable() not accepting many valid arrays.
The problem is that although variables themselves cannot contain many
characters, such as '-', ' ' and '?', arrays indices can, therefore we
need to be prepared for pretty much any string. And there should be no
harm in accepting any string, since it will still fail the test if it
isn't a …
> Isvariable arrays

- libpromises/cf3.defs.h
- tests/acceptance/10_files/01_create/perms-mode.cf
My initial stab at this. I'll add tests if it looks good.
> Fixes #7826: Allow '=' in symbolic modes

- misc/init.d/cfengine3.in
Multiple cf-consumer processes are expected so warning about the
expected state just creates a false alarm.
> Change: Suppress warning from multiple cf-conusmer processes

- libcfnet/client_code.c
When a checksum is done to check is it is necessary to update the file,
the copy will stop anyway because of the networking error.
When it is used to check a file after copy (before moving .cfnew)
the agent should not consider the content it has received as correct
(espacially in a networking/server error context).
> In case of networking error, assume checksum is wrong

- cf-runagent/cf-runagent.c
- cf-serverd/server_classic.c
- cf-serverd/server_tls.c
- libcfnet/classic.c
- libcfnet/client_code.c
- libcfnet/client_protocol.c
- libcfnet/net.c
- libcfnet/net.h
- libcfnet/tls_generic.c
Follows #2356.
* Fail on networking errors during file copy (this avoids continuing the copy when the
file in error was the last evaluated in a directory)
* Free dirh in case of networking error
* Mark connection broken in SendTransaction
* ReceiveTransaction should always returns -1 in case of error (some calls to it test this value for errors)
> Improve networking errors handling

- libpromises/locks.c
- tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/package_lock.cf
- tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/package_lock.cf.expected
- tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/package_lock.cf.module
- tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/package_lock.cf.sub
Normally, when CFEngine grabs a promise lock, that exact lock is not
expected to be grabbed again for the duration of the cf-agent run. And
in fact, this is made impossible by the promise lock cache (see
EvalContextPromiseLockCacheContains()). If a promise is in fact
reevaluated, it is always because some part of the promise has
changed, even something as simple as the promise comment. This alters
the lock name, and hence it will count as a new lock. This behavior
sometimes requires specific workarounds to rerun promises inside
often-used bundles.
However, the global package lock works a bit differently: Since we
want to it to be a truly global lock, we need to reuse it. The first
step in this process is to remove it from the promise lock cache. This
is already done.
However, we run into …
> Redmine #7933: Fix timing bug when grabbing global package lock.

- tests/unit/generic_agent_test.c
```
commit ebd9cdcc552ca6804e15b97a9b1e5f9ba617abde
Author: Kristian Amlie <kristian.amlie@cfengine.com>
Date:   Thu Feb 25 09:49:54 2016
Remove test that is no longer relevant.
This is tested in the masterfiles repository.
commit b673a01394ba07ffa7c0d3b9af423f6efdceb622
Author: Kristian Amlie <kristian.amlie@cfengine.com>
Date:   Thu Feb 25 09:48:26 2016
Refactor generic_agent_test to use temporary workdir.
This means we can enable some tests that were not enabled before, and
is also more resilient against spurious failures in cases where
/var/cfengine/inputs already exists on the disk.
```
> Test workdir refactor

- configure.ac
- libpromises/evalfunction.c
- libpromises/files_copy.c
- libpromises/files_copy.h
We want to copy the attributes of the source link to the destination link.
Seen when using copy_from.preserve => "true".
Based on a patch by:
Eystein Måløy Stenberg <eystein.maloy.stenberg@cfengine.com>
> Don't follow symbolic links when copying extended attributes.

- configure.ac
Fix a typo which was resulted in the check for yp_get_default_domain being skipped on BSD and GNU targets
Standardize the regex used to check for a GNU target
> Fix regex for matching BSD and GNU tagets

- libpromises/evalfunction.c
- tests/acceptance/01_vars/02_functions/findfiles.cf
> Redmine#7981: findfiles() now skips relative paths.

- libpromises/systype.c
The change introduced in [9889494](https://github.com/cfengine/core/commit/98894948b26daedd76e6ff5303c6e75757231492) is causing the process promises to fails on older version of FreeBSD since -J (Display information about processes which match the specified jail IDs) @is a feature that was introduced in FreeBSD 9.3
> Only set VPSOPTS to 'auwx -J 0' when the FreeBSD version is > 9.3

- cf-agent/cf-agent.c
https://dev.cfengine.com/issues/7137
```
commit b2ddcccb3867ad8dcd55d25047654f657b59b8c0
Author: Kristian Amlie <kristian.amlie@cfengine.com>
Date:   Mon Mar 14 11:13:42 2016
Redmine #7137: Change verbosity of variable logging to debug.
This was done because of discussions in named tickets, relating to
potential length of variable strings as well as security concerns with
variables containing sensitive data.
Cancel-changelog: 34be1225eabdc845c573e7e7b2ce127e7149537e
Changelog: Log variable definitions in debug output.
commit 80a30d425fcb6b186a5f936edb588fdf3ba113a5
Author: Kristian Amlie <kristian.amlie@cfengine.com>
Date:   Mon Mar 14 11:13:17 2016
Add missing VarRefDestroy() in LogVariableValue().
```
> Fixups after discussion in #7137.

- libpromises/eval_context.c
- libpromises/expand.c
- libpromises/generic_agent.c
- libpromises/loading.c
- libpromises/rlist.c
- tests/acceptance/00_basics/def.json/json-inputs-not-array.cf
- tests/acceptance/00_basics/def.json/json-inputs-not-array.cf.json
- tests/acceptance/00_basics/def.json/json-inputs-not-auto-applied.cf
- tests/acceptance/00_basics/def.json/json-inputs-not-auto-applied.cf.json
- tests/acceptance/dcs.cf.sub
This was done in order to solve the problem that def.json is applied
to all policy files, including failsafe.cf. If there is a syntax error
in any of those files, all policy files will stop working and the host
is unable to recover.
Now one has to use the "inputs" section by referring to it as the
$(def.augments_inputs) variable, which it will populate.
Changelog: Fix bug which could render host unable to recover from a
syntax error, even if failsafe.cf was utilized. This could happen if
the file containing the syntax error was specified in the def.json
special file.
Changelog: Change: Policy files specified in the "inputs" section of
def.json will no longer be auto-loaded. One has to refer to the
$(def.augments_inputs) variable in the policy (the standard
masterfiles policies include …
> Redmine #7961: Remove auto-loading of "inputs" mentioned in def.json.

- ChangeLog
This is causing the doc build to fail with an unresolved link.
> Remove: Markup from function

- tests/acceptance/Makefile.am
- tests/acceptance/plucked.cf.sub
Note: This PR and https://github.com/cfengine/masterfiles/pull/679 are
co-dependant.
This is necessary in order to write tests for the edit_line bundles
using the results classes body.
All edit_line bundles were updated to use the results body, and the
plucked.cf.sub now reflects the updated versions.
Ref: Jira CFE-1954
> Change: switch to results classes body for edit_line classes

- cf-agent/files_properties.c
- libpromises/mod_common.c
5e7c0373f918e9b089ed0eef30671ee33a1e8ea5 changed the conditions to display general stat info about the considered files. These messages are useless and should be removed.
> Remove useless and annoying INFO log messages in Considerfile

- tests/acceptance/dcs.cf.sub
- tests/acceptance/testall
Strings starting with "CFE-", "ENT-", "ARCHIVE-" and "QA-" are valid
ticket identifiers.
Redmine support is retained for existing tests.
> Add support for Jira tickets in test suppression meta tags.

- contrib/enterprise/report.pl
When using --list the output type was forced to list being an ansible
compatible seralized json string. However this made it impossible to
--list in any other output type.
This also adds an ansible_emptyhostvars output type which inserts a
_meta section defining that no host vars exist. This can speed up
working with ansible on a large scale env as it avoids making individual
executions to retrieve host data.
> Fix: Use specifed output type with --list

- configure.ac
- misc/determine-version.py
- tests/acceptance/00_basics/macros/if_triple.cf
- tests/acceptance/00_basics/macros/if_triple.cf.sub.template
This way we can build all versions we want automatically, without
having to hardcode the version number in the source, using the
EXPLICIT_VERSION variable. If the variable is not set, and git is
available, it will try to figure it out from git tags.
Note that all of this is done in the autogen stage, because git will
generally not be available at the configure stage. This is also
required in order for tarballs to come with the correct version
embedded in them, because they won't have git available to figure this
out.
> CFE-2183: Figure out version instead of hardcoding.

- libpromises/cf3lex.l
- tests/acceptance/00_basics/macros/if.cf
- tests/acceptance/00_basics/macros/if_feature.cf
Changelog: Fix the lexer which could not handle empty newline(s)
before a ```@endif```.
Modified by: Kristian Amlie <kristian.amlie@cfengine.com>
- Removed dedicated test and instead made more permutations in
existing tests.
- Fix misquoted ParseDebug strings.
> Jira #2337: The lexer can go wrong with @if minimum_version macro

- tests/acceptance/testall
It's actually the last path that ends up being used, not the first,
and it is this order of priority we want. This was motivated by trying
to run acceptance tests in a directory not named core, but core was
present next to it.
> Reverse order of binary lookup in testall.

- libpromises/logic_expressions.c
- tests/acceptance/02_classes/01_basic/from_json_booleans.cf
- tests/acceptance/02_classes/01_basic/from_json_booleans.cf.expected.json
@jimis this is what we discussed on IRC. See the acceptance test: only `from_true` is defined, the others (`false`, `null`, and a missing value) are false.
All other acceptance tests pass.
> Add "true" as a special expression that is always EVAL_EXPRESSION_TRUE

- cf-agent/cf-agent.c
- cf-key/cf-key.c
- cf-promises/cf-promises.c
- libpromises/generic_agent.c
- libpromises/generic_agent.h
The motivation for this is that during policy loading, certain
functions may be evaluated that open pipes, and if these pipes at any
point become disconnected, we get an EPIPE signal. This is ignored
once we get to the evaluation stage, but during loading the signal
handlers have not been enabled yet.
This was originally seen during introduction of the mapdata()
function, which opens a pipe to an external process. In the test for
this function, `cat` was used to output a prerendered response, but
`cat` was also expected to consume the data input. Depending on
timing, if the data was written to `cat` before it terminated,
everything would be fine, but if `cat` terminated before data could be
written (because it was catting a file, not from stdin), cf-promises
would get an EPIPE signal and …
> Cleanup signal handling for agents and enable them earlier.

- libpromises/evalfunction.c
Changelog: Behavior change: When using readintlist(), readreallist()
or readstringlist(), parsing an empty file will no longer result in a
failed function call, but instead an empty list. Failure to open the
file will still result in a failed function call.
> Parsing an empty file should give empty list, not no list at all.

- cf-agent/verify_files_utils.c
Setting the setgid or setuid bits on a file owned by
root is not an error and should trigger a warning instead.
In dry-run mode, log message should clearly state that no
action is taken.
> Improve logging when managing setuid/setgid

- libpromises/processes_select.c
- tests/unit/split_process_line_test.c
The problem is that the ucb style ps can return empty fields, so we
need to account for that:
- Abstract the choice of parsing algorithm so it can be easily
specified when running SplitProcLine().
- Make ucb ps use the "empty fields" algorithm.
- When dealing with lines that can have empty fields, never leave a
field NULL, even if the ps line is too short to cover all the
headers. This fixes the segfault, since in the ucb parsing case, the
return value of SplitProcLine() would not be used, and hence we
would try to read the string afterwards.
Also enable some tests on all platforms that should now pass
everywhere.
> CFE-2161: Fix missing ps fields causing segfaults on Solaris.

- configure.ac
- libpromises/dbm_lmdb.c
There is a race condition in LMDB that will fail to open the database
environment if another process is opening it at the exact same
time. This condition is signaled by returning ENOENT, which we should
never get otherwise. This can lead to error messages on a heavily
loaded machine, so try to open it again after allowing other threads
to finish their opening process.
Ref: CFE-2300
> Fix "No such file or directory" LMDB error on heavily loaded hosts.

- cf-serverd/server.c
- tests/acceptance/16_cf-serverd/serial/001.cf.sub
- tests/acceptance/16_cf-serverd/serial/004.cf.sub
- tests/acceptance/16_cf-serverd/serial/007.cf.sub
- tests/acceptance/16_cf-serverd/serial/008.cf.sub
- tests/acceptance/16_cf-serverd/serial/010.cf.sub
- tests/acceptance/16_cf-serverd/serial/011.cf.sub
- tests/acceptance/16_cf-serverd/serial/allow_path1_then_deny_path2_a.cf.sub
- tests/acceptance/16_cf-serverd/serial/allowlegacyconnects_present.srv
- tests/acceptance/16_cf-serverd/serial/copy_from_classic_protocol_success.cf.sub
- tests/acceptance/16_cf-serverd/serial/copy_from_digest_different.cf.sub
- tests/acceptance/16_cf-serverd/serial/copy_from_digest_different_expand_shortcut.cf.sub
- tests/acceptance/16_cf-serverd/serial/copy_from_encrypted_md5_zero_length_file.cf.sub
- tests/acceptance/16_cf-serverd/serial/copy_from_md5_zero_length_file.cf
- tests/acceptance/16_cf-serverd/serial/simple_copy_from_admit_localhost.cf.sub
Stop accepting clients using non TLS connections by default.
Changelog: Clients connections using non TLS protocol are rejected
by default. (CFE-2339).
> CFE-2339 Don't accept old protocol by default.

- tests/acceptance/default.cf.sub
So that tests in the masterfiles policy framework can leverege the
standard library directly.
Ref: Jira #CFE-2331
> Change: Don't load plucked.cf.sub when testing masterfiles

- libpromises/failsafe.cf
This has become important after the switch to the new package promise
for inventory by default, since it will immediately start looking for
the package modules.
> ENT-2737: Fix failsafe.cf not populating modules directory.

- libpromises/processes_select.c
- tests/unit/split_process_line_test.c
HP-UX like to produce dates space padded to two digits, like so:
"May  4".
> ENT-2738: Tolerate more than one space in dates in ps output.

- examples/compare.cf
There was a _bundle name_ mismatch under `example/compare.cf`. Hence corrected it.
> updated the bundle name in compare.cf

- tests/acceptance/16_cf-serverd/serial/001.cf.sub
- tests/acceptance/16_cf-serverd/serial/004.cf.sub
- tests/acceptance/16_cf-serverd/serial/007.cf.sub
- tests/acceptance/16_cf-serverd/serial/008.cf.sub
- tests/acceptance/16_cf-serverd/serial/010.cf.sub
- tests/acceptance/16_cf-serverd/serial/011.cf.sub
- tests/acceptance/16_cf-serverd/serial/allow_path1_then_deny_path2_a.cf.sub
- tests/acceptance/16_cf-serverd/serial/copy_from_digest_different.cf.sub
- tests/acceptance/16_cf-serverd/serial/copy_from_digest_different_expand_shortcut.cf.sub
- tests/acceptance/16_cf-serverd/serial/copy_from_encrypted_md5_zero_length_file.cf.sub
- tests/acceptance/16_cf-serverd/serial/lan_open.srv
- tests/acceptance/16_cf-serverd/serial/localhost_deny_one_directory.srv
- tests/acceptance/16_cf-serverd/serial/localhost_deny_one_directory_with_regex.srv
- tests/acceptance/16_cf-serverd/serial/localhost_open.srv
- tests/acceptance/16_cf-serverd/serial/localhost_open_admit_hostnames.srv
- tests/acceptance/16_cf-serverd/serial/localhost_open_hostname.srv
- tests/acceptance/16_cf-serverd/serial/simple_copy_from_admit_localhost.cf.sub
After removing "protocol_version" all the tests were run with
classic protocol only. This is bringing back testing using both
classic and TLS protocols.
> Revert removed tests for both classing and TLS protocol.

- libpromises/processes_select.c
The header is always the first line, so just use that, instead of
scanning for "PID" which can occur in process names.
Changelog: Fix intermittent error message of type:
"error: Process table lacks space for last columns: <cmd>"
> CFE-2371: Prevent misinterpretation of ps column header line.

- libenv/time_classes.c
This greatly simplifies the removal of time-based classes and makes it much faster and more reliable by using tags instead of blindly shooting down class names.
> libenv: simplify and improve the removal of time-based classes

- cf-agent/files_editline.c
- libpromises/attributes.c
- libpromises/cf3.defs.h
- libpromises/mod_files.c
- tests/acceptance/10_files/07_delete_lines/select_end_match_eof_true.cf
- tests/acceptance/10_files/09_insert_lines/insert_line_end_match_eof.cf
Make sure that if select_end is not matched in file, EOF is used as
and of region by default.
To change default behavior, 'select_end_match_eof' was introduced.
The default value is true, so EOF is threated as end of region by default.
Changelog: EOF is implicitly matched as an end of the region in edit_line
promises. To change default behavior 'select_end_match_eof' parameter
was introduced. (CFE-2263)
> CFE-2263 Fix select_end EOF matching.

- cf-execd/cf-execd-runner.c
- tests/acceptance/25_cf-execd/mail_1st_run_empty_new_log.cf
- tests/acceptance/25_cf-execd/mail_empty_old_and_new_log.cf
- tests/acceptance/25_cf-execd/mailfilter_1st_run_everything_filtered.cf
- tests/acceptance/25_cf-execd/mailfilter_common.cf.sub
- tests/acceptance/25_cf-execd/mailfilter_empty_old_log_everything_filtered.cf
It was assumed we could short circuit in this case, but we can't
because we still don't know whether the filtered output of the new log
will produce any lines or not. So go through it even if the old log
cannot be opened, and treat it as if the old log is a 0-byte file.
Changelog: Fix bug which caused empty emails to be sent from cf-execd
if there was no previous output log and the new log was fully filtered
by email filters.
> ENT-2739: Don't skip output filtering if old output log doesn't exist.

- libpromises/failsafe.cf
> ENT-2755: Fix cf-serverd being launched under wrong account on Windows.

- libpromises/fncall.c
- tests/acceptance/01_vars/02_functions/ifelse_isvariable.cf
- tests/acceptance/01_vars/02_functions/ifelse_isvariable.cf.expected.json
see https://tracker.mender.io/browse/CFE-2260
* fixes the acceptance test (it was a bit broken before)
* special-cases the FnCall `ifelse("!any", ANYTHING, "foo")` to be allowed to evaluate even though `ANYTHING` may be an unexpanded variable. This is only done if `ifelse()` is called with exactly 3 arguments, but could be generalized fairly easily.
Use case:
```
ifelse( isvariable("init.passwd_file"), $(init.passwd_file), "/etc/passwd")
```
> CFE-2260: allow ifelse(FALSE, $(x), "something else") to work

- libpromises/rlist.c
- tests/unit/rlist_test.c
It all started from a segfault in rlist_test.c but reviewing the locking code in rlist.c indicated that most of it was bogus. In the end all thread-safety got removed, since it's only used in single-threaded contexts.
> CFE-2345: Rlists and thread-safety

- cf-agent/verify_processes.c
This moves the logging of a class definition as the result of a
restart_class attached to a processes promise from info to verbose. No
other class definition logging happens in info.
> Change: Switch processes restart_class logging to verbose

- libpromises/evalfunction.c
- libpromises/fncall.c
- libpromises/var_expressions.c
- tests/acceptance/01_vars/02_functions/getindices.cf
- tests/acceptance/01_vars/02_functions/getindices.cf.expected.json
```
If we have two indexed CFEngine variables:
vars:
"a[x]"    string => "one";
"a[x][y]" string => "two";
this structure is impossible to turn into JSON because if we do, we
get:
{
"a": {
"x": "one",
"x": {
"y": "two"
}
}
}
which contains two identical "x" keys, and is therefore invalid JSON.
In this case the old code would crash in some cases, but it's order
dependent, so it didn't always happen.
It's not necessary to use JSON for getindices(), since it returns a
list, but this was nevertheless the path taken in the code. So fix it
by avoiding this code path and taking the legacy path which handles
this case. Some extra care is needed because there are several ways in
which the input can be JSON, either by being specified inline, or by
referring to a variable that holds JSON, and in …
```
> CFE-2397: Avoid JSON incompatible code path in getindices().

- examples/isipinsubnet.cf
This will be used in https://github.com/cfengine/documentation/pull/1553 instead of the current inline example.
> ENT-7949: add example for isipinsubnet()

- cf-agent/verify_exec.c
- libpromises/attributes.c
- libpromises/cf3.defs.h
- tests/acceptance/08_commands/01_modules/module_with_no_output.cf
- tests/acceptance/08_commands/01_modules/module_with_no_output.cf.sub
Currently, when commands promise is used there is no option
to override default 'no_output' behavior which is true.
This will allow overwriting the default 'no_output' value.
Changelog: Fix 'contain' attribute 'no_output' having no effect when
the 'commands' promise is using 'module => "true"'.
Based on a patch by Marcin Pasinski <marcin.pasinski@cfengine.com>.
CFE-2412
> Make sure that no_output option can be used together with module.

- libutils/json.c
Manual backport of dd337dd04d6d95ad03931db8c329ecfdcfb67aa8
Jira #CFE-2141
> Change: Log level for keeping verbatim JSON to DEBUG

- libpromises/unix.c
When using Solaris with some kind of NFS safe_open might cause some weird errors.
> Use open instead of safe_open for hardcoded /dev/null path. 

- tests/unit/tar_portability_test.sh
Fixed by removing workdir in the shell script before running the test.
> tar_portability_test.sh failing because of long paths.

- cf-agent/verify_files.c
- cf-agent/verify_files_utils.c
- libpromises/cf3.defs.h
- tests/acceptance/10_files/12_acl/acl.cf.sub
Fixes CFE-616. Added acl_entries to phase 1 of VerifyFilePromise to ensure acls are applied, and changed order of applying perms and acls. ACLs are now applied after regular perms and the test passes.
> ACL bug CFE-616

- tests/acceptance/19_security/other_writeable/group_write.cf
- tests/acceptance/19_security/other_writeable/other_write.cf
This execresult() is being executed 4-5 because of the different
evaluation passes. The first times, the .cf file doesn't even exist. As
a result, failsafe.cf is created and executed, which launches
cf-serverd.
The fix here is necessary after the CFE-2162 changes were introduced, to
avoid running the command before populating the variable.
> CFE-2455: Fix ghost cf-serverd process remnants started in the chroot

- tests/acceptance/16_cf-serverd/serial/network/004.cf
- tests/acceptance/16_cf-serverd/serial/network/004.cf.sub
- tests/acceptance/16_cf-serverd/serial/network/lan_open.srv
This cf-serverd test (004.cf) uses the public interface, and as other
network tests have shown, fail on the cloud with "temporary name
resolution". So move it under "network" subdirectory, in order to be
skipped together with the rest of the network tests.
> INF-339: Alleviate network issues when testing on the Cloud.

- libpromises/failsafe.cf
Previously the results were changing because of ifelapsed promise locking.
> CFE-2474: Ensure that running failsafe many times in a row acts the sam

- libpromises/evalfunction.c
- tests/acceptance/01_vars/02_functions/variablesmatching.cf
- tests/acceptance/01_vars/02_functions/variablesmatching.cf.expected.json
As proposed in https://dev.cfengine.com/issues/7885 this is a function that parallels `variablesmatching()` in every way except it collects the value of the variables in addition to their name.
Acceptance test included.
> Redmine#7885: add data_matching() function paralleling variablesmatching()

- libpromises/failsafe.cf
Failsafe policy does some file copies to update policy and modules. When doing
these file copies, it should avoid copying VCS files (like .gitignore files).
> CFE-2439: failsafe policy should not copy VCS files

- libpromises/evalfunction.c
- libpromises/fncall.c
- libpromises/fncall.h
- tests/acceptance/01_vars/02_functions/maparray.cf
- tests/acceptance/01_vars/02_functions/maparray_mapdata.cf
- tests/acceptance/01_vars/02_functions/maparray_mapdata.cf.expected.json
- tests/acceptance/01_vars/02_functions/maplist.cf
- tests/acceptance/01_vars/02_functions/maplist.cf.expected.json
Briefly, this allows the user to do `maplist(function($(this)), mylist)` (delay evaluation of function calls inside some special iteration functions).
Also covers `maparray()` and `mapdata()`.
I added some tests.
If this is acceptable, I can add a ChangeLog entry and docs.
@nickanderson this is a long-standing feature request, and users definitely expect it to work this way.
> ARCHIVE-1619: allow maplist(), maparray(), and mapdata() to evaluate function calls during iteration

- misc/init.d/cfengine3.in
According to the LSB standards init scripts status should return 3 if
the service is not running.
http://refspecs.linuxbase.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html
> CFE-2421 Fix: Return code when init script status down

- cf-agent/verify_users.h
- cf-agent/verify_users_stub.c
- libpromises/evalfunction.c
- tests/acceptance/01_vars/02_functions/getuserinfo.cf
- tests/acceptance/01_vars/02_functions/getuserinfo.cf.expected.json
This is a first rough cut of the function `getuserinfo()` I proposed in #1413 
Returns:
```json
{
"description": "root",
"gid": 0,
"home_dir": "/root",
"shell": "/bin/bash",
"uid": 0,
"username": "root"
}
```
Still TODO: `locked` boolean, primary group name, list of secondary group names, list of secondary GIDs, and password data.
> Add getuserinfo() function

- examples/getuserinfo.cf
- libenv/sysinfo.c
- libenv/sysinfo.h
- libpromises/evalfunction.c
@jimis @nickanderson @skreuzer as discussed in #2575 and #1413 
For the current execution's user info, you still have to `getuserinfo()` which implicitly looks at the current UID. Or you can use the current promise UID variable: `getuserinfo($(this.promiser_uid))`. That way, we avoid wasting time converting the passwd struct to a data container on every promise evaluation, since I think it will be needed very rarely in the context of general CFEngine execution.
> Add sys.user_data container for user starting agent.

- libpromises/evalfunction.c
- tests/acceptance/01_vars/02_functions/gettags.cf
- tests/acceptance/01_vars/02_functions/gettags.cf.expected.json
Simple change, low risk. Acceptance test included.
> Allow getvariablemetatags() and getclassmetatags() to get a specific tag key

- misc/systemd/cf-redis-server.service.in
redis-server needs to daemonize, otherwise non-systemd platforms will
hang when trying to launch it.
> ENT-2831: Fix bootstrap hanging on non-systemd platforms.

- misc/systemd/cf-execd.service.in
- misc/systemd/cf-serverd.service.in
When the package is initially installed, the cf-serverd service unit is
enabled and started. This is before bootstrap happens, and thus before
there is a promises.cf in $(sys.inputdir). cf-serverd ends up running
from failsafe.cf and will never reload its config from promises.cf after
it appears in inputs. This change prevents cf-serverd from starting
until the host has been bootstrapped.
> ENT-2376 Prevent cf-serverd from being started without promises.cf on systemd hosts

- cf-agent/cf-agent.c
- cf-execd/cf-execd.c
- cf-key/cf-key.c
- cf-monitord/cf-monitord.c
- cf-promises/cf-promises.c
- cf-runagent/cf-runagent.c
- cf-serverd/cf-serverd-functions.c
- libpromises/generic_agent.c
- libpromises/generic_agent.h
- libutils/writer.c
- libutils/writer.h
- tests/acceptance/mock_package_manager.c
Must be merged with: https://github.com/cfengine/nova/pull/989
I'm doing this since cf-net tool should not depend on libpromises, but should use this function, like the other binaries.
> GenericAgentWriteHelp renamed and moved out of libpromises

- libpromises/processes_select.c
The correct approach when it is not available is to make the list of
ps information empty, not to delete it. This is already what happens
if the command can't be executed, but if executed with the wrong
arguments (ucb arguments for a non-ucb ps variant), the list would be
deleted.
> CFE-2506: Fix crash on Solaris when ps ucb variant is not available.

- misc/systemd/cfengine3.service.in
Historically stopping or starting the cfengine3 service has been a
synchronous process. This preserves that synchronous behaviour for the
umbrella service under systemd.
> ENT-2841: Ensure synchronous start and stop with systmectl

- contrib/enterprise/host-info.sh
This script allows for easy lookup of information about a given host
from the command line on the policy server.
It allows lookup by hostname, IP address or SHA.
> Add host info script

- libpromises/evalfunction.c
- tests/acceptance/01_vars/02_functions/getindices_and_getvalues_return_same_with_empty_datacontainer.cf
Restores 3.7.x and earlier behaviour.
Changelog: commit
> CFE-2479: Behaviour change: getvalues(inexistent_var) returns an empty list.

- libpromises/expand.c
I am preparing a issue on Jira about this (and other performance issues), but this seems to fix the performance worsening between 3.9 and 3.10 in ncf code evaluation.
> CFE-2524: Only call BundleResolvePromiseType when it is needed as it is expensive

- HACKING.md
As of 3.10, it's no longer just the IP address -- it could be the hostname.
> Change documentation for what gets written to policy_server.dat

- configure.ac
- misc/determine-version.py
On FreeBSD, python is installed via the ports system which by default will place binaries in /usr/local/bin. Switching the shebang line to `/usr/bin/env python` in misc/determine-version.py will make this script a bit more portable across different platforms
Add 'amd64' to the list of accepted x86 platforms when checking the value of $host_cpu. On FreeBSD this was preventing XEN_CPUID_SUPPORT from being defined which compiled out the functions to detect if the machine was running as a domU under Xen. This addresses the issues documented in CFE-2203
> FreeBSD Build Tweaks

- tests/acceptance/Makefile.am
- tests/acceptance/plucked.cf.sub
While working on CFE-2519 the presense of manage_variable_values_ini in
the plucked library was being used instead of the MPF and no error was
thrown since the body was found complicating test development.
None of the bodies or bundles removed from the plucked library were used
in any tests.
> Unpluck unused bodies and bundles from test framework

- tests/acceptance/Makefile.am
- tests/acceptance/plucked.cf.sub
Reverts cfengine/core#2758, because of broken tests in masterfiles
> Revert "Unpluck unused bodies and bundles from test framework"

- tests/acceptance/01_vars/02_functions/network/selectservers.cf
For some reason 8.8.8.8 is answering at port 80 only from Travis'
VMs. Try using another host that does not listen to 80 for sure.
> Fix failing acceptance test on Travis.

- libenv/sysinfo.c
- libpromises/evalfunction.c
- tests/acceptance/01_vars/02_functions/211.cf
- tests/acceptance/01_vars/02_functions/getvalues_array_string.cf
- tests/acceptance/01_vars/02_functions/getvalues_plain_string.cf
- tests/acceptance/01_vars/03_lists/001.cf
it should always return a list, even when v is a simple string.
> CFE-2504: restore old getvalues(v) behaviour;

- tests/unit/passopenfile_test.c
I found this in a compiler warning when building for mac in travis. I don't see the reason why the if statements are excluded.
> Fixing weird if statements in passopenfile_test

- libenv/sysinfo.c
This adds support for detecting Amazon Linux which is a fork of RHEL optimized for running in EC2
> Detect Amazon linux

- tests/acceptance/01_vars/deep_delayed_expansion/def.json
- tests/acceptance/01_vars/deep_delayed_expansion/main.cf
- tests/acceptance/01_vars/deep_delayed_expansion/my_globals.cf.sub
When setting a cfengine variable from another cfengine variable that
contains an un-dereferenced variable the agnet should dereference
deeply.
> Test deep delayed expansion

- cf-execd/cf-execd-runner.c
Changelog: Fix a bug which could cause cf-execd to believe there was
an error when sending the email report, when there really wasn't.
> cf-execd: Add incorrect error check to email filter code.

- cf-key/Makefile.am
pcre.h is now included (from generic_agent.h)
> CFE-2525: Add missing pcre build flags to cf-key

- libenv/unix_iface.c
ifconfig utility is installed into the BINDIR by default since commit https://sourceforge.net/p/net-tools/code/ci/36b541c9f3efe55c5871674ee926be8b20339497/, made on 2011-12-02.
> unix_iface: try to look for ifconfig in /bin as well

- HACKING.md
Remove the reference to redmine since the bug tracker has been moved over to jira
> Remove reference to redmine

- cf-agent/verify_files.c
When promising to copy remote paths recursively if the paht is a non
directory a warning is emitted but the file is copied anyway so it does
what the use meant. The warning in this case end up being useless noise.
Perhaps it is useful for debugging, but for policy writers it only poses
a challenge to be worked around. This removes the need to implement
additional policy in order to differentate between files and directories
only for the suppression of the warning.
Ref: https://groups.google.com/forum/#!topic/help-cfengine/ekSgRU3j1W4
> Change: Warning about depth_search on a non directory to DEBUG

- tests/acceptance/10_files/templating/classic_template_wont_render_cf_null_with_empty_datacontainer.cf
- tests/acceptance/10_files/templating/classic_template_wont_render_cf_null_with_empty_datacontainer.cf.tpl
(cherry picked from commit f3958aa4b4ba487aaedeb4ec4dfff7f8be5e07de)
> Add: test classic template wont render cf_null with absent data container

- libpromises/cf3parse.y
- libpromises/dbm_api.c
- libpromises/eval_context.c
- libpromises/evalfunction.c
- libpromises/expand.c
- libpromises/policy.c
`master` before fixes:
```
23:23:20 client:vagrant core $ sudo valgrind --leak-check=full --track-origins=yes /var/cfengine/bin/cf-promises
==18603== Memcheck, a memory error detector
==18603== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==18603== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==18603== Command: /var/cfengine/bin/cf-promises
==18603==
==18603==
==18603== HEAP SUMMARY:
==18603==     in use at exit: 187,199 bytes in 155 blocks
==18603==   total heap usage: 1,261,910 allocs, 1,261,755 frees, 308,693,390 bytes allocated
==18603==
==18603== 8 bytes in 1 blocks are definitely lost in loss record 2 of 66
==18603==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==18603==    by 0x5434729: strdup …
```
> Various memory leaks (valgrind cf-promises)

- misc/init.d/cfengine3.in
> ENT-3123: Stop service cfengine3 status from warning on multiple httpd processes

- examples/with.cf
- libpromises/eval_context.c
- libpromises/iteration.c
- libpromises/mod_common.c
- tests/acceptance/00_basics/01_compiler/with_iteration.cf
- tests/acceptance/00_basics/01_compiler/with_iteration.cf.expected.json
- tests/acceptance/testall
Fixes https://tracker.mender.io/browse/CFE-1092
Add universal "with" attribute to allow functions calls in promiser on $(item).
Add acceptance test.
Changelog: CFE-1092: allow function calls in promiser using universal "with" attribute.
> Allow function calls in promiser through new "with" attribute.

- cf-net/Makefile.am
All other binaries were moved to bin from sbin. See here: https://github.com/cfengine/core/commit/72054384c17c34f3e0662ea0b0f3221ac5151c95. This is to install cf-net in bin as well.
> Install cf-net binary in bin instead of sbin.

- cf-promises/cf-promises.c
- libpromises/match_scope.c
- libpromises/match_scope.h
- libutils/regex.c
- libutils/regex.h
Trivial.
As requested in https://github.com/cfengine/core/pull/2480#discussion_r116465231 by @jimis
> Rename PartialMatch to PartialRegexMatch

- cf-agent/cf-agent.c
- cf-promises/cf-promises.c
- libpromises/generic_agent.c
- libpromises/generic_agent.h
@nickanderson I got sick of writing stuff like this, which doesn't even show all the classes:
```
{
methods:
"test";
vars:
"test_state" data => bundlestate(test);
"test_string" string => storejson(test_state);
reports:
"$(this.bundle): state of things = $(test_string)";
}
bundle agent test
{
...
}
```
So I believe there's a practical need, especially for quick demos and for debugging.
If this is merged, I'll adjust #2480 as well (it needs rebasing anyway) and write docs as usual.
The options and code changes are minimal. We're just moving the support code for `--show-vars` and `--show-classes` (plus one enum) to `generic_agent.[ch]` and write the exact same glue as cf-promises in `cf-agent/cf-agent.c` to show vars and classes before destroying the policy. The only …
> cf-agent: learn --show-vars and --show-classes to show final state

- contrib/katepart-cfengine.highlight.xml
This change should enable single quoted Strings to be highlighted as well.
> adding single quoted Strings to highlighting

- libpromises/evalfunction.c
- libutils/json-utils.c
`readfile()`, `readjson()`, `readyaml()`, `readenvfile()` and `readcsv()` now all follow the same syntax: 
* First parameter is file path, and required
* Second parameter is max bytes to read, and optional.
Fixed an issue where csv and env parser would output bogus error messages and destroy data when the byte limit was reached.
Need to update docs and add more tests.
https://tracker.mender.io/browse/CFE-2657
https://tracker.mender.io/browse/CFE-2656
> Fixes to readenvfile() readcsv() readfile() (CFE-2657, CFE-2656)

- cf-net/cf-net.c
Enterprise should not use md5
Ticket: ENT-3201
> Set default digest based on version (ENT-3201)

- libpromises/evalfunction.c
Introduced in https://github.com/cfengine/core/pull/2858, 6 days ago.
No changelog added, the changelog entry from last commit is fine.
> Fixed default size bug in readfile() (CFE-2661)

- libpromises/locks.c
Example policy to test this:
```
body contain mypowershell
{
!windows::
useshell => "useshell";
windows::
useshell => "powershell";
}
body action fastlocks
{
ifelapsed   => "0";    # disable ifelapsed lock
expireafter => "1";    # promise expires after 1 minute
}
{
commands:
"sleep"
args => "3000",
action => fastlocks,
contain => mypowershell;
}
```
> make cf-agent kill other expired (expireafter) agents on windows (CFE-2211)

- misc/determine-version.py
instead of `git show-ref master`
> ENT-3240: check for master branch via `git branch -r --merged`

- libutils/platform.h
SUNOS_5 define is used in generic_agent.c, but it's not defined
anywhere.
> Ensure that CFE-2527 fix works on Solaris.

- misc/init.d/cfengine3.in
Without the lsb init functions included systemv init scripts will not
automatically redirect to systemctl.
> ENT-3326: Properly redirect init script to systemd on debian systems

- contrib/enterprise/sha-deletion.sh
For bulk removals of host records this script is incomparably easier
to use than the UI or the REST API.  For single host removals it is
still slightly easier than the REST API and there is lot less to remember.
I've been using this for many months; there are really no caveats.  Input is
fully validated before use.  (It's not checked that a given SHA actually *exists*
on the hub before attempting to remove it; only that is validly formatted as a SHA.
However, this matches the behavior of the UI for hostkey removals, so not an issue.)
> sha-deletion.sh wrapper script for record cleanup

- contrib/cf-profile/README.md
`cf-agent -v | ./cf-profile.pl -a` will work on currently supported versions of CFEngine (3.7 and 3.10)
Rather than have three sections (before 3.5.0, up to 3.7.0, and after 3.7.1) in the README, it is cleaner to just give the command that worked originally and works again now.
I don't feel super strongly about my proposed wording (feel free to edit it) but the README definitely needs to be updated as the current instructions are out of date, for example, `cf-agent -v --legacy-output | ./cf-profile.pl -a` will not work on 3.7.3 as the "legacy-output" option has been removed.
> Remove mention of CFEngine versions from README

- misc/changelog-generator/changelog-generator
- misc/changelog-generator/test-changelog-generator
@jimis: These are the changes we have made in Mender's changelog-generator that can be ported back to CFEngine's generator. Pick and choose as you like. Even with these ports there are substantial differences, mostly due to different repository structure, but this at least brings them closer to each other.
> Changelog-generator updates

- configure.ac
The 'u' in the autotools default generates a lot of warnings when passed to
'ar'. Setting the flags to just 'cr' will prevent the "`u' modifier ignored
since `D' is the default (see `U')" message.
> Set AR_FLAGS to 'cr' to avoid autotools default of 'cru'.

- libutils/man.c
in order to enable reproducible builds.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.
> libutils/man.c: allow to override build time

- configure.ac
- libutils/platform.h
Release notes for glibc-2.25 state:
The inclusion of <sys/sysmacros.h> by <sys/types.h> is deprecated.
This means that in a future release, the macros “major”, “minor”, and
“makedev” will only be available from <sys/sysmacros.h>.
These macros are not part of POSIX nor XSI, and their names frequently
collide with user code; see for instance glibc bug 19239 and Red Hat
bug 130601. <stdlib.h> includes <sys/types.h> under _GNU_SOURCE, and
C++ code presently cannot avoid being compiled under _GNU_SOURCE,
exacerbating the problem.
evalfunction.c: In function ‘FnCallFileStatDetails’:
evalfunction.c:3191:64: error: implicit declaration of function ‘minor’; did you mean ‘mknod’? [-Werror=implicit-function-declaration]
snprintf(buffer, CF_MAXVARSIZE, "%jd", (uintmax_t) minor(statbuf.st_dev) ); …
> Inclusion of sysmacros.h by types.h is deprecated.

- misc/systemd/cf-execd.service.in
> ENT-3395: cf-execd systemd service now only kills cf-execd itself

- tests/acceptance/00_basics/01_compiler/CFE-2698.x.cf
Test that an undefined variable used in a function with the unless
attribute does not caue a fatal error
> CFE-2689: Acceptance Test

- examples/peerleaders.cf
The test does not work if HOSTNAME is now downcased. CFEngine always
downcases the hostname and the fqdn must be found in the list in order
to determine peers.
> Fix peerleaders test

- libenv/sysinfo.c
Define the hard class `alpine_linux` if the file /etc/alpine-release
exists on disk.
Retrieve the version information from the alpine-release file and define a
hard class with the canonified version of the release appended.
> Improve support for Alpine Linux

- libpromises/exec_tools.c
- libpromises/pipes_unix.c
cf-execd uses cf_popen_sh() to launch exec_command every 5 minutes. In
this function, fork() and exec() are called. But after fork() and before
exec(), the child process calls CloseChildrenFD(), which locks a mutex,
and also free()s memory, which internally also locks mutexes!  However
cf-execd is multi-threaded at that point, and every non-reentrant
non-signal-handler-safe function is strictly forbidden in this context.
Solution: avoid all unsafe operations, even if that entails race
conditions and memory leaks. Races don't matter because all secondary
threads are frozen after fork(), leaks don't matter either as exec()
overwrites the whole process.
> CFE-2719: Fix rare cf-execd hang

- contrib/cfengine-code-style.el
It is the convention to have such a header in every Emacs lisp
library.  One benefit is that it helps tools that extract Emacs
packages from repositories that contain much more than just the
Emacs lisp.  Without this change the tools used to maintain the
Emacsmirror does not see the license because it only extracts
the library itself from the repository and discards all other
history.
Note that I have used a variation that says "version 3" and thereby implies "exactly version 3, but not any later version". I can do that because the `LICENSE` files says so. However `cfengine.el` is releases under "version 3, or (at your option) any later version", and it would be best to do that here too. But I cannot legally do that.
Please add a **second commit** (do not change my commit) to make this …
> Add permission statement to cfengine-code-style.el

- cf-key/cf-key-functions.c
- cf-key/cf-key-functions.h
- cf-key/cf-key.c
When running cf-key to generate new keys, set the exit value of the
program to be 0 on success and 1 on failure. This makes it easier to
catch errors during setup of a new machine.
Change the default behavior of the program to not write anything to stdout,
opting to use the Log() function which can write to stdout and will also
allow output to be sent to syslog.
Add a --inform option to set the global log level to LOG_LEVEL_INFO.
Change the permissions of the randseed file to 600 and catch the exception
if the chmod call fails.
> Set the exit value when running cf-key

- libpromises/promises.c
For constraints if/ifvarclass/unless, we now print the whole rval of the constraint.
Previously the message was just "skipping variable because ifvarclass is not defined" while the variable itself was defined.
Old message example:
verbose: Skipping promise 'mailto' because 'if'/'ifvarclass' is not defined
Changed to:
verbose: Skipping promise 'mailto' because constraint 'ifvarclass => not(isvariable("mailto"))' is not met
Changelog: commit
> CFE-2697: Improve misleading verbose message

- cf-agent/files_changes.c
Promise comments are printed in verbose logs for all promise types except file
change monitoring. This can cause extra noise and multi-line promise comments
are not always handled well in syslog filtering.
> ENT-3414: Move promise comment to verbose

- libpromises/cf3parse.y
This pull request is to fix the following bug found when running make install.
$ make install
Making install in libcompat
Making install in libutils
Making install in libcfnet
Making install in libenv
Making install in libpromises
YACC cf3parse.c
byacc: 1 shift/reduce conflict.
updating cf3parse.h
CC cf3parse.lo
cf3parse.y: In function 'yyparse':
cf3parse.y:496:79: error: 'YYEOF' undeclared (first use in this function)
if (yychar == BUNDLE || yychar == BODY || yychar == YYEOF)
^
cf3parse.y:496:79: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [cf3parse.lo] Error 1
make[2]: *** [install] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2
I figured, since it's not declared and not used elsewhere in the file, …
> CFE-2703: Removing undeclared references

- libenv/unix_iface.c
interfaces_data is commonly larger than the maximum data size allowed to be
collected by cf-hub. Data larger than 1k is truncated. Instead of reporting
truncated data this change stops tagging the variable so that it will not be
collected to the Enterprise hub.
> ENT-3483: Do not tag large volatile data for inventory

- tests/acceptance/Makefile.am
This exports now properly environment variables to testall, so other
unidentified breakage should also be fixed.
> CFE-2736: Fix libxml2 tests not being skipped

- .travis.yml
- tests/acceptance/16_cf-serverd/serial/copy_from_inexistent_file_connection_closed-classic_protocol.cf.sub
- tests/acceptance/16_cf-serverd/serial/copy_from_inexistent_file_connection_closed.cf.sub
- tests/acceptance/serverd-multi-versions-blacklist.txt
- tests/acceptance/serverd-multi-versions.sh
- travis-scripts/after_script.sh
- travis-scripts/script.sh
And add this as a new job to Travis.
These versions are tested so far:
* currently built server with 3.10.2 agent
* currently built server with 3.7.6 agent
* currently built agent with 3.10.2 server
* currently built agent with 3.7.6 server
> ENT-3430: Add a script to run cf-serverd tests with various versions

- libpromises/generic_agent.c
This change makes it more apparent that an additional augments file has
completed its processing rather than seeming like it was processed
multiple times.
> CFE-2084: Improve multiple augments logging

- tests/acceptance/01_vars/02_functions/iterating_variablesmatching_results.cf
(cherry picked from commit 9925ead74fd8e94603b86feda28ce4934a06218b)
> CFE-2593: Test that iterating variablesmatching() results does not crash the agent

- libpromises/failsafe.cf
When the agent is bootstrapped from an unprivledged user using sudo systemctl
may complain about not being able to access the a tty.
notice: Q: ".../systemctl rest": Failed to open /dev/tty: No such device or address
This is because cfengine runs commands in their own sessions.
This change simply suppresses the command output to avoid distracting operators.
> CFE-1459: Suppress output from systemctl based restart of services in bootstrap/failsafe

- libpromises/loading.c
- libpromises/policy.c
Somebody may accidentally run cf-agent or cf-promises on a JSON
file that is not a valid policy file in the JSON format.
> Don't segfault if a JSON policy file contains no bundles and bodies

- libpromises/loading.c
- libpromises/policy.c
Somebody may accidentally run cf-agent or cf-promises on a JSON
file that is not a valid policy file in the JSON format.
(cherry picked from commit 5f56849ff583dbab543dfc0c146d5b7edfb9dd3a)
> CFE-2754: Fix segfault on JSON policy files with no bundles and bodies

- tests/acceptance/dcs.cf.sub
(cherry picked from commit 84c81f4701a2e8e8f8f5473377ae858dc9c40597)
> INF-311: fix failing tests on Solaris 10, because of gmake not found.

- cf-agent/cf-agent.c
- libpromises/generic_agent.c
- libpromises/generic_agent.h
When running cf-agent (compiled on Fedora 27), I get a segfault in pcre because of no initial value for the `show_classes` and `show_variables` regexes.
> Fix segfault when no show-evaluated-vars/classes is specified

- INSTALL
The project documentation still references the old URL for the help-cfengine mailing list. This change updates it to the current one.
> Update URL for help-cfengine mailing list.

- cf-serverd/server_transform.c
- libpromises/attributes.c
- libpromises/verify_vars.c
According to the recently updated documentation on promise
locking, there are several promise types that don't support any
form of promise locking:
* access
* classes
* defaults
* meta
* roles
* vars
When a policy writer uses "ifelapsed" or "expireafter" attributes
(via an action body) on these promise types which don't support
them, a warning should be issued rather than the setting being
silently ignored.
Codewise, it would be great if every promise evaluation called
GetTransactionConstraints(), that way we could only have the
check and warning in one place. Unfortunately, that's not the
case, VerifyVarPromise() is not calling that particular function
and neither is handling of 'access' and 'roles' in cf-serverd.
> CFE-2748: Issue a warning on ignored locking attributes

- libenv/unix_iface.c
- tests/acceptance/02_classes/01_basic/ipaddr_classes.cf
Hard classes for the IPv4 addresses have the "ipv4_" prefix so
the IPv6 ones should use the same pattern. However, we shouldn't
just prefix the existing hard classes as users may rely on them
being available without the prefix. Thus add new ones.
> CFE-2310: Add IPv6 hard classes with the "ipv6_" prefix

- configure.ac
Commit 41c0afd ("Improve readability") moved the error handling for a
missing libacl header into AC_CHECK_HEADER's action-if-not-found.  This
was a mistake, though, as this action is executed for each header not
found, which was not the intent of the original check.
For libacl, it is enough for any of the header files [acl.h sys/acl.h
acl/libacl.h] to be present.
> fix detection of libacl headers

- tests/unit/Makefile.am
With the new linker flags introduced in cfengine/buildscripts#328
no unittests should be failing on AIX.
> No expected unittest failures on AIX anymore

- libpromises/evalfunction.c
- libpromises/fncall.c
- tests/acceptance/01_vars/02_functions/filesexist-can-detect-files-containing-hash-character.cf
- tests/acceptance/01_vars/02_functions/filesexist-is-collecting.cf
- tests/acceptance/02_classes/02_functions/empty_list_or_data_doesnt_return_true_for_filesexist.cf
Adding a test in the first commit because it turns out things just work as [expected/documented](https://docs.cfengine.com/docs/3.10/reference-functions-filesexist.html). The other commit is a related minor fix-up.
> Hashes in file paths in filesexist()

- libpromises/evalfunction.c
- tests/acceptance/01_vars/02_functions/hash_to_int.cf
- tests/acceptance/01_vars/02_functions/randomint.cf
Can be used instead of randomint, for deterministic outcome.
The return value is based on a SHA digest of the input string alone.
Ticket: CFE-2733
https://ci.cfengine.com/job/pr-pipeline/140/
https://ci.cfengine.com/job/pr-pipeline/143/
https://ci.cfengine.com/job/pr-pipeline/145/
https://ci.cfengine.com/job/pr-pipeline/149/
https://ci.cfengine.com/job/pr-pipeline/166/
https://ci.cfengine.com/job/pr-pipeline/177/
https://ci.cfengine.com/job/pr-pipeline/180/
https://ci.cfengine.com/job/pr-pipeline/181/
https://ci.cfengine.com/job/pr-pipeline/182/
> CFE-2733: New hash_to_int function

- libpromises/unix.c
Since isexecutable() is only checking to see if a file is executable we do not
need to have an error message that is always emitted if the file does not exist.
The function will return non-true and the class will not be set. If the file
does not exist, it's not executable.
> CFE-741 Do not error when file does not exist with isexecutable()

- libpromises/generic_agent.c
- tests/acceptance/00_basics/def.json/policy_server_classes.cf
- tests/acceptance/00_basics/def.json/policy_server_classes.cf.json
This means that classes defined as part of the context discovery
(e.g. 'am_policy_hub' and 'policy_server') can be used in the
augments.
> CFE-2482: Load augments at the end of context discovery

- cf-agent/verify_methods.c
Method parameters have to be set for method evaluation and then
unset when the evaluation is done. Otherwise they may appear in
wrong places in the logs and/or incorrectly influence who knows
what.
> CFE-2779: Make sure parameters are set only for the method evaluation

- libpromises/unix.c
This reverts commit 0df7a2a3fa18e710a24c1c040d5bb2f43e73aa1a.
This change was found to affect more areas than desired.
> Revert "CFE-741 Do not error when file does not exist with isexecutable()"

- libpromises/evalfunction.c
This introduces another stat() syscall which is
inefficient, isexecutable() now does:
lstat() -> stat() -> stat()
It becomes quite a bit more complex if you want
to refactor this nicely. You have to take into
account:
* Other functions like returnszero()
* IsExecutable() C function is used by commands promises
* The error message for world writable executables
* Windows compatibility functions
Thus, I kept the existing codebase and behavior as is,
and only fixed this specific issue.
Ticket: CFE-741
> CFE-741: Don't error when calling isexecutable on broken link

- libpromises/evalfunction.c
- tests/acceptance/01_vars/02_functions/array_subkey_collision.cf
Whenever there is a conflict of array variable definitions prefer
the container subkeys over simple values when converting to JSON.
> CFE-2536: Resolve subkey conflicts when converting to JSON

- tests/acceptance/01_vars/02_functions/mustache_iterating_object_workaround.cf
Our implementation of the mustache templating iterates over not
only JSON arrays but also over JSON objects (their
properties). That can easily result in duplicates when rendering
the output (see CFE-2125 for more details). However, the
iterations are done on purpose to make our extensions to the
referential implementation work. So instead of disabling them
let's just make sure an easy workaround works.
> CFE-2125: Add a test for a workaround for mustache section iterations

- cf-serverd/server_transform.c
meta type promises are valid in all bundle types.
> CFE-2066 3.7.x Do not ignore meta promises in server bundles

- cf-serverd/server_transform.c
meta type promises are valid in all bundle types.
(cherry picked from commit 05036fe47749b3b51f35a87d8fd7ee775dd61a44)
> CFE-2066 3.10.x Do not ignore meta promises in server bundles

- libpromises/pipes.c
- libpromises/pipes_unix.c
We need to do totally different tricks on windows.
> ENT-2713: Make the PipeIsReadWriteReady OS-specific

- cf-agent/verify_files_utils.c
- libpromises/files_lib.c
- libpromises/generic_agent.c
- libpromises/locks.c
(cherry picked from commit df970a9b80002fbc98ec02c432142f7b74d81e20)
> CFE-2802 Fix spelling in log messages

- tests/acceptance/01_vars/02_functions/shuffle-exact.cf
It seems to be suffering from the same issues as on RHEL 4 and
Debian 4.
> Disable the shuffle-exact.cf test on RHEL 5 too

- cf-key/cf-key-functions.c
- cf-key/cf-key-functions.h
- libpromises/crypto.c
- libpromises/crypto.h
These functions can be useful for other tools so they should not
be in sources specific for cf-key.
> Make a few functions from cf-key reusable

- cf-testd/cf-testd.c
Waiting for up to 10 seconds means that cf-testd can terminate
quite a while after being terminated (signalled).
> Shorten the WaitForIncoming() loop in cf-testd

- libpromises/eval_context.c
- libpromises/eval_context.h
- libpromises/files_names.c
- libpromises/files_names.h
- libpromises/generic_agent.c
- libpromises/loading.c
- libutils/sequence.c
- libutils/sequence.h
Example usage:
```
root@dev core $ cat imported.cf
bundle agent __main__
{
reports:
"Hello __main__, imported.cf can be executed directly";
}
bundle agent useful_functionality(caller)
{
reports:
"$(this.promise_filename) is used as a library from $(caller)";
}
root@dev core $ cat entry.cf
body common control
{
inputs => {"${sys.policy_entry_dirname}/imported.cf"};
}
{
methods:
"Library call"
usebundle => useful_functionality("$(sys.policy_entry_basename)");
reports:
"Hello main";
}
root@dev core $ sudo /var/cfengine/bin/cf-agent -f ./entry.cf -K
R: /home/vagrant/cfe/core/imported.cf is used as a library from entry.cf
R: Hello main
root@dev core $ sudo /var/cfengine/bin/cf-agent -f ./imported.cf -K
R: Hello __main__, imported.cf can be executed directly
root@dev core $ …
```
> CFE-2788: Added __main__ bundles with special semantics

- libpromises/eval_context.c
- libpromises/eval_context.h
- libpromises/expand.c
- libpromises/loading.c
- libpromises/verify_vars.c
- libutils/sequence.c
- libutils/sequence.h
- tests/acceptance/01_vars/01_basic/can_not_define_variables_in_remote_bundles.cf
- tests/acceptance/08_commands/01_modules/set-context.cf
- tests/acceptance/08_commands/01_modules/set-context.cf.txt
- tests/unit/sequence_test.c
As described and discussed in CFE-1915, defining remote variables
(injecting variables into remote bundles) is dangerous and must
be blocked. However, using a dot-separated common prefix for
variables raises no security concerns and can be considered
valid.
> CFE-1915: Allow dots in variable identifiers with no such bundle

- libutils/mustache.c
- tests/acceptance/01_vars/02_functions/mustache_iterating_object_should_use_context_for_single_block_render.cf
Only lists are supposed to be iterated over. Otherwise duplicates
appear when using JSON with objects that have multiple
properties. See CFE-2125 for details.
However, our '{{@}}' extension to the mustache specification
requires JSON objects' properties to be iterated over because
it's the names of these properties (keys) it should be
substituted with.
> CFE-2125: Do not iterate over JSON objects' properties in mustache

- cf-agent/verify_files.c
- tests/acceptance/10_files/templating/mustache_invalid_template_data.cf
Passing no template_data should result in using datastate()
instead as our documentation says. But passing invalid data is a
different case that should result in an error and the template
not being rendered.
> CFE-2194: Do not render templates when passed invalid data

- cf-net/cf-net.c
Ticket: CFE-2832
(cherry picked from commit cfcde9391ae930166671e75dbf70fd1c781f2121)
> CFE-2832: Fixed segfault when giving invalid arguments to cf-net (3.12)

- libpromises/eval_context.c
Ticket: https://tracker.mender.io/browse/CFE-2793
> CFE-2793: Bundle name is now part of the log message when aborting a bundle

- ChangeLog
- libpromises/generic_agent.c
- tests/acceptance/00_basics/def.json/augments_order.cf
- tests/acceptance/00_basics/def.json/augments_order.cf.augmenter.json
- tests/acceptance/00_basics/def.json/augments_order.cf.json
These are supposed to be most specialized and finest-granularity
policies (based on e.g. $(sys.flavor) and similar things). So
they should override values of any variables defined in 'vars' in
def.json if they defined the same variables, of course.
See the discussion in CFE-2741 for more details.
Changelog: CFE-2844: Apply augments after vars, classes and inputs in def.json
(cherry picked from commit 8bdc87c26f69e1886ac863bc9e62b68b6125f75e)
> CFE-2844: Make sure 'augments' from def.json are applied last

- cf-serverd/cf-serverd-functions.c
This number is used in the listen() syscall and determines the
maximum number of established connections that could be waiting
to be accepted. Any connections beyond this limit are either
refused or, worse, fed cookies (see tcp_syncookies in
man:tcp(7)).
Kernel has its own limit for this number (per socket) which is an
upper bound and it defaults to 128 [1]. So let's use this maximal
possible value as a default, there's nothing to lose for us. We
have a capability to handle many connections in threads
(specified in 'body server control' -> maxconnections), but if
too many connections are attempted at once, we need a big enough
backlog/queue to give us enough time to process them. Starting
threads may just not be fast enough, especially in combination
with our bad way of counting threads …
> 3.10.x - Increase the connection backlog/queue size in cf-serverd

- misc/systemd/cf-runalerts.service.in
The unit has been changed to execute with php explicitly instead of relying on runalerts.php to be executable.
> ENT-3929 Fix cf-runalerts systemd unit conditions so the service will run

- cf-execd/cf-execd-runner.c
Admittedly rare, but the absence of this log statement made trouble-shooting an issue more difficult for me.
> Added a log message for the case that the output file has ceased to exist by the time cf-execd tries to mail it.

- .gitignore
- misc/systemd/cf-hub.service.in
- misc/systemd/cfengine3.service.in
This PR was triggered by the PR #3172 and my [Fedora-packaging activities](https://copr.fedorainfracloud.org/coprs/vpodzime/CFEngine/). The Fedora community RPM should not contain unit files for daemons that are not part of the community package so they cannot be required.
> Small changes for the systemd service files

- libpromises/evalfunction.c
- tests/acceptance/01_vars/02_functions/variablesmatching.cf
These are internal variables and should not be included in the result.
Ticket: CFE-2812
> Skip varibles with '#' in their lval (name) in variablesmatching()

- libpromises/evalfunction.c
- tests/acceptance/01_vars/02_functions/string_replace.cf
- tests/acceptance/01_vars/02_functions/string_replace.cf.expected.json
Spent a lot more time doing this than necessary because I was trying to create a Buffer function for doing simple replacement, but didn't check string_lib until later.
Wanted to open the PR quickly in case I should use buffers instead, so I haven't pushed tests yet. Will do soon.
> CFE-2850: Added function string_replace

- libutils/file_lib.c
This commit adds an additional log message (at level ERR) explaining why we refuse to follow a symlink in certain conditions. I was confused when it happened to me, and this error message would have been a big help.
It also adds GNU global tags, as well as systemd files, to the relevant .gitingore files.
The PR contains my commit as well as your merge of my last PR. Let me know if that's a problem.
> Additional error reporting around safe links

- libutils/file_lib.c
This commit adds an additional log message (at level ERR) explaining
why we refuse to follow a symlink in certain conditions. I was
confused when it happened to me, and this error message would have
been a big help.
(cherry picked from commit 2c84b4e1b379a926cd5eab1056402ba090631e3d)
> Additional error reporting around safe links.

- tests/acceptance/10_files/rename/main.cf
As seen in these test results, during the first iteration of dirs (knuth)
match.1 was correct as expected and results in each filename being renamed with
a _renamed suffix. When iteration moves to the second element of dirs (lamport)
match.1 seems to be stuck on "three" as one is renamed to three_renamed and two
is renamed to three_renamed also.
```
cf-agent -KIf ./10_files/rename/main.cf -D AUTO,DEBUG
info: Created directory '/tmp/TESTDIR.cfengine/.'
R: test description: Test that files can be renamed using regular expression
matches from the promiser
R: /home/nickanderson/Northern.Tech/CFEngine/core/tests/acceptance/./10_files/rename/../../dcs.cf.sub SFAIL/CFE-2879
info: Created file '/tmp/TESTDIR.cfengine/test/knuth/incoming/one', mode 0600
info: Created file …
```
> CFE-2879 Test that iterating over paths with backreferences does not confuse match results

- cf-agent/files_changes.c
AFAICT all the values in struct stat are uint32 (usually).
Thus the most appropriate way to print is to cast to uintmax_t
and use modifier %ju. (%jd is for intmax_t, see man 3 printf).
https://lgtm.com/rules/2160310550/
> Fixed format modifiers and casts in files_changes.c

- libutils/logging.c
- libutils/logging.h
This const does nothing and can be confusing.
https://lgtm.com/rules/2157860314/
> Removed unnecessary const in return type

- contrib/cf-info/cf-info.sh
cf-info was the precursor to cf-diag (see https://github.com/cfengine/core/blob/master/contrib/cf-diag/cf-diag.sh)
Purpose: facilitate diagnostics when investigating issues with CFEngine reporting.
It works by checking common pain points (e.g. read-only filesystem, old policy version) in large infrastructures.
This script is meant to be run on hosts managed by CFEngine by human
operators investigating problems with CFEngine reporting.
Intended for use with policy channels (see https://github.com/cfengine/core/tree/master/contrib/masterfiles-stage)
> Add cf-info.sh diagnostic script

- libpromises/feature.h
Most likely a copy-paste error
https://lgtm.com/rules/2162200682/
> Renamed duplicate #ifdef guard

- README.md
Hi team,
I noticed that you've enabled automated code review by LGTM.com for pull requests, and that a significant number of alerts got fixed. Great! The code quality grade is ever improving; here's a badge to show it in your `README.md` if you like.
[![Language grade: C/C++](https://img.shields.io/lgtm/grade/cpp/g/cfengine/core.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/cfengine/core/)
Keep up the good work!
(full disclosure: I'm on the LGTM team :slightly_smiling_face:)
> Add LGTM.com code quality badge for C++

- cf-agent/files_changes.c
- cf-agent/files_changes.h
- cf-agent/verify_files_utils.c
This struct is 2304 bytes, and shouldn't be copied around so frequently.
I didn't change it everywhere yet, the cfPS function is used in so many places.
> CFE-2886: Changed Attr parameter to Attr * in FileChangesCheckAndUpdateHash

- cf-monitord/env_monitor.c
- cf-monitord/history.c
- cf-monitord/history.h
This struct is 3208 bytes and shouldn't be copied.
> Pass Averages struct by pointer

- libpromises/generic_agent.c
This variable shadowed the functions filename parameter.
https://lgtm.com/rules/2156240606/
> CFE-2886: Changed variable name to avoid confusion

- tests/acceptance/testall
Multiple tests under tests/acceptance won't work if the local git repo is located on a nfs-mounted directory (well, that's my suspicion as to why the tests are failing). This commit allows the developer to direct tests/acceptance/testall to setup its working files in a configurable location (e.g. '/tmp/workdir').
The developer can customize this by setting the BASE_WORKDIR environment variable:
BASE_WORKDIR=/tmp/workdir make check
or by invoking testall with a new flag, --base-workdir
./testall --base-workdir=/tmp/workdir
> Make BASE_WORKDIR configurable in tests/acceptance/testall

- cf-agent/acl_posix.c
- cf-agent/files_changes.c
- cf-agent/files_edit.c
- cf-agent/files_editline.c
- cf-agent/files_editxml.c
- cf-agent/files_links.c
- cf-agent/files_operators.c
- cf-agent/nfs.c
- cf-agent/retcode.c
- cf-agent/vercmp.c
- cf-agent/verify_acl.c
- cf-agent/verify_databases.c
- cf-agent/verify_environments.c
- cf-agent/verify_exec.c
- cf-agent/verify_files.c
- cf-agent/verify_files_utils.c
- cf-agent/verify_methods.c
- cf-agent/verify_packages.c
- cf-agent/verify_processes.c
- cf-agent/verify_storage.c
- cf-agent/verify_users.c
- cf-monitord/history.c
- cf-monitord/verify_measurements.c
- libpromises/eval_context.c
- libpromises/eval_context.h
- libpromises/verify_classes.c
- libpromises/verify_reports.c
This big struct shouldn't be copied by value
when not necessary.
https://github.com/cfengine/core/pull/3276
https://github.com/cfengine/enterprise/pull/435
> CFE-2886: Changed cfPS to take Attributes *

- libpromises/known_dirs.c
Compile-time 'bindir' on mingw builds is /var/cfengine/bin. Only
later when the packages are created, things are shuffled around
to various different directories.
> ENT-4115: Avoid using GetDefaultBinDir() on Windows

- cf-agent/files_editxml.c
Might improve performance while editing xml files.
Had to skip some functions which edit the contents of the struct.
(Don't want to make unintended changes to behavior).
> CFE-2886: Changed static functions in files_editxml to use Attributes *

- libpromises/policy.c
https://lgtm.com/rules/2156240606/
> Renamed variables which were shadowing params in policy.c

- cf-agent/verify_files.c
- cf-agent/verify_files_hashes.c
- cf-agent/verify_files_utils.c
- cf-serverd/server_common.c
- libcfnet/client_code.c
- libpromises/evalfunction.c
- libpromises/files_hashes.c
- libpromises/files_hashes.h
- libpromises/loading.c
On Windows writing a file in text mode means Unix newlines ("\n")
are transparently replaced by Windows newlines ("\r\n") and wise
versa for reading. We are using the text mode when writing
mustache-rendered contents into files and thus they end up having
Windows newlines. So in order to get comparable results for
digests of a file (Windows newlines) and in-memory string
representation (Unix newlines) we need to use the text mode when
reading the file and calculating the digest.
Other uses of the HashFile() function don't seem to be restricted
to working with text files and don't compare in-memory string
representations with file contents so we should use binary mode
there.
Ticket: ENT-2526
(cherry picked from commit 1f26996fe7526d58afe046a5a79bb5253697c026)
> [3.12.x] Read mustache-rendered files in text mode when comparing digest

- cf-agent/verify_files.c
- cf-agent/verify_files_hashes.c
- cf-agent/verify_files_utils.c
- cf-serverd/server_common.c
- libcfnet/client_code.c
- libpromises/evalfunction.c
- libpromises/files_hashes.c
- libpromises/files_hashes.h
- libpromises/loading.c
On Windows writing a file in text mode means Unix newlines ("\n")
are transparently replaced by Windows newlines ("\r\n") and wise
versa for reading. We are using the text mode when writing
mustache-rendered contents into files and thus they end up having
Windows newlines. So in order to get comparable results for
digests of a file (Windows newlines) and in-memory string
representation (Unix newlines) we need to use the text mode when
reading the file and calculating the digest.
Other uses of the HashFile() function don't seem to be restricted
to working with text files and don't compare in-memory string
representations with file contents so we should use binary mode
there.
Ticket: ENT-2526
(cherry picked from commit 1f26996fe7526d58afe046a5a79bb5253697c026)
> [3.10.x] Read mustache-rendered files in text mode when comparing digest

- cf-agent/files_editxml.c
- cf-agent/files_editxml.h
- cf-agent/verify_files.c
> CFE-2886: Changed ScheduleEditXmlOperations() to use Attributes *

- contrib/cf-log/cf-log.pl
contrib/cf-log.sh shows promise_summary.log but converts epoch times to
human-readable. This is convenient for handling reports of "my
application was having issues at 8:57 PM, did CFEngine break it?"
"Why, no, CFEngine wasn't running then, it ran at 8:59 PM."
> Add contrib/cf-log.sh (shows promise_summary.log)

- contrib/cf-log/cf-log.pl
contrib/cf-log/cf-log.pl shows promise_summary.log but converts
epoch times to human-readable.
This is convenient for handling reports of:
- "My application was having issues at 8:57 PM, did CFEngine break it?"
- "Why, no, CFEngine wasn't running then, it ran at 8:59 PM (which
I can quickly tell by running cf-log.pl)."
(cherry picked from commit b7da0a5a4c381235797236798c24f103b5492a96)
> [3.10.x] Add contrib/cf-log (shows promise_summary.log with human times)

- libutils/hash_map.c
- tests/unit/map_test.c
> Revert "Revert "ENT-4136: Fixed memory leak in HashMapPrintStats and its unit test""

- cf-agent/cf-agent.c
- cf-execd/cf-execd.c
- cf-promises/cf-promises.c
- cf-serverd/cf-serverd-functions.c
- cf-serverd/cf-serverd.c
- libutils/misc_lib.c
- libutils/misc_lib.h
Discovered using valgrind.
I had to introduce an alternative to putenv(),
putenv_static() which stores it's argument in
a static sequence so it can be freed later.
I wanted to use setenv(), but it is marked as
deprecated, and not portable.
This change means that env strings are always
reachable. (Until they are destroyed by
putenv_static_destroy())
> CFE-2918: Fixed small memory leaks of environment variable strings

- cf-agent/cf-agent.c
- cf-execd/cf-execd.c
- cf-promises/cf-promises.c
- cf-serverd/cf-serverd-functions.c
- cf-serverd/cf-serverd.c
- libutils/misc_lib.c
- libutils/misc_lib.h
> Revert "CFE-2918: Fixed small memory leaks of environment variable strings"

- libpromises/eval_context.c
- tests/acceptance/08_commands/01_modules/set-persistent-class.cf
This is an internal debugging information that is more confusing
than useful to the user.
> Change the 'Adding class to heap' message to DEBUG

- codecov.yaml
I'm tired of the spam. The comment is huge. Because of
fluctuations in coverage it has far more noise than useful
information.
> Disable codecov comments

- cf-agent/verify_files.c
- tests/acceptance/10_files/mustache_respects_warn_only.cf
The outcome classes were not defined when rendering a mustache template
in warn_only mode.
> CFE-2600: Fixed missing class with mustache templates in warn_only mode

- tests/unit/csv_parser_test.c
Just want to run this on all platforms to see if possible to recreate bug from ENT-2722. From what I can see it was fixed by @jimis in 2016.
> ENT-2722: Test for carriage return before newline

- libpromises/evalfunction.c
data_readstringarray and data_readstringarrayidx were logging errors in inform mode. This change sets the correct log level for the error logs.
> CFE-2922 Correct log level for data_readstringarray*

- libpromises/pipes.c
- libpromises/rlist.c
- libpromises/rlist.h
- tests/unit/rlist_test.c
This needs to do different things on Windows and UNIX-like systems.
Add a function to split string on newlines to do so because it is
not trivial because the "\r\n" 2-byte sequence
represents a newline on Windows.
Ticket: ENT-3716
> Respect windows newlines when splitting data in PipeReadData()

- libpromises/pipes.c
- libpromises/rlist.c
- libpromises/rlist.h
- tests/unit/rlist_test.c
This needs to do different things on Windows and UNIX-like systems.
Add a function to split string on newlines to do so because it is
not trivial because the "\r\n" 2-byte sequence
represents a newline on Windows.
Ticket: ENT-3716
(cherry picked from commit aad945ff22e2f84cb601810db9df409f06aca8da)
> [3.12.x] Respect windows newlines when splitting data in PipeReadData()

- libpromises/pipes.c
- libpromises/rlist.c
- libpromises/rlist.h
- tests/unit/rlist_test.c
This needs to do different things on Windows and UNIX-like systems.
Add a function to split string on newlines to do so because it is
not trivial because the "\r\n" 2-byte sequence
represents a newline on Windows.
Ticket: ENT-3716
(cherry picked from commit aad945ff22e2f84cb601810db9df409f06aca8da)
> [3.10.x] Respect windows newlines when splitting data in PipeReadData()

- cf-agent/cf-agent.c
- cf-execd/cf-execd.c
- cf-promises/cf-promises.c
- cf-serverd/cf-serverd-functions.c
- libutils/set.c
- libutils/set.h
- tests/unit/set_test.c
This fixes some small memory leaks in argument parsing
for cf-agent, cf-execd, cf-promises, and cf-serverd.
These leaks were not so serious, as they only happen
once, during startup (they don't increase over time).
It also fixes a memory leak in set_test.
This part of the code is also not performance critical,
so the extra copying should be no problem.
Before this change it was impossible to use SetJoin
without leaking memory. This is because SetJoin reused
elements from second argument, so you end up with 2 sets
with pointers to the same data. Sets only have keys, so there
is no soft destroy function.
Now, if you use the copy function parameter to SetJoin, for
example with xstrdup, both sets can be destroyed using normal
SetDestroy.
StringSetJoin could be made to always use xstrdup, …
> ENT-4136: Made SetJoin and StringSetJoin optionally copy elements

- libpromises/evalfunction.c
- tests/acceptance/08_commands/01_modules/classes-automatically-canonified.cf
Changelog: CFE-2877 Class names set by module protocol are automatically canonified
(cherry picked from commit dc44c8e550e756dacf318076e19460dcda97840f)
> CFE-2887: Test classes defined by module protocol are automatically canonified

- .gitignore
- Makefile.am
- cf-check/Makefile.am
- cf-check/cf-check.c
- cf-check/lmdump.c
- cf-check/lmdump.h
- configure.ac
- libenv/sysinfo.c
- tests/acceptance/Makefile.am
- tests/acceptance/testall
- tests/unit/dynamic_dependency_test.sh
- travis-scripts/valgrind.sh
Corrupt local databases (LMDB) continues to be a problem.
cf-check will be used to diagnose and remediate problems
with corrupt databases. It is a standalone binary, which
doesn't evaluate policy or use the local databases, thus
it can be used in situations where the other binaries
like cf-agent would hang.
cf-check replaces our lmdb database dumper, lmdump.
`cf-check lmdump` or symlinking / renaming it to lmdump
will make cf-check have the exact same behavior as lmdump.
cf-check will include much more functionality in the future
and some of the code will be added to other binaries,
for example to do health checks of databases on startup.
https://github.com/cfengine/core/pull/3367
https://github.com/cfengine/enterprise/pull/456 …
> ENT-4064: Added a new binary: cf-check

- codecov.yaml
I'm tired of the spam. The comment is huge. Because of
fluctuations in coverage it has far more noise than useful
information.
> Disable codecov comments (3.12)

- libpromises/loading.c
- libpromises/policy.c
- libpromises/policy.h
We are computing hashes/digests of policy files when loading them
to detect duplicate policy files etc. However, this information
is useful even later, e.g. for logging where it allows us to tie
the promise outcome with a particular version of the policy file
the promise appeared in.
Ticket: ENT-3996
> Add parsed policy files hashes/digests to Policy

- libutils/map.h
This macro defines a typed map with many functions. Most of these
functions dereference their 'map' argument so they should assert
it's not NULL. The two exceptions are the `Prefix##MapDestroy()`
and `Prefix##MapSoftDestroy()` functions which should do nothing
when given `NULL`.
> Asserts and checks for TYPED_MAP_DEFINE

- libutils/Makefile.am
- libutils/mutex.c
- libutils/mutex.h
- libutils/threaded_queue.c
- libutils/threaded_queue.h
- tests/unit/Makefile.am
- tests/unit/threaded_queue_test.c
Can push, pop, block before popping if queue is empty, return
amount of elements, capacity, copy, etc. Can also be created
as a non-thread safe queue, if that is needed.
Ticket: ENT-3831
> ENT-3831: Added new thread safe queue data structure

- travis-scripts/valgrind.sh
Previously, the agent was bypassing networking.
The bootstrap IP doesn't work for connecting to cf-serverd.
This commit introduces cf-net to the test, which doesn't
bypass networking, and writes 127.0.0.1 to policy_server.dat,
so cf-net uses the loopback interface to connect to server.
> Travis: Fix issues with running serverd in valgrind test

- cf-check/Makefile.am
- cf-check/cf-check.c
- cf-check/diagnose.c
- cf-check/diagnose.h
- cf-check/lmdump.c
- cf-check/lmdump.h
- travis-scripts/valgrind.sh
Following up from https://github.com/cfengine/core/pull/3367
This command assesses the health of embedded (LMDB) databases.
It forks a subprocess for each listed database,	iterates through
all data in the	database (printing it to /dev/null) and	returns
non-zero exit code if any database is corrupt.
> ENT-4064: Added diagnose command to cf-check

- tests/unit/threaded_queue_test.c
Test was sometimes hanging on rhel7 because of
test_threads_wait_empty. When the waiting thread was spawned,
ThreadedQueueWaitEmpty occasionally managed to acquire the lock
before any of the threads that were spawned to add elements, which
resulted in the amount of elements added were 101, not 100 like
the while loop was checking for.
Another sleep statement was added to let the pushing threads
finish their work before spawning the waiting thread.
...also, added all the tests back and removed the dummy test.
Ticket: ENT-4220
> ENT-4220: Added fix for threaded_queue_test hanging

- cf-serverd/server_tls.c
- cf-serverd/server_transform.c
- configure.ac
- libcfnet/tls_client.c
- libcfnet/tls_generic.c
- libcfnet/tls_generic.h
- libpromises/feature.c
https://github.com/cfengine/buildscripts/pull/454
This requires OpenSSL 1.1.1 so it only has a chance to compile and pass tests when combined with https://github.com/cfengine/buildscripts/pull/454.
> TLS 1.3 support

- .travis.yml
- travis-scripts/script.sh
AddressSanitizer (ASAN) adds instrumentation to binaries
to detect memory leaks, buffer overflows etc.
It is similar to valgrind, but detects other kinds of problems,
and is much more performant (but a makes it a little harder
to build).
> ENT-3858: Travis: Run unit tests with ASAN

- cf-check/cf-check.c
Example:
```
root@dev core $ cf-check
cf-check:
Utility for diagnosis and repair of local CFEngine databases.
This BETA version of the tool is for testing purposes only.
Commands:
dump - Print the contents of a database file
diagnose - Assess the health of one or more database files
version - Print version information
help - Print this help menu
Usage:
$ cf-check command [options]
Examples:
$ cf-check dump -a /var/cfengine/state/cf_lastseen.lmdb
$ cf-check diagnose /var/cfengine/state/*.lmdb
No command given.
root@dev core $ cf-check version
cf-check BETA version 3.13.0a.9f1942a
root@dev core $ cf-check -V
cf-check BETA version 3.13.0a.9f1942a
root@dev core $ cf-check dump -a /var/cfengine/state/cf_lastseen.lmdb
key: 0x7f356a0f0f34[16] a192.168.100.10, data: 0x7f356a0f0f44[37] …
```
> ENT-4064: help and version commands in cf-check

- libutils/Makefile.am
- libutils/condition_macros.h
- libutils/platform.h
A small part of: https://tracker.mender.io/browse/ENT-3725
> ENT-3725: Added a new C macro, assert_or_return

- contrib/cf-diag/cf-diag.sh
Add colorization to cf-diag to make it easier for operators to find and fix problems.
It only colorizes the output if stdout is pointing to a tty.
We could have gotten fancier and added an option to force color regardless, but I don't think that's necessary.
This change was made by @mikeweilgart, I am just forwarding it upstream.
> Add colorization to cf-diag.sh

- cf-execd/cf-execd.c
- cf-key/cf-key.c
- cf-monitord/cf-monitord.c
- cf-promises/cf-promises.c
- cf-runagent/cf-runagent.c
I ran into this in https://support.northern.tech/hc/en-us/requests/4073
man page for cf-runagent said
-v
Output verbose information about the behaviour of the agent
but it didn't; it output verbose information about the behavior of cf-runagent.
Nick Anderson suggested I update the man pages by editing these C files,
so here you go.
> Update man pages to remove harded 'agent' on verbose option

- misc/init.d/cfengine3.in
This way we can use the functions from the init script in the
state restoration process where we need to start daemons.
Ticket: ENT-4313
> Allow sourcing the init script from state restore

- libpromises/eval_context.c
- libutils/logging.c
- libutils/logging.h
This can be used to eliminate potential small memory leaks
in multi-threaded programs, like cf-hub and cf-serverd.
> ENT-4313: Introduce function to clean up logging contexts

- misc/init.d/cfengine3.in
Just to be safe, let's unset these to ensure that our binaries use exactly the libraries they specify internally.
> ENT-4110: unset LD_LIBRARY_PATH and LIBPATH in init scripts

- libpromises/eval_context.c
- libutils/logging.c
- libutils/logging.h
This can be used to eliminate potential small memory leaks
in multi-threaded programs, like cf-hub and cf-serverd.
> ENT-4313: Introduce function to clean up logging contexts (3.12)

- cf-check/Makefile.am
- cf-check/backup.c
- cf-check/diagnose.c
- cf-check/utilities.c
- cf-check/utilities.h
When no files are specified, default behavior is identical to
/var/cfengine/state/*.lmdb (expanded by shell).
This command can be used as a prototype for `cf-check repair`:
```
cf-check diagnose || ( cf-check backup && rm -f /var/cfengine/state/*.lmdb && echo "Successful repair!")
```
Example:
```
$ cf-check diagnose || ( cf-check backup && rm -f /var/cfengine/state/*.lmdb && echo "Successful repair!")
No filenames specified, defaulting to .lmdb files in /var/cfengine/state/
Status of '/var/cfengine/state/cf_state.lmdb': OK
Status of '/var/cfengine/state/history.lmdb': OK
Status of '/var/cfengine/state/packages_installed_apt_get.lmdb': OK
Status of '/var/cfengine/state/nova_measures.lmdb': OK
Status of '/var/cfengine/state/nova_static.lmdb': OK
Status of …
```
> ENT-4064: cf-check: diagnose and backup now use state directory by default

- cf-agent/files_links.c
- tests/acceptance/10_files/02_maintain/copy_linkpattern_from_contains_dots.cf
When source containt `<path>/../<file>`, eg:
* `/tmp/source/../templates/group`
copylink_pattern failed with:
```
error: Can't stat '/tmp/source/templates' in ExpandLinks. (lstat: No such file or directory)
```
> CF-2960: copylink_pattern honor '/../' in copy source

- cf-agent/files_links.c
- tests/acceptance/10_files/02_maintain/copy_linkpattern_from_contains_dots.cf
When source containt `<path>/../<file>`, eg:
* `/tmp/source/../templates/group`
copylink_pattern failed with:
```
error: Can't stat '/tmp/source/templates' in ExpandLinks. (lstat: No such file or directory)
```
(cherry picked from commit ce831f95dfb672708c55f97ead7e90ed201411c5)
> [3.12.x] CFE-2960: copylink_pattern honor '/../' in copy source

- cf-agent/files_links.c
- tests/acceptance/10_files/02_maintain/copy_linkpattern_from_contains_dots.cf
When source containt `<path>/../<file>`, eg:
* `/tmp/source/../templates/group`
copylink_pattern failed with:
```
error: Can't stat '/tmp/source/templates' in ExpandLinks. (lstat: No such file or directory)
```
(cherry picked from commit ce831f95dfb672708c55f97ead7e90ed201411c5)
> [3.10.x] CFE-2960: copylink_pattern honor '/../' in copy source

- libpromises/evalfunction.c
- tests/acceptance/08_commands/01_modules/module-array-allows-slash.cf
Previously, the function only allowed alphanumerical and
characters `_`, `.`, `-`, `[` and `]`. Forward slash is not used
for anything in module protocol commands, and is therefore added. Also
reenabled the test for slashes in module commands.
Ticket: CFE-2478
> [3.12.x] CFE-2478: Allow forward slash character in module protocol commands

- libpromises/evalfunction.c
- tests/acceptance/08_commands/01_modules/module-array-allows-slash.cf
Previously, the function only allowed alphanumerical and
characters `_`, `.`, `-`, `[` and `]`. Forward slash is not used
for anything in module protocol commands, and is therefore added. Also
reenabled the test for slashes in module commands.
Ticket: CFE-2478
> [3.10.x] CFE-2478: Allow forward slash character in module protocol commands

- libpromises/systype.c
- tests/unit/mon_processes_test.c
Increased it to 30 chars instead of 8
> CF-2951: ps command can handle longer usernames

- libpromises/systype.c
- tests/unit/mon_processes_test.c
Increased it to 30 chars instead of 8
(cherry picked from commit 3a05f707332fe91447c53022b437205979ce420b)
> CF-2951: ps command can handle longer usernames (3.12)

- libpromises/systype.c
- tests/unit/mon_processes_test.c
Increased it to 30 chars instead of 8
(cherry picked from commit 3a05f707332fe91447c53022b437205979ce420b)
> CF-2951: ps command can handle longer usernames (3.10)

- .gitignore
- .style.yapf
- contrib/cf-remote/README.md
- contrib/cf-remote/cf_remote/__main__.py
- contrib/cf-remote/cf_remote/commands.py
- contrib/cf-remote/cf_remote/log.py
- contrib/cf-remote/cf_remote/main.py
- contrib/cf-remote/cf_remote/packages.py
- contrib/cf-remote/cf_remote/paths.py
- contrib/cf-remote/cf_remote/remote.py
- contrib/cf-remote/cf_remote/utils.py
- contrib/cf-remote/cf_remote/web.py
- lgtm.yml
```
olehermanse@OHMBP-1880 ~ $ cf-remote info -H 34.248.141.126
ubuntu@34.248.141.126
OS           : ubuntu (debian)
Architecture : x86_64
CFEngine     : Not installed
Binaries     : dpkg, apt
olehermanse@OHMBP-1880 ~ $ cf-remote packages hub deb
3.12.1 LTS (default)
3.10.5 LTS
Using 3.12.1 LTS (default):
Downloading package: /Users/olehermanse/.cfengine/cf-remote/packages/cfengine-nova-hub_3.12.1-1_amd64.deb
olehermanse@OHMBP-1880 ~ $ cf-remote install --hub 34.248.141.126 --package /Users/olehermanse/.cfengine/cf-remote/packages/cfengine-nova-hub_3.12.1-1_amd64.deb
ubuntu@34.248.141.126
OS           : ubuntu (debian)
Architecture : x86_64
CFEngine     : Not installed
Binaries     : dpkg, apt
Copying '/Users/olehermanse/.cfengine/cf-remote/packages/cfengine-nova-hub_3.12.1-1_amd64.deb' …
```
> CFE-2889: cf-remote info, install, packages

- libpromises/pipes.c
It also might happen when pipe is closed (child process exited)
Ticket: ENT-3719
Merge together: https://github.com/cfengine/enterprise/pull/486
> Keep read data when PipeIsReadWriteReady returns negative result

- contrib/cf-remote/cf_remote/commands.py
- contrib/cf-remote/cf_remote/main.py
- contrib/cf-remote/cf_remote/packages.py
- contrib/cf-remote/cf_remote/remote.py
- contrib/cf-remote/cf_remote/utils.py
- contrib/cf-remote/cf_remote/web.py
```
$ cf-remote install --demo --clients ./clients.txt --hub ./hub.txt --bootstrap ./bootstrap.txt 
ec2-user@34.245.0.209
OS           : rhel (fedora)
Architecture : x86_64
CFEngine     : Not installed
Binaries     : rpm, yum
Package already downloaded: '/Users/olehermanse/.cfengine/cf-remote/packages/cfengine-nova-hub-3.12.1-1.x86_64.rpm'
Copying: '/Users/olehermanse/.cfengine/cf-remote/packages/cfengine-nova-hub-3.12.1-1.x86_64.rpm' to '34.245.0.209'
Installing: 'cfengine-nova-hub-3.12.1-1.x86_64.rpm' on '34.245.0.209'
CFEngine 3.12.1 was successfully installed on '34.245.0.209'
Bootstrapping: '34.245.0.209' -> '172.31.33.214'
Bootstrap succesful: '34.245.0.209' -> '172.31.33.214'
Transferring def.json to hub: '34.245.0.209'
Triggering an agent run on: '34.245.0.209'
Disabling password …
```
> CFE-2889: cf-remote: File input and policy server information

- libpromises/locks.c
Added a `GetErrorStr()` call to distinguish between programming
errors (EINVAL) and permission errors (EPERM) for `kill()`.
Ticket: ENT-4395
Should be cherry-picked, though I am unsure if it needs a changelog entry.
> ENT-4395: Increased verbosity of AcquireLock permission error

- cf-check/backup.c
The default location for file backups by agent file promises
is /var/cfengine/backups/.  It would be nicer not to have
both backup/ and backups/ (confusing).
> Change /var/cfengine/backup/ to backups/

- libpromises/evalfunction.c
In CFE-2887 the module protocol began automatically canonifying classes
that were defined in order to align with the behaviour of policy. This
change moves a warning about the class containing invalid characters to
VERBOSE as to align with policy.
(cherry picked from commit 829afc3d3b786cc3b5d8c469f1023d589b9dc33c)
> CFE-3008 Message about invalid class characters from module protocol moved to VERBOSE (3.12.x)

- libpromises/evalfunction.c
In CFE-2887 the module protocol began automatically canonifying classes
that were defined in order to align with the behaviour of policy. This
change moves a warning about the class containing invalid characters to
VERBOSE as to align with policy.
(cherry picked from commit 829afc3d3b786cc3b5d8c469f1023d589b9dc33c)
> CFE-3008 Message about invalid class characters from module protocol moved to VERBOSE (3.10.x)

- libpromises/evalfunction.c
In CFE-2887 the module protocol began automatically canonifying classes
that were defined in order to align with the behaviour of policy. This
change moves a warning about the class containing invalid characters to
VERBOSE as to align with policy.
(cherry picked from commit 829afc3d3b786cc3b5d8c469f1023d589b9dc33c)
> CFE-3008 Message about invalid class characters from module protocol moved to VERBOSE (3.7.x)

- contrib/cf-remote/cf_remote/commands.py
- contrib/cf-remote/cf_remote/main.py
Useful if you want to install multiple hubs in one command.
This is a more niche use case, so I won't change the name or
description of the options. (99% of users will want 1 hub and 1
bootstrap IP).
> cf-remote: --hub and --bootstrap now accept more than one IP/hostname

- cf-agent/verify_packages.c
- cf-execd/cf-execd-runner.c
- libutils/string_lib.c
- libutils/string_lib.h
- tests/unit/string_lib_test.c
From Jira:
```
We have two functions ReplaceStr() and StringReplace() that do pretty much the same, but not exactly. We should squash them and get rid of one of them - probably the former one as it has worse performance.
Acceptance criteria:
1. Only one function for replacing strings in place used in our codebase.
2. Unit tests for the function written and passing.
```
Currently WIP, still needs tests for `StringReplace()`
https://github.com/cfengine/enterprise/pull/483
> ENT-3749: Squash ReplaceStr() and StringReplace()

- libpromises/files_lib.c
Previously, cf-key (for instance) would report that it could not
create the directory, indicating that something had gone wrong.
With this commit, `mkdir()` will not log error if it just failed
because the file already exists.
Ticket: CFE-646
> CFE-646: Suppressed noisy error when directories already exist

- contrib/cf-remote/cf_remote/commands.py
- contrib/cf-remote/cf_remote/demo.py
- contrib/cf-remote/cf_remote/remote.py
- contrib/cf-remote/cf_remote/ssh.py
The main reason why `install` wasn't working in Digital Ocean was that it opened a lot of SSH connections to the same host. This pull request fixes that and some other problems highlighted by LGTM code analysis.
> cf-remote: Reuse SSH connections and other fixes (Digital Ocean Compatibility)

- cf-agent/verify_databases.c
- cf-agent/verify_users_pam.c
- libpromises/fncall.c
- libpromises/known_dirs.c
In all cases, if the functions would return
NULL previously it would result in undefined
behavior / crashes (deref NULL pointer). So
logging errors and/or stopping agent should
be safe changes.
https://lgtm.com/rules/2151900540/
> Fixed inconsistent NULL checks

- libcfnet/cfnet.h
- libpromises/cf3.defs.h
- libutils/Makefile.am
- libutils/definitions.h
Currently moved only size-related definitions that we'd like
to use in libutils.
Ticket: CFE-3001
> CFE-3001: Moved common definitions to libutils

- contrib/cf-remote/cf_remote/commands.py
- contrib/cf-remote/cf_remote/remote.py
- contrib/cf-remote/cf_remote/ssh.py
This preserves formatting on the first line,
for example in cf-agent output.
> cf-remote: Better command output and error handling

- libutils/json-yaml.c
- tests/acceptance/01_vars/02_functions/parseyaml_with_unquoted_values_starting_with_digits.cf
The JsonParseAsNumber() tries to parse the given string as a
number, *and also moves the pointer to the point it failed to
continue doing so*. To use it as a check function we need to give
it a pointer it can mangle instead of the pointer we plan to
continue using.
Ticket: CFE-2033
Changelog: Fix parsing YAML values starting with numbers
> Avoid swallowing the number part of YAML string value

- cf-agent/cf-agent.c
- libcfnet/conn_cache.c
Currently the connection cache is destroyed after each bundle pass. In our usage of the agent (where we can have quite a lot of file copies all in different bundles), this leads to slower execution time and an increased load on the server (with up to tens of connections created and destroyed during a single run).
This patch naively activates the connection cache at the agent run level. This appears to have been held back (https://tracker.mender.io/browse/CFE-2678) because of https://tracker.mender.io/browse/CFE-2511, and waiting for a way to avoid reusing broken connections.
I could work on this as we really want to have a working connection cache. Does the solution proposed in CFE-2511 description suits you, and would allow reusing the connection cache for a whole agent run?
> CFE-2678: Global connection cache

- libpromises/files_lib.c
Previously, cf-key (for instance) would report that it could not
create the directory, indicating that something had gone wrong.
With this commit, `mkdir()` will not log error if it just failed
because the file already exists.
Ticket: CFE-646
(cherry picked from commit e9c4cca0019ef4be871d4151b5a42b154938ab5c)
> CFE-646: Suppressed noisy error when directories already exist (3.12.x)

- libpromises/files_lib.c
Previously, cf-key (for instance) would report that it could not
create the directory, indicating that something had gone wrong.
With this commit, `mkdir()` will not log error if it just failed
because the file already exists.
Ticket: CFE-646
(cherry picked from commit e9c4cca0019ef4be871d4151b5a42b154938ab5c)
> CFE-646: Suppressed noisy error when directories already exist (3.10.x)

- libpromises/evalfunction.c
Failing to read a registry value in the registryvalue() function
is an error.
Ticket: CFE-2568
Note: This compensates the change of behavior introduced in
cfengine/enterprise@268a4d8169.
https://github.com/cfengine/enterprise/pull/492
> Log an error if reading registry value failed in registryvalue()

- cf-key/cf-key.c
(cherry picked from commit 18d73537ebcbb99e428705b25c5187f44e4b67a6)
> CFE-2997 Fix cf-key help output to indicate ability to delete by key digest (3.10.x)

- libpromises/verify_vars.c
When used with `string_template` (see https://tracker.mender.io/browse/CFE-2983), the message is displayed twice as the function is called twice, I don't know why or how to avoid it.
Do you have any idea on how to display this log only once?
We could maybe add a debug message to state when a function is skipped during previous passes, as it can help debug a function that succeeds later than expected, what do you think about it?
> CFE-2983: Display an error when a function defining a variables still fails at last pass

- libpromises/policy.c
When adding promise attributes there may be none in which case
"rval" is an empty array not an object, like in this example::
{
"attributes": [
{
"line": 202,
"lval": "data",
"rval": []
}
],
"line": 202,
"promiser": "tests_passed"
}
AttributeValueToJson() can return an array as well as an object
so we need to take that into account when appending its result.
Ticket: CFE-3019
> Fix a segfault in 'cf-promises -p json-full'

- cf-check/backup.c
The default location for file backups by agent file promises
is /var/cfengine/backups/.  It would be nicer not to have
both backup/ and backups/ (confusing).
(cherry picked from commit c0990bf9242c3e956e726df22fce8f62deb41c71)
> Change /var/cfengine/backup/ to backups/ (3.12)

- libpromises/policy.c
When adding promise attributes there may be none in which case
"rval" is an empty array not an object, like in this example::
{
"attributes": [
{
"line": 202,
"lval": "data",
"rval": []
}
],
"line": 202,
"promiser": "tests_passed"
}
AttributeValueToJson() can return an array as well as an object
so we need to take that into account when appending its result.
Ticket: CFE-3019
(cherry picked from commit 98e667b7beb9537daf0585a79aae86d47f260afb)
> Fix a segfault in 'cf-promises -p json-full' (3.12)

- libpromises/policy.c
When adding promise attributes there may be none in which case
"rval" is an empty array not an object, like in this example::
{
"attributes": [
{
"line": 202,
"lval": "data",
"rval": []
}
],
"line": 202,
"promiser": "tests_passed"
}
AttributeValueToJson() can return an array as well as an object
so we need to take that into account when appending its result.
Ticket: CFE-3019
(cherry picked from commit 98e667b7beb9537daf0585a79aae86d47f260afb)
> Fix a segfault in 'cf-promises -p json-full' (3.10)

- cf-agent/verify_databases.c
- cf-agent/verify_users_pam.c
- libpromises/fncall.c
- libpromises/known_dirs.c
In all cases, if the functions would return
NULL previously it would result in undefined
behavior / crashes (deref NULL pointer). So
logging errors and/or stopping agent should
be safe changes.
https://lgtm.com/rules/2151900540/
> ENT-4497: Fixed inconsistent NULL checks (3.12)

- cf-agent/verify_databases.c
- cf-agent/verify_users_pam.c
- libpromises/fncall.c
- libpromises/known_dirs.c
In all cases, if the functions would return
NULL previously it would result in undefined
behavior / crashes (deref NULL pointer). So
logging errors and/or stopping agent should
be safe changes.
https://lgtm.com/rules/2151900540/
> ENT-4497: Fixed inconsistent NULL checks (3.10)

- libutils/hash_map.c
- libutils/map.c
- libutils/string_lib.c
- tests/unit/map_test.c
Merge together: 
https://github.com/cfengine/core/pull/3549
https://github.com/cfengine/enterprise/pull/493
https://github.com/cfengine/nova/pull/1382
> ENT-4505: Don't allow NULL pointers as strings in hashing

- libutils/hash_map.c
- libutils/map.c
- libutils/string_lib.c
- tests/unit/map_test.c
NULL pointer is not a string and should not be accepted
as keys or for hashing. A NULL usually indicates that
something went wrong (a function call failed). If the
error is not handled (by checking for NULL) it will be
used in subsequent function calls, like HashString().
To prevent this and force programmers to handle errors
correctly, don't accept NULL as a string.
See corresponding commit in enterprise.
https://github.com/cfengine/core/pull/3559
https://github.com/cfengine/enterprise/pull/494
https://github.com/cfengine/nova/pull/1383
> ENT-4505: Don't allow NULL pointers as strings in hashing (3.12)

- libenv/sysinfo.c
- tests/acceptance/02_classes/03_os/ubuntu.cf
**Before:**
```
root@ip-172-31-45-190 core $ cf-promises --show-classes | grep -i ubuntu
linux_x86_64_4_15_0_1032_aws__34_Ubuntu_SMP_Thu_Jan_17_15_18_09_UTC_2019 source=agent,derived-from=sys.long_arch,hardclass
ubuntu                                                       inventory,attribute_name=none,source=agent,derived-from-file=/etc/os-release,hardclass
ubuntu_18                                                    inventory,attribute_name=none,source=agent,derived-from=sys.flavor,hardclass
ubuntu_18_04                                                 inventory,attribute_name=none,source=agent,derived-from-file=/etc/os-release,hardclass
ubuntu_18_4                                                  inventory,attribute_name=none,source=agent,hardclass
root@ip-172-31-45-190 core $ …
```
> CFE-2882: Don't trim leading zeroes in ubuntu minor version class

- cf-key/cf-key-functions.c
- libpromises/crypto.c
- libpromises/crypto.h
Private key files encrypted with a broken cipher and default
hard coded passphrase provide no real security, and is only an
inconvenience. Maybe it was intended to add a password prompt
later, but it's been 10 years now, and the cipher and passphrase
remain untouched. The function which reads keys still supports
both encrypted and unencrypted keys, it will decrypt if necessary.
This passphrase was introduced as part of cf-key in:
c7765f71ff04f07f497988a2a068122394da30bc
> Private keys generated by cf-key are no longer encrypted

- libpromises/generic_agent.c
- libpromises/loading.c
This makes it clear in the logs that the policy run was running
the failsafe policy to either bootstrap or try to recover.
Ticket: CFE-3031
> Set policy->release_id to "failsafe"/"bootstrap" when running failsafe.cf

- libcfnet/cfnet.h
- libpromises/cf3.defs.h
- libutils/Makefile.am
- libutils/definitions.h
Currently moved only size-related definitions that we'd like to use in `libutils`.
Ticket: CFE-3001
> CFE-3001: Moved common definitions to libutils - 3.10.x

- libcfnet/cfnet.h
- libpromises/cf3.defs.h
- libutils/Makefile.am
- libutils/definitions.h
Currently moved only size-related definitions that we'd like to use in `libutils`.
Ticket: CFE-3001
> CFE-3001: Moved common definitions to libutils - 3.12.x

- libpromises/evalfunction.c
- tests/acceptance/01_vars/02_functions/classfiltercsv_1.cf
- tests/acceptance/01_vars/02_functions/classfiltercsv_1.cf.csv
- tests/acceptance/01_vars/02_functions/classfiltercsv_2.cf
- tests/acceptance/01_vars/02_functions/classfiltercsv_2.cf.csv
- tests/acceptance/01_vars/02_functions/classfiltercsv_3.cf
- tests/acceptance/01_vars/02_functions/classfiltercsv_3.cf.csv
- tests/acceptance/01_vars/02_functions/classfiltercsv_4.cf
- tests/acceptance/01_vars/02_functions/classfiltercsv_4.cf.csv
- tests/acceptance/01_vars/02_functions/classfiltercsv_5.cf
- tests/acceptance/01_vars/02_functions/classfiltercsv_5.cf.csv
Will currently only filter data, does not remove duplicates and
such. Also cannot sort yet.
This is not ready to be merged, but I want feedback.
@nickanderson if you want to try it, you could check out my branch and compile it.
> CFE-2768: Added function to filter CSV by class expressions

- libpromises/generic_agent.c
- libpromises/loading.c
During bootstrap sub-agent runs are executed on policy files (in
particular update.cf) and thus are just normal agent runs without
any bootstrap options/arguments and not running failsafe. Unless
we populate the cf_promises_release_id file, these runs will have
their release_id set to '<unknown-release-id>' instead of
'bootstrap'.
Ticket: CFE-3031
> Populate the release_id file during/for bootstrap

- libpromises/Makefile.am
- libpromises/cf-windows-functions.h
- libutils/Makefile.am
- libutils/known_dirs.c
- libutils/known_dirs.h
- tests/unit/Makefile.am
Also moved some windows-only things out from `cf-windows-functions`. `known_dirs` should not depend on something that uses `libpromises`-specific things.
Ticket: CFE-3006
> CFE-3006: Moved known_dirs to libutils - 3.12.x

- misc/init.d/cfengine3.in
cf-hub is forking and also it is fine to run it multiple times in
parallel as long as just one instance runs the main loop. The
"Warning: Multiple cf-hub processes present. Should restart CFEngine."
message is just confusing in such situations.
> Do not warn about multiple cf-hub processes

- cf-monitord/mon_cpu.c
- cf-monitord/mon_network_sniffer.c
cf-monitord parses data from tcpdump and /proc.
This commit ensures that the data doesn't overflow the
buffers used.
https://lgtm.com/rules/2158250570/
> Prevented buffer overflows in cf-monitord data parsing (3.12)

- libutils/hash_map.c
- tests/unit/map_test.c
Otherwise the size is unchanged and the map thinks it still has
all the items that were there before. The items are gone, but
when new ones are inserted, the table sooner or later hits the
threshold and grows automatically. Repeat this process of "insert
a couple hundred items, clear, repeat" multiple times and the
table grows and grows...and grows.
Ticket: CFE-3032
Changelog: Fix growing memory footprint of daemons
> Set map->load to 0 at the end of HashMapClear()

- examples/classfiltercsv.cf
This aligns the style with that used in peerleaders() which does render
correctly in docs.
> Fix style for prep section in classfiltercsv() example

- libutils/hash_map.c
- tests/unit/map_test.c
Otherwise the size is unchanged and the map thinks it still has
all the items that were there before. The items are gone, but
when new ones are inserted, the table sooner or later hits the
threshold and grows automatically. Repeat this process of "insert
a couple hundred items, clear, repeat" multiple times and the
table grows and grows...and grows.
Let's decrement map->load everytime we remove an item and assert
that it reaches 0 when all items are removed.
Ticket: CFE-3032
Changelog: Fix growing memory footprint of daemons
(cherry picked from commit 09e5d244793d80ec6e953ae6f57f045eda30ab0d)
> [3.12.x] Make sure map->load is 0 at the end of HashMapClear()

- libpromises/locks.c
- libpromises/processes_select.c
- libpromises/rlist.h
- tests/acceptance/05_processes/01_matching/process_select_fncalls.cf
Function calls which always fail, like getuid("nosuchuser"), are
never resolved. Previously this would cause a programming error,
since the body is expected to have a list of strings, not
unresolved function calls.
The function calls are silently skipped (with a verbose message)
as this matches the behavior of calling the functions in a vars
promise, and using that as a body parameter.
> CFE-1968: Unresolved function calls in process_select body are now skipped

- cf-key/cf-key-functions.c
- cf-key/cf-key-functions.h
- cf-key/cf-key.c
This option, when used with --show-hosts changes the formatting
of the output. Instead of padding and truncating each of the
fields, they are printed, in full, with no padding, and separated
by a single tab character. The output is not as pretty, but should
be more useful for parsing by other scripts / tooling.
**Example:**
```
root@dev core $ cf-key -s
Direction  IP                                       Name                      Last connection            Key
Outgoing   192.168.100.10                           -                         Mon Apr 15 09:34:56 2019   MD5=a9b9a2c7f9cf17a3f0a378f2c38ee587
Total Entries: 1
root@dev core $ cf-key -s --no-truncate
Direction       IP      Name    Last connection Key
Outgoing        192.168.100.10  -       Mon Apr 15 09:34:56 2019 …
```
> CFE-3036: Added --no-truncate option to cf-key

- cf-execd/cf-execd-runner.c
- libpromises/evalfunction.c
https://lgtm.com/rules/2154840805/
> Replaced uses of localtime with the safer localtime_r

- cf-execd/cf-execd-runner.c
- libpromises/evalfunction.c
https://lgtm.com/rules/2154840805/
> Replaced uses of localtime with the safer localtime_r (3.12)

- cf-key/cf-key-functions.c
- cf-key/cf-key-functions.h
- cf-key/cf-key.c
This option, when used with --show-hosts changes the formatting
of the output. Instead of padding and truncating each of the
fields, they are printed, in full, with no padding, and separated
by a single tab character. The output is not as pretty, but should
be more useful for parsing by other scripts / tooling.
> CFE-3036: Added --no-truncate option to cf-key (3.12)

- .lgtm/cpp-queries/function-returns-bool-macro.qhelp
- .lgtm/cpp-queries/function-returns-bool-macro.ql
This custom query looks for functions with return type other than
`int` and `bool`, and alerts if they return `true` or `false`.
The severity can be reduced later, I just want to test this.
It can also be expanded to catch int functions, but then
we will have a lot of alerts.
> LGTM: Detect non-bool functions which return true or false

- contrib/cf-remote/cf_remote/demo.py
This caused all hosts to be excluded from reporting
when running in --demo mode without --call-collect.
>  cf-remote: Only exclude hosts in call collect mode

- cf-agent/verify_processes.c
- tests/acceptance/05_processes/01_matching/process_count_fncalls.cf
Previously, having a failing function call inside in_range_define
or out_of_range_define would cause a programming error when
trying to define that as a class. Fixed it by detecting the
case, printing a normal error, and skipping defining the class.
> CFE-2067:  Removed programming error in handling of process_count body

- .lgtm/cpp-queries/function-returns-bool-variable.qhelp
- .lgtm/cpp-queries/function-returns-bool-variable.ql
Since logical expressions and `true`/`false` macros are `int`
type, this query only detects functions which return a `bool`
variable (or a value typecast to `bool`).
> LGTM: Detect non-bool functions which return bool variable

- cf-agent/files_editline.c
- cf-agent/verify_environments.c
- cf-monitord/history.c
- libpromises/cf3.defs.h
Let's hope no code was relying on this being 0.
https://lgtm.com/rules/2162380048/
> Define all enum values in PromiseResult

- libcfnet/tls_client.c
- libcfnet/tls_generic.c
When the client gets SSL_ERROR_WANT_READ or SSL_ERROR_WANT_WRITE,
we should re-try instead of shutting down the whole session
because these errors are expected, as documented in the OpenSSL
documentation (and functions' man pages)
Ticket: CFE-3023
Changelog: Reduce SSL/TLS shutdowns on bad networks
> Retry SSL operations on SSL_ERROR_WANT_READ/WRITE

- .lgtm/cpp-queries/missing-argument-null-check.c
- .lgtm/cpp-queries/missing-argument-null-check.qhelp
- .lgtm/cpp-queries/missing-argument-null-check.ql
This query has 6000 alerts currently, but I still think it will be valuable for new Pull Requests.
> LGTM: Query for dereferencing a pointer argument without NULL-comparison

- libpromises/unix.c
Returning non-zero from a function returning bool is the same as
returning true. If there is an error in the child process, the function
should return false to indicate failure.
> Fix ShellCommandReturnsZero() return value in error path

- libpromises/eval_context.c
No change in behavior, mainly to satisfy LGTM rule.
Found by LGTM:
https://lgtm.com/rules/1508474826013/
> Use proper enum constant for true in expressions (3.12)

- cf-agent/files_editline.c
- cf-agent/files_select.c
- cf-agent/files_select.h
- cf-agent/retcode.c
- cf-agent/retcode.h
- cf-agent/verify_databases.c
- cf-agent/verify_files_utils.c
- cf-agent/verify_files_utils.h
- cf-serverd/server_classic.c
- cf-serverd/server_classic.h
- cf-serverd/server_common.c
- cf-serverd/server_common.h
- libpromises/eval_context.c
- libpromises/files_lib.c
- libpromises/files_lib.h
No changes in behavior. Only improvements in readability and
maintainability.
https://lgtm.com/rules/1508524786076/
Had to resolve conflicts because 3.12.x codebase doesn't use
Attributes pointers.
>  Changed several functions to respect bool type (3.12)

- libpromises/processes_select.c
- libutils/file_lib.c
- libutils/file_lib.h
These files were created with 0644 permissions, and then
repaired in policy. However, since they are deleted / recreated
periodically, it causes INFO noise. Safer and better user
experience to create them with restricted permissions to
begin with.
Affected files:
* `$(sys.statedir)/cf_procs`
* `$(sys.statedir)/cf_rootprocs`
* `$(sys.statedir)/cf_otherprocs`
https://github.com/cfengine/core/pull/3649
https://github.com/cfengine/enterprise/pull/510
https://github.com/cfengine/masterfiles/pull/1389
> ENT-4601: Switched perms of various temporary files in state to 0600

- libpromises/processes_select.c
- libutils/file_lib.c
- libutils/file_lib.h
These files were created with 0644 permissions, and then
repaired in policy. However, since they are deleted / recreated
periodically, it causes INFO noise. Safer and better user
experience to create them with restricted permissions to
begin with.
Affected files:
* `$(sys.statedir)/cf_procs`
* `$(sys.statedir)/cf_rootprocs`
* `$(sys.statedir)/cf_otherprocs`
Had to resolve some conflicts due to cf-check functions.
(cherry picked from commit 461dc7019ab5acebabc341143838a2307d9b92db)
https://github.com/cfengine/core/pull/3651
https://github.com/cfengine/enterprise/pull/511
https://github.com/cfengine/masterfiles/pull/1380
> ENT-4601: Switched perms of various temporary files in state to 0600 (3.10)

- libpromises/processes_select.c
- libutils/file_lib.c
- libutils/file_lib.h
These files were created with 0644 permissions, and then
repaired in policy. However, since they are deleted / recreated
periodically, it causes INFO noise. Safer and better user
experience to create them with restricted permissions to
begin with.
Affected files:
* `$(sys.statedir)/cf_procs`
* `$(sys.statedir)/cf_rootprocs`
* `$(sys.statedir)/cf_otherprocs`
(cherry picked from commit 461dc7019ab5acebabc341143838a2307d9b92db)
https://github.com/cfengine/core/pull/3657
https://github.com/cfengine/enterprise/pull/516
https://github.com/cfengine/masterfiles/pull/1390
> ENT-4601: Switched perms of various temporary files in state to 0600 (3.12)

- cf-agent/package_module.c
If a package module has an interpreter specified, it can either
be just a path to the interpreter executable or it can also
provide options for the intepreter. If there are no such options,
'package_module->script_exec_opts' has to be NULL because we
later rely on that.
(cherry picked from commit 54bd7b7bd08cb9252cccc1cd334fdd89e928ba10)
> [3.12.x] Fix potentially unitialized 'script_exec_opts' of a package module

- misc/determine-version.py
Otherwise do things the old way using 'cmp=' because if
'cmp_to_key' doesn't exist, we are running an old version of
Python which supports 'cmp='.
This fixes running determine_version.py on CentOS 6 which has
Python 2.6.
> Only use 'cmp_to_key' in determine_version if it exists

- libpromises/generic_agent.c
- tests/acceptance/00_basics/def.json/class_from_classexpression.cf
- tests/acceptance/00_basics/def.json/class_from_classexpression.cf.json
- tests/acceptance/README
A condition in an augments file is treated as a class expression
if it ends in `::`. Otherwise it is treated as a regular
expression.
Previously there was a bug, where the conditions in augments files
were treated as both class expressions and regular expressions.
This was ambiguous, and problematic since something like
`cfengine.nginx.enabled` as a regex would match a class called
`cfengine_nginx_enabled`, while as a class expression would match
`cfengine && nginx && enabled`.
This was fixed in 3.12.1 by treating it as a regex only.
(Documented and intended behavior).
Some users still wanted a way to use class expression, so the `::`
suffix solves the problem. For the example above, you can use this
in the augments file:
`cfengine.nginx.enabled::`
Since classes cannot end with `:`, this …
> CFE-2954: Augments files can now handle class expressions by appending '::'

- libpromises/evalfunction.c
They all use FnCallSetOp() internally, which was lacking free
for some error handling return paths.
> ENT-4586: Fixed memory leak in: differences(), intersection(), unique()

- libpromises/evalfunction.c
They all use FnCallSetOp() internally, which was lacking free
for some error handling return paths.
> ENT-4586: Fixed memory leak in: differences(), intersection(), unique() (3.12)

- libpromises/generic_agent.c
- tests/acceptance/00_basics/def.json/class_from_classexpression.cf
- tests/acceptance/00_basics/def.json/class_from_classexpression.cf.json
- tests/acceptance/README
A condition in an augments file is treated as a class expression
if it ends in `::`. Otherwise it is treated as a regular
expression.
Previously there was a bug, where the conditions in augments files
were treated as both class expressions and regular expressions.
This was ambiguous, and problematic since something like
`cfengine.nginx.enabled` as a regex would match a class called
`cfengine_nginx_enabled`, while as a class expression would match
`cfengine && nginx && enabled`.
This was fixed in 3.12.1 by treating it as a regex only.
(Documented and intended behavior).
Some users still wanted a way to use class expression, so the `::`
suffix solves the problem. For the example above, you can use this
in the augments file:
`cfengine.nginx.enabled::`
Since classes cannot end with `:`, this …
> CFE-2954: Augments files can now handle class expressions by appending '::' (3.12)

- libpromises/processes_select.c
- tests/acceptance/05_processes/01_matching/inverse_ttime_inverse_found.cf
Fixing the rather weird test seems to be a better idea than changing our super-complex `ps` output parsing code.
> Fix AIX inverse process selection test

- cf-agent/cf-agent.c
- cf-execd/cf-execd.c
- cf-promises/cf-promises.c
- cf-serverd/cf-serverd-functions.c
- cf-serverd/cf-serverd.c
- libutils/deprecated.h
- libutils/misc_lib.c
- libutils/misc_lib.h
- tests/unit/misc_lib_test.c
They still leak on exotic platforms which don't support
setenv. Fixing this is much more difficult than it seems.
Fixed one conflict in includes while cherry-picking.
> CFE-2918: Introduced wrappers for setenv and putenv which don't leak (3.12)

- cf-agent/verify_packages.c
Commit 9cd859620825 ("Fix cfe_internal packages to avoid return code
check.") had ExecPackageCommand() skip the return code verification to
avoid noise in the log for a command that is expected to fail.  This
results in ExecPackageCommand() indicating success, though, which leads
to the completely bogus message:
```
verbose: Package schedule execution ok for 'cfe_internal_non_existing_package' (outcome cannot be promised by cf-agent)
```
Decide if we want to ignore the package before looking at the status
code to restore the intended behavior.
Also, clean up the package name check by wrapping it in a macro.  Note
that passing the result of strlen(3) to strncmp(3) is no different than
simply calling strcmp(3), so just do the latter.
> fix bogus success message for 'cfe_internal' package

- libpromises/evalfunction.c
Found by manually running enterprise hub agent in valgrind.
See: https://github.com/cfengine/core/pull/3463/files#r286054720
> Fixed memory leak in filesexist()

- libcfnet/tls_generic.c
There is a flag for disabling TLS 1.0, we shouldn't just use 0.
Ticket: CFE-3068
> Fix disabling TLS 1.0

- libcfnet/tls_generic.c
There is a flag for disabling TLS 1.0, we shouldn't just use 0.
Ticket: CFE-3068
(cherry picked from commit 9862f3928c204d7f3defc6a3dc8d3e1ee3f08819)
> [3.12.x] Fix disabling TLS 1.0

- misc/determine-version.py
https://github.com/cfengine/enterprise/pull/522
https://github.com/cfengine/nova/pull/1430
https://github.com/cfengine/masterfiles/pull/1413
> Fix determine_version.py to deal with the 3.12.2-2 re-release

- contrib/pgsql_RA
In most recent versions of PostgreSQL the process in the `ps -ef`
output says "walreceiver" instead of "wal receiver". So we need
to adapt the regex matching it.
> Fix detection of the WAL receiver process in the PG RA

- .lgtm/cpp-queries/bool-type-mismatch-return.ql
Gets rid of at least 2 false positives. I think query needs more
work to handle all variants of type casts.
> LGTM: Boolean type checking now respects type casts

- libutils/string_lib.c
- libutils/string_lib.h
- tests/unit/string_lib_test.c
> ENT-4777: Added function to trim trailing CRLF from a line of CSV data

- libutils/file_lib.c
My mistake. Luckily, it was only ever used with 0077 anyway,
so no change in behavior.
> SetUmask function now correctly applies the given umask

- libpromises/attributes.c
- libpromises/cf3.defs.h
- libpromises/verify_vars.c
The normal way of initializing a struct to zeroes is:
```
Attributes a = { 0 };
```
* If the struct has only simple types (int, enum, pointers), this
works well.
* If the struct has other structs inside (not pointers to structs)
it still works, compilers seem to 0 out everything correctly.
* It does however trigger some warnings when compiling with
`-Wextra`.
These warnings are useful in other scenarios, like here:
```
return (FnCallResult) { FNCALL_FAILURE, { 0 } };
```
Ensuring that you specify correct number of initial values,
and use `{` for structs, and don't use `{` for integers or
pointers. A kind of type checking, if you will.
Thus, to satisfy this warning, I added a macro for the
`Attributes` struct. It should be noted that this struct is the
only one which needs the special …
> Attributes structs are now initialized using a macro

- cf-check/backup.c
- cf-check/utilities.c
Should also make it respect `--with-statedir` configure option.
> CFE-2994: cf-check directories can now be controlled from ENV vars

- cf-check/backup.c
- cf-check/utilities.c
Should also make it respect `--with-statedir` configure option.
> CFE-2994: cf-check directories can now be controlled from ENV vars (3.12)

- examples/action_policy.cf
https://github.com/cfengine/documentation/pull/2144
> CFE-3084: Added example illustrating body action action_policy warn and nop

- libpromises/bootstrap.c
- libpromises/bootstrap.h
- libpromises/generic_agent.c
- libutils/writer.c
- travis-scripts/valgrind.sh
Contains the ID from `/var/cfengine/bootstrap_id.dat`, if present.
> CFE-2977: Added sys.bootstrap_id policy variable

- contrib/cf-info/cf-info.sh
cf-info.sh assumed the last 2 runs in promise_summary.log were for update.cf and promises.cf.   Added logic to specify the last update.cf run and the last non-update.cf run to be used instead.
Also changed the "Last cf-agent run started x minutes ago and lasted y seconds" code to only show the last non-update.cf run.
> cf-info.sh - fixed issue with update.cf and promises.cf calculations

- libenv/sysinfo.c
Version specific classes are useful for subdividing the enterprise host tree, so
we need to tag them so that they are collected by default.
Ticket: ENT-4752
> ENT-4752 Set tag on version specific os related class for default collection

- cf-monitord/history.c
The previous log line did not provide useful information, and made it look as if
it were still trying to determine if the line matched or not.
> ENT-4814: cf-monitord fixes (log messages, tracking growing files, C code opportunistic cleanup)

- libutils/file_lib.c
My mistake. Luckily, it was only ever used with 0077 anyway,
so no change in behavior.
> SetUmask function now correctly applies the given umask (3.12.2)

- libutils/file_lib.c
My mistake. Luckily, it was only ever used with 0077 anyway,
so no change in behavior.
> SetUmask function now correctly applies the given umask (3.12)

- libutils/file_lib.c
My mistake. Luckily, it was only ever used with 0077 anyway,
so no change in behavior.
> SetUmask function now correctly applies the given umask (3.10)

- cf-check/backup.c
- cf-check/backup.h
- cf-check/cf-check.c
- cf-check/diagnose.c
- cf-check/diagnose.h
- cf-check/lmdump.c
- cf-check/lmdump.h
- cf-check/repair.c
- cf-check/repair.h
- cf-check/utilities.c
- cf-check/utilities.h
- libutils/sequence.c
- libutils/sequence.h
cf-check now supports the same options as the other CFEngine
binaries; log-level, verbose, debug, manpage, version, help.
There were some error messages before, but this commit ensures that
all commands (diagnose, repair, backup) both print errors and exit
with non-zero exit code, when no db files are found.
Also clarified log messages and code comments to be more clear.
The DB check in cf-agent and cf-execd does not fail if there are
no files.
> CFE-3082: cf-check code cleanup, better errors, man page and other options

- configure.ac
- misc/Makefile.am
Policy was giving errors on systemd systems, since it
expects the services to be installed.
> CFE-3030: systemd service is now installed by default

- cf-monitord/env_monitor.c
- cf-monitord/mon_network.c
- cf-monitord/mon_processes.c
0600 matches the permissions enforced by policy.
Affected files:
* `cf_incoming`
* `cf_outgoing`
* `cf_users`
* `env_data`
> ENT-4863: Set create permissions of monitord files in state directory to 0600

- examples/eval.cf
-1^2.1 can be -nan on some platforms.
> Prevent the example of 'nan' result from eval() from breaking tests

- libpromises/crypto.c
- libutils/unix_dir.c
Found using ubuntu 18 vagrant virtualbox VM (and gcc).
> ENT-3510: Fixed a couple of new compiler warnings

- configure.ac
- misc/Makefile.am
Policy was giving errors on systemd systems, since it
expects the services to be installed.
> CFE-3030: systemd service is now installed by default (3.12)

- libutils/sequence.c
- libutils/sequence.h
Makes it easier to reuse without adding many dependencies.
Ideally, config.h (platform.h) should be included in c files,
not headers.
> ENT-4885: Moved platform.h include in sequence

- .mailmap
Fixed mappings for Maciej, Vratislav, Craig, Ole, Krl, Kristian, Hichame,
Aleksey, Mike, Alexis, and Marcin to deduplicate authorship.
The mail address with the most commits was used as the primary.
> Tidied mailmap entries

- .clang-format
Correct according to our style guide.
> clang-format: Add spaces after type casts

- tests/acceptance/10_files/templating/mustache_from_json_or_classic_array.cf
This tests covers rendering the same data structure from both classic arrays and
JSON via edit_template_string => "inline_mustache".
It exposes several gaps with respect to rendering data from classic arrays:
- It does not seem possible to render data from classic arrays when
edit_template_string receives data explicitly from datastate() (but it works
when the data is JSON).
- It does not seem possible to render data from classic array when
edit_template_string receives data from bundlestate (but it works when the data
is JSON).
- It does not seem possible to render data from classic array when
edit_template_string receives data implicitly from datastate() (but it works
when the data is JSON)
> CFE-3124 Added test for mustache rendered from JSON or classic array

- misc/Makefile.am
Only relevant for make install from sources (not packages).
> CFE-3030: Run daemon-reload after installing systemd files

- .gitignore
This was causing problem with the following workflow:
- On master branch
- With libntech submodule
- libntech submodule has peg Makefile
- Run `git checkout 3.12.x`
- libntech folder is left in place (no submodule)
- The peg Makefile inside libntech is now ignored (not commited)
- Run `git clean -fXd`
- peg Makefile is deleted
- Run `git checkout master`
- libntech is now a submodule again, but peg Makefile is deleted
This change should be backported to make it work as expected.
> Added individual Makefiles to .gitignore

- contrib/cf-remote/cf_remote/main.py
Before:
```
> $ cf-remote -H $(hostname)
Traceback (most recent call last):
File "/home/nickanderson/bin/cf-remote", line 11, in <module>
main()
File "/home/nickanderson/Northern.Tech/CFEngine/core/contrib/cf-remote/cf_remote/main.py", line 133, in main
validate_args(args)
File "/home/nickanderson/Northern.Tech/CFEngine/core/contrib/cf-remote/cf_remote/main.py", line 125, in validate_args
args.command = args.command.strip()
```
After:
```
> $ cf-remote -H $(hostname)
cf-remote: Invalid or missing command
```
> CFE-3134: Fixed crash when no command supplied for cf-remote

- contrib/cf-remote/cf_remote/main.py
Before:
```
> $ cf-remote -h
usage: cf-remote [-h] [--hosts HOSTS] [--clients CLIENTS] [--hub HUB]
[--bootstrap BOOTSTRAP] [--package PACKAGE]
[--hub-package HUB_PACKAGE] [--client-package CLIENT_PACKAGE]
[--log-level LOG_LEVEL] [--demo] [--call-collect]
[--version [VERSION]]
[command] [args [args ...]]
Spooky CFEngine at a distance
positional arguments:
command               Action to perform (default: None)
args                  Arguments (default: None)
optional arguments:
-h, --help            show this help message and exit
--hosts HOSTS, -H HOSTS
Which hosts to connect to (ssh) (default: None)
--clients CLIENTS, -c CLIENTS
Where to install client package (default: None)
--hub HUB             Where to install hub package (default: None)
--bootstrap BOOTSTRAP, -B BOOTSTRAP
cf-agent …
```
> CFE-3136: Added valid commands to cf-remote help output

- libpromises/mod_common.c
- libpromises/syntax.c
- tests/unit/syntax_test.c
The function which checks if a variable name is valid, CheckParseVariable, was wrong in so many ways:
1. No unit test
2. Very hard to read
3. Gives wrong error messages (Always "reserved name", even when that is not the issue)
4. Stack buffer overflow for variables longer than 1024 bytes
5. For some edge cases like, `"a."`, the result is random (dependent on uninitialized memory)
6. It does a lot of passes over the same data (strlen, strlen, strchr, sscanf)
7. It's also just wrong, `".a"` is invalid, so is `".a[b]"`, but `".a[b.c]"` is valid when it clearly shouldn't be
(I'll fix 7. in a separate PR).
> Prevented buffer overflow when policy variable names are longer than 1024 bytes

- .gitignore
This was causing problem with the following workflow:
- On master branch
- With libntech submodule
- libntech submodule has peg Makefile
- Run `git checkout 3.12.x`
- libntech folder is left in place (no submodule)
- The peg Makefile inside libntech is now ignored (not commited)
- Run `git clean -fXd`
- peg Makefile is deleted
- Run `git checkout master`
- libntech is now a submodule again, but peg Makefile is deleted
This change should be backported to make it work as expected.
> Added individual Makefiles to .gitignore (3.10)

- .gitignore
This was causing problem with the following workflow:
- On master branch
- With libntech submodule
- libntech submodule has peg Makefile
- Run `git checkout 3.12.x`
- libntech folder is left in place (no submodule)
- The peg Makefile inside libntech is now ignored (not commited)
- Run `git clean -fXd`
- peg Makefile is deleted
- Run `git checkout master`
- libntech is now a submodule again, but peg Makefile is deleted
This change should be backported to make it work as expected.
> Added individual Makefiles to .gitignore (3.12)

- .clang-format
- cf-check/Makefile.am
- cf-check/cf-check.c
- cf-check/dump.c
- cf-check/dump.h
cf-check: dump command now dumps DB contents to JSON5
Example:
```
$ cf-check dump /var/cfengine/state/cf_lastseen.lmdb
{
"a192.168.100.10\0": "MD5=efbb78408659e9e99188218a8518b7ec\0",
"kMD5=efbb78408659e9e99188218a8518b7ec\0": "192.168.100.10\0",
"qoMD5=efbb78408659e9e99188218a8518b7ec\0": "\0\xf6h]\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0",
}
```
`dump` was previously an alias for `lmdump`.
`lmdump` command, as well as symlinking `cf-check` as `lmdump`,
is still supported, for compatibility.
New functionality will be added to `dump` command.
Some code should be moved to JSON library, but I need to make
bigger changes there, so I think it's okay to merge this first.
> cf-check: dump command now dumps DB contents to JSON5

- configure.ac
- misc/Makefile.am
- misc/selinux/Makefile.am
- misc/selinux/cfengine-enterprise.fc
- misc/selinux/cfengine-enterprise.te
It complements the upstream SELinux cfengine module [1] created
by someone, probably for CFEngine Community, which is installed
by default on RHEL/CentOS 7+ systems.
It also defines a separate **unconfined** domain for cf-agent.
[1] https://github.com/fedora-selinux/selinux-policy-contrib/blob/rawhide/cfengine.te
https://github.com/cfengine/core/pull/3813
https://github.com/cfengine/masterfiles/pull/1492
https://github.com/cfengine/buildscripts/pull/612
> Add SELinux policy for CFEngine Enterprise

- libenv/sysinfo.c
The format of the /etc/redhat-release file was changed:
```
Red Hat Linux release 6.2 (Zoot)
Red Hat Enterprise Linux release 8.0 (Ootpa)
```
(Our code didn't expect the Enterprise part).
**Before:**
```
[ec2-user@ip-172-31-38-120 core]$ sudo /var/cfengine/bin/cf-promises --show-classes | grep redhat
inventory_redhat_have_python_symlink                         source=promise                          
redhat                                                       inventory,attribute_name=none,source=agent,hardclass
redhat_pure                                                  source=promise,inventory,attribute_name=none
```
**After:**
```
[ec2-user@ip-172-31-38-120 core]$ /var/cfengine/bin/cf-promises --show-classes | grep redhat
inventory_redhat_have_python_symlink …
```
> CFE-3140: redhat_8 and redhat_8_0 are now defined on RHEL 8

- cf-check/backup.c
- cf-check/diagnose.c
- cf-check/diagnose.h
- cf-check/repair.c
- cf-check/utilities.c
- cf-check/utilities.h
**Example:**
```
root@dev core $ truncate --size 9000 /var/cfengine/state/packages_installed_apt_get.lmdb
root@dev core $ cf-check diagnose --no-fork
info: No filenames specified, defaulting to .lmdb files in /var/cfengine/state
info: Status of '/var/cfengine/state/cf_lastseen.lmdb': LMDB_INVALID_DATABASE
info: Status of '/var/cfengine/state/cf_observations.lmdb': OK
info: Status of '/var/cfengine/state/cf_state.lmdb': OK
Bus error (core dumped)
root@dev core $ gdb --args cf-check diagnose --no-fork
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by …
```
> CFE-3145: Added --no-fork to cf-check diagnose command

- misc/determine-version.py
After releasing say 3.15.0 beta, we don't want to start building
3.16.0 packages, 3.15.0 is still yet to be released.
https://github.com/cfengine/core/pull/3837
https://github.com/cfengine/enterprise/pull/545
https://github.com/cfengine/nova/pull/1517
https://github.com/cfengine/masterfiles/pull/1505
> Do not increment version after alpha/beta release

- cf-check/backup.c
- cf-check/diagnose.c
- cf-check/diagnose.h
- cf-check/repair.c
- cf-check/utilities.c
- cf-check/utilities.h
Useful for if you want cf-check to crash (under gdb).
Cherry-picked from: https://github.com/cfengine/core/pull/3835
> CFE-3145: Added --no-fork to cf-check diagnose command (3.12)

- libpromises/mod_common.c
- libpromises/syntax.c
- tests/unit/syntax_test.c
Cherry-picks from https://github.com/cfengine/core/pull/3807
Merge-conflict: bool-correctness fixes not in 3.12.x
> Prevented buffer overflow when policy variable names are longer than 1024 bytes (3.12)

- libenv/sysinfo.c
Contents of os-release on RHEL 8:
```
[ec2-user@ip-172-31-38-120 core]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.0 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.0"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.0 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.0:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.0
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.0"
```
Our older platform detection code (which uses the redhat-release file) sets
the hard class `redhat`, not `rhel`. For backwards compatibility, I added an
alias, so both are defined.
**Before:**
``` …
```
> CFE-3140: An ID of rhel in os-release file will now define both rhel and redhat classes

- cf-check/diagnose.c
cf-check now works as before when you don't add `--no-fork`, and when you do, it uses `fflush` and `dup2` for the redirection, instead of `/dev/fd`. Both the new and old approach was tested and work on OS X and Ubuntu 18.04.
> cf-check: Improve portability of --no-fork mode

- cf-check/Makefile.am
- cf-check/db_structs.h
- cf-check/dump.c
cf-check can use our knowledge of what these databases contain (structs), as well as the JSON code in libntech, to print the information in a readable way. Here's a comparison:
**mdb_dump:**
```
root@dev core $ mdb_dump -np /var/cfengine/state/cf_lastseen.lmdb
VERSION=3
format=print
type=btree
mapsize=104857600
maxreaders=126
db_pagesize=4096
HEADER=END
a192.168.100.10\00
MD5=0924931c0116d2640e609bfbb424dc18\00
kMD5=0924931c0116d2640e609bfbb424dc18\00
192.168.100.10\00
qoMD5=0924931c0116d2640e609bfbb424dc18\00
\cd\96z]\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00
DATA=END
root@dev core $
```
**lmdump:**
```
root@dev core $ lmdump -a /var/cfengine/state/cf_lastseen.lmdb
key: 0x7f3bc38abf34[16] a192.168.100.10, data: …
```
> CFE-2989: Human readable JSON5 dumping of LMDB databases

- libenv/sysinfo.c
Contents of os-release on RHEL 8:
```
[ec2-user@ip-172-31-38-120 core]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.0 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.0"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.0 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.0:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.0
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.0"
```
Our older platform detection code (which uses the redhat-release file) sets
the hard class `redhat`, not `rhel`. For backwards compatibility, I added an
alias, so both are defined.
**Before:**
``` …
```
> CFE-3140: An ID of rhel in os-release file will now define both rhel and redhat classes (3.12)

- configure.ac
It seems this variable already had a value, with the include
path of the header, so overwriting it here was a bad idea.
We should probably fix the line below as well, but I don't
know what's appropriate, and this patch was enough to fix
my problems when building on OpenBSD.
Merge first: https://github.com/cfengine/libntech/pull/10
> Fixed issue with including pcre.h on OpenBSD

- libpromises/systype.c
* `ps -axo`: truncates the ouptut of ps at the width of terminal.
* `ps -axwwo`: displays the full length of the command and args
Without this patch cf-agent --bootstrap fails with 80 column
terminals, and success with wider terminals. Error message:
```
cf-agent[29746]: CFEngine(agent)  Bootstrapping failed, cf-execd is not running
```
From the `man ps` page of NetBSD (https://netbsd.gw.com/cgi-bin/man-cgi?ps+1):
```
-w           Use 132 columns to display information instead of the
default, which is your window size.  If the -w option is
specified more than once, ps will use as many columns as
necessary without regard to your window size.
```
Reading the ps man page of OpenBSD seems to have the same problem:
https://man.openbsd.org/ps
> NetBSD ps output gets truncated

- libpromises/eval_context.c
- libpromises/eval_context.h
- libpromises/promises.c
- tests/acceptance/00_basics/04_bundles/unless_bug.cf
**Bug fix:**
`unless_bug.cf`:
```
bundle agent test
{
meta:
any::
"description" -> { "CFE-2698" }
string => "This test shows a bug in unless which should be fixed";
vars:
any::
"target_variable"
string => "value";
"vars_promise_which_should_be_skipped"
string => "value",
unless => isvariable( $(variable_defined_later) );
"variable_defined_later"
string => "target_variable";
}
```
**Change in error message:**
Before:
```
$ cf-agent unless_illegal.x.cf -D AUTO -K
error: unless_illegal.x.cf:0:0: In attribute 'unless', Function does not return the required type. Given attribute value 'isvariable("$(no_such_variable)")'
error: Fatal CFEngine error: Cannot continue
$ echo $?
1
```
After:
```
$ cf-agent unless_illegal.x.cf -D AUTO -K
R: test description: This test ensures that unresolved …
```
> CFE-2689: Fixed bug and error message in unless attribute

- libenv/unix_iface.c
Previously IPv6 addresses were blindly added to the sys.ip_addresses
variable. This commit makes sure that the address is not added to
the variable if it is present in 'ignored_interfaces.rx'.
> CFE-3156: IPv6 addresses now respects ignored_interfaces.rx

- cf-agent/verify_processes.c
- tests/acceptance/05_processes/process_stop.cf
https://github.com/cfengine/enterprise/pull/550
Previously, the return code from the process_stop command wrongly did not
influence the result of the promise. With this change, when process_stop command
returns zero, the promise will be considered repaired and when process_stop
returns non-zero the promise will be failed/notkept. Additionally, this change
clarifies existing and adds additional log messages.
Ticket: ENT-4988
(cherry picked from commit fa4ea6d47bd60718930e2ee7896d882e4d7fb67e)
> ENT-4988/3.12.x: Fixed promise result when using process_stop in processes type promises

- cf-agent/verify_processes.c
- tests/acceptance/05_processes/process_stop.cf
https://github.com/cfengine/enterprise/pull/551
Previously, the return code from the process_stop command wrongly did not
influence the result of the promise. With this change, when process_stop command
returns zero, the promise will be considered repaired and when process_stop
returns non-zero the promise will be failed/notkept. Additionally, this change
clarifies existing and adds additional log messages.
Ticket: ENT-4988
(cherry picked from commit fa4ea6d47bd60718930e2ee7896d882e4d7fb67e)
(cherry picked from commit acdde64f6756ae80905cc83ad686744c8ec159c8)
> ENT-4988/3.10.x: Fixed promise result when using process_stop in processes type promises

- cf-agent/verify_files_utils.c
- libpromises/files_copy.c
- libpromises/files_copy.h
- tests/acceptance/10_files/02_maintain/004.cf
- tests/acceptance/10_files/02_maintain/005.cf
- tests/acceptance/10_files/02_maintain/006.cf
- tests/acceptance/10_files/copy_from_preserve_false.cf
Depends on the `preserve` attribute, although we should probably discuss how it should look @nickanderson 
Need to run acceptance tests.
> ENT-4016: Fix copy_from overwriting permissions on destination file

- contrib/cf-remote/cf_remote/ssh.py
- contrib/cf-remote/cf_remote/utils.py
Example:
```
$ cf-remote info -H ci.cfengine.com
olehermanse@ci.cfengine.com
CFEngine      : 3.12.0
Policy server : 172.30.0.100
$
```
> CFE-3137: cf-remote: Use whoami username first if none specified

- contrib/cf-remote/cf_remote/commands.py
- contrib/cf-remote/cf_remote/main.py
- contrib/cf-remote/cf_remote/packages.py
- contrib/cf-remote/cf_remote/remote.py
- contrib/cf-remote/cf_remote/utils.py
Example:
```
$ cf-remote install --hub 34.255.3.86 --bootstrap 172.31.34.185 --edition community
ubuntu@34.255.3.86
CFEngine      : Not installed
Package already downloaded: '/Users/olehermanse/.cfengine/cf-remote/packages/cfengine-community_3.12.2-2_amd64-debian7.deb'
Copying: '/Users/olehermanse/.cfengine/cf-remote/packages/cfengine-community_3.12.2-2_amd64-debian7.deb' to '34.255.3.86'
Installing: 'cfengine-community_3.12.2-2_amd64-debian7.deb' on '34.255.3.86'
CFEngine 3.12.2 (Community) was successfully installed on '34.255.3.86'
Bootstrapping: '34.255.3.86' -> '172.31.34.185'
Bootstrap successful: '34.255.3.86' -> '172.31.34.185'
olehermanse@OHMBP ~ $ cf-remote info -H 34.255.3.86 …
```
> CFE-3135: cf-remote: Added --edition option to enable installing community packages

- examples/function-return-types.cf
Not sure how it got in to master without this.
> CFE-3165/master: Fix prep for example illustrating function return types

- examples/data_regextract.cf
- tests/acceptance/01_vars/02_functions/data_regextract-2.cf
- tests/acceptance/01_vars/02_functions/data_regextract-2.cf.readfile
https://github.com/cfengine/documentation/pull/2203
> CFE-3171/master: Added tests to exercises multiline mode behavior in data_regextract

- libpromises/dbm_lmdb.c
- libpromises/locks.c
LMDB keys are limited to 511 bytes, by default. To get around
this, the keys were changed to be hashes some time ago.
This change effectively reverts that commit, making the keys
normal strings by default, and overwriting the last part with a
hash, if necessary (if the key would exceed 511 bytes).
> CFE-2596: Keys in the lock database, cf_lock.lmdb, are now human-readable

- libpromises/locks.c
This may be causing reporting failures in some cases.
Ticket: ENT-4921
> ENT-4921: Removed stime_range and ttime_range constraints from promise hash

- libpromises/systype.c
* `ps -axo`: truncates the ouptut of ps at the width of terminal.
* `ps -axwwo`: displays the full length of the command and args
Without this patch cf-agent --bootstrap fails with 80 column
terminals, and success with wider terminals. Error message:
```
cf-agent[29746]: CFEngine(agent)  Bootstrapping failed, cf-execd is not running
```
From the `man ps` page of NetBSD (https://netbsd.gw.com/cgi-bin/man-cgi?ps+1):
```
-w           Use 132 columns to display information instead of the
default, which is your window size.  If the -w option is
specified more than once, ps will use as many columns as
necessary without regard to your window size.
```
Reading the ps man page of OpenBSD seems to have the same problem:
https://man.openbsd.org/ps
> Fixed bug in ps parsing on OpenBSD / NetBSD causing bootstrap to fail (3.12)

- libpromises/systype.c
* `ps -axo`: truncates the ouptut of ps at the width of terminal.
* `ps -axwwo`: displays the full length of the command and args
Without this patch cf-agent --bootstrap fails with 80 column
terminals, and success with wider terminals. Error message:
```
cf-agent[29746]: CFEngine(agent)  Bootstrapping failed, cf-execd is not running
```
From the `man ps` page of NetBSD (https://netbsd.gw.com/cgi-bin/man-cgi?ps+1):
```
-w           Use 132 columns to display information instead of the
default, which is your window size.  If the -w option is
specified more than once, ps will use as many columns as
necessary without regard to your window size.
```
Reading the ps man page of OpenBSD seems to have the same problem:
https://man.openbsd.org/ps
> Fixed bug in ps parsing on OpenBSD / NetBSD causing bootstrap to fail (3.10)

- tests/unit/lastseen_migration_test.c
Function "HashPubKey()" has a 'const' inconsistency between its declaration and definition, causing, causing a compilation error (under "make check").
> HashPubKey(): consistency of declaration and definition

- libpromises/systype.c
- tests/acceptance/05_processes/01_matching/owner.cf
- tests/acceptance/05_processes/01_matching/tty.cf
The acceptance tests had not been covering 'tty' or 'process_owner'.  The two commits here begin to fill that gap.
The 'process_owner' test is standalone.
The 'tty' test has an associated source code change.  See the comment within its commit message for more details.
See issues CFE-3025, which itself emerged from CFE-3020 and CFE-1655
> Acceptance tests for process handling: CFE-3025

- libpromises/logic_expressions.c
- libpromises/logic_expressions.h
- libpromises/string_expressions.c
This PR brings libntech submodule up to date (with master HEAD) and fixes some necessary includes, since `bool.h` was removed.
> libntech: Removed bool.h in favor of stdbool.h

- cf-agent/cf-agent.c
- cf-check/Makefile.am
- cf-check/backup.c
- cf-check/backup.h
- cf-check/cf-check.c
- cf-check/diagnose.c
- cf-check/diagnose.h
- cf-check/dump.c
- cf-check/repair.c
- cf-check/repair.h
- cf-check/replicate_lmdb.c
- cf-check/replicate_lmdb.h
- cf-check/utilities.c
- cf-check/utilities.h
- cf-execd/cf-execd.c
- libcompat/clock_gettime.c
- libpromises/Makefile.am
- libpromises/dbm_api.c
- libpromises/dbm_api.h
- libpromises/dbm_lmdb.c
- libpromises/mutex.c
- libpromises/mutex.h
- libpromises/patches.c
- libpromises/prototypes3.h
- tests/unit/Makefile.am
3.12.x version of #3873 
https://github.com/cfengine/core/pull/3886
https://github.com/cfengine/enterprise/pull/554
> [3.12.x] LMDB recovery

- libpromises/dbm_lmdb.c
The performance gain is not worth the instability and issues with
consistency on these legacy platforms.
Ticket: ENT-4002
Changelog: Local databases now use synchronous access on AIX and Solaris
> Never use MDB_NOSYNC on AIX and Solaris

- cf-serverd/server_tls.c
SSL_accept() may fail with SSL_get_error() returning
SSL_ERROR_WANT_READ or WANT_WRITE in some cases. That doesn't
indicate a fatal error in SSL connection establishing, but rather
a potentially temporary problem which could be fixed by a
retry. And that's exactly what we should do.
See man:SSL_accept(3) for details.
This is a follow-up for ca691fe91ecea6fe7f091ce5680ad7f0a1a020ce
which did the same for SSL_connect, SSL_read and SSL_write.
Ticket: CFE-3066
Changelog: cf-serverd now tries to accept connection multiple times
> Retry SSL_accept() if WANT_READ or WANT_WRITE is indicated

- cf-check/repair.c
If the child process receives SIGBUS, it should just die and let
the parent handle the situation.
> Reset SIGBUS handling in a child process replicating LMDB

- cf-serverd/cf-serverd-enterprise-stubs.c
- cf-serverd/cf-serverd-enterprise-stubs.h
- cf-serverd/server.c
- cf-serverd/server_common.c
- cf-serverd/server_tls.c
- cf-serverd/server_tls.h
- cf-testd/cf-testd.c
- libcfnet/Makefile.am
- libcfnet/README.md
- libcfnet/cfnet.h
- libcfnet/client_code.c
- libcfnet/client_protocol.c
- libcfnet/connection_info.c
- libcfnet/net.c
- libcfnet/protocol.c
- libcfnet/protocol.h
- libcfnet/protocol_version.c
- libcfnet/protocol_version.h
- libcfnet/tls_client.c
- libpromises/attributes.c
- libpromises/dbm_api.c
- libpromises/dbm_api.h
- libpromises/expand.c
- libpromises/expand.h
This PR includes several improvements to the handling of network protocol version.
It also adds a v3, named "cookie", which will be used for enterprise features only. (Reporting cookies for duplicate host identification).
Merge together: 
https://github.com/cfengine/core/pull/3907
https://github.com/cfengine/enterprise/pull/557
https://github.com/cfengine/nova/pull/1537
https://github.com/cfengine/mission-portal/pull/930
https://github.com/cfengine/documentation/pull/2229
> ENT-4406: Network protocol v3 - cookie

- libpromises/evalfunction.c
- tests/acceptance/01_vars/02_functions/readstringlist-many-comments.cf
This should also fix many erroneous occurences of the following error message:
```
error: Comment regex '\s*#[^\n]*' was irreconcilable reading input 'test.txt' probably because it legally matches nothing
```
(A warning can still appear if a comment regex actually matches nothing).
Also made this comment removing logic faster.
Affected functions include:
* readstringlist()
* readintlist()
* readreallist()
* peers()
* peerleader()
* peerleaders()
* data_readstringarray()
* data_readstringarrayidx()
* data_expand()
* readstringarray()
* readstringarrayidx()
* readintarray()
* readrealarray()
* parsestringarray()
* parsestringarrayidx()
* parseintarray()
* parserealarray()
> CFE-3188: Fixed issue when removing comments from files in various policy functions

- misc/selinux/cfengine-enterprise.te
Some macro expands to a rule that requires the xdp_socket class
so we need to "import" it.
> Add one more class to the SELinux policy definitions

- cf-serverd/server_tls.c
SSL_accept() may fail with SSL_get_error() returning
SSL_ERROR_WANT_READ or WANT_WRITE in some cases. That doesn't
indicate a fatal error in SSL connection establishing, but rather
a potentially temporary problem which could be fixed by a
retry. And that's exactly what we should do.
See man:SSL_accept(3) for details.
This is a follow-up for ca691fe91ecea6fe7f091ce5680ad7f0a1a020ce
which did the same for SSL_connect, SSL_read and SSL_write.
Ticket: CFE-3066
Changelog: cf-serverd now tries to accept connection multiple times
(cherry picked from commit 03bd0698a9fd330b72a1068ea023345b445d3cd0)
> [3.12.x] Retry SSL_accept() if WANT_READ or WANT_WRITE is indicated

- libcfnet/tls_generic.c
Security vulnerabilities were found in TLS 1.0 [1]. None of them
applies to the mutually authenticated peer-to-peer TLS
communication in CFEngine, but the version 1.0 of the protocol is
now considered deprecated.
TLS 1.1 is supported by CFEngine 3.7.0 and newer so it is safe to
default the minimum required TLS version to 1.1 while making it
possible to change the minimum required version to 1.0 in policy.
[1] https://www.acunetix.com/blog/articles/tls-vulnerabilities-attacks-final-part/
Ticket: ENT-4616
Changelog: Default minimum allowed TLS version is now 1.1
https://github.com/cfengine/core/pull/3936
https://github.com/cfengine/masterfiles/pull/1574
> Add a recommended minimum TLS version and default to it

- cf-net/cf-net.c
- libcfnet/protocol.c
- libcfnet/protocol.h
Added functions `Get` and `StatGet`, where the latter just stats the file before calling the former function with the correct file size. `Get` uses `GET <block_size> <remote_path>` to retrieve a file.
Ticket: CFE-3087
> CFE-3087: New functions Get and StatGet for protocol

- libenv/unix_iface.c
Previously, when an interface had multiple IPv4 addresses set, the parsing of
these addresses would add the interface to the sys.interfaces and sys.hardware
variables multiple times, resulting in the interface showing up as a duplicate
in the list.
This fix makes sure that an interface is only added once for every interface
type, regardless of how many IPv4 addresses the interface contains.
> CFE-3046: Only add unique IPv4 interfaces to sys.interfaces

- cf-agent/verify_users_pam.c
- cf-monitord/mon_cpu.c
- cf-monitord/mon_io_linux.c
- cf-monitord/mon_mem_linux.c
- libpromises/processes_select.c
Should be the last ones in core.
> Changed occurences of `(f)open` to `safe_(f)open`

- cf-agent/verify_users_pam.c
This condition has not been needed on other unixes, but was
needed for me to test the [FreeBSD users PR.](https://github.com/cfengine/core/pull/3589)
> Prevented potential segmentation fault in verify_users_pam.c

- ChangeLog
- libenv/unix_iface.c
Previously, when an interface had multiple IPv4 addresses set, the parsing of
these addresses would add the interface to the sys.interfaces and sys.hardware
variables multiple times, resulting in the interface showing up as a duplicate
in the list.
This fix makes sure that an interface is only added once for every interface
type, regardless of how many IPv4 addresses the interface contains.
(cherry picked from commit c40f502)
> CFE-3046: Only add unique IPv4 interfaces to sys.interfaces (3.12)

- libpromises/rlist.c
An empty rlist is represented as a NULL pointer, so all Rlist
functions should handle NULL pointers at runtime.
Fixes an issue on FreeBSD, where RlistContainsString is
called on a NULL pointer (before any elements are added):
Core was generated by `/var/cfengine/bin/cf-key'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00000008024219ba in thr_kill () from /lib/libc.so.7
(gdb) bt
#0  0x00000008024219ba in thr_kill () from /lib/libc.so.7
#1  0x0000000802421984 in __raise (s=6) at /usr/src/lib/libc/gen/raise.c:52
#2  0x00000008024218f9 in abort () at /usr/src/lib/libc/stdlib/abort.c:65
#3  0x000000080249d101 in __assert (func=<optimized out>, file=<optimized out>, line=<optimized out>, failedexpr=<optimized out>)
at /usr/src/lib/libc/gen/assert.c:51
#4  0x00000008008cc5b5 in …
> Fixed abort / segfault in Rlist code not expecting NULL pointer

- contrib/cf-remote/cf_remote/spawn.py
Better default for developers who want fast machines. Gotta go fast!
> cf-remote: Use XL instances in AWS, when possible

- cf-execd/cf-execd-runner.c
- cf-execd/cf-execd.c
- libpromises/cf3.defs.h
- libpromises/eval_context.c
- libpromises/evalfunction.c
- libpromises/unix.c
> [3.12.x] Try harder to kill agent process in case of 'agent_expireafter' in cf-execd

- cf-agent/Makefile.am
- cf-promises/Makefile.am
When compiling with explicit CFLAGS / LDFLAGS these are not handled in
the same way in different automake files.
The way we are mixing user-provided flags with configure generated ones
is not ideal, this change doesn't fix that, but it at least makes it
more consistent.
For example, compiling like this:
```
./autogen.sh --enable-debug && make CFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address"
```
Would cause the explicit flags to override flags from configure when
building cf-agent, but not in cf-promises. The end result is that debug
info (line numbers) is missing in some places.
**Before change:**
```
Direct leak of 9 byte(s) in 1 object(s) allocated from:
#0 0x7fc5c3640538 in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x77538)
#1 0x7fc5c31badc0 in xstrdup …
```
> Consistent handling of make flags in cf-promises/cf-agent

- contrib/cf-remote/cf_remote/ssh.py
- contrib/cf-remote/requirements.txt
Some hosts are configured to use 'admin' as administration user and
refuse to allow access to root.
> Added 'admin' as user in `cf-remote`

- tests/acceptance/05_processes/01_matching/promiser_match_is_correct.cf
We spawn an agent process in a shell and then immediately check
that it is running. If it takes a bit to start (easy to happen on
a heavy-loaded machine running tests) the process is not
found. Let's give it a second to start before we try extracting
information about it.
> Mitigate race condition in the promiser_match_is_correct.cf test

- examples/files_depth_search_include_basedir.cf
This example shows how to promise permissions recursively and promise a directory tree is empty. It illustrates the behavior of `include_basedir` in `depth_search` bodies and that the `delete` attribute ignores `include_basedir`.
Ticket: CFE-3218
merge together: https://github.com/cfengine/documentation/pull/2253
> CFE-3218/master: Added example for depth_search include_basedir

- examples/files_depth_search_include_basedir.cf
The function-return-types.cf example is rendered in the Functions section of the
reference manual.
https://docs.cfengine.com/docs/master/reference-functions.html
It renders the prep section, the policy, and the output sections in blocks.
files_depth_search_include_basedir.cf is rendered in the include_basedir
section.
https://docs.cfengine.com/docs/master/reference-promise-types-files.html#include_basedir
It renders the prep section poorly.
Ticket: CFE-3217
----
#
> CFE-3217/master: Aligned style between an example that renders properly, and one that does not

- libpromises/mod_common.c
https://github.com/cfengine/core/pull/3964
https://github.com/cfengine/masterfiles/pull/1601
https://github.com/cfengine/nova/pull/1560
> ENT-3153: Added query_timeout to body hub control

- libpromises/evalfunction.c
- tests/acceptance/01_vars/02_functions/basename_1.cf
- tests/acceptance/01_vars/02_functions/basename_2.cf
Acts in the same way as the POSIX basename program. It retrieves only the
last part of a given path:
```
basename("/etc/sshd/sshd_config") -> "sshd_config"
```
Also supports optional suffix exclusion:
```
basename("/etc/host.conf", ".conf") -> "host"
```
Okay currently this is probably unnecessarily convoluted.
> CFE-3196: New policy function basename() added

- cf-agent/retcode.c
- cf-agent/verify_exec.c
- examples/inform.cf
- libpromises/attributes.c
- libpromises/cf3.defs.h
- libpromises/mod_exec.c
This constraint can be used to suppress the sometimes spammy
INFO log messages, emitted by commands promises:
```
info: Executing 'no timeout' ... '/bin/cat /tmp/module_cache'
info: Completed execution of '/bin/cat /tmp/module_cache'
```
Not all commands promises change the system. Thus, we allow
policy writers to customize whether the promise should be
logged in INFO, or not.
Example policy:
```
{
commands:
"/bin/touch /tmp/module_cache"
inform => "true"; # Default
"/bin/cat /tmp/module_cache"
inform => "false", # Read-only promise, no INFO logging wanted
module => "true";
}
```
> CFE-2973: Added inform constraint to commands promises

- examples/read_module_protocol.cf
- libpromises/evalfunction.c
- libpromises/evalfunction.h
This function reads module protocol from a file, and can be used
for caching the results of commands modules.
Running the example:
```
root@dev core $ cf-agent -K /northern.tech/cfengine/core/examples/read_module_protocol.cf
R: Module cache was read!
R: cached_module.my_variable = Mon Dec  9 13:10:33 2019
root@dev core $ cf-agent -K /northern.tech/cfengine/core/examples/read_module_protocol.cf
R: Module cache was read!
R: cached_module.my_variable = Mon Dec  9 13:10:33 2019
root@dev core $ rm /northern.tech/cfengine/core/examples/cached_module
root@dev core $ cf-agent -K /northern.tech/cfengine/core/examples/read_module_protocol.cf
R: Module cache was read!
R: cached_module.my_variable = Mon Dec  9 13:10:41 2019
root@dev core $
```
> CFE-2973: Added read_module_protocol() policy function

- examples/files_depth_search_include_basedir.cf
This example shows how to promise permissions recursively and promise a
directory tree is empty. It illustrates the behavior of `include_basedir` in
`depth_search` bodies and that the `delete` attribute ignores `include_basedir`.
Ticket: CFE-3218
(cherry picked from commit f0ec9c0b93a332a214985cf7c46a3e7b3d0c122f)
Aligned style between an example that renders properly, and one that does not
The function-return-types.cf example is rendered in the Functions section of the
reference manual.
https://docs.cfengine.com/docs/master/reference-functions.html
It renders the prep section, the policy, and the output sections in blocks.
files_depth_search_include_basedir.cf is rendered in the include_basedir
section.
https://docs.cfengine.com/docs/master/reference-promise-types-files.ht …
> CFE-3218/3.12.x: Added example for depth_search include_basedir

- tests/acceptance/01_vars/01_basic/access_classic_array_key_value_using_with.cf
> CFE-3223/master: Test that `with` can be used in the index of a classic array to access the value

- libpromises/evalfunction.c
- tests/unit/evalfunction_test.c
Trying to get to the bottom of some segmentation fault which only
happens on solaris.
It looks like the buffer returned by `basename()` is marked as read only. Testing a fix.
> Fixed basename() segfault on Solaris

- tests/unit/Makefile.am
Looks like I fixed it on accident.
> Expect success in evalfunction_test on mac

- libpromises/cf3parse.y
This memory leak appears when the LHS of a promise
constraint is `data` or `template_data`, and the RHS
is a string literal. If the string literal is not
valid JSON, perhaps because of unexpanded variables,
a `parsejson` function call is inserted instead. The name
of the function call (for example `parsejson`) is leaked
in this case.
Not picked up by our CI, since valgrind test only runs
community parts of masterfiles.
> Fixed small memory leak in policy evaluation

- libpromises/cf3parse.y
This memory leak appears when the LHS of a promise
constraint is `data` or `template_data`, and the RHS
is a string literal. If the string literal is not
valid JSON, perhaps because of unexpanded variables,
a `parsejson` function call is inserted instead. The name
of the function call (for example `parsejson`) is leaked
in this case.
Not picked up by our CI, since valgrind test only runs
community parts of masterfiles.
> Fixed small memory leak in policy evaluation (3.15)

- libpromises/evalfunction.c
- tests/acceptance/01_vars/02_functions/countlinesmatching_errors_on_absent_file.cf
- tests/acceptance/01_vars/02_functions/countlinesmatching_returns_0_on_inaccessable_file.cf
countlinesmatching() did not error when the file being counted does not exist or
was unable to be accessed. The result of 0 matching lines is correct, but there
is also an expectation of an error message to indicate the file is missing.
Ticket: CFE-3234
> CFE-3234/master: Moved error reading file in countlinesmatching() from verbose to error

- libpromises/evalfunction.c
- tests/acceptance/01_vars/02_functions/countlinesmatching_errors_on_absent_file.cf
- tests/acceptance/01_vars/02_functions/countlinesmatching_returns_0_on_inaccessable_file.cf
countlinesmatching() did not error when the file being counted does not exist or
was unable to be accessed. The result of 0 matching lines is correct, but there
is also an expectation of an error message to indicate the file is missing.
Added test for countlinesmatching() erroring on absent file.
This test simply runs an existing test and inspects the agent run output for an
error.
Ticket: CFE-3234
(cherry picked from commit 5b4ab064165b7f35ac46cde37c8fb7dd096fc61c)
> CFE-3234/3.15.x: Moved error reading file in countlinesmatching() from verbose to error

- libpromises/evalfunction.c
- tests/acceptance/01_vars/02_functions/countlinesmatching_errors_on_absent_file.cf
- tests/acceptance/01_vars/02_functions/countlinesmatching_returns_0_on_inaccessable_file.cf
countlinesmatching() did not error when the file being counted does not exist or
was unable to be accessed. The result of 0 matching lines is correct, but there
is also an expectation of an error message to indicate the file is missing.
Added test for countlinesmatching() erroring on absent file.
This test simply runs an existing test and inspects the agent run output for an
error.
Ticket: CFE-3234
(cherry picked from commit 5b4ab064165b7f35ac46cde37c8fb7dd096fc61c)
> CFE-3234/3.12.x: Moved error reading file in countlinesmatching() from verbose to error

- tests/acceptance/01_vars/02_functions/basename_1.cf
`translatepath` created discrepancies between windows and unix
acceptance tests. When removed, it seems to work fine everywhere.
> Fixed basename acceptance test for windows

- contrib/cf-remote/cf_remote/cloud_data.py
So that 'cf-remote spawn' can be used for spawning RHEL 8 and
CoreOS VMs.
> Add info about RHEL 8 and CoreOS VMs to cf_remote/cloud_data.py

- cf-agent/Makefile.am
- cf-agent/verify_users_pam.c
- configure.ac
Add users support for FreeBSD.
Use pw insread of useradd and usermod, user chpass instead of chpasswd, use rmuser instead of userdel. 
Implement fgetpwent() and fgetgrent() for FreeBSD.
Needs to be tested as I have only tested some cases myself for my personal needs.
> Add users support for FreeBSD

- libenv/sysinfo.c
- libpromises/evalfunction.c
This was originally just meant for `validdata`, but I wanted to make the existing functions a bit more modular (and hopefully more readable as well).
> Refactor read(data|csv|yaml|envfile|json) to use new DATAFILETYPE enums instead of parsing strings

- cf-check/replicate_lmdb.c
There's nothing to do wihout LMDB and thus no way how to use the arguments.
> Mark arguments in replicate_lmdb() as unused with no LMDB

- libpromises/iteration.c
- tests/acceptance/01_vars/01_basic/nested_parens_var_ref.cf
If a variable reference contains parentheses, we need to make
sure we find the matching parenthesis for the opening one, not
the first opposite parenthesis.
For example '$(my_array[key(1)])' needs to match the second
closing parenthesis not the first one.
Ticket: CFE-3242
Changelog: Variable references with nested parentheses no longer
cause errors
> CFE-3242: Find the matching parenthesis in variable reference

- libpromises/iteration.c
- tests/acceptance/01_vars/01_basic/nested_parens_var_ref.cf
If a variable reference contains parentheses, we need to make
sure we find the matching parenthesis for the opening one, not
the first opposite parenthesis.
For example '$(my_array[key(1)])' needs to match the second
closing parenthesis not the first one.
Ticket: CFE-3242
Changelog: Variable references with nested parentheses no longer
cause errors
(cherry picked from commit d3a144e829dd3e8fc3c9ae36b221e9efde969062)
> [3.15.x] Find the matching parenthesis in variable reference

- libpromises/iteration.c
- tests/acceptance/01_vars/01_basic/nested_parens_var_ref.cf
If a variable reference contains parentheses, we need to make
sure we find the matching parenthesis for the opening one, not
the first opposite parenthesis.
For example '$(my_array[key(1)])' needs to match the second
closing parenthesis not the first one.
Ticket: CFE-3242
Changelog: Variable references with nested parentheses no longer
cause errors
(cherry picked from commit d3a144e829dd3e8fc3c9ae36b221e9efde969062)
> [3.12.x] Find the matching parenthesis in variable reference

- contrib/cf-remote/cf_remote/main.py
Unlike the comment says, the 'NAME' positional argument is
defined with 'nargs=?' and thus 'args.name' is not a list.
> Fix how 'NAME' argument to 'cf-remote destroy' is handled

- cf-check/dump.c
**Example:**
```
root@dev core $ cf-check dump /var/cfengine/state/nova_agent_execution.lmdb
{
"delta_gavr": 297.001673,
"last_exec": 1578593375,
}
```
> cf-check: Added nice printing for nova_agent_executions.lmdb

- contrib/cf-remote/cf_remote/ssh.py
Example:
```
$ export CFREMOTE_SSH_KEY="~/.ssh/id_rsa.pub"
$ cf-remote info --hosts hub
ubuntu@34.244.238.16
CFEngine      : 3.16.0a.c505dc774 (Enterprise)
$
```
> cf-remote: Added ability to set ssh key from env var

- cf-key/cf-key.c
It is kind of implied that --force-removal can be destructive.
We don't have any specific reasoning for this phrasing, so it
is not so useful, just confusing / concerning for a user.
> ENT-5090: Removed (USE AT YOUR OWN RISK) from cf-key help menu for -x

- cf-key/cf-key.c
It is kind of implied that --force-removal can be destructive.
We don't have any specific reasoning for this phrasing, so it
is not so useful, just confusing / concerning for a user.
> ENT-5090: Removed (USE AT YOUR OWN RISK) from cf-key help menu for -x (3.12)

- cf-key/cf-key.c
It is kind of implied that --force-removal can be destructive.
We don't have any specific reasoning for this phrasing, so it
is not so useful, just confusing / concerning for a user.
> ENT-5090: Removed (USE AT YOUR OWN RISK) from cf-key help menu for -x (3.15)

- .travis.yml
Mac builds started failing without any changes in our code.
Most likely because of changes in one of the dependencies,
or the travis environment. Let's delay a while and see
if the issue is resolved automatically.
> Travis: Allow mac builds to fail until issue is resolved

- cf-agent/verify_files_utils.c
- libpromises/files_copy.c
- libpromises/files_copy.h
- tests/acceptance/10_files/02_maintain/004.cf
- tests/acceptance/10_files/02_maintain/005.cf
- tests/acceptance/10_files/02_maintain/006.cf
- tests/acceptance/10_files/copy_from_preserve_false.cf
@nickanderson wanted this cherry-picked.
There were some merge conflicts, as the new `safe_open_create_perms` function has not been backported to this version, as well as the `Attributes` parameter in `CfCopyFile` not being a pointer. I decided to keep the code improvements even though they are irrelevant to the functionality improvements.
> [3.12.x] ENT-4016: Fix copy_from overwriting permissions on destination file

- libpromises/cf3parse.y
RlistAppendScalar already calls `xstrdup`. Found by running
binaries (bootstrap) built with AddressSanitizer (ASAN) enabled.
> Fixed memory leak in handling of inline JSON in policy evaluation

- contrib/cf-remote/requirements.txt
paramiko 2.6.0 would not load openssh style private keys.
apache-libcloud is needed for cf-remote spawn.
Ticket: ENT-5320
> ENT-5320 Updated paramiko version and added apache-libcloud

- libpromises/cf3parse.y
RlistAppendScalar already calls `xstrdup`. Found by running
binaries (bootstrap) built with AddressSanitizer (ASAN) enabled.
> Fixed memory leak in handling of inline JSON in policy evaluation (3.15)

- libpromises/cf3parse.y
RlistAppendScalar already calls `xstrdup`. Found by running
binaries (bootstrap) built with AddressSanitizer (ASAN) enabled.
> Fixed memory leak in handling of inline JSON in policy evaluation (3.12)

- Makefile.am
- contrib/vagrant-ci/centos-6-x64/Makefile.am
We want it to be part of the tarballs so that './configure' works
on the unpacked tarball and it is possible to run the tests this
way when starting with the tarball.
> Add the new Vagrant-CI to 'dist'

- cf-check/Makefile.am
Needed for compiling with ASAN, using env vars. There are other/better ways of handling these things, but I copied the pattern from another of our Makefiles to at least make it more consistent (and make it work).
> Autotools: Pick up flags from environment when building cf-check

- cf-agent/verify_files_utils.c
- tests/acceptance/10_files/purge_reports_as_repaired.cf
Given a recursive file promise with purging enabled, the promise will
not be propagated as repaired if the target directory contains some
directory hierarchy that is removed by the promise. While the function
`PurgeLocalFiles` correctly keeps track of any failed attempts to remove
files from the target directory, it does not report the repaired promise
in case it removes files or directories from the target directory
successfully.
Fix the issue by properly updating the promise to PROMISE_RESULT_CHANGE
if puring either a directory or file successfully. Add an acceptance
test to verify behaviour.
Signed-off-by: Patrick Steinhardt <ps@pks.im>
> cf-agent: files: report purged dirs and files as repaired

- cf-agent/verify_files_utils.c
- tests/acceptance/10_files/purge_reports_as_repaired.cf
Given a recursive file promise with purging enabled, the promise will
not be propagated as repaired if the target directory contains some
directory hierarchy that is removed by the promise. While the function
`PurgeLocalFiles` correctly keeps track of any failed attempts to remove
files from the target directory, it does not report the repaired promise
in case it removes files or directories from the target directory
successfully.
Fix the issue by properly updating the promise to PROMISE_RESULT_CHANGE
if puring either a directory or file successfully. Add an acceptance
test to verify behaviour.
Ticket: CFE-3260
Signed-off-by: Patrick Steinhardt <ps@pks.im>
(cherry picked from commit 24fbbca3921d34e205342a303e74234870496ca5)
> CFE-3260/3.15.x:  cf-agent: files: report purged dirs and files as repaired

- cf-agent/verify_files_utils.c
- tests/acceptance/10_files/purge_reports_as_repaired.cf
Given a recursive file promise with purging enabled, the promise will
not be propagated as repaired if the target directory contains some
directory hierarchy that is removed by the promise. While the function
`PurgeLocalFiles` correctly keeps track of any failed attempts to remove
files from the target directory, it does not report the repaired promise
in case it removes files or directories from the target directory
successfully.
Fix the issue by properly updating the promise to PROMISE_RESULT_CHANGE
if puring either a directory or file successfully. Add an acceptance
test to verify behaviour.
Ticket: CFE-3260
Signed-off-by: Patrick Steinhardt <ps@pks.im>
(cherry picked from commit 24fbbca3921d34e205342a303e74234870496ca5)
> CFE-3260/3.12.x: cf-agent: files: report purged dirs and files as repaired

- libpromises/evalfunction.c
https://lgtm.com/rules/2165170567/
> Made classfiltercsv() fail properly on invalid class expression index

- .travis.yml
Mac builds started failing without any changes in our code.
Most likely because of changes in one of the dependencies,
or the travis environment. Let's delay a while and see
if the issue is resolved automatically.
(cherry picked from commit 828a73f52b580ef4b7f25b91f26df12b46c3b0ef)
> Travis: Allow mac builds to fail until issue is resolved (3.15)

- libpromises/cf3lex.l
- tests/acceptance/00_basics/macros/if.cf
A final PR for the version detection macros. In some cases you want to specify just one version, or versions before or after (exclusive);
```
@if maximum_version(3.15.999) # Ugly
@if before_version(3.16) # More readable
```
```
@if minimum_version(3.15.5)
@if after_version(3.15.4)
```
```
@if between_versions(3.15.0, 3.15.0) # Ugly
@if at_version(3.15.0) # More readable
```
I guess the last one missing is `not_version` (inverse of `at`), but I don't really see a case where it's useful, and you can acheive it using `at_version` + `else`.
> CFE-3198: Added macros before_version, at_version and after_version

- contrib/cf-remote/cf_remote/packages.py
- contrib/cf-remote/cf_remote/remote.py
Tested on Ubuntu 18, Ubuntu 16, CentOS 7, CentOS 6
> cf-remote: Fixed package selection for new package names

- cf-check/diagnose.c
- cf-check/diagnose.h
Performs diagnosis and repair on symlink target instead of symlink.
Repaired files / copies are placed alongside symlink target.
In some cases, the symlink target is deleted to repair a corrupt
database, and the symlink is left as a broken symlink. This is
handled gracefully by the agent, it will be recreated. Broken
symlinks are now detected as an acceptable condition in diagnose,
it won't try to repair them or delete them.
> ENT-5162 cf-check: Symlinked LMDB databases are now preserved in repair

- libpromises/evalfunction.c
https://lgtm.com/rules/2165170567/
> Made classfiltercsv() fail properly on invalid class expression index (3.15)

- libpromises/cf3lex.l
- libutils/Makefile.am
- libutils/version_comparison.c
- libutils/version_comparison.h
- tests/acceptance/00_basics/macros/if.cf
- tests/unit/Makefile.am
- tests/unit/version_comparison_test.c
**Conflicts:** 
[Had to add `version_comparison` from libntech.](https://github.com/cfengine/core/pull/4066/commits/42dcf4c3c6e4ae2debcc7e3aa6c797c32f830875)
**Changes:**
Had to update the test, with numbers that make sense for 3.12.x. (See last commit).
**Cherry-picked from:**
https://github.com/cfengine/core/pull/4052
https://github.com/cfengine/core/pull/4055
https://github.com/cfengine/core/pull/4062
> Added macros: maximum_version, between_version, before_version, after_version, at_version (3.12)

- cf-check/diagnose.c
- cf-check/diagnose.h
Performs diagnosis and repair on symlink target instead of symlink.
Repaired files / copies are placed alongside symlink target.
In some cases, the symlink target is deleted to repair a corrupt
database, and the symlink is left as a broken symlink. This is
handled gracefully by the agent, it will be recreated. Broken
symlinks are now detected as an acceptable condition in diagnose,
it won't try to repair them or delete them.
> ENT-5162 cf-check: Symlinked LMDB databases are now preserved in repair (3.15)

- cf-check/diagnose.c
- cf-check/diagnose.h
Performs diagnosis and repair on symlink target instead of symlink.
Repaired files / copies are placed alongside symlink target.
In some cases, the symlink target is deleted to repair a corrupt
database, and the symlink is left as a broken symlink. This is
handled gracefully by the agent, it will be recreated. Broken
symlinks are now detected as an acceptable condition in diagnose,
it won't try to repair them or delete them.
> ENT-5162 cf-check: Symlinked LMDB databases are now preserved in repair (3.12)

- libcfnet/protocol_version.h
https://github.com/cfengine/core/pull/4071
https://github.com/cfengine/enterprise/pull/593
https://github.com/cfengine/nova/pull/1612
> ENT-4829: Enabled skipping CRLF termination of reporting lines

- cf-monitord/history.c
If a measurements promise regex doesn't match any line of a given
file, it should not produce an error logged to syslog. It's just
noise and the default value 0.0 of the measurement indicates that
nothing was measured. Running with '--verbose' then shows the log
message and helps with debugging.
Ticket: ENT-5171
Changelog: Measurements promises with no match no longer produce errors
> Do not log an error in case of no match for a measurements promise

- cf-monitord/history.c
If a measurements promise regex doesn't match any line of a given
file, it should not produce an error logged to syslog. It's just
noise and the default value 0.0 of the measurement indicates that
nothing was measured. Running with '--verbose' then shows the log
message and helps with debugging.
Ticket: ENT-5171
Changelog: Measurements promises with no match no longer produce errors
(cherry picked from commit 29c298e649da5f87107db3d7e61533064a961a89)
> ENT-5171/3.15.x: Do not log an error in case of no match for a measurements promise

- cf-monitord/history.c
If a measurements promise regex doesn't match any line of a given
file, it should not produce an error logged to syslog. It's just
noise and the default value 0.0 of the measurement indicates that
nothing was measured. Running with '--verbose' then shows the log
message and helps with debugging.
Ticket: ENT-5171
Changelog: Measurements promises with no match no longer produce errors
(cherry picked from commit 29c298e649da5f87107db3d7e61533064a961a89)
> ENT-5171/3.12.x: Do not log an error in case of no match for a measurements promise

- contrib/cf-remote/cf_remote/commands.py
- contrib/cf-remote/cf_remote/main.py
- contrib/cf-remote/cf_remote/spawn.py
- contrib/cf-remote/cf_remote/ssh.py
For me, when I try to use cf-remote spawn and then cf-remote install with the same "named" group/host things fail with paramiko saying "not a valid RSA private key". I believe this is due to the version of paramiko I am using does not understand my type of private key (not PEM). Newer paramiko would likely work fine: https://github.com/paramiko/paramiko/blob/master/paramiko/pkey.py#L286
So upgrading paramiko to 2.7.0 fixes the issue as well but I still think it is nice to try the "right" username first.
> Cfremote prefer cloud user

- libenv/unix_iface.c
Previously, when an interface had multiple IPv4 addresses set, the parsing of
these addresses would add the interface to the sys.interfaces and sys.hardware
variables multiple times, resulting in the interface showing up as a duplicate
in the list.
This fix makes sure that an interface is only added once for every interface
type, regardless of how many IPv4 addresses the interface contains.
Changelog: Fixed an issue causing duplicate entries in sys.interfaces, and
sys.hardware.
Ticket: CFE-3046
(cherry picked from commit 3f1bc9d2c97d760bbb31979516fe8afbd9a7b4cc)
> CFE-3046: Only add unique IPv4 and MAC addresses to sys interfaces (3.12)

- misc/systemd/cf-apache.service.in
- misc/systemd/cf-hub.service.in
During upgrades the services are started in random order and so
need a Requires= to force them to start in the proper order.
Ticket: ENT-5125
> Added cf-postgres requirement to cf-apache and cf-hub systemd units

- libpromises/item_lib.c
https://lgtm.com/rules/2158250570/
> Removed unsafe use of strcpy+strcat

- Makefile.am
- autogen.sh
- cf-check/Makefile.am
- tests/unit/Makefile.am
The CFEngine code used to get this right, but a couple of issues have crept in
at some point.
Although most people build in the same directory-tree location as the source,
GNU autotools offers the ability for these locations to differ.
This is particularly useful when wanting to develop and test parallel builds
from a shared source location, for instance using different platforms and/or
different "--with-foo" options.
A typical use would be the following parallel builds:
mkdir -p build/platform_1; cd build/platform_1; ../../autogen.sh
mkdir -p build/platform_2; cd build/platform_2; ../../autogen.sh
mkdir -p build/platform_3; cd build/platform_3; ../../autogen.sh
Subsequent development in the source can then be immediately tested
on those three platforms, in parallel, and with the previous …
> Fixed failure to build when source and build locations differ

- libenv/unix_iface.c
Currently the IPv6 address provided for an interface in the $(sys.inet6)
data is arbitrary if more than one address is bound to that interface.
Given that IPv6 requires all interfaces have a link-local address, this
is a common scenario.  Add a mechanism to GetProcFileInfo() to choose
between the previous and new entries if more than one is found for an
extracted key, and use this mechanism to rank link-local addresses below
others.
Also, the post-processing functions passed to GetProcFileInfo() have a
strange return value.  This is seemingly due to a misunderstanding with
how function pointer types relate to function definitions.  Clean this
up.
> Prefer routable IPv6 addresses over link-local

- travis-scripts/script.sh
It is debatable whether errorexit tests should be considered safe
or not, but errorlog should definitely be considered safe.
> CFE-3041 Travis: Run errorlog acceptance tests

- tests/acceptance/10_files/templating/mustache_no_end.error.cf
- tests/acceptance/testall
- travis-scripts/script.sh
Purpose is explained in testall script;
* `.x.cf` is for tests which are supposed exit with error,
for example, invalid policy syntax.
* `.error.cf` is for tests which are supposed to log errors,
but exit with 0. For example failed promises.
> CFE-3041: Added .error.cf possibility to acceptance tests (3.15)

- contrib/pgsql_RA
The following upstream commits:
ClusterLabs/resource-agents@a43075be72683e1d4ddab700ec16d667164d359c
ClusterLabs/resource-agents@5ab3339e8cb236583d375f5577f5a4dc129d5b27
added support for PostgreSQL 12 which uses a slightly different
mechanism for standby replica configuration and promotion. We
need those changes to support PostgreSQL 12 in CFEngine 3.15.x
and newer.
Ticket: ENT-5352
> Update the PostgreSQL HA resource agent to support PG 12

- configure.ac
It should not list them, they are listed in
libntech/configure.ac and have different AM_CONDITIONAL's
> configure.ac: Removed libntech automake files

- cf-agent/verify_services.c
- tests/acceptance/09_services/standard_services-from-non-default-namespace.cf
When no service_method was specified the standard_services services bundle
should be used. This default only worked if you were already in the default
namespace. This change makes sure that the standard_services method used is from
the default namespace and fixes the case where services promises are used from
non default namespaces expecting to leverage the standard_services
implementation.
> ENT-5406/3.12.x: Fixed selection of standard_services when used from non-default namespace

- cf-agent/verify_services.c
- tests/acceptance/09_services/standard_services-from-non-default-namespace.cf
When no service_method was specified the standard_services services bundle
should be used. This default only worked if you were already in the default
namespace. This change makes sure that the standard_services method used is from
the default namespace and fixes the case where services promises are used from
non default namespaces expecting to leverage the standard_services
implementation.
> ENT-5406/3.15.x: Fixed selection of standard_services when used from non-default namespace

- contrib/cf-remote/cf_remote/remote.py
The tags are in a list, not a dictionary.
> cf-remote: Fixed small issue when installing on windows

- libpromises/processes_select.c
This can happen if the CMD field is empty and filled with space, for
example in the case of zombie processes. Presumably the reason this
has passed before is because it would later result in a strndup call
with a negative size, which on most platforms would just mean the same
as zero. However, on AIX 7 this crashes instead, which is how the
issue was detected (split_process_line_test:test_platform_extra_table
test).
Changelog: Fix rare crashing bug when parsing zombie entries in ps
output. The problem was only ever observed on AIX, but could
theoretically happen on any platform depending on exact libc behavior.
Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>
note to cf-bottom:
https://github.com/cfengine/buildscripts/pull/705
> ENT-5329: Don't go back further than field start when parsing CMD field.

- misc/selinux/cfengine-enterprise.te
Discovered on a call-collected CentOS 8.1 host.
> SELinux fixes

- contrib/cf-remote/cf_remote/demo.py
When using --demo mode (without call collect), cf-hub will now
collect reports every minute instead of every 5 minutes.
> cf-remote: Added hub schedule to --demo (pull collect)

- cf-agent/cf-agent.c
This restriction blocks effective use as a development
environment on devices without a stable non-loopback
interface, such as a phone.
Ticket: CFE-3304
> CFE-3304 Removed restriction on bootstrap to loopback interface

- contrib/vagrant-ci/centos-6-x64/Makefile.am
The file is created by './autogen.sh' and 'make clean' should
only remove files created by './configure' and 'make'.
'make maintainer-clean' is the more thorough cleanup.
> Preserve contrib/vagrant-ci/centos-6-x64/Makefile.in on 'make clean'

- cf-agent/verify_users_pam.c
- tests/acceptance/17_users/unsafe/10_password_hash_is_not_cached.cf
- tests/acceptance/17_users/unsafe/20_modify_user_missing_secondary_group.cf
- tests/acceptance/17_users/unsafe/20_modify_user_secondary_groups.cf
- tests/acceptance/17_users/unsafe/user_queries.cf.sub
- tests/acceptance/dcs.cf.sub
- tests/acceptance/testall
Modify user promise secondary groups attribute handling to examine current state and set new state appropriately instead of clearing all secondary groups and then setting (workaround for SUSE issue).
TODO:
Ticket: ENT-3710
> ENT-3710 Improved management of secondary groups to avoid intermediary state failures

- cf-agent/verify_users_pam.c
- tests/acceptance/17_users/unsafe/10_password_hash_is_not_cached.cf
- tests/acceptance/17_users/unsafe/20_modify_user_missing_secondary_group.cf
- tests/acceptance/17_users/unsafe/20_modify_user_secondary_groups.cf
- tests/acceptance/17_users/unsafe/user_queries.cf.sub
- tests/acceptance/dcs.cf.sub
- tests/acceptance/testall
Modify user promise secondary groups attribute handling to examine current state and set new state appropriately instead of clearing all secondary groups and then setting (workaround for SUSE issue).
Cherry picked manually due to lots of conflicts in the C code.
Based on https://github.com/cfengine/core/pull/4126
> ENT-3710 Improved management of secondary groups to avoid intermediary state failures (3.15.x)

- misc/init.d/cfengine3.in
ENT-5528/master: Fixed service status cfengine3 on systemd managed hosts
Before change:
[root@host001 ~]# service cfengine3 status
Warning: PID file '/var/cfengine/cf-execd.pid' does not contain the right PID ('' != '5991'). Should restart CFEngine.
cf-execd is not running
Warning: PID file '/var/cfengine/cf-serverd.pid' does not contain the right PID ('' != '5992'). Should restart CFEngine.
cf-serverd is not running
Warning: PID file '/var/cfengine/cf-monitord.pid' does not contain the right PID ('' != '5993'). Should restart CFEngine.
cf-monitord is not running
[root@host001 ~]# ps aux | grep [c]f-
root      5991  0.0  3.1 137460  7648 ?        Ss   17:33   0:01 /var/cfengine/bin/cf-execd --no-fork
root      5992  0.0  6.0 239056 14468 ?        Ss   17:33   0:04 …
> ENT-5528/3.15.x: Fixed service status cfengine3 on systemd managed hosts

- libpromises/promises.c
- tests/acceptance/02_classes/01_basic/variable_class_expressions_with_if.cf
If a class context is specified in the policy or if 'ifvarclass'
constraint is used, the 'if' constraint should be evaluated as
well.
Ticket: CFE-2615
Changelog: 'if' constraint now works in combination with class contexts
> Evaluate 'if' even in case of class context or 'ifvarclass'

- tests/acceptance/00_basics/01_compiler/no_error_when_key_contains_space.x.cf
NOTE: This test is named with .x.cf suffix so that it will be run as part of CI
and start failing as soon as the bug is fixed.
Ticket: CFE-3320
----
#
> CFE-3320/master: Test that data containers keys can contain spaces

- libpromises/promises.c
- tests/acceptance/02_classes/01_basic/variable_class_expressions_with_if.cf
If a class context is specified in the policy or if 'ifvarclass'
constraint is used, the 'if' constraint should be evaluated as
well.
Ticket: CFE-2615
Changelog: 'if' constraint now works in combination with class contexts
(cherry picked from commit 6e1dd86e56cc977b587c92ac18b4a62bee61fdd3)
> [3.15.x] Evaluate 'if' even in case of class context or 'ifvarclass'

- libpromises/promises.c
- tests/acceptance/02_classes/01_basic/variable_class_expressions_with_if.cf
If a class context is specified in the policy or if 'ifvarclass'
constraint is used, the 'if' constraint should be evaluated as
well.
Ticket: CFE-2615
Changelog: 'if' constraint now works in combination with class contexts
(cherry picked from commit 6e1dd86e56cc977b587c92ac18b4a62bee61fdd3)
Conflicts:
libpromises/promises.c
> [3.12.x] Evaluate 'if' even in case of class context or 'ifvarclass'

- examples/storage-cifs.cf
https://github.com/cfengine/documentation/pull/2312
Ticket: CFE-3187
(cherry picked from commit f5ea3145f68b930e0e3e1ce15229ac7c8c0a0a63)
> CFE-3187/3.15.x: Added example illustrating use of cifs mount_type

- cf-agent/cf-agent.c
- cf-check/cf-check.c
- cf-execd/cf-execd.c
- cf-key/cf-key.c
- cf-monitord/cf-monitord.c
- cf-net/cf-net.c
- cf-promises/cf-promises.c
- cf-runagent/cf-runagent.c
- cf-serverd/cf-serverd-functions.c
- cf-testd/cf-testd.c
- configure.ac
- tests/acceptance/mock_package_manager.c
https://github.com/cfengine/core/pull/4190
https://github.com/cfengine/nova/pull/1676
> libntech bump and WriterWriteHelp()/ManPageWrite() backports

- tests/acceptance/Makefile.am
This is very similar in nature to pull request #3933 (see it for a fuller explanation).
Although most building is driven when the build tree is the same as the source tree, autotools fully supports the capability for these trees to be in different locations.
This patch corrects a particular issue with this.
I think an independent but related issue remains in "tests/acceptance/testall" in function "finish_xml" (currently near line 1125) with the use of "$XML" (two occurrences).  A fix on the existing code looks non-trivial, but that is because I think the code is not as clean as it should be.  If so, a clean-up of the code would greatly ease the fixing of that problem, but that is beyond the remit of this PR.
> Fix error when source and build locations differ.

- cf-secret/cf-secret.c
Attempt to read the next header after the last one fails because
the ParseHeader() function just reads until it hits the maximum
limit of characters to read or the key-value delimiter (':'). The
check for the end of the headers section of the file needs to be
done outside of this function, just like it is done in
ParseHeaders() which is part of the decryption process.
Ticket: CFE-3368
> Properly detect end of the headers section in 'cf-secret print-headers'

- libpromises/dbm_lmdb.c
Permissions will be 0600 as expected by MPF
cfe_internal/enterprise/CFE_knowledge.cf
Ticket: ENT-5986
merge with:
https://github.com/cfengine/masterfiles/pull/1768
> ENT-5986 LMDB files are now created with correct permissions

- cf-monitord/mon_io_linux.c
Latest libntech renamed TOSTRING to TO_STRING. Fix here accordingly and
clean the wrongly used "- 1" from the log expression.
https://github.com/cfengine/core/pull/4207
https://github.com/cfengine/nova/pull/1678
> libntech: Bumped to latest; rename TO_STRING macro

- examples/string_trim.cf
- libpromises/evalfunction.c
- tests/acceptance/01_vars/02_functions/string_trim.cf
- tests/acceptance/01_vars/02_functions/string_trim.cf.expected.json
The function will remove leading and trailing white spaces (including
newline) from the input string.
Added an example file and a simple acceptance test.
Ticket: CFE-3074
Signed-off-by: Lluis Campos <lluis.campos@northern.tech>
> CFE-3074: Added string_trim() policy function

- cf-agent/files_editxml.c
- cf-agent/verify_files_utils.c
- cf-check/dump.c
- cf-secret/cf-secret.c
- libpromises/cf3lex.l
- libpromises/cf3parse.y
- libpromises/syntax.c
Makes `make CFLAGS="-Wno-format-truncation -Werror"` work, at least on my Fedora system.
> Fixed problems highlighted by gcc warnings

- cf-agent/cf-agent.c
- cf-agent/files_editline.c
- cf-agent/nfs.c
- cf-agent/package_module.c
- cf-agent/retcode.c
- cf-agent/verify_packages.c
- cf-check/cf-check.c
- cf-check/dump.c
- cf-check/validate.c
- cf-execd/cf-execd.c
- cf-secret/cf-secret.c
- cf-testd/cf-testd.c
- libcfnet/conn_cache.c
- libcfnet/protocol.c
- libcfnet/protocol_version.c
- libcfnet/tls_generic.c
- libenv/sysinfo.c
- libpromises/class.c
- libpromises/dbm_api.c
- libpromises/eval_context.c
- libpromises/evalfunction.c
- libpromises/generic_agent.c
- libpromises/iteration.c
- libpromises/loading.c
- libpromises/mod_methods.c
- libpromises/policy.c
- libpromises/rlist.c
- libpromises/verify_vars.c
- tests/unit/logging_test.c
This has annoyed me for quite some time.
There are many reasons to do this:
* It's shorter, faster to type and read and causes less line-splitting
* Safe should be default anyway, unsafe functions should be marked as such
* Easier to remember (Is it StringSafeEqual or SafeStringEqual?)
https://github.com/cfengine/core/pull/4218
https://github.com/cfengine/enterprise/pull/621
https://github.com/cfengine/nova/pull/1680
> Renamed StringSafeEqual() to StringEqual()

- libenv/sysinfo.c
This header is very OS-specific and using the generic
'sys/sysctl.h' path causes a warning on modern GNU/Linux
distributions with modern GCC:
In file included from sysinfo.c:76:
/usr/include/sys/sysctl.h:21:2: error: #warning "The <sys/sysctl.h> header is deprecated and will be removed." [-Werror=cpp]
21 | #warning "The <sys/sysctl.h> header is deprecated and will be removed."
|  ^~~~~~~
> Include 'sysctl.h' as 'linux/sysctl.h' on Linux

- libpromises/verify_vars.c
Note that this may change behavior, I changed them to false,
because that's what makes sense to me, but previously they would
return `(bool) -1`, which is `1` / `true`.
> verify_vars.c: Removed -1 returns from bool function

- .lgtm/cpp-queries/missing-argument-null-check.ql
Using .findRootCause() was incorrect, since it returned
the whole macro definition line (`#define NULL ...`),
not just the macro's name. Looking for the NULL
MacroInvocation seems more straight forward and reliable.
Before changing this query, it had 4931 results.
After fixing it, the query returns 4502 results.
(Most results are true positives, and there are so many, because
each pointer access is counted, not each bad function or
parameter). Some functions have many pointer accesses,
where 1 NULL check would get rid of all the alerts.
Verified results manually for sequence.c file, which had 5
alerts before this fix. The fix removes the 3 false positives,
but leaves the 2 true positives.
Tested query locally using vscode extension: …
> LGTM: Fixed false positives in NULL check query

- cf-agent/nfs.c
- cf-agent/verify_storage.c
Intention of code seemed to be to track number of changes to fstab, and then
in the end, perform mounting if there were more than 1 change.
> storage promises managing nfs mounts should now correctly mount after editing fstab entries

- cf-agent/cf-agent.c
- cf-agent/files_editline.c
- cf-agent/nfs.c
- cf-agent/package_module.c
- cf-agent/retcode.c
- cf-agent/verify_packages.c
- cf-check/cf-check.c
- cf-check/dump.c
- cf-check/validate.c
- cf-execd/cf-execd.c
- cf-monitord/mon_io_linux.c
- cf-secret/cf-secret.c
- cf-testd/cf-testd.c
- libcfnet/conn_cache.c
- libcfnet/protocol.c
- libcfnet/protocol_version.c
- libcfnet/tls_generic.c
- libenv/sysinfo.c
- libpromises/class.c
- libpromises/dbm_api.c
- libpromises/eval_context.c
- libpromises/evalfunction.c
- libpromises/generic_agent.c
- libpromises/iteration.c
- libpromises/loading.c
- libpromises/mod_methods.c
- libpromises/policy.c
- libpromises/rlist.c
- libpromises/verify_vars.c
- tests/unit/logging_test.c
Backported commit:
a60798f53c0297277fe38c6e6b44952f29529b33
https://github.com/cfengine/core/pull/4231
https://github.com/cfengine/enterprise/pull/623
https://github.com/cfengine/nova/pull/1682
> Renamed StringSafeEqual() to StringEqual() (3.15)

- cf-agent/verify_files.c
- examples/files_content.cf
- examples/helloworld.cf
- libpromises/attributes.c
- libpromises/cf3.defs.h
- libpromises/mod_files.c
- tests/acceptance/10_files/08_field_edits/file_content.cf
- tests/acceptance/10_files/08_field_edits/file_content.error.cf
To allow a promise for the full contents of a file.
https://github.com/cfengine/documentation/pull/2327
> CFE-3276: Added files promise content attribute

- libpromises/locks.c
log_string in action bodies is no longer used in promise hashing.
Promise hashes are used to track a promise between agent runs,
so anything which changes every run (like time) should be excluded.
Log messages very commonly have timestamps, and our default from
standard library does.
> CFE-3376: Fixed locking of promises using log_repaired / log_string with timestamps

- ChangeLog
> ENT-5710/master: Stripped backticks that break documentation build

- cf-agent/files_editline.c
- tests/acceptance/10_files/09_insert_lines/017.cf
It may fail nicely or it may insert some unspecified content into
the file depending on the OS and FS used.
> Do not try to insert lines from a directory

- libpromises/locks.c
log_string in action bodies is no longer used in promise hashing.
Promise hashes are used to track a promise between agent runs,
so anything which changes every run (like time) should be excluded.
Log messages very commonly have timestamps, and our default from
standard library does.
Ticket: CFE-3376
Signed-off-by: Ole Herman Schumacher Elgesem <ole@northern.tech>
(cherry picked from commit a18ad4e92b50bc3d119f4cee3523dbb5f3e41694)
> [3.15.x] Fixed locking of promises using log_repaired / log_string with timestamps

- cf-agent/cf-agent.c
Reports generation only happens if there is exactly one
'cf-agent' process running (to avoid corruptions in the reporting
data). If some promise in the policy uses an action policy with
'background => true', there might still be a forked child process
evaluating the promise when the main process reaches the point
when it wants to generate reports. In such cases, it is important
that the main process waits for the forked child processes.
Ticket: ENT-6042
Changelog: Promises with 'action => bg()' no longer break reporting data
> Wait for background processes before generating reports

- tests/acceptance/17_users/unsafe/10_modify_user_with_many_attributes.cf
- tests/acceptance/17_users/unsafe/10_modify_user_with_many_attributes_warn.cf
Issue is that `usermod` on suse doesn't like editing seconday groups together
with any other attributes. In real life, this isn't a big issue - the promise
will be completely repaired on second run. However, this test failed.
This commit changes this behsvior to expect secondary group to *not* be set
after first promise run. When this get fixed, this commit should be reverted :)
merge together: https://github.com/cfengine/buildscripts/pull/760
> ENT-5335 add workarounds for tests failing on SUSE.

- cf-agent/files_changes.c
No need to write to the DB if there is no change and no need to
spam the output.
Ticket: CFE-3382
Changelog: Directory listings in files changes monitoring are now only updated when there is a change
> Only write directory listing if it changes

- contrib/cf-remote/cf_remote/commands.py
- contrib/cf-remote/cf_remote/spawn.py
Fixes error on my Ubuntu / WSL setup:
```
>>> os.getlogin()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory
>>> getpass.getuser()
'olehermanse'
```
See:
https://github.com/parmentelat/apssh/issues/1
> cf-remote: Replaced os.getlogin() with whoami()

- tests/acceptance/17_users/unsafe/10_modify_user_with_many_attributes.cf
- tests/acceptance/17_users/unsafe/10_modify_user_with_many_attributes_warn.cf
Issue is that `usermod` on suse doesn't like editing secondary groups together
with any other attributes. In real life, this isn't a big issue - the promise
will be completely repaired on second run. However, this test failed.
This commit changes this behavior to expect secondary group to *not* be set
after first promise run. When this get fixed, this commit should be reverted :)
(cherry picked from commit 3d36de3949c0e4a5a1e7e7d3b3fabc1d6b822801)
----
#
> ENT-5335 add workarounds for tests failing on SUSE - 3.12.x
