cfengine/core

tests/acceptance/17_users/unsafe/10_modify_user_with_many_attributes.cf
tests/acceptance/17_users/unsafe/10_modify_user_with_many_attributes_warn.cf

Issue is that `usermod` on suse doesn't like editing secondary groups together
with any other attributes. In real life, this isn't a big issue - the promise
will be completely repaired on second run. However, this test failed.
This commit changes this behavior to expect secondary group to *not* be set
after first promise run. When this get fixed, this commit should be reverted :)
(cherry picked from commit 3d36de3949c0e4a5a1e7e7d3b3fabc1d6b822801)
----
#

ENT-5335 add workarounds for tests failing on SUSE - 3.15.x

---

tests/acceptance/05_processes/01_matching/promiser_match_is_correct.cf

We spawn an agent process in a shell and then immediately check
that it is running. If it takes a bit to start (easy to happen on
a heavy-loaded machine running tests) the process is not
found. Let's give it a second to start before we try extracting
information about it.
(cherry picked from commit a623c13507d6d0620d11104f3c86dffedfcbdf66)
----
#

ENT-5719 Mitigate race condition in the promiser_match_is_correct.cf test - 3.12.x

---

misc/init.d/cfengine3.in
tests/acceptance/17_users/unsafe/10_modify_user_with_many_attributes.cf
tests/acceptance/17_users/unsafe/10_modify_user_with_many_attributes_warn.cf

fixes suse 12.
https://github.com/cfengine/buildscripts/pull/762

ENT-6098 fix init_script_test.sh failure of suse 12 and 15

---

libpromises/expand.c
tests/acceptance/01_vars/04_containers/pass_variable_container.cf
tests/acceptance/01_vars/04_containers/pass_variable_container.cf.expected
tests/unit/expand_test.c

TODO:
(not sure if the second step above is necessary/worth it)

Expand variables specifying data/list names in @() references

---

libpromises/expand.c
tests/acceptance/01_vars/04_containers/pass_variable_container.cf
tests/acceptance/01_vars/04_containers/pass_variable_container.cf.expected
tests/unit/expand_test.c

[3.12.x] Expand variables specifying data/list names in @() references

---

contrib/cf-remote/cf_remote/commands.py
contrib/cf-remote/cf_remote/main.py
contrib/cf-remote/cf_remote/remote.py
contrib/cf-remote/cf_remote/ssh.py

```
olehermanse@OH-WIN core $ cf-remote deploy --hub hub /northern.tech/cfengine/masterfiles
ubuntu@34.250.47.156
CFEngine      : 3.17.0a.ec47889f4 (Enterprise)
Copying: '/home/olehermanse/.cfengine/cf-remote/masterfiles.tgz' to 'ubuntu@34.250.47.156'
Running: 'systemctl stop cfengine3 && rm -rf /var/cfengine/masterfiles && mv masterfiles /var/cfengine/masterfiles && systemctl start cfengine3 && cf-agent -Kf update.cf && cf-agent -K'
```

CFE-3405 cf-remote: Added deploy command for deploying masterfiles

---

libpromises/cf3parse.y
tests/acceptance/04_examples/mock_stdlib.cf

Previously, bundles could be empty but bodies could not.
You could "trick" the parser by adding a class guard:
```
body package_method yum {any::}
```
That is no longer necessary, you can now do:
```
body package_method yum {}
```
This is useful for testing, or cases where you don't actually
care about the contents of the body.

CFEngine policy bodies can now be completely empty

---

.gitignore
cf-monitord/Makefile.am
cf-monitord/get_socket_info.c
cf-monitord/mon_network.c
cf-monitord/proc_net_parsing.c
cf-monitord/proc_net_parsing.h

Read socket info from /proc/net in cf-monitord

---

.gitignore
cf-monitord/Makefile.am
cf-monitord/get_socket_info.c
cf-monitord/mon_network.c
cf-monitord/proc_net_parsing.c
cf-monitord/proc_net_parsing.h

[3.15.x] Read socket info from /proc/net in cf-monitord

---

cf-agent/cf-agent.c

The exit blocked effective use in a development environment
without a stable non-loopback interface, such as a phone (android/termux).
(cherry picked from commit 5b00565454195b0b79f420c5abeca764b1476ff0)

CFE-3304: Removed restriction on bootstrap to loopback interface (3.15)

---

cf-serverd/server_classic.c
cf-serverd/server_common.c
cf-serverd/server_common.h
libcfnet/client_code.c
libcfnet/client_protocol.c
libcfnet/client_protocol.h
libcfnet/connection_info.c
libcfnet/tls_generic.c
libenv/sysinfo.c
libpromises/evalfunction.c
libpromises/lastseen.c
libpromises/lastseen.h
tests/static-check/run_checks.sh
travis-scripts/script.sh

All of the pointer sign ones are fixed. Some format truncation remaining, but they are not trivial.

CFE-3389 CFE-3409: Fixed compiler warnings for format truncation and pointer sign

---

libpromises/string_expressions.c
tests/acceptance/00_basics/01_compiler/no_error_when_key_contains_space.cf

Ticket: CFE-3320
Changelog: Spaces inside square brackets (slist/data index) are now allowed in class expressions

Allow spaces inside square brackets in class expressions

---

libpromises/string_expressions.c
tests/acceptance/00_basics/01_compiler/no_error_when_key_contains_space.cf

Ticket: CFE-3320
Changelog: Spaces inside square brackets (slist/data index) are now allowed in class expressions
(cherry picked from commit 53e21fdc713783dcc1690e5cbfbf54e9e2fb388e)

[3.12.x] Allow spaces inside square brackets in class expressions

---

libenv/sysinfo.c
libpromises/cf3.extern.h
libpromises/cf3globals.c
libpromises/expand.c
libpromises/verify_classes.c
tests/static-check/cppcheck_suppressions.txt
tests/unit/set_domainname_test.c

This is to make the truncation behavior consistent, since
fqhost is maximum 1023 characters. Thus, domain or host name
may in rare cases be truncated on their own, but fqhost will
never be truncated (compared to uqhost and domain).
Also introduced warning messages if you use host names or
domain names which are longer than 255 characters. The limit
for fqhost in DNS is 255 characters:
https://tools.ietf.org/html/rfc2181#section-11

CFE-3409: Limited unqualified host and domain name to 511 characters

---

libpromises/string_expressions.c
tests/acceptance/00_basics/01_compiler/no_error_when_key_contains_space.cf

Ticket: CFE-3320
Changelog: Spaces inside square brackets (slist/data index) are now allowed in class expressions
(cherry picked from commit 53e21fdc713783dcc1690e5cbfbf54e9e2fb388e)

[3.15.x] Allow spaces inside square brackets in class expressions

---

codecov.yaml

Since we have fluctuations in test coverage, codecov is
currently not useful, and in some cases creating extra noise in
PRs / diffs etc.
First attempt is to disable the status / PR interactions:
https://community.codecov.io/t/disable-all-intereactions-on-prs/1218/10
Then, we should still be able to go to codecov.io to see coverage info
but it won't create noise in PRs. If this doesn't work, I'll rip it all
out.

CFE-3410 Codecov: Disabled PR statuses

---

tests/static-check/run_checks.sh

Not too many exceptions were necessary, and we can work on
getting rid of those over time.

CFE-3414 static-check: Added -Wall and -Wextra flags

---

libcfnet/policy_server.c

I used StringCopy because it guarantees destination will be
terminated. strncpy does not.
https://lgtm.com/rules/2158250570/

Fixed unbounded write in policy_server.c

---

contrib/cf-remote/cf_remote/commands.py
contrib/cf-remote/cf_remote/main.py

Demo:
```
olehermanse@OHMBP core $ cf-remote list deb
Available releases: 3.16.0, 3.15.x, 3.15.2, 3.15.1, 3.15.0, 3.15.0b1, 3.12.x, 3.12.5, 3.12.4, 3.12.3, 3.12.2, 3.12.1, 3.12.0
Using 3.15.2 LTS (default):
https://cfengine-package-repos.s3.amazonaws.com/enterprise/Enterprise-3.15.2/hub/debian_7_x86_64/cfengine-nova-hub_3.15.2-1.debian7_amd64.deb
https://cfengine-package-repos.s3.amazonaws.com/enterprise/Enterprise-3.15.2/hub/debian_8_x86_64/cfengine-nova-hub_3.15.2-1.debian8_amd64.deb
https://cfengine-package-repos.s3.amazonaws.com/enterprise/Enterprise-3.15.2/hub/debian_9_x86_64/cfengine-nova-hub_3.15.2-1.debian9_amd64.deb
https://cfengine-package-repos.s3.amazonaws.com/enterprise/Enterprise-3.15.2/hub/debian_10_x86_64/cfengine-nova-hub_3.15.2-1.debian10_amd64.deb …
```

CFE-3424 cf-remote: Added new command to list available packages

---

libpromises/expand.c
libpromises/promises.c

Makes it a lot more clear to debug evaluation.
**Test policy:**
```
bundle agent __main__
{
vars:
(windows)::
"A" string => "a";
(windows.ubuntu)::
"B" string => "b";
}
```
**Output:**
```
verbose: V: BEGIN variables (pass 1)
debug: Skipping vars promise expansion with promiser 'A' due to class guard '(windows)::' (pass 1)
debug: Skipping vars promise expansion with promiser 'B' due to class guard '(windows.ubuntu)::' (pass 1)
verbose: V: .........................................................
verbose: V: BEGIN variables (pass 2)
debug: Skipping vars promise expansion with promiser 'A' due to class guard '(windows)::' (pass 2)
debug: Skipping vars promise expansion with promiser 'B' due to class guard '(windows.ubuntu)::' (pass 2)
verbose: V: …
```

Added debug message for promises skipped because of class guards

---

contrib/cf-remote/cf_remote/cloud_data.py

It's RHEL 8.2 and it already has the updated SELinux policy that
we require.
Ticket: ENT-6103

Use a newer version of RHEL 8 in 'cf-remote spawn'

---

docs/custom_promise_types/cfengine.py

Not in use yet, discovered while testing out promise modules.
Added necessary logging functions, and log levels to assertion.
Fixed result for repaired promises.

CFE-3390: Small fixes to CFEngine promise module library

---

misc/selinux/cfengine-enterprise.te

These rules should not be needed because only processes forked
from the agent should access the folder, but pre-evaluation
causes all our processes accessing the folder.
Ticket: CFE-3240
Changelog: AVCs are no longer produced for CFEngine processes accessing /proc/net
(cherry picked from commit a4f3aae826bc584eec799fc8804dd5988b463c97)

[3.15.x] Add SELinux rules for accessing /proc/xen

---

misc/selinux/cfengine-enterprise.te

These rules should not be needed because only processes forked
from the agent should access the folder, but pre-evaluation
causes all our processes accessing the folder.
Ticket: CFE-3240
Changelog: AVCs are no longer produced for CFEngine processes accessing /proc/net
(cherry picked from commit a4f3aae826bc584eec799fc8804dd5988b463c97)

[3.12.x] Add SELinux rules for accessing /proc/xen

---

cf-agent/cf-agent.c
libpromises/Makefile.am
libpromises/cf3lex.l
libpromises/cf3parse.y
libpromises/cf3parse_logic.h
libpromises/mod_common.c
libpromises/mod_custom.c
libpromises/mod_custom.h
libpromises/parser_helpers.h
libpromises/policy.c
libpromises/policy.h
libpromises/syntax.c

**Epic:**
https://tracker.mender.io/browse/CFE-1939
**This task: (First mergeable iteration of promise modules)**
https://tracker.mender.io/browse/CFE-3390
**Specification:**
https://github.com/cfengine/core/blob/master/docs/custom_promise_types/modules.md
https://github.com/cfengine/core/pull/4271
**TODO before first merge:**
**TODO in future PRs:**
- Implement common attributes (if, unless, action, meta)
- Define variables and classes from modules
- Keep module running for entire agent run instead of spawning per promise

CFE-3390: Custom Promise Types

---

contrib/cf-remote/cf_remote/remote.py

cf-remote was picking SUSE rpms on RHEL machines, because
it was missing the extra tags we added for CentOS.

CFE-3445: cf-remote: Fixed package selection on RHEL

---

cf-agent/package_module.c
cf-agent/verify_new_packages.c
cf-agent/verify_new_packages.h
cf-agent/verify_packages.c
libpromises/eval_context.c

Just move the cfPS() calls into the HandleNewPackagePromiseType()
function instead of passing things back and forth for no good
reason.
Also change some of the log messages to be in sync with other log
messages produced by an agent run.
Ticket: ENT-5291

Properly inform about changes in the new 'packages' promise

---

contrib/cf-remote/cf_remote/commands.py
contrib/cf-remote/cf_remote/main.py
contrib/cf-remote/cf_remote/utils.py
contrib/cf-remote/cf_remote/web.py

For example:
```
$ cf-remote install --hub hub --bootstrap hub --package 'http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5735/PACKAGES_HUB_x86_64_linux_ubuntu_16/cfengine-nova-hub_3.17.0a.e29846823~11116.ubuntu16_amd64.deb' --demo
Downloading package: '/home/olehermanse/.cfengine/cf-remote/packages/url_specified/cfengine-nova-hub_3.17.0a.e29846823~11116.ubuntu16_amd64.deb'
ubuntu@18.202.174.100
CFEngine      : Not installed
Copying: '/home/olehermanse/.cfengine/cf-remote/packages/url_specified/cfengine-nova-hub_3.17.0a.e29846823~11116.ubuntu16_amd64.deb' to 'ubuntu@18.202.174.100'
Installing: 'cfengine-nova-hub_3.17.0a.e29846823~11116.ubuntu16_amd64.deb' on …
```

CFE-3453 cf-remote: packages can now be specified with URLs

---

libpromises/lastseen.c
libpromises/lastseen.h
tests/unit/lastseen_test.c

Logical counterpart to Adress2Hostkey.
Ticket: ENT-6181

Add a function for getting IP address for hostkey from LMDB

---

cf-agent/verify_users_pam.c

Found by running valgrind agent run on a demo hub.
(cherry picked from commit 571d28089833675065f5a9e2df61805bf7cb76ba)

Fixed memory leak in users promises (3.15)

---

contrib/cf-remote/cf_remote/commands.py
contrib/cf-remote/cf_remote/remote.py

To speed things up.
Ticket: CFE-3003
Changelog: cf-remote now installs CFEngine to hosts in parallel

Install CFEngine to hosts in parallel

---

tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/defaults.cf

(cherry picked from commit 1a55637153bd2989775262f14e047b810c01af89)
----
#

ENT-6200 Disable flaky test on whole Solaris and older suse, also - 3.12.x

---

tests/acceptance/00_basics/ifelapsed_and_expireafter/timed/defaults.cf

(cherry picked from commit 1a55637153bd2989775262f14e047b810c01af89)
----
#

ENT-6200 Disable flaky test on whole Solaris and older suse, also - 3.15.x

---

cf-agent/verify_packages.c

Changed here:
https://github.com/cfengine/core/commit/47223e7112243b183cb7a14aa8e0ecd2729720e6#diff-2c933bcbb521c8e7dae80f608cfd69e5a1657354a13c94874525de66cd1bdfe1R198
Causes failures in deployment tests.
Big thanks to @craigcomstock for the forensics.

ENT-6383: Reverted log level change for old package promises

---

contrib/cf-remote/cf_remote/commands.py
contrib/cf-remote/cf_remote/main.py
contrib/cf-remote/cf_remote/remote.py

Added `--remote-download` argument to the cf-remote that enables to download packages directly to the target machine with curl

CFE-3464: Added `--remote-download` argument to cf-remote

---

tests/acceptance/01_vars/02_functions/not.cf

Backported test from master, had to use strcmp() to get correct
return type, since 3.15.x doesn't have the changed return type
for not().
(cherry picked from commit 7af98c413c0ca5102a0a678bcaa8c219236e88df)

CFE-3470: Added acceptance test for not() (3.15)

---

tests/acceptance/01_vars/02_functions/not.cf

Clean cherry-pick from 3.15.x version, included both SHAs below,
for reference.
(cherry picked from commit 7af98c413c0ca5102a0a678bcaa8c219236e88df)
(cherry picked from commit 921d4a9c95166a0b7198eff70d068fd61f83b94a)

CFE-3470: Added acceptance test for not() (3.12)

---

tests/acceptance/01_vars/02_functions/or.cf

Backported test from master, had to use strcmp() to get correct
return type, since 3.15.x doesn't have the changed return type
for or().
(cherry picked from commit 324840cc640bfec72d35308914f462a70be9790b)

CFE-3471: Extensive test of or() function (3.15)

---

tests/acceptance/01_vars/02_functions/or.cf

Clean cherry-pick from 3.15.x version, inclued both SHAs below,
for reference.
(cherry picked from commit 324840cc640bfec72d35308914f462a70be9790b)
(cherry picked from commit 43a8b0ca1203d0aec6efa88398d72b2a3c1a9b86)

CFE-3471: Extensive test of or() function (3.12)

---

tests/static-check/run.sh

Freshly released with newer versions of compilers and static
checkers.

Use Fedora 33 as the base image for static checks

---

contrib/cf-remote/cf_remote/commands.py
contrib/cf-remote/cf_remote/remote.py

```
olehermanse@OH-WIN core $ cf-remote install --hub hub --bootstrap hub --demo --remote-download --package "https://example.com/blahblah.deb"
ubuntu@34.245.14.146
CFEngine      : Not installed
Downloading 'https://example.com/blahblah.deb' on 'ubuntu@34.245.14.146' using curl
Encountered a bad command exit code!
Command: 'curl --fail -O https://example.com/blahblah.deb'
Exit code: 22
Stdout:
Stderr:
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0 …
```

CFE-3488 cf-remote: More clear failure when --remote-download encounters 404 and similar errors

---

tests/acceptance/00_basics/ifelapsed_and_expireafter/locks.cf
tests/acceptance/00_basics/ifelapsed_and_expireafter/locks.cf.sub

Goal is to merge this test and let it run in CI for a while (a week?) and hope that the new test fails on solaris sparc at some point, or that the test passes in a run where the original redmine test fails.

ENT-6205 add ifelapsed locks test without abort

---

cf-agent/verify_files_utils.c

When cf-agent encounters SETUID files that are not present in the setuid log
file ( $(sys.workdir)/cfagent.$(sys.fqhost).log ) a WARNING is emitted. Until
now the promise result was also updated in a way making the promise seem to be
not kept. This change removes the updating of the promise result so that the
real promise outcome is un-altered. The warning will still be emitted and the
file will be added to the log if it is not already there.
Ticket: ENT-6519

ENT-6519/master: Stopped updating files promise result with WARN (notkept) when setuid files are encountered

---

contrib/cf-remote/cf_remote/commands.py
contrib/cf-remote/cf_remote/main.py

So that new VMs can be added to an existing group of VMs which
allows creation of big groups of VMs in batches (e.g. to avoid
rate limits on cloud APIs).
Ticket: CFE-3502
Changelog: 'cf-remote spawn' now supports adding new VMs to an existing group

Add the '--append' option to 'cf-remote spawn'

---

contrib/cf-remote/cf_remote/commands.py
contrib/cf-remote/cf_remote/spawn.py

Instead of getting a fresh list for every VM being
destroyed to speed things up.

Only list all nodes once in 'cf-remote destroy'

---

tests/acceptance/29_simulate_mode/diff_mode.cf
tests/acceptance/29_simulate_mode/manifest_mode.cf

Because they were both failing and causing test.xml file unreadable

ENT-6569 Exclude RHEL5 from diff_mode.cf and manifest_mode.cf tests

---

cf-agent/cf-agent.c
libpromises/cf3parse.y
libpromises/cf3parse_logic.h
libpromises/mod_custom.c
libpromises/mod_custom.h
libpromises/policy.c
libpromises/syntax.c
libpromises/syntax.h
tests/acceptance/30_custom_promise_types/04_unknown_promise_type.error.cf
tests/unit/data/bundle_custom_promise_type.cf
tests/unit/data/bundle_invalid_promise_type.cf
tests/unit/parser_test.c

Since inputs are parsed one by one, and then merged later,
there is no way to know when parsing a file whether a promise
type has already been declared. Thus we must assume that
anything which is not a built in promise type, is a custom
promise type and perform error checking later.

CFE-3510: Custom promise types can now be declared in separate files

---

libpromises/evalfunction.c

Fixed vulnerabillity where malformed input could trigger buffer overflow in
policy function format.
Ticket: CFE-3525

CFE-3525: Fixed buffer overflow vulnerabillity in policy function format()

---

libpromises/evalfunction.c

Fixed vulnerabillity where malformed input could trigger buffer overflow in
policy function format.
Ticket: CFE-3525
(cherry picked from commit 3fb57366017715f0b91031909350fed9b07d3224)

CFE-3525: Fixed buffer overflow vulnerabillity in policy function format() (3.15.x)

---

libpromises/evalfunction.c

Fixed vulnerabillity where malformed input could trigger buffer overflow in
policy function format.
Ticket: CFE-3525
(cherry picked from commit 3fb57366017715f0b91031909350fed9b07d3224)

CFE-3525: Fixed buffer overflow vulnerabillity in policy function format() (3.12.x)

---

docs/custom_promise_types/gpg.py
docs/custom_promise_types/password-store-sync.cf

Use a directory of .asc (public key) and .fp (fingerprint) files
to ensure gpg keys are up to date.
```
gpg_keys:
"/home/user/.gnupg"
keydir => "/home/user/.password-store/.pub-keys";
```
Ticket: CFE-3519

CFE-3519 Added gpg_keys promise type

---

cf-agent/verify_files.c

Promising the exact content of a file is an action.
Ticket: CFE-3507
Changelog: "No action for file" warning is no longer triggered when only 'content => "something"' is used

Do not report no action for 'content => "something"' in files promises

---

cf-agent/cf-agent.c
cf-agent/simulate_mode.c
cf-agent/simulate_mode.h
cf-agent/verify_files.c
cf-agent/verify_files_utils.c
libpromises/cf3.extern.h
libpromises/changes_chroot.c
libpromises/changes_chroot.h
libpromises/eval_context.h
libpromises/fncall.c
tests/acceptance/29_simulate_mode/manifest_full_mode.cf
tests/acceptance/29_simulate_mode/manifest_full_mode.cf.expected

New simulation mode that manifests all changed files as well as
all other files evaluated by the agent run which were not skipped
(by file selection rules).
Ticket: CFE-3506

Added a new --simulate=manifest-full mode

---

cf-agent/simulate_mode.c
libpromises/changes_chroot.c
tests/acceptance/29_simulate_mode/diff_mode.cf
tests/acceptance/29_simulate_mode/manifest_full_mode.cf
tests/acceptance/29_simulate_mode/manifest_mode.cf

As the file says::
* INCLUDE THIS HEADER ALWAYS FIRST in order to define appropriate macros for
* including system headers (such as _FILE_OFFSET_BITS).
_FILE_OFFSET_BITS (and others) determine offsets of fields in
various structures that we use, for example 'struct
dirent'. Accessing fields at wrong offsets means we get garbage
data.
Ticket: ENT-6537

Include <platform.h> early in simulate_mode.c

---

cf-agent/verify_files_utils.c

ENT-6750/master: Stopped emitting warning and recording result when observing new SETGID files

---

cf-agent/verify_new_packages.c

For other promise types, promises skipped due to locking only
result in 'debug' log messages being emitted and cfPS() is not
called. There's no reason why 'packages' promises should behave
differently.
Ticket: ENT-6553
Changelog: Reduced the noise caused by packages promises being skipped in evaluation passes 2 and 3

Do not record 'packages' promises skipped due to locking

---

.travis.yml

Failing Mac builds have caused master to be red for some days.
This seems to be because Travis changed the installed packages
on their default image. Since we are already testing MacOS
on GitHub Actions, and they are much faster and more reliable,
I don't see a point in fixing the travis build, so I disabled it.

Travis: Disabled MacOS

---

.travis.yml

Failing Mac builds have caused master to be red for some days.
This seems to be because Travis changed the installed packages
on their default image. Since we are already testing MacOS
on GitHub Actions, and they are much faster and more reliable,
I don't see a point in fixing the travis build, so I disabled it.
Had to resolve conflicts since this was already an allowed
failure on 3.15.x (but not on master).
(cherry picked from commit 1539824f12107a18652c4ce8a995f5fb269b6c7f)

Travis: Disabled MacOS (3.12)

---

.travis.yml

Failing Mac builds have caused master to be red for some days.
This seems to be because Travis changed the installed packages
on their default image. Since we are already testing MacOS
on GitHub Actions, and they are much faster and more reliable,
I don't see a point in fixing the travis build, so I disabled it.
Had to resolve conflicts since this was already an allowed
failure on 3.15.x (but not on master).
(cherry picked from commit 1539824f12107a18652c4ce8a995f5fb269b6c7f)

Travis: Disabled MacOS (3.15)

---

docs/custom_promise_types/cfengine.py

Promise module python library now handles all exception classes and additionally logs the exception type followed by the message. This way we at least get a hint in case of an assertion error without any message.

CFE-3573: Assertion error no longer logs empty error msg

---

misc/selinux/cfengine-enterprise.te

Discovered while working on ENT-6735.

SELinux: Allow cf-serverd getattr on cfengine_log_t:lnk_file

---

cf-execd/cf-execd-runagent.c

Otherwise LGTM complains that write() return value is ignored and
if it's only asserted, it complains it's unused in non-debug
builds.

Assert results from write() in cf-execd/cf-execd-runagent.c with NDEBUG_UNUSED

---

libpromises/acl_tools_posix.c

Otherwise this confusing error message is logged:
Failed to get UID for user 'cfapache': Success

Do not print error if there was no error in AllowAccessForUsers()

---

contrib/pgsql_RA

The PostgreSQL resource agent we provide supports both RHEL 6 and
7, but RHEL 6 is EOL and we encourage users to use RHEL 7 for
their HA setups so we should not confuse them in the comment.
Ticket: ENT-6825

Change comment in the pgsql_RA to mention RHEL 7 not 6

---

libpromises/policy.c

'extra_hashes' is a StringMap which means the actual hash map is
in its 'impl' field.

Fix iteration over the 'extra_hashes' map in PolicyMerge

---

cf-agent/cf-agent.c
cf-agent/files_editline.c
cf-agent/files_editxml.c
cf-agent/retcode.c
cf-monitord/env_monitor.c
cf-serverd/server_transform.c
libpromises/attributes.c
libpromises/eval_context.c
libpromises/expand.c
libpromises/instrumentation.c
libpromises/locks.c
libpromises/mod_custom.c
libpromises/ornaments.c
libpromises/policy.c
libpromises/policy.h
libpromises/promises.c
libpromises/verify_vars.c

Custom promise modules can potentially implement multiple promise types so they need to know the type of the promise they are asked to validate or evaluate.

Send promise type to custom promise modules

---

configure.ac

Avahi support is broken and we need to have a way to disable
Avahi support even if the headers are available in the system.

Disable Avahi support by default and add a way to enable it

---

cf-serverd/cf-serverd-functions.c
configure.ac

This PR is base on the systemd one https://github.com/cfengine/core/pull/4499 because it uses the same autotools option for systemd.

CFE-3581: Graceful restart option

---

libenv/sysinfo.c
tests/acceptance/02_classes/01_basic/expected_os_classes.cf

Expected class `suse` was not defined on SUSE 15 _(see [CFE-3608](https://tracker.mender.io/browse/CFE-3608))_. This PR makes sure `suse` is defined and also tests that all other supported OS'es has their expected os-classes are defined.

CFE-3569: Make sure hard class suse is defined on SUSE

---

configure.ac
examples/variablesmatching.cf
libenv/sysinfo.c

This way we can propagate the environment variable to C
sources. If there is no such environment variable, or the value
is empty, we default to "1".
Ticket: ENT-5348
merge together
https://github.com/cfengine/masterfiles/pull/1944
https://github.com/cfengine/core/pull/4548

ENT-5348 Define 'RELEASE' macro based on the $RELEASE environment variable (3.12.x)

---

libenv/sysinfo.c
tests/acceptance/02_classes/01_basic/expected_os_classes.cf

Ticket: CFE-3569
(cherry picked from commit 2d0c678df5b9b64e792ad6b96ff14e9efcb45fac)

CFE-3569: Make sure hard class suse is defined on SUSE (3.12.x)

---

libenv/sysinfo.c
tests/acceptance/02_classes/01_basic/expected_os_classes.cf

Ticket: CFE-3569
(cherry picked from commit 2d0c678df5b9b64e792ad6b96ff14e9efcb45fac)

CFE-3569: Make sure hard class suse is defined on SUSE (3.15.x)

---

libpromises/eval_context.c

Output string was changed from:
`"class names [...]"`
to:
`"class expressions [...]"`
Ticket: CFE-3560

Changed log message about whitespace in class expressions to be error

---

tests/acceptance/01_vars/01_basic/os_name_human_not_unknown.cf

Test that sys.os_name_human does not resolve to unknown _(see [CFE-3569](https://tracker.mender.io/browse/CFE-3569))_.

CFE-3569: sys.os_name_human not Unknown

---

tests/acceptance/17_users/unsafe/user_queries.cf.sub

Issue was that since recently, it changed from 1 (like on RHEL) to 2 (like on
other Linuxes).
(cherry picked from commit e54da26fb0dbfb46816779ac7cc6acfab36106ec)
----
#

ENT-6975 update 'bin' gid for suse 15 in tests - 3.12.x

---

tests/acceptance/17_users/unsafe/user_queries.cf.sub

Issue was that since recently, it changed from 1 (like on RHEL) to 2 (like on
other Linuxes).
(cherry picked from commit e54da26fb0dbfb46816779ac7cc6acfab36106ec)
----
#

ENT-6975 update 'bin' gid for suse 15 in tests. - 3.15.x

---

tests/valgrind-check/valgrind.sh
travis-scripts/valgrind.sh

Recently a measurement tracking entropy available was added to the MPF. The
measurement causes cf-check dump to emit an error when dumping the
nova_static.lmdb database which in turn causes the Valigrind check to fail.
cf-check dump ./nova_static.lmdb
{
"available_entropy/proc/sys/kernel/random/entropy_avail": "
Error: This database contains unknown binary data - use --simple to print anyway
This change filters lines including "This database contains unknown binary data"
from consideration as an error by the Valgrind check.
Ticket: ENT-6626

ENT-6626: Filtered error about unknown binary data from Valgrind test for cf-check dump (master)

---

cf-agent/verify_files_utils.c

In versions before 3.12.0 it was not possible to suppress errors generated from
promises to copy remote files that did not exist. Because of this limitation,
this specific log message was moved from ERROR to INFO as it could generate many
logs that were impossible to avoid, whereas INFO log messages are not always
emitted, especially by regularly scheduled runs.
Version 3.12.0 introduced the missing_ok attribute which allows for clients to
avoid considering a missing remote file as an error.
This change restores the log level for the message to ERROR. Users should
instrument their policy with missing_ok if they are promising copies of files
that may not exist.
Ticket: ENT-5879
Changelog: Restored log level for failure to state remote files without missing_ok to ERROR

ENT-5879: Fixed log level for failure to stat remote files without missing_ok (3.15)

---

libpromises/mod_custom.c
libpromises/policy.c
tests/acceptance/30_custom_promise_types/08_slist_attrs.cf
tests/acceptance/30_custom_promise_types/multiline_insert.py

Just pass the slists as JSON arrays with strings.
Ticket: CFE-3444
Changelog: Custom promise modules using JSON protocol now support slist attributes
TODO:

Support slist attributes with custom promise modules using JSON protocol

---

cf-agent/verify_files_utils.c

In versions before 3.12.0 it was not possible to suppress errors generated from
promises to copy remote files that did not exist. Because of this limitation,
this specific log message was moved from ERROR to INFO as it could generate many
logs that were impossible to avoid, whereas INFO log messages are not always
emitted, especially by regularly scheduled runs.
Version 3.12.0 introduced the missing_ok attribute which allows for clients to
avoid considering a missing remote file as an error.
This change restores the log level for the message to ERROR. Users should
instrument their policy with missing_ok if they are promising copies of files
that may not exist.
Ticket: ENT-5879
Changelog: Restored log level for failure to state remote files without missing_ok to ERROR
(cherry picked from …

ENT-5879: Fixed log level for failure to stat remote files without missing_ok (3.12)

---

tests/acceptance/Makefile.am
tests/acceptance/README
tests/acceptance/selftest.sh
tests/acceptance/selftest/fail.cf
tests/acceptance/selftest/flaky_fail.cf
tests/acceptance/selftest/flaky_pass.cf
tests/acceptance/selftest/pass.cf
tests/acceptance/selftest/skipped.cf
tests/acceptance/selftest/soft.cf
tests/acceptance/testall

If a tests/acceptance test outputs FLAKEY, testall
will consider it a flakey failure and not fail the
test run.
Ticket: ENT-6935

ENT-6935 Added flakey test result handling to testall

---

tests/acceptance/Makefile.am

Getting this selftest working in CI is proving difficult.
Remove for now in preference for green builds.
Ticket: ENT-6935

ENT-6935 Disable testall selftest

---

libpromises/eval_context.c

Output string was changed from:
`"class names [...]"`
to:
`"class expressions [...]"`
Ticket: CFE-3560
(cherry picked from commit eb9dd6c5d315d5a7daebc50610529f306ed56a04)

CFE-3560: Changed log message about whitespace in class expressions to be error (3.15.x)

---

tests/acceptance/01_vars/01_basic/this_promiser_ifvarclass.cf

No functional change, only updating metadata to refer to ticket in jira instead of redmine.
This test is still soft failing.

CFE-2262: Update old test for this.promiser in ifvarclass (master)

---

tests/acceptance/dcs.cf.sub
tests/acceptance/selftest.sh
tests/acceptance/selftest/flakey_meta_fail.cf
tests/acceptance/selftest/flakey_meta_no_ticket.cf
tests/acceptance/selftest/soft_no_ticket.cf

Tests can now report FLAKEY or add test_flakey_fail meta promise similar to test_soft_fail.
In this way the test will report FLAKEY when failing, but Pass when passing.
Ticket: ENT-6947
merge after https://github.com/cfengine/core/pull/4565 is merged and rebased here

ENT-6947 Added FLAKEY/test_flakey_fail test result to acceptance test framework

---

libpromises/eval_context.c

Output string was changed from:
`"class names [...]"`
to:
`"class expressions [...]"`
Ticket: CFE-3560
(cherry picked from commit eb9dd6c5d315d5a7daebc50610529f306ed56a04)

CFE-3560: Changed log message about whitespace in class expressions to be error (3.12.x)

---

libenv/sysinfo.c
tests/acceptance/02_classes/01_basic/hp_ux_major.cf

Make sure hard class with OS- name & version major is defined on HP-UX. E.g. `hpux_10`, `hpux_11`. _(see [CFE-3609](https://tracker.mender.io/browse/CFE-3609))_

CFE-3609: Hard class with OS- name & version major on HP-UX

---

cf-agent/cf-agent.c
cf-agent/verify_files_utils.c
cf-agent/verify_files_utils.h

The SINGLE_COPY_CACHE is a helper structure to remember files
that were copied by the agent because they matched a regular
expression from the SINGLE_COPY_LIST ('files_single_copy' agent
control attribute). It should not be treated as a list of regular
expressions, it should be a list of simple strings (file
paths). And because ordering doesn't matter, it can be a set
which is optimized for fast presence checking.
Also make sure the structure is not leaked by the agent run.
Ticket: CFE-3621
Changelog: files_single_copy no longer treats paths of copied files as regular expressions

Change SINGLE_COPY_CACHE to be a StringSet

---

libenv/sysinfo.c
tests/acceptance/02_classes/01_basic/hp_ux_major.cf

Make sure hard class with OS- name & version major is defined on HP-UX.
Ticket: CFE-3609
(cherry picked from commit 701cbaf2a1e353a4f1a959dc03780052863e4524)

CFE-3609: Hard class with OS- name & version major on HP-UX (3.15.x)

---

libenv/sysinfo.c
tests/acceptance/02_classes/01_basic/hp_ux_major.cf

Make sure hard class with OS- name & version major is defined on HP-UX.
Ticket: CFE-3609
(cherry picked from commit 701cbaf2a1e353a4f1a959dc03780052863e4524)

CFE-3609: Hard class with OS- name & version major on HP-UX (3.12.x)

---

tests/acceptance/dcs.cf.sub
tests/acceptance/selftest.sh
tests/acceptance/selftest/flakey_meta_fail.cf
tests/acceptance/selftest/flakey_meta_no_ticket.cf
tests/acceptance/selftest/soft_no_ticket.cf

If a tests/acceptance test outputs FLAKEY, testall
will consider it a flakey failure and not fail the
test run.
Ticket: ENT-6935
(cherry picked from commit 65db29137ece9d8cb183bbcd3cef6e8a99790f76)

ENT-6947 Added flakey test result handling to testall (3.15.x)

---

tests/acceptance/dcs.cf.sub
tests/acceptance/selftest.sh
tests/acceptance/selftest/flakey_meta_fail.cf
tests/acceptance/selftest/flakey_meta_no_ticket.cf
tests/acceptance/selftest/soft_no_ticket.cf

If a tests/acceptance test outputs FLAKEY, testall
will consider it a flakey failure and not fail the
test run.
Ticket: ENT-6935
(cherry picked from commit 65db29137ece9d8cb183bbcd3cef6e8a99790f76)

ENT-6947 Added flakey test result handling to testall (3.12.x)

---

cf-agent/cf-agent.c
cf-agent/files_changes.c
cf-agent/verify_files_utils.c
libpromises/generic_agent.c
libpromises/loading.c
tests/static-check/run_checks.sh

DefaultVarPromiseWrapper was created to silence
cast-function-type warning in ScheduleAgentOperations.
StrCmpWrapper can be found in libntech #128.
Ticket: CFE-3417

CFE-3417: Added DefaultVarPromise wrapper and used StrCmpWrapper in sequence fuctions

---

configure.ac

This message was useful to confirm that libntech is built
with debug options. I thought I might leave it in.

Added autoconf message for whether debug option is present

---

tests/acceptance/Makefile.am

It fails to compile there and it's not needed because we don't
run acceptance tests on Windows.
Also use the platform-based AM conditional, building test
binaries have nothing to do with us building builtin extensions
even though it happens to be in the same cases.
Ticket: CFE-3562

Do not build 30_custom_promise_types/custom_promise_binary.c on Windows

---

tests/acceptance/30_custom_promise_types/custom_promise_binary.c

The `getline` function is not well supported on exotic
platforms like solaris, hpux so change to small custom
function `eatline`.
Ticket: CFE-3562

CFE-3562 Refactor custom_promise_binary.c to be more portable

---

libpromises/pipes_unix.c

[3.15.x]  CFE-3625: Set Filedescriptor Limit to a more practical Size #4615 

---

libpromises/evalfunction.c
tests/acceptance/01_vars/02_functions/findfiles_up.cf
tests/acceptance/01_vars/02_functions/findfiles_up.cf.expected.json

Added policy function findfiles_up which finds files by looking for
matches of a glob while searching up the directory tree structure from a
given point.
This function returns a data container with the benefit of being able to
refrence position directly. E.g. `$(dc[0])`
Ticket: CFE-3577
merge together: [cfengine/libntech#136](https://github.com/cfengine/libntech/pull/136)

CFE-3577: Added policy function findfiles_up

---

libpromises/lastseen.c
libpromises/lastseen.h
tests/unit/lastseen_test.c

The lastseen local DB has entries of multiple types. In
particular, there are k-entries mapping hostkeys to IP addresses
and a-entries for the reverse mapping of IP addresses to
hostkeys. The ideal state is to have the entries of those two
types coherent (bijective), but it's not always possible. For
this reason, we need to be able to delete k-entries even if there
is no matching a-entry.
Do not require a-entries when deleting digests in
RemoveKeysFromLastSeen() if must_be_coherent is false.
Ticket: ENT-6490

ENT-6490: Add a new 'a_entry_required' parameter to DeleteDigestFromLastSeen()

---

libpromises/lastseen.c
libpromises/lastseen.h
tests/unit/lastseen_test.c

The lastseen local DB has entries of multiple types. In
particular, there are k-entries mapping hostkeys to IP addresses
and a-entries for the reverse mapping of IP addresses to
hostkeys. The ideal state is to have the entries of those two
types coherent (bijective), but it's not always possible. For
this reason, we need to be able to delete k-entries even if there
is no matching a-entry.
Do not require a-entries when deleting digests in
RemoveKeysFromLastSeen() if must_be_coherent is false.
Ticket: ENT-6490
(cherry picked from commit 93b778ca3aa60e130fc5d063dee9744d398a683d)

[3.15.x] Add a new 'a_entry_required' parameter to DeleteDigestFromLastSeen()

---

libpromises/lastseen.c
libpromises/lastseen.h
tests/unit/lastseen_test.c

The lastseen local DB has entries of multiple types. In
particular, there are k-entries mapping hostkeys to IP addresses
and a-entries for the reverse mapping of IP addresses to
hostkeys. The ideal state is to have the entries of those two
types coherent (bijective), but it's not always possible. For
this reason, we need to be able to delete k-entries even if there
is no matching a-entry.
Do not require a-entries when deleting digests in
RemoveKeysFromLastSeen() if must_be_coherent is false.
Ticket: ENT-6490
(cherry picked from commit 93b778ca3aa60e130fc5d063dee9744d398a683d)

[3.12.x] Add a new 'a_entry_required' parameter to DeleteDigestFromLastSeen()

---

libpromises/iteration.c
tests/static-check/run_checks.sh

As `upto` is `size_t` its impossible for it to be less than 0.
At the same time the current algorithm doesnt allow any
underflowing to occur since it uses `ref_str` as an anchor.
The lowest upto can go is 0 if the bracket is found at the start,
at which point all subsequent `memchr` will result in `NULL`.
Ticket: CFE-3418

CFE-3418: Fixed type-limits compiler warnings

---

libpromises/cmdb.c
libpromises/cmdb.h
libpromises/generic_agent.c

Host-specific values should take precedence over possibly more generic values from augments.

Protect classes and variables from CMDB data from being re-defined in augments

---

tests/unit/mon_processes_test.c

Issue was that even with current ±10% allowed spread of number of processes
enumerated by CFEngine vs `ps` this test was failing sometimes, with errors
like this:
> 27 is not within the range 21-26
(cherry picked from commit 2c90edf9678d825ea23a37353aa904797cbb71b1)

ENT-6941: Increased range of allowed values of number of processes (3.12)

---

tests/unit/mon_processes_test.c

Issue was that even with current ±10% allowed spread of number of processes
enumerated by CFEngine vs `ps` this test was failing sometimes, with errors
like this:
> 27 is not within the range 21-26
(cherry picked from commit 2c90edf9678d825ea23a37353aa904797cbb71b1)

ENT-6941: Increased range of allowed values of number of processes (3.15)

---

libpromises/evalfunction.c

Bad logic causes writing array out of bounds.
No need to backport, see ticket CFE-3675
Ticket: CFE-3675

CFE-3675: Bugfix in policy function `selectservers`

---

libpromises/eval_context.c
tests/acceptance/00_basics/04_bundles/non_default_def.cf

'def' is a pretty common name for a bundle and so using it
outside of the default namespace should be allowed. It doesn't
produce an error in PolicyCheckBundle() and referring to
variables from a 'def' bundle in a non-default namespace
should just work.
Ticket: CFE-3668
(cherry picked from commit cfb55d6dd4f5f26ca6a9b89b9b5afe630aad7646)

[3.15.x] Do not assert namespace is not specified for 'def.' variables

---

.github/workflows/asan_unit_tests.yml

These actions started failing with 404 messages sometimes, hope this helps.

Actions: Fix apt failures by running update

---

libpromises/class.c
libpromises/class.h
libpromises/cmdb.c
libpromises/eval_context.c
libpromises/eval_context.h
libpromises/generic_agent.c
libpromises/variable.c
libpromises/variable.h
libpromises/verify_classes.c
libpromises/verify_vars.c
tests/acceptance/00_basics/def.json/classes_with_ns_tags.cf
tests/acceptance/00_basics/def.json/classes_with_ns_tags.cf.json
tests/acceptance/00_basics/def.json/variables.cf
tests/acceptance/00_basics/def.json/variables.cf.json
tests/acceptance/01_vars/01_basic/vars_comments_emitted_in_show_vars.cf
tests/acceptance/01_vars/01_basic/vars_comments_emitted_in_show_vars.cf.sub
tests/acceptance/02_classes/01_basic/classes_comments_emitted_in_show_classes.cf
tests/acceptance/02_classes/01_basic/classes_comments_emitted_in_show_classes.cf.sub
tests/unit/class_test.c
tests/unit/variable_test.c

Associate comments with variables and classes

---

tests/acceptance/00_basics/ifelapsed_and_expireafter/redmine_6334.cf
tests/acceptance/05_processes/01_matching/inverse_ttime_inverse_found.cf

00_basics/ifelapsed_and_expireafter/locks.cf for solaris11sparc
00_basics/ifelapsed_and_expireafter/redmine_6334.cf for solaris11sparc
01_vars/01_basic/os_version_major.cf for centos5
05_processes/01_matching/inverse_ttime_inverse_found.cf for aix 7.1
Ticket: ENT-7048
(cherry picked from commit 001130f3facb2c6a0df331d05b2c745fbcc7cbc4)
Conflicts:
tests/acceptance/00_basics/ifelapsed_and_expireafter/locks.cf
tests/acceptance/01_vars/01_basic/os_version_major.cf

ENT-7048 Marked acceptance tests flakey for appropriate platforms (3.12.x)

---

tests/acceptance/00_basics/ifelapsed_and_expireafter/redmine_6334.cf
tests/acceptance/05_processes/01_matching/inverse_ttime_inverse_found.cf

00_basics/ifelapsed_and_expireafter/locks.cf for solaris11sparc
00_basics/ifelapsed_and_expireafter/redmine_6334.cf for solaris11sparc
01_vars/01_basic/os_version_major.cf for centos5
05_processes/01_matching/inverse_ttime_inverse_found.cf for aix 7.1
Ticket: ENT-7048
(cherry picked from commit 001130f3facb2c6a0df331d05b2c745fbcc7cbc4)
Conflicts:
tests/acceptance/00_basics/ifelapsed_and_expireafter/locks.cf
tests/acceptance/01_vars/01_basic/os_version_major.cf

ENT-7048 Marked acceptance tests flakey for appropriate platforms (3.15.x)

---

libpromises/cf3parse_logic.h
libpromises/syntax.c

The code for parsing custom promises assumed body type is always agent.
This is not the case, and here is why:
The parser calls `ParseError` when encountering a non-agent body type.
But the parser continues parsing until a limit of 13 errors have been
encountered. Thus one cannot assume the body type is always agent.
Instead we have to handle the cases when it's not.
Ticket: ENT-7099

ENT-7099: Fixed bad assertion parsing promise agent blocks

---

cf-execd/cf-execd-runagent.c
cf-execd/cf-execd-runagent.h
cf-execd/cf-execd.c
cf-execd/execd-config.c
cf-execd/execd-config.h

cf-execd should run cf-agent locally if 'localhost' (or a
localhost IP address) agent run is requested via the
runagent.socket.
Ticket: ENT-7090
Changelog: cf-execd now executes cf-agent for "localhost" requests via the runagent.socket

Run cf-agent for localhost requests on the runagent.socket

---

libpromises/policy.c
tests/acceptance/00_basics/04_bundles/unsupported_promise_types_in_common.x.cf

CFE-3672: Fixed crash when attempting to put methods promises in bundles which are not agent bundles

---

examples/complicated_cpu_bound_benchmark.cf

This makes the policy take around 1 second instead of 10 on my
machine. Users can always change this range, but having it
somewhat fast by default makes sense.

complicated_cpu_bound_benchmark.cf: Made default range lower to reduce runtime

---

libpromises/feature.c

So that some policy can be omitted on hosts that cannot load
host-specific data.

ENT-6789: Add a feature class for host-specific data loading

---

cf-agent/cf-agent.c
cf-execd/cf-execd.c
cf-key/cf-key.c
cf-monitord/cf-monitord.c
cf-promises/cf-promises.c
cf-runagent/cf-runagent.c
cf-serverd/cf-serverd-functions.c
cf-serverd/cf-serverd.c
libpromises/generic_agent.c
libpromises/generic_agent.h

As man:openlog(3) says:
The string pointed to by 'ident' is prepended to every message,
and is typically set to the program name.  If 'ident' is NULL,
the program name is used.  (POSIX.1-2008 does not specify the
behavior when ident is NULL.)
And of course not all systems we support are nice and use program
name if we pass NULL as the 'ident' argument.
Ticket: ENT-7100
Changelog: CFEngine processes are now properly identified in syslog on non-GNU/Linux systems
(cherry picked from commit 5147f4a93a87b4ba651c6f2c3fbe1853ad1b0a86)

[3.15.x] Make sure program name is used as identifier in syslog

---

misc/selinux/cfengine-enterprise.te

Backport of https://github.com/cfengine/core/pull/4698 and cfengine/core@8a61693 which wasn't backported before for some reason.

[3.15.x] SELinux fixes

---

libpromises/verify_classes.c
libpromises/verify_vars.c
tests/acceptance/01_vars/01_basic/vars_comments_emitted_in_verbose.cf
tests/acceptance/02_classes/01_basic/classes_comments_emitted_in_verbose.cf

Ticket: CFE-2442
Ticket: CFE-2443
Changelog: Verbose log now contains comments associated with 'vars' and 'classes' promises

Verbose-log comments associated with 'vars' and 'classes' promises

---

tests/acceptance/30_custom_promise_types/07_python_library.cf
tests/acceptance/30_custom_promise_types/08_slist_attrs.cf
tests/acceptance/30_custom_promise_types/09_log_level.cf
tests/acceptance/30_custom_promise_types/10_log_level_bad_module.cf
tests/acceptance/30_custom_promise_types/16_data_attrs.cf
tests/acceptance/30_custom_promise_types/17_early_module_failure.cf
tests/acceptance/30_custom_promise_types/18_early_module_failure_classes.cf

This allows us to change to version 3.5 more easily soon.

Changed python version check in promise module tests

---

libpromises/mod_custom.c
misc/custom_promise_types/cfengine.py

TL;DR of this PR is that error messages from promise modules now look like this:
```
error: Unknown attribute 'versionss' for git promise with promiser 'starter_pack_repo' (example.cf:11)
```

CFE-3683: Made filename and line number available to promise module

---

libpromises/dbm_quick.c
libpromises/dbm_tokyocab.c

With commit 032bda408 (Add a new function for overwriting a value in
local DB, 2020-05-27), a new function `DBPrivOverwrite()` has been
introduced with implementations for the various database backends. As it
turns out, both the implementation for qdbm and for tokyocabinet are
broken and don't compile out of the box: both use a different signature
compared to the declared one, and the tokyocabinet implementation uses
wrong variable names.
Fix both issues by adapting the implementations' function signatures and
by using the correct set of variables in case of tokyocabinet.

libpromises: Fix compilation of qdbm and tokycabinet backends

---

ChangeLog

The backticks cause the doc build to break unable to resolve the link to the
function.
Ticket: ENT-6692

ENT-6692: Fixed doc build (master)

---

libpromises/cmdb.c
libpromises/generic_agent.c
tests/acceptance/00_basics/def.json/variables_bare_array.cf
tests/acceptance/00_basics/def.json/variables_bare_array.cf.json
tests/acceptance/00_basics/def.json/variables_bare_string.cf
tests/acceptance/00_basics/def.json/variables_bare_string.cf.json

When discussing this feature, we mentioned that the new
format was only a problem/incompatibility for objects.
If the value is something like a string (or list)
the old structure "just works". This also means that
in the future, when 3.18.0+ is common, we can tell users
to just rename "vars" to "variables". As long as they
don't have any objects they don't have to make further
changes. This can be added as a warning, even.
Looking at our examples it seems quite common that
augments variables are strings or lists, and quite
rare that they are objects (data containers), so for
most users, they can just rename "vars" to "variables".
(With this change).
Without this change, the code crashes (abort assertion
error) if you try to do this.

Enabled non-object bare values inside augments variables key

---

.travis.yml
README.md

Removed 3.10.x and added 3.18.x branch builds to travis config
Adjusted badges
Ticket: ENT-6713

ENT-6713 Update badges and travis config for 3.18.0 release

---

tests/acceptance/00_basics/06_host_specific_data/01-vars.cf
tests/acceptance/00_basics/06_host_specific_data/01-vars.cf.json
tests/acceptance/00_basics/06_host_specific_data/01-vars.cf.sub
tests/acceptance/00_basics/06_host_specific_data/02-variables.cf
tests/acceptance/00_basics/06_host_specific_data/02-variables.cf.json
tests/acceptance/00_basics/06_host_specific_data/02-variables.cf.sub
tests/acceptance/00_basics/06_host_specific_data/03-variables-value.cf
tests/acceptance/00_basics/06_host_specific_data/03-variables-value.cf.json
tests/acceptance/00_basics/06_host_specific_data/03-variables-value.cf.sub
tests/acceptance/00_basics/06_host_specific_data/04-classes.cf
tests/acceptance/00_basics/06_host_specific_data/04-classes.cf.json
tests/acceptance/00_basics/06_host_specific_data/04-classes.cf.sub
tests/acceptance/00_basics/06_host_specific_data/05-variables-tag-comment.cf
tests/acceptance/00_basics/06_host_specific_data/05-variables-tag-comment.cf.json
tests/acceptance/00_basics/06_host_specific_data/06-classes-tag-comment.cf
tests/acceptance/00_basics/06_host_specific_data/06-classes-tag-comment.cf.json
tests/acceptance/00_basics/06_host_specific_data/07-invalid-data.cf
tests/acceptance/00_basics/06_host_specific_data/07-invalid-data.cf.json
tests/acceptance/00_basics/06_host_specific_data/08-class-expression.cf
tests/acceptance/00_basics/06_host_specific_data/08-class-expression.cf.json
tests/acceptance/00_basics/06_host_specific_data/09-class-reg-expression.cf
tests/acceptance/00_basics/06_host_specific_data/09-class-reg-expression.cf.json
tests/acceptance/00_basics/06_host_specific_data/10-variable-references.cf
tests/acceptance/00_basics/06_host_specific_data/10-variable-references.cf.json
tests/acceptance/00_basics/06_host_specific_data/11-augments-no-override.cf
tests/acceptance/00_basics/06_host_specific_data/11-augments-no-override.cf.def.json
tests/acceptance/00_basics/06_host_specific_data/11-augments-no-override.cf.json

Acceptance tests for host-specific data loading

---

examples/rxdirs.cf

Ticket: CFE-3718
(cherry picked from commit 42227b172c13c3c561ae0ed1dcf63e42185e0cec)

CFE-3718: Added example illustrating rxdirs perms body attribute (3.18.x)

---

cf-check/Makefile.am
cf-check/dump.c
cf-check/observables.c
cf-check/observables.h
libpromises/monitoring_read.c

Without using ts_key we can't dump custom measurements.
Ticket: ENT-7452

ENT-7452 Use ts_key file for measurement names in cf-check dump

---

libpromises/mod_custom.c

There are two possible ways for `PromiseModule_receive` to return NULL.
These lines are 285 and 302 in `mod_custom.c`. By adding this check we
can at least ensure that the promise evaluation fails and the agent continues.
The manual testing consisted of a custom promise
and a simple policy file:
```python
from cfengine import PromiseModule, Result
class CustomPromiseTypeModule(PromiseModule):
def __init__(self, **kwargs):
super().__init__('custom_promise', '0.0.1', **kwargs)
self.add_attribute('attribute', str)
def evaluate_promise(self, promiser, attribute):
#print('blah')  # Would segfault because of NULL from line 285
#print()  # Would segfault because of NULL from line 302
return Result.KEPT, None
```
```cfengine3
promise agent custom
{
path => …
```

Fixed segmentation fault when custom promise sends invalid response

---

libpromises/mod_custom.c

Mark custom promise as failed if module doesn't send valid JSON
Ticket: None
(cherry picked from commit 2a6c302a5f343794ed9b4931de351c35bfa56dec)

Fixed segmentation fault when custom promise sends invalid response (3.18.x)

---

libenv/sysinfo.c

Please see ticket [ENT-7454](https://tracker.mender.io/browse/ENT-7454)
Tested on OpenSUSE Leap 15.1 ✅ 
Ticket: ENT-7454

ENT-7454: Added OpenSUSE to policy var `sys.os_name_human`

---

libenv/sysinfo.c
tests/static-check/cppcheck_suppressions.txt

Tested:
cherry-picked to 3.18.x - https://github.com/cfengine/core/pull/4762
Ticket: ENT-7502

ENT-7502: Fixed Windows version unknown in MP

---

libpromises/failsafe.cf

Workaround for lmdb invalid argument issues in CI (ENT-7500)
Ticket: ENT-7511

ENT-7511 Skip update policy run with --skip-bootstrap-policy-run

---

libpromises/failsafe.cf

Workaround for lmdb invalid argument issues in CI (ENT-7500)
Ticket: ENT-7511
(cherry picked from commit ee529a5ca34e537ed00044b3bc7909b7bf9763d4)

ENT-7511 Skip update policy run with --skip-bootstrap-policy-run (3.18.x)

---

libpromises/failsafe.cf

Workaround for lmdb invalid argument issues in CI (ENT-7500)
Ticket: ENT-7511
(cherry picked from commit ee529a5ca34e537ed00044b3bc7909b7bf9763d4)

ENT-7511 Skip update policy run with --skip-bootstrap-policy-run (3.15.x)

---

cf-check/Makefile.am
cf-check/dump.c
cf-check/observables.c
cf-check/observables.h
libpromises/monitoring_read.c

Without using ts_key we can't dump custom measurements.
Ticket: ENT-7452
(cherry picked from commit 418aa12f13e3fa5f4edd07c5fea55806e39b3f14)

ENT-7452: Use ts_key file for measurement names in cf-check dump (3.15)

---

cf-check/Makefile.am
cf-check/dump.c
cf-check/observables.c
cf-check/observables.h
libpromises/monitoring_read.c

Without using ts_key we can't dump custom measurements.
Ticket: ENT-7452
(cherry picked from commit 418aa12f13e3fa5f4edd07c5fea55806e39b3f14)

ENT-7452: Use ts_key file for measurement names in cf-check dump (3.18)

---

libpromises/cmdb.c
libpromises/generic_agent.c

JSON has a special value 'null' which represents and empty
value. We should thus treat it as such -- in most cases this
means the same as if the child object was not present. For
example with this JSON::
"obj": {
"child" : null
}
the 'child' sub-object should be treated as a potential 'child2'
sub-object which is not present at all. That is, when handling
JSON/CMDB data.
Ticket: ENT-7434
Changelog: 'null' JSON value is now handled as empty data in augments/host-specific data

ENT-7434: Use JSON_NOT_NULL()/NULL_JSON() to better handle augments/CMDB data

---

libpromises/attributes.c

Recognize both 'info' and 'inform' as LOG_LEVEL_INFO log level
and produce a warning if the log level is not recognized.
Also use StringEqual() instead of strcmp() == 0.

Make the ActionAttributeLogLevelFromString function be nicer on users

---

libpromises/cmdb.c
libpromises/generic_agent.c

[3.18.x] ENT-7434: Use JSON_NOT_NULL()/NULL_JSON() to better handle augments/CMDB data

---

cf-key/cf-key.c

Changed cf-key option --print-digest to take an optional argument.
cf-key now defaults to the public key file in workdir, if no argument
is specified or an empty string is given as the argument.
Please see ticket [CFE-3682](https://tracker.mender.io/browse/CFE-3682)
Ticket: CFE-3682

CFE-3682: cf-key --print-digest now takes optional argument

---

cf-agent/verify_files.c
tests/acceptance/28_inform_testing/01_files/insert_lines_noop.cf

File editing happens in two phases -- the changes are modeled in
a memory buffer and then the buffer is compared with the file on
disk to see if any changes need to be made. If the buffer and the
file differ, the buffer is committed to disk (as the file).
Thus, in places where the changes in the memory buffer are done,
it's not yet clear if they should be shown to the user as 'info:'
messages and so they need to be buffered and only actually logged
if some changes are committed to disk.
Ticket: CFE-3708
Changelog: Only real changes in files now produce info messages

CFE-3708: Avoid excessive logging from in-memory changes in files promises

---

libpromises/fncall.c
tests/acceptance/01_vars/02_functions/ifelse_undefined.cf

The existing test case apparently wasn't sufficient to
catch a regression that may have occurred.
Ticket: ENT-7556
(cherry picked from commit 8550de2be3042e6236f292e63620123c2cc675a7)

ENT-7556 ifelse() not falling back in case of undefined vars (3.15)

---

libpromises/fncall.c
tests/acceptance/01_vars/02_functions/ifelse_undefined.cf

The existing test case apparently wasn't sufficient to
catch a regression that may have occurred.
Ticket: ENT-7556
(cherry picked from commit 8550de2be3042e6236f292e63620123c2cc675a7)

ENT-7556 ifelse() not falling back in case of undefined vars (3.18)

---

cf-agent/verify_files.c
tests/acceptance/28_inform_testing/01_files/insert_lines_noop.cf

File editing happens in two phases -- the changes are modeled in
a memory buffer and then the buffer is compared with the file on
disk to see if any changes need to be made. If the buffer and the
file differ, the buffer is committed to disk (as the file).
Thus, in places where the changes in the memory buffer are done,
it's not yet clear if they should be shown to the user as 'info:'
messages and so they need to be buffered and only actually logged
if some changes are committed to disk.
Ticket: CFE-3708
Changelog: Only real changes in files now produce info messages
(cherry picked from commit 1b647c2c32735992c392b680f4597bd7b1005676)

[3.18.x] CFE-3708: Avoid excessive logging from in-memory changes in files promises

---

libpromises/fncall.c
libpromises/verify_vars.c
tests/acceptance/01_vars/02_functions/execresult_action_immediate.cf

For cases where a fresh value is needed every time, for example:
```
vars:
"date"
string => execresult("/bin/date", "noshell"),
action => immediate;
```
Ticket: CFE-3754
Changelog: Cached functions are now always called inside promises with 'iflapsed => "0"'
Steps:
https://github.com/cfengine/core/pull/4792
https://github.com/cfengine/masterfiles/pull/2085

[CFE-3754] Call cached functions every time if 'ifelapsed => "0"' is specified 

---

CONTRIBUTING.md

Ticket: ENT-7627
(cherry picked from commit a08082b21b835b5a607cb0706d9e0adcbec49639)

ENT-7627: Changed IRC channel reference from freenode to libera.chat (3.18)

---

CONTRIBUTING.md

Ticket: ENT-7627
(cherry picked from commit a08082b21b835b5a607cb0706d9e0adcbec49639)

ENT-7627: Changed IRC channel reference from freenode to libera.chat (3.15)

---

CONTRIBUTING.md

ENT-7627: Changed IRC channel reference from freenode to libera.chat

---

libpromises/policy.c

It just works, '$(this.handle)' is properly replaced by the value
of the attribute.
Ticket: CFE-3439
Changelog: Custom promises can now use the 'handle' attribute
https://github.com/cfengine/core/pull/4795
https://github.com/cfengine/masterfiles/pull/2087

Support the 'handle' attribute in custom promises

---

libpromises/policy.c

It just works, '$(this.handle)' is properly replaced by the value
of the attribute.
Ticket: CFE-3439
Changelog: Custom promises can now use the 'handle' attribute
(cherry picked from commit 660723e770c140ee99a2b5b0d6cf5090ddcdb0dc)

[3.18.x] Support the 'handle' attribute in custom promises

---

libpromises/files_repository.c

Fixes https://tracker.mender.io/browse/CFE-3640.

CFE-3640: Don't try to backup files with an empty name

---

libpromises/files_repository.c

When creating new files (for example with a copy_from when the destination
does not exist), if backups are enabled, the agent would try to backup the
previous state of the (non-existent) destination. It makes the promise
fail and logs errors about the backup of an empty file name.
Changelog: Don't fail on new file creation when backups are enabled
Ticket: CFE-3640
(cherry picked from commit dc07dc879d1c1ec7d5b1686b5647019940e4feb1)

[3.18.x] Don't try to backup files with an empty name

---

misc/selinux/cfengine-enterprise.fc

Same as /var/cfengine so that our daemons and processes can
access it.
Ticket: ENT-7898
(cherry picked from commit 41a873d2d14d6e6c2d798f20475da3b0f7d0e778)

[3.15.x] ENT-7898: Label /opt/cfengine as cfengine_var_lib_t

---

misc/selinux/cfengine-enterprise.fc

Same as /var/cfengine so that our daemons and processes can
access it.
Ticket: ENT-7898
(cherry picked from commit 41a873d2d14d6e6c2d798f20475da3b0f7d0e778)

[3.18.x] ENT-7898: Label /opt/cfengine as cfengine_var_lib_t

---

libpromises/eval_context.c
libpromises/eval_context.h
libpromises/generic_agent.c
tests/acceptance/02_classes/01_basic/persistent_negate.cf
tests/acceptance/02_classes/01_basic/persistent_negate.cf.sub
tests/acceptance/02_classes/01_basic/persistent_negate.cf.sub2

Ticket: ENT-5886
Changelog: '-N/--negate now prevents persistent classes from being defined'

Fix '-N/--negate' preventing persistent classes from being defined

---

ChangeLog
libpromises/eval_context.c
libpromises/eval_context.h
libpromises/generic_agent.c
tests/acceptance/02_classes/01_basic/persistent_negate.cf
tests/acceptance/02_classes/01_basic/persistent_negate.cf.sub
tests/acceptance/02_classes/01_basic/persistent_negate.cf.sub2

Ticket: ENT-5886
Changelog: '-N/--negate now prevents persistent classes from being defined'
(cherry picked from commit 3e3a744743adc6e554013699aad0839a1cde461c)

[3.18.x] Fix '-N/--negate' preventing persistent classes from being defined

---

ChangeLog
libpromises/eval_context.c
libpromises/eval_context.h
libpromises/generic_agent.c
tests/acceptance/02_classes/01_basic/persistent_negate.cf
tests/acceptance/02_classes/01_basic/persistent_negate.cf.sub
tests/acceptance/02_classes/01_basic/persistent_negate.cf.sub2

Ticket: ENT-5886
Changelog: '-N/--negate now prevents persistent classes from being defined'
(cherry picked from commit 3e3a744743adc6e554013699aad0839a1cde461c)
Conflicts:
libpromises/eval_context.c

[3.15.x] Fix '-N/--negate' preventing persistent classes from being defined

---

ChangeLog

The documentation pulls in changelogs and having markdown inside these files
breaks when the doc build is unable to automatically resolve links. This change
simply swaps ` for ' to fix the doc build.

Fixed doc build

---

libpromises/evalfunction.c

Otherwise static checkers complain that 'wantbundle' may be NULL.

Use StringEqual() in DefaultTemplateData()

---

misc/selinux/cfengine-enterprise.fc
misc/selinux/cfengine-enterprise.te

The notification scripts that can be hooked up to alerts are
supposed to be able to do basically anything on the system. Thus
we need to allow that, but we shouldn't enable our httpd and PHP
do anything on the system.
Ticket: ENT-8029

Add a special SELinux type and domain for Mission Portal action scripts

---

misc/selinux/cfengine-enterprise.fc
misc/selinux/cfengine-enterprise.te

The notification scripts that can be hooked up to alerts are
supposed to be able to do basically anything on the system. Thus
we need to allow that, but we shouldn't enable our httpd and PHP
do anything on the system.
Ticket: ENT-8029
(cherry picked from commit ef652c0d21c04fc5792e34075a52849d76497010)

ENT-8029: Add a special SELinux type and domain for Mission Portal action scripts (3.18)

---

misc/selinux/cfengine-enterprise.fc
misc/selinux/cfengine-enterprise.te

The notification scripts that can be hooked up to alerts are
supposed to be able to do basically anything on the system. Thus
we need to allow that, but we shouldn't enable our httpd and PHP
do anything on the system.
Ticket: ENT-8029
(cherry picked from commit ef652c0d21c04fc5792e34075a52849d76497010)
Conflicts:
misc/selinux/cfengine-enterprise.te

ENT-8029: Add a special SELinux type and domain for Mission Portal action scripts (3.15)

---

libpromises/evalfunction.c

Otherwise static checkers complain that 'wantbundle' may be NULL.
(cherry picked from commit 8976b0c3826221d04e299c0c205a54dfa3366dbf)
Backport of https://github.com/cfengine/core/pull/4869.

[3.18.x] Use StringEqual() in DefaultTemplateData()

---

misc/selinux/cfengine-enterprise.te

Needed for Federated Reporting.
Ticket: ENT-7493
Changelog: Federated Reporting is now supported on RHEL 8 hubs

SELinux: Allow access to /opt/cfengine for commands over SSH

---

README.md

Travis badges are for any PRs on the branches so not what we want.
Jenkins badges aren't accurate either due to lack of known
issue exceptions.
Ticket: ENT-7870

ENT-7870 Remove inaccurate build badges

---

README.md

Travis badges are for any PRs on the branches so not what we want.
Jenkins badges aren't accurate either due to lack of known
issue exceptions.
Ticket: ENT-7870
(cherry picked from commit cdfb560ffafe3211c685a2b6ec99c2812b69ef52)

ENT-7870 Remove inaccurate build badges (3.18)

---

README.md

Travis badges are for any PRs on the branches so not what we want.
Jenkins badges aren't accurate either due to lack of known
issue exceptions.
Ticket: ENT-7870
(cherry picked from commit cdfb560ffafe3211c685a2b6ec99c2812b69ef52)

ENT-7870 Remove inaccurate build badges (3.15)

---

libpromises/generic_agent.c
tests/acceptance/00_basics/02_switches/show-evaluated-vars.cf
tests/acceptance/00_basics/02_switches/show-evaluated-vars.cf.sub
tests/acceptance/08_commands/01_modules/vars-from-module-have-source-and-derived_from-tags.cf
tests/acceptance/08_commands/01_modules/vars-without-explicit-tags-do-not-segfault.cf
tests/acceptance/08_commands/01_modules/vars-without-explicit-tags-do-not-segfault.cf.sub

[3.18.x] ENT-7724: Added test for --show-evaluated-vars not segfaulting when vars from module are not explicitly tagged

---

misc/changelog-generator/changelog-generator

Issue was that backticks in changelogs break docs builds, and Nick had
to fix it manually. Quote from cfengine#4863:
> The documentation pulls in changelogs and having markdown inside these files
> breaks when the doc build is unable to automatically resolve links.
Ticket: ENT-7979

Replace backticks with single quotes in changelogs

---

libpromises/eval_context.c
tests/acceptance/02_classes/01_basic/cancel_hardclass.cf

Fixed a bug allowing you to undefine a hard classes.

ENT-7718: No longer possible to undefine reserved hard classes

---

libpromises/failsafe.cf

- https://github.com/cfengine/masterfiles/pull/2179
- https://github.com/cfengine/documentation/pull/2597
With build.cfengine.com and cfbs released, we would like to be able to
distribute compliance reports as cfbs modules. We don't need (or necessarily
want) to distribute compliance report definitions to every host since they are
only useful for an enterprise hub, so we introduced this directory '.no-distrib'
as an excluded directory for bootstrap and failsafe.
With this change bootstrap/failsafe will exclude any directory named .no-distrib.
Note, until the update policy is updated with the same
exclusion, any policy update will receive the files in those directories.
Ticket: ENT-8079

Added bootstrap/failsafe exclusion for directories named .no-distrib

---

cf-agent/verify_files_utils.c

This, for example, is clearly wrong:
info: Copied file 'hub_cmdb/host_specific.json' from '/var/cfengine/data/./host_specific.json.cfnew' to '63.33.55.11'
should say "... from '63.33.55.11' to '/var/cfengine...'".

Fix the log message for remote copies

---

cf-agent/verify_files_utils.c

This, for example, is clearly wrong:
info: Copied file 'hub_cmdb/host_specific.json' from '/var/cfengine/data/./host_specific.json.cfnew' to '63.33.55.11'
should say "... from '63.33.55.11' to '/var/cfengine...'".
(cherry picked from commit 94d1d3b778af5243bc1c4048077b0ae4ed50fd7e)

[3.18.x] Fix the log message for remote copies

---

libpromises/eval_context.c
tests/acceptance/02_classes/01_basic/cancel_hardclass.cf

Fixed a bug allowing you to undefine a hard classes.
Ticket: ENT-7718
(cherry picked from commit 945c8483b5fb1baf38110bbccbe8e8b1519beda4)

ENT-7718: No longer possible to undefine reserved hard classes (3.18.x)

---

libpromises/eval_context.c
tests/acceptance/02_classes/01_basic/cancel_hardclass.cf

Fixed a bug allowing you to undefine a hard classes.
Ticket: ENT-7718
(cherry picked from commit 945c8483b5fb1baf38110bbccbe8e8b1519beda4)

ENT-7718: No longer possible to undefine reserved hard classes (3.15.x)

---

.github/workflows/cifuzz.yml

Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz, on which cfengine already runs (although there is only a single fuzzer for now)

GH Actions: Add CIFuzz integration

---

libpromises/locks.c
libpromises/mod_custom.c
libpromises/policy.c

steps:
https://github.com/cfengine/core/pull/4905
https://github.com/cfengine/masterfiles/pull/2223

CFE-3434: Custom promise locking and ifelapsed

---

misc/changelog-generator/changelog-generator

Issue was that backticks in changelogs break docs builds, and Nick had
to fix it manually. Quote from https://github.com/cfengine/core/pull/4863:
> The documentation pulls in changelogs and having markdown inside these files
> breaks when the doc build is unable to automatically resolve links.
Ticket: ENT-7979
(cherry picked from commit 69d2537c55393e2e4771cb1af33f0a162aa233ba)

Replace backticks with single quotes in changelogs - 3.18.x

---

misc/changelog-generator/changelog-generator

Issue was that backticks in changelogs break docs builds, and Nick had
to fix it manually. Quote from https://github.com/cfengine/core/pull/4863:
> The documentation pulls in changelogs and having markdown inside these files
> breaks when the doc build is unable to automatically resolve links.
Ticket: ENT-7979
(cherry picked from commit 69d2537c55393e2e4771cb1af33f0a162aa233ba)

Replace backticks with single quotes in changelogs - 3.15.x

---

libpromises/policy.c

Acceptance test: https://github.com/cfengine/masterfiles/pull/2222

CFE-3432: Enable comment-attribute for custom promise types

---

libpromises/failsafe.cf

https://github.com/cfengine/core/pull/4902
https://github.com/cfengine/masterfiles/pull/2215
https://github.com/cfengine/documentation/pull/2614
With build.cfengine.com and cfbs released, we would like to be able to
distribute compliance reports as cfbs modules. We don't need (or necessarily
want) to distribute compliance report definitions to every host since they are
only useful for an enterprise hub, so we introduced this directory '.no-distrib'
as an excluded directory for bootstrap and failsafe.
With this change bootstrap/failsafe will exclude any directory named .no-distrib.
Note, until the update policy is updated with the same
exclusion, any policy update will receive the files in those directories.
Ticket: ENT-8079
(cherry picked from commit …

ENT-8079: Added bootstrap/failsafe exclusion for directories named .no-distrib (3.18)

---

cf-agent/verify_users.c
cf-agent/verify_users_pam.c

Log messages at log level info should state what the actual changes on
the system are, not the promise outcome. The promise outcome should be
logged at log level verbose.
Ticket: CFE-3906

CFE-3906: Fix wrong use of log level in users promises log messages

---

cf-agent/verify_users.c
cf-agent/verify_users_pam.c

Log messages at log level info should state what the actual changes on
the system are, not the promise outcome. The promise outcome should be
logged at log level verbose.
Ticket: CFE-3906
(cherry picked from commit 6b3b7f48f28e4fd49bf91c2fde5c86bba5b0f9a3)

CFE-3906: Fix wrong use of log level in users promises log messages (3.18.x)

---

libpromises/evalfunction.c

Inform level logging is intended for messages about changes that CFEngine is
making. These messages are about errors reading files in proc. Prior to this
change you would see errors like this while running as a privileged user:
info: Error while reading file '/proc/sys/net/ipv6/conf/lo/stable_secret' (Input/output error)
info: Error while reading file '/proc/sys/fs/binfmt_misc/register' (Invalid argument)
info: Error while reading file '/proc/sys/net/ipv6/route/flush' (Permission denied)
info: Error while reading file '/proc/sys/net/ipv6/conf/default/stable_secret' (Input/output error)
info: Error while reading file '/proc/sys/net/ipv6/conf/enp0s25/stable_secret' (Input/output error)
info: Error while reading file '/proc/sys/net/ipv6/conf/all/stable_secret' (Input/output error)
info: …

CFE-3818: Moved errors from data_sysctlvalues from inform to verbose (3.18)

---

libpromises/evalfunction.c

Inform level logging is intended for messages about changes that CFEngine is
making. These messages are about errors reading files in proc. Prior to this
change you would see errors like this while running as a privileged user:
info: Error while reading file '/proc/sys/net/ipv6/conf/lo/stable_secret' (Input/output error)
info: Error while reading file '/proc/sys/fs/binfmt_misc/register' (Invalid argument)
info: Error while reading file '/proc/sys/net/ipv6/route/flush' (Permission denied)
info: Error while reading file '/proc/sys/net/ipv6/conf/default/stable_secret' (Input/output error)
info: Error while reading file '/proc/sys/net/ipv6/conf/enp0s25/stable_secret' (Input/output error)
info: Error while reading file '/proc/sys/net/ipv6/conf/all/stable_secret' (Input/output error)
info: …

CFE-3818: Moved errors from data_sysctlvalues from inform to verbose (3.15)

---

cf-agent/verify_files.c
libpromises/mod_custom.c

Fixed segfaults on Solaris 10 caused by NULL as arguments in different format functions.
E.g. on Solaris 10 the following statement segfaults
```C
printf("%s\n", NULL);
```
while on other platforms it would output `(null)`

Fixed segfaults on Solaris 10 caused by NULL as argument in string format functions

---

libpromises/loading.c

These messages clutter up the verbose log for something that I do not think we
have had tickets about, so it's really just noise in most cases of reading a
verbose log. Many of these are generated by the MPF itself, so it's rather
expected.
Ticket: CFE-3934

CFE-3934: Moved Skipping loading of duplicate policy file messages from VERBOSE to DEBUG

---

cf-agent/verify_files.c

cherry-picked from https://github.com/cfengine/core/pull/4923

Fixed segfaults on Solaris 10 caused by NULL as argument in string format functions (3.15.x)  

---

cf-agent/verify_methods.c
libpromises/conversion.c
libpromises/conversion.h
libpromises/eval_context.c
libpromises/eval_context.h
libpromises/expand.c
libpromises/generic_agent.c
libpromises/loading.c
libpromises/policy.c
libpromises/policy.h
tests/acceptance/01_vars/02_functions/mustach_doesnt_render_null.cf
tests/acceptance/21_methods/reachable/bundle_promiser_call_by_arg_defined.cf
tests/acceptance/21_methods/reachable/bundle_promiser_call_by_arg_undefined.x.cf
tests/acceptance/21_methods/reachable/bundle_promiser_defined.cf
tests/acceptance/21_methods/reachable/bundle_promiser_undefined.x.cf
tests/acceptance/21_methods/reachable/bundle_promiser_unreachable.cf
tests/acceptance/21_methods/reachable/bundle_reversed_usebundle_parameters_defined.cf
tests/acceptance/21_methods/reachable/bundle_reversed_usebundle_parameters_undefined.x.cf
tests/acceptance/21_methods/reachable/bundle_usebundle_call_by_arg_defined.cf
tests/acceptance/21_methods/reachable/bundle_usebundle_call_by_arg_undefined.x.cf
tests/acceptance/21_methods/reachable/bundle_usebundle_defined.cf
tests/acceptance/21_methods/reachable/bundle_usebundle_parameters_defined.cf
tests/acceptance/21_methods/reachable/bundle_usebundle_parameters_undefined.x.cf
tests/acceptance/21_methods/reachable/bundle_usebundle_undefined.x.cf
tests/acceptance/21_methods/reachable/bundle_usebundle_unreachable.cf
tests/unit/conversion_test.c
tests/unit/policy_test.c

I fixed this issue, but refrained from starting to fix more than necessary.
https://github.com/cfengine/core/pull/4929
https://github.com/cfengine/masterfiles/pull/2268

ENT-8430: Fixed default for ignore_missing_bundles and ignore_missing_inputs 

---

cf-agent/verify_methods.c
libpromises/conversion.c
libpromises/conversion.h
libpromises/eval_context.c
libpromises/eval_context.h
libpromises/expand.c
libpromises/generic_agent.c
libpromises/loading.c
libpromises/policy.c
libpromises/policy.h
tests/acceptance/01_vars/02_functions/mustach_doesnt_render_null.cf
tests/acceptance/21_methods/reachable/bundle_promiser_call_by_arg_defined.cf
tests/acceptance/21_methods/reachable/bundle_promiser_call_by_arg_undefined.x.cf
tests/acceptance/21_methods/reachable/bundle_promiser_defined.cf
tests/acceptance/21_methods/reachable/bundle_promiser_undefined.x.cf
tests/acceptance/21_methods/reachable/bundle_promiser_unreachable.cf
tests/acceptance/21_methods/reachable/bundle_reversed_usebundle_parameters_defined.cf
tests/acceptance/21_methods/reachable/bundle_reversed_usebundle_parameters_undefined.x.cf
tests/acceptance/21_methods/reachable/bundle_usebundle_call_by_arg_defined.cf
tests/acceptance/21_methods/reachable/bundle_usebundle_call_by_arg_undefined.x.cf
tests/acceptance/21_methods/reachable/bundle_usebundle_defined.cf
tests/acceptance/21_methods/reachable/bundle_usebundle_parameters_defined.cf
tests/acceptance/21_methods/reachable/bundle_usebundle_parameters_undefined.x.cf
tests/acceptance/21_methods/reachable/bundle_usebundle_undefined.x.cf
tests/acceptance/21_methods/reachable/bundle_usebundle_unreachable.cf
tests/unit/conversion_test.c
tests/unit/policy_test.c

- Added StringIsBoolean()
- Added test for BooleanFromString()
- Fixed default for ignore_missing_bundles and ignore_missing_inputs
- Simplified BooleanFromString() and StringIsBoolean()
- Added config to EvalContext
- Fixed inconsistencies with methods promises and missing bundles
- Added missing reports promise type in mustache test
- Added tests for defined vs undefined vs unreachable bundles

ENT-8430: Fixed default for ignore_missing_bundles and ignore_missing_inputs (3.18)

---

examples/rxdirs.cf
libpromises/attributes.c
libpromises/policy.c
libpromises/policy.h
tests/acceptance/plucked.cf.sub

Commits from #4927 cherry-picked to *3.18.x* **without changing the default for `rxdirs`**.
MPF changes: https://github.com/cfengine/masterfiles/pull/2270

[3.18.x] CFE-951: log a warning if 'mode' is set, but 'rxdirs' is not

---

libpromises/policy.c

When a default value for an attribute that should be set
explicitly is used, a warning is emitted. It should be easier for
the user to identify which promise exactly it is coming from.
Ticket: CFE-951

Add more details to the warning in PromiseGetConstraintAsBooleanWithDefault()

---

libpromises/policy.c

When a default value for an attribute that should be set
explicitly is used, a warning is emitted. It should be easier for
the user to identify which promise exactly it is coming from.
Ticket: CFE-951
(cherry picked from commit 4025aa1ae1fbeada324c67e95ae929c928a5a6a1)

[3.18.x] Add more details to the warning in PromiseGetConstraintAsBooleanWithDefault()

---

libpromises/conversion.c

Apparently, 'sscanf("0", "%ju", &uintmax_t_var)' fails on
HP-UX. 'int' and '%d' work, so let's just use those.
Also add assertions that the 'sscanf()' calls on numeric strings
actually work, it's clearly not guaranteed.
Ticket: CFE-3937

Use 'int' and '%d' when converting UID/GID to a number on HP-UX

---

libpromises/conversion.c

Apparently, 'sscanf("0", "%ju", &uintmax_t_var)' fails on
HP-UX. 'int' and '%d' work, so let's just use those.
Also add assertions that the 'sscanf()' calls on numeric strings
actually work, it's clearly not guaranteed.
Ticket: CFE-3937
(cherry picked from commit 31c2e9bbe9e69529fa0caf4bf60c466046be2519)

[3.18.x] Use 'int' and '%d' when converting UID/GID to a number on HP-UX

---

cf-agent/verify_processes.c
cf-agent/verify_processes.h
libpromises/cf3.defs.h
libpromises/conversion.c
libpromises/mod_process.c

'processes' promises can specify signals to be sent to matching
processes. The 'signals' attribute specifies a sequence of
signals to be sent, most common being '{ "term", "kill"}'.
However, in many cases, sending the signals one right after
another makes little sense because the receiving process doesn't
have a chance to react in between them.
Let's support special signal specifications in the form 'N' or
'Ns' (e.g. '10' or '10s') representing sleeps between the
signals.
Ticket: ENT-5899
Ticket: CFE-2207
Changelog: 'N' or 'Ns' signal specs can now be used to sleep
between signals sent by 'processes' promises
https://github.com/cfengine/core/pull/4936
https://github.com/cfengine/enterprise/pull/685

Support adding sleeps between signals in processes promises

---

cf-agent/verify_processes.c
cf-agent/verify_processes.h
libpromises/cf3.defs.h
libpromises/conversion.c
libpromises/mod_process.c

3.18.x version of https://github.com/cfengine/core/pull/4936

[3.18.x] ENT-5899: Support adding sleeps between signals in processes promises

---

cf-agent/verify_files.c
tests/acceptance/10_files/01_create/content_create_by_default.cf

```
root@hub:~# cat ~/content.cf 
bundle agent __main__
{
files:
"/tmp/test_1"
content => "Hello one!$(const.n)";
"/tmp/test_2"
create => "true",
content => "Hello two!$(const.n)";
"/tmp/test_3"
create => "false",
content => "Hello three!$(const.n)";
}
root@hub:~# cf-agent -KIf ~/content.cf 
info: Created file '/tmp/test_1', mode 0600
info: Updated content of '/tmp/test_1' with content 'Hello one!
'
info: Created file '/tmp/test_2', mode 0600
info: Updated content of '/tmp/test_2' with content 'Hello two!
'
root@hub:~# cat /tmp/test_1
Hello one!
root@hub:~# cat /tmp/test_2
Hello two!
root@hub:~# cat /tmp/test_3
cat: /tmp/test_3: No such file or directory
```

CFE-3916: content files promises now creates files by default

---

cf-agent/verify_files.c
tests/acceptance/10_files/01_create/cfengine_create_by_default.cf
tests/acceptance/10_files/templating/missing_file.cf

cfengine template method files promises now create files by default, unless `create => "false"` is specified. Files are not created if the rendering failes, unless `create => "true"` is specified.

CFE-3955 & CFE-3954: cfengine template method now creates files by default

---

libcfnet/protocol_version.c
libpromises/mod_common.c
libpromises/mod_files.c

This change adds protocol 3 (cookie) to the syntax-description output which is
needed in order to keep automatically generated docs that use the
CFEngine_promise_attribute macro up to date.

ENT-8560: Added protocol 3 (cookie) to syntax description

---

libpromises/cf3.defs.h
tests/static-check/run.sh

Newer GCC, clang and cppcheck mean more issues detected.

Default static checks to use Fedora 35 base image

---

cf-agent/files_editline.c
cf-agent/simulate_mode.c
libpromises/syslog_client.c
tests/static-check/run.sh

And fix the newly-discovered issues...
(the first 2 commits are from #4958)
https://github.com/cfengine/libntech/pull/160

Use Fedora 36 for static checks by default

---

tests/acceptance/31_tickets/CFE-3987/1/before_test.xml.txt
tests/acceptance/31_tickets/CFE-3987/1/test.cf
tests/acceptance/31_tickets/CFE-3987/2/before_test.xml.txt
tests/acceptance/31_tickets/CFE-3987/2/test.cf

This change adds two tests, the first (acceptance/31_tickets/CFE-3987/1/test.cf)
tests the behavior described by the related issue, inserting text before a
selected region should insert immediately before the selected region even if
select_line_matching is not explicitly specified. This test is currently set to soft fail.
The second (acceptance/31_tickets/CFE-3987/2/test.cf) tests the workaround where
after select_line_matching is explicitly defined, the text is inserted
immediately before the selected region. This test passes (as expected).

CFE-3987 Added tests related to inserting text based on a location within select_region

---

tests/acceptance/31_tickets/ENT-8817/1/expected_output.txt
tests/acceptance/31_tickets/ENT-8817/1/main.cf
tests/acceptance/31_tickets/ENT-8817/2/expected_output.txt
tests/acceptance/31_tickets/ENT-8817/2/main.cf

These tests check that a bundle qualified variable reference, e.g.
$(bundle.variable) refer to the promisers namespace, especially when the
promiser is not in the default namespace. They are added in a soft failing state
to facilitate a future fix.

ENT-8817: Added tests that bundle qualified variables reference the promisers namespace

---

.gitignore

This change prevents temporary files created by emacs flycheck from being
considered by git, mucking up git status output.

Git ignored emacs flycheck temporary files

---

tests/acceptance/31_tickets/ENT-8818/1/README.org
tests/acceptance/31_tickets/ENT-8818/1/staging/main.cf

This test exercises a bug that causes the agent to crash with an error like:
cf-agent: eval_context.c:2233: GetVariableTableForScope: Assertion `!ns || strcmp("default", ns) == 0' failed.

ENT-8818: Added test variables referencing non-existing namespaces do not crash

---

tests/acceptance/31_tickets/CFE-2367/1/test.cf
tests/acceptance/31_tickets/CFE-2367/2/test.cf

Adding tests for CFE-2367 posthumously since I found this is no longer happening but the ticket was never closed.

CFE-2367: Added tests that fileexists does not error fatally when given an undefined var parameter

---

misc/selinux/cfengine-enterprise.te

Accidentally introduced in e9b804bd708 when backporting things
from master.

Remove an unresolved conflict from backporting SELinux rules

---

misc/selinux/cfengine-enterprise.te

It should be entered by a transition from the cfengine_httpd_t
domain not from init_t. And it should be allowed to execute
things from /bin and /usr/bin.

Fixes for the cfengine_action_script_t domain

---

travis-scripts/script.sh

New version of determitne-version.sh doesn't need it
Also, stop fetching submodules recursevely
IDK how it worked before, but recently Travis started failing with an error like this:
Fetching submodule libntech
fatal: remote error: upload-pack: not our ref 54e12b54a0be037b8fab70433c29194debcb1c91
Errors during submodule fetch:
libntech
(cherry picked from commit 29567b8ecb8e6014fd1a80c9304ac551a86c0327)

ENT-8819 Do not unshallow git repo in Travis script - 3.15.x

---

travis-scripts/script.sh

New version of determitne-version.sh doesn't need it
Also, stop fetching submodules recursevely
IDK how it worked before, but recently Travis started failing with an error like this:
Fetching submodule libntech
fatal: remote error: upload-pack: not our ref 54e12b54a0be037b8fab70433c29194debcb1c91
Errors during submodule fetch:
libntech
(cherry picked from commit 29567b8ecb8e6014fd1a80c9304ac551a86c0327)

ENT-8819 Do not unshallow git repo in Travis script - 3.18.x

---

misc/selinux/cfengine-enterprise.te

It should be entered by a transition from the cfengine_httpd_t
domain not from init_t.
(cherry picked from commit 2646f98e1948dede617e2f15e51e9fdd1f194dc9)

[3.15.x] Fixes for the cfengine_action_script_t domain

---

libpromises/crypto.c

The legacy encrypted network stuff on community uses Blowfish
which is only provided by the legacy provider in OpenSSL 3+.

Load the legacy provider on OpenSSL 3+

---

tests/acceptance/16_cf-serverd/serial/simple_copy_from_admit_localhost.cf
tests/acceptance/16_cf-serverd/serial/simple_copy_from_deny_localhost.cf

See https://github.com/cfengine/core/commit/b1797df53cb1f95e5af2bdf83f5e174901f06393
Ubuntu 20 and 22 fail to resolve 127.0.0.1/::1 to localhost
and so we must skip these two tests.
Ticket: ENT-7362
(cherry picked from commit be7b592b51b8ac44c72109a3274efa8d38f7344e)
https://github.com/cfengine/buildscripts/pull/1098
https://github.com/cfengine/core/pull/4991

ENT-7362 Skip tests that require reverse lookup of localhost on Ubuntu 22 (3.18)

---

configure.ac

Debian is taking steps towards removing xml2-config in favour of pkg-config.
This means cfengine3 will build without libxml2 support.
This patch modifies configure.ac to detect libxml2 via pkg-config, falling
back to xml2-config if pkg-config is not available.
Ticket: CFE-4014
Signed-off-by: Hugh McMaster <hugh.mcmaster@outlook.com>

configure.ac: Enabled use of pkg-config to find libxml2

---

cf-agent/files_editline.c
tests/acceptance/31_tickets/ENT-8788/1/main.cf

Ticket: ENT-8788
Changelog: Insertion of contents of a file with blank lines into
another file with blank lines no longer results in
mixed content

ENT-8788: Respect 'file_preserve_block' and 'preserve_all_lines' in InsertLineAtLocation()

---

libpromises/promises.c
tests/acceptance/01_vars/01_basic/this_promiser_ifvarclass.cf

Just like for other promise types, use the real promiser from the
policy file (with variables expanded) for if/ifvarclass/unless
checking and then undefine it again to let the special behavior
of '$(this.promiser)' in 'files' promises take part.
Ticket: ENT-7008
Ticket: CFE-2262
Changelog: '$(this.promiser)' can now be used in 'files' promise
attributes 'if', 'ifvarclass' and 'unless'

ENT-7008: Define '$(this.promiser)' for checking if/unless in 'files' promises

---

libpromises/promises.c
tests/acceptance/01_vars/01_basic/this_promiser_ifvarclass.cf

Just like for other promise types, use the real promiser from the
policy file (with variables expanded) for if/ifvarclass/unless
checking and then undefine it again to let the special behavior
of '$(this.promiser)' in 'files' promises take part.
Ticket: ENT-7008
Ticket: CFE-2262
Changelog: '$(this.promiser)' can now be used in 'files' promise
attributes 'if', 'ifvarclass' and 'unless'
(cherry picked from commit 433c193b7d4b4fefc623a505251848b344d6af58)

[3.18.x] ENT-7008: Define '$(this.promiser)' for checking if/unless in 'files' promises

---

cf-agent/files_editline.c
tests/acceptance/31_tickets/ENT-8788/1/main.cf

Ticket: ENT-8788
Changelog: Insertion of contents of a file with blank lines into
another file with blank lines no longer results in
mixed content
(cherry picked from commit 2037084dc1ce20f628904366ce1d3d9afab9aee4)

[3.18.x] ENT-8788: Respect 'file_preserve_block' and 'preserve_all_lines' in InsertLineAtLocation()

---

contrib/masterfiles-stage/common.sh

in git_deploy_refspec ${temp_stage} is moved entirely to ${1} (the target aka /var/cfengine/masterfiles)
But in git_cfbs_deploy_refspec only out/masterfiles is moved so the directory is left.
Ticket: ENT-9039
merge together 
https://github.com/cfengine/core/pull/5006
https://github.com/cfengine/nova/pull/1915

ENT-9039: Fixed git_cfbs_deploy_refspec in masterfiles_stage leaving temp dir

---

contrib/masterfiles-stage/common.sh

in git_deploy_refspec ${temp_stage} is moved entirely to ${1} (the target aka /var/cfengine/masterfiles)
But in git_cfbs_deploy_refspec only out/masterfiles is moved so the directory is left.
Ticket: ENT-9039
(cherry picked from commit 64f6f919c1b463ba4fe5de0fa9b107360ca3126c)

ENT-9039: Fixed git_cfbs_deploy_refspec in masterfiles_stage leaving temp dir (3.18)

---

libpromises/mod_custom.c
libpromises/policy.c
tests/acceptance/30_custom_promise_types/05_meta_attr.cf

Resulting in no special behavior or handling, just like for all
the other promise types except 'vars' and 'classes'.
Ticket: CFE-3440
Changelog: 'meta' attribute can now be used in custom promises

Enable use of the 'meta' attribute with custom promises

---

cf-agent/package_module.c
cf-check/dump.c
cf-check/validate.c

In some cases the response from the module results in empty
data and sometimes no data at all. Not sure why.
Regardless it makes sense to refactor the package module handling
code to save the updates <inventory> key with a zero length value
in this case instead of sometimes a zero length and sometimes a
`\n` (newline) character.
Adjusted cf-check to allow zero length values in both dump and
validate portions of the code.
Ticket: ENT-9050
(cherry picked from commit aebabc46e7adc63d000fa1b0eb4f673fe9273235)

ENT-9050: Adjust cf-check and package module code for empty updates list (3.15)

---

cf-agent/package_module.c
cf-check/dump.c
cf-check/validate.c

In some cases the response from the module results in empty
data and sometimes no data at all. Not sure why.
Regardless it makes sense to refactor the package module handling
code to save the updates <inventory> key with a zero length value
in this case instead of sometimes a zero length and sometimes a
`\n` (newline) character.
Adjusted cf-check to allow zero length values in both dump and
validate portions of the code.
Ticket: ENT-9050
(cherry picked from commit aebabc46e7adc63d000fa1b0eb4f673fe9273235)

ENT-9050: Adjust cf-check and package module code for empty updates list (3.18)

---

cf-monitord/env_monitor.c

If this, do that, else, do that anyway. Instead, just do that.
Ticket: CFE-4022
(cherry picked from commit e9bf9a246ec50a4afa08e2acabc907153788af5f)

CFE-4022: Redacted useless ifelse (3.18)

---

cf-monitord/env_monitor.c

If this, do that, else, do that anyway. Instead, just do that.
Ticket: CFE-4022
(cherry picked from commit e9bf9a246ec50a4afa08e2acabc907153788af5f)

CFE-4022: Redacted useless ifelse (3.15)

---

libcfnet/tls_generic.c
tests/acceptance/16_cf-serverd/serial/copy_from_reordered_ciphers_success.cf
tests/acceptance/16_cf-serverd/serial/copy_from_reordered_ciphers_success.cf.sub
tests/acceptance/16_cf-serverd/serial/default_ciphers_tlsversion.srv
tests/acceptance/16_cf-serverd/serial/reordered_default_ciphers_tlsversion.srv

When splitting the colon-separated list of ciphers between cipher
suites (TLS 1.3+) and ciphers (TLS <= 1.2) care must be taken to
make sure neither of the new lists ends up with a trailing
colon.
The items from the original list can be copied over together with
their colons, but then we must make sure the last one in each
list doesn't have a colon.
Also add a verbose log message making it easier to see which
ciphers and cipher suits are being enabled.
Ticket: ENT-9018
Changelog: Allowed ciphers are now properly split into TLS 1.3
cipher suites and ciphers used for TLS 1.2 and older

ENT-9018: Make sure cipher list strings don't have trailing colons

---

libcfnet/tls_generic.c
tests/acceptance/16_cf-serverd/serial/copy_from_reordered_ciphers_success.cf
tests/acceptance/16_cf-serverd/serial/copy_from_reordered_ciphers_success.cf.sub
tests/acceptance/16_cf-serverd/serial/default_ciphers_tlsversion.srv
tests/acceptance/16_cf-serverd/serial/reordered_default_ciphers_tlsversion.srv

[3.18.x] ENT-9018: Make sure cipher list strings don't have trailing colons

---

libcfnet/tls_generic.c
tests/acceptance/16_cf-serverd/serial/copy_from_reordered_ciphers_success.cf
tests/acceptance/16_cf-serverd/serial/copy_from_reordered_ciphers_success.cf.sub
tests/acceptance/16_cf-serverd/serial/default_ciphers_tlsversion.srv
tests/acceptance/16_cf-serverd/serial/reordered_default_ciphers_tlsversion.srv

[3.15.x] ENT-9018: Make sure cipher list strings don't have trailing colons

---

configure.ac

Otherwise we rely on it and fail to get data from it. Not all our
builds provide xml2-config even when they use
'--with-libxml2=/var/cfengine'.
Ticket: ENT-9070

Check if $with_libxml2/bin/xml2-config exists and is executable

---

m4/cf3_gcc_flags.m4

AC_PREPROC_IFELSE outputs "checking how to run the C preprocessor..."
before executing its given preprocessor code.
Calling `AC_MSG_CHECKING(for HP-UX aC)' before AC_PREPROC_IFELSE results in
interrupted output, with the yes/no result of AC_MSG_RESULT appearing
on a separate line without context.
Ticket: CFE-4027
Signed-off-by: Hugh McMaster <hugh.mcmaster@outlook.com>

cf3_gcc_flags.m4: Fixed order of `configure' output

---

tests/acceptance/16_cf-serverd/serial/copy_from_tls_1_3_fail.cf
tests/acceptance/16_cf-serverd/serial/copy_from_tls_1_3_fail.cf.sub
tests/acceptance/16_cf-serverd/serial/copy_from_tls_1_3_success.cf
tests/acceptance/16_cf-serverd/serial/copy_from_tls_1_3_success.cf.sub
tests/acceptance/16_cf-serverd/serial/no_tls_1_3.srv
tests/acceptance/16_cf-serverd/serial/tls_1_3_only.srv

ENT-4617: Tests for connections requiring TLS 1.3

---

tests/acceptance/16_cf-serverd/serial/copy_from_tls_1_3_fail.cf
tests/acceptance/16_cf-serverd/serial/copy_from_tls_1_3_fail.cf.sub
tests/acceptance/16_cf-serverd/serial/copy_from_tls_1_3_success.cf
tests/acceptance/16_cf-serverd/serial/copy_from_tls_1_3_success.cf.sub
tests/acceptance/16_cf-serverd/serial/no_tls_1_3.srv
tests/acceptance/16_cf-serverd/serial/tls_1_3_only.srv

To make sure it actually works as expected.
Ticket: ENT-4617
(cherry picked from commit 37f412596f4449e511de43367b811f873df550ad)

[3.18.x] ENT-4617: Add tests for connections requiring TLS 1.3

---

misc/Makefile.am
misc/cf-support

This script gathers various system information as well
as log files and creates a tarball.
If the host has enterprise CFEngine installed further
details and files will be collected.
Ticket: ENT-9037
https://github.com/cfengine/core/pull/5010
https://github.com/cfengine/nova/pull/1918
https://github.com/cfengine/buildscripts/pull/1106
https://github.com/cfengine/system-testing/pull/445

ENT-9037: Added cf-support utility for generating support information

---

cf-testd/cf-testd.c

ENT-9129: Initialize SSL related items in cf-testd to avoid segfault on aarch64

---

misc/Makefile.am
misc/cf-support

This utility gathers various system information as well
as log files and creates a tarball.
If the host has enterprise CFEngine installed further
details and files will be collected.
Ticket: ENT-9037
(cherry picked from commit fda7b47f893a74d68df528487b3050acee2bfedf)

ENT-9037: Added cf-support utility for generating support information (3.18)

---

cf-testd/cf-testd.c

Ticket: ENT-9129
(cherry picked from commit 7c6eabaa8375ee4a04291edff95204806537b7d5)

ENT-9129: Initialize cf-testd config struct to avoid segfault on aarch64 (3.18)

---

cf-agent/Makefile.am
cf-monitord/Makefile.am

Out of tree builds not working:
$ cd core
$ make distclean
$ cd ..
$ mkdir build
$ cd build
$ ../core/autogen.sh --enable-debug
$ make -j8
Eventually gives me:
Making all in cf-agent
make[2]: *** No rule to make target '../../core/libntech/libutils/libutils.la', needed by 'manifest_file'.  Stop.

Fix non-root builds

---

cf-agent/simulate_mode.c
libpromises/mod_custom.c

They are only used in assert()s. Found by GCC 4.8.5-44 on CentOS 7 which seems to be extra picky in some ways.

Mark two vars as NDEBUG_UNUSED

---

tests/acceptance/testall

On systems without rpm don't bother checking.
Wish github actions knew about related PRs, TODO
https://github.com/cfengine/core/pull/5061
https://github.com/cfengine/masterfiles/pull/2493

ENT-9162: Refined testall check for rpmcmpver binary

---

tests/acceptance/testall

Needed to add the check for `rpm` to another section where we check that all set binaries exist and are executable.

ENT-9162: Refined testall check for rpmcmpver binary (follow up)

---

tests/acceptance/testall

On a test system running Ubuntu, the rpm binary was installed but almost certainly will have no packages installed that way. So make that test instead: rpm -qa | wc -l != 0 means we need rpmvercmp.

ENT-9162: Refined check of rpmvercmp in testall script

---

.github/workflows/acceptance_tests.yml
.github/workflows/asan_unit_tests.yml
.github/workflows/ci.yml
.github/workflows/macos_unit_tests.yml
.github/workflows/unit_tests.yml

No need to run acceptance tests which take a lot of minutes if unit tests don't pass.
Ticket: ENT-9203
(cherry picked from commit bfbcfc4f0307c1efa4e0f00a8e0078ca98d29e3c)
Conflicts:
.github/workflows/cifuzz.yml
.github/workflows/ci.yml
Removed cifuzz as not present in 3.18.x

ENT-9203: Refactored github actions to add dependencies (3.18)

---

.github/workflows/acceptance_tests.yml
.github/workflows/ci.yml
.github/workflows/unit_tests.yml

No need to run acceptance tests which take a lot of minutes if unit tests don't pass.
Ticket: ENT-9203
(cherry picked from commit bfbcfc4f0307c1efa4e0f00a8e0078ca98d29e3c)
Conflicts:
.github/workflows/cifuzz.yml
.github/workflows/ci.yml
Removed cifuzz, asan_unit_tests and macos_unit_tests as not present in 3.15.x
(cherry picked from commit f02db53f2273098e5ad4690f45dc646849a33332)

ENT-9203: Refactored github actions to add dependencies (3.15)

---

misc/systemd/cf-serverd.service.in

cf-serverd needs working network so it should only start when working network is ready.
Ticket: ENT-8456
Changelog: cf-serverd now starts in the network-online.target on
systemd-based systems
(cherry picked from commit https://github.com/vpodzime/cfengine-core/commit/962bac57c2afb1d70f33b9f463b763bc9395a296)
https://github.com/cfengine/core/pull/5070
https://github.com/cfengine/masterfiles/pull/2508

[3.18.x] ENT-8456: Move cf-serverd.service to the network-online.target

---

misc/cf-support

cf-support will now search the entire filesystem
for core files related to cf-* binaries, request to install gdb, and log backtraces to the support
tarball.
Ticket: CFE-4064
related: 
https://github.com/cfengine/core/pull/5073
https://github.com/cfengine/buildscripts/pull/1131
https://github.com/cfengine/system-testing/pull/457

CFE-4064: Added core analysis to cf-support tool

---

misc/cf-support

cf-support will now search the entire filesystem
for core files related to cf-* binaries, request to install gdb, and log backtraces to the support
tarball.
Ticket: CFE-4064
(cherry picked from commit 129a46519566f74415050e8abf02bcc32685cf09)
test with
https://github.com/cfengine/system-testing/pull/457
https://github.com/cfengine/buildscripts/pull/1134

CFE-4064: Added core analysis to cf-support tool (3.18)

---

AUTHORS

* "less than": something non-countable
* "fewer than": something countable
So change "people with less than 10 commits..." to "people with fewer than 10 commits...".
Example ref: https://www.grammarly.com/blog/fewer-vs-less/

AUTHORS: minor fix to grammar.

---

ChangeLog
misc/selinux/cfengine-enterprise.te

Ticket: ENT-9473
Changelog: Use of an external SMTP server for reports from
Mission Portal is no longer blocked by SELinux
(cherry-picked commit 8caea7310cc2d9dddc05edd7ee7b284ce14a9fa9)
(partially-backported commit 34d7969170909de505f75ab018e33916ad7a6f41)

[3.18.x] ENT-9473: Allow httpd/PHP to send reports via external SMTP server

---

misc/selinux/cfengine-enterprise.te

It needs some space for temporary files when returning large data sets as query results.
Ticket: ENT-9496
Changelog: SELinux no longer breaks SQL queries with large result
sets on RHEL 8 hubs

ENT-9496: Allow PostgreSQL to create directories under /var/cfengine

---

ChangeLog
misc/selinux/cfengine-enterprise.te

It needs some space for temporary files when returning large data sets as query results.
Ticket: ENT-9496
Changelog: SELinux no longer breaks SQL queries with large result
sets on RHEL 8 hubs
(cherry picked from commit 0177e6c3f0d03d19b1cf3f0c6977e9f68e0a8d9d)

[3.18.x] ENT-9496: Allow PostgreSQL to create directories under /var/cfengine

---

misc/selinux/cfengine-enterprise.te

Found when testing scheduled reports emailing.
Ticket: ENT-9557

ENT-9557: Allow selinux hub context to send email

---

misc/selinux/cfengine-enterprise.te

Found when testing scheduled reports emailing.
Ticket: ENT-9557
(cherry picked from commit a304cf100825886af8c929456128194be64b7680)

ENT-9557: Allow selinux hub context to send email (3.18)

---

misc/selinux/cfengine-enterprise.te

Found when testing scheduled reports emailing.
Ticket: ENT-9557
(cherry picked from commit a304cf100825886af8c929456128194be64b7680)

ENT-9557: Allow selinux hub context to send email (3.15)

---

INSTALL
misc/selinux/cfengine-enterprise.te

RHEL 9 required a few adjustments to cfengine-enterprise selinux policy which do not break RHEL 8.
Ticket: ENT-8824
(cherry picked from commit abf36bbe4d4a4107f3666dde606d1bad4525fab8)
Conflicts:
INSTALL
misc/selinux/cfengine-enterprise.te

ENT-8824: Adjust selinux policy for RHEL 9 (3.18)

---

INSTALL
cf-agent/nfs.c

Previously the format of the line to check in
/etc/fstab would be empty, now it will conform
properly to the BSD style format as mentioned
in man fstab on MacOS.
Ticket: CFE-4093

CFE-4093: Fix storage promise for nfs on MacOS

---

cf-agent/files_editline.c

This change simply tries to make it more clear how the log message can be avoided.
Ticket: CFE-192

CFE-192: Added suggestion to use a negative lookahead when non-convergent edits are attempted

---

cf-agent/nfs.c

Previously the format of the line to check in
/etc/fstab would be empty, now it will conform
properly to the BSD style format as mentioned
in man fstab on MacOS.
Ticket: CFE-4093
(cherry picked from commit 50ca18585b3581b7b4876e712b16e57f03023732)

CFE-4093 Fix storage promise for nfs on MacOS - 3.18.x

---

cf-agent/nfs.c

Previously the format of the line to check in
/etc/fstab would be empty, now it will conform
properly to the BSD style format as mentioned
in man fstab on MacOS.
Ticket: CFE-4093
(cherry picked from commit 50ca18585b3581b7b4876e712b16e57f03023732)

CFE-4093 Fix storage promise for nfs on MacOS - 3.15.x

---

misc/selinux/cfengine-enterprise.te

Ticket: ENT-8824
I believe this was a regression caused by this commit: https://github.com/cfengine/core/commit/34d7969170909de505f75ab018e33916ad7a6f41
for SELinux fixes for Build
PR: https://github.com/cfengine/core/pull/5083 
Ticket: https://tracker.mender.io/browse/ENT-9472
https://github.com/cfengine/buildscripts/pull/1137
https://github.com/cfengine/system-testing/pull/462
https://github.com/cfengine/masterfiles/pull/2529
https://github.com/cfengine/core/pull/5111

ENT-8824: Removed unsupported name_connect capability for udp_socket class

---

misc/selinux/cfengine-enterprise.te

PostgreSQL 15 needs this because it does stat() on its shared memory blocks (on /dev/shm which is a tmpfs).

Allow PostgreSQL to getattr in tmpfs

---

INSTALL

Not sure if this was every `yaml-devel` but checked on three systems and `libyaml-devel` seems to be the right answer.

Fixed redhat package for yaml dependency

---

cf-key/cf-key-functions.c
configure.ac
libpromises/crypto.c
misc/selinux/cfengine-enterprise.te

Backported changes from master for redhat 9 to 3.18.x branch.
Includes selinux policy changes as well as adjustments to work with OpenSSL 3+.
https://github.com/cfengine/buildscripts/pull/1159
https://github.com/cfengine/core/pull/5114
https://github.com/cfengine/masterfiles/pull/2544

ENT-9621: Added support for redhat 9 agent (3.18)

---

misc/selinux/cfengine-enterprise.te

PHP (cfengine_httpd_t) needs to be able to talk to Postfix Master process via a unix socket when sending emails directly and cf-hub needs to be able to read /tmp when processing scheduled reports.

More SELinux fixes for sending reports via email

---

misc/selinux/cfengine-enterprise.te

Extra two rules for call-collect when RHEL 8 is running on the hub not just on the hosts.

SELinux fixes for call-collect

---

misc/selinux/cfengine-enterprise.te

When doing call-collect, cf-serverd on a hub receives a connection and then passes the opened socket to cf-hub which uses it to gather reports. So it needs to be allowed to use the socket.

Add SELinux rule for cf-hub using a socket owned by cf-serverd

---

misc/selinux/cfengine-enterprise.te

Ticket: ENT-9694
together:
https://github.com/cfengine/buildscripts/pull/1173
https://github.com/cfengine/core/pull/5129 (selinux fix for ldap_port_t)
https://github.com/cfengine/mission-portal/pull/1857 (move ldap_log to applications folder where it belongs)

ENT-9694: Added selinux ldap port access for Mission Portal

---

libpromises/cf3.defs.h
tests/acceptance/29_simulate_mode/diff_mode.cf.expected
tests/acceptance/29_simulate_mode/manifest_full_mode.cf.expected
tests/acceptance/29_simulate_mode/manifest_mode.cf.expected

This more restrictive default directory permission better aligns with our more
secure defaults for files.
Ticket: ENT-8447

ENT-8447: Changed the default mode for directories from 755 to 700

---

misc/selinux/cfengine-enterprise.te

This is needed in order for cf-reactor to write out to cfbs process to get module inputs.
Ticket: none

Added fifo_file write access for cf-reactor

---

misc/selinux/cfengine-enterprise.te

cf-hub needs access to set socket options when connecting to cf-serverd (port 5308)
Ticket: ENT-9605

ENT-9605: Added setopt for cf-hub connecting to cf-serverd

---

libpromises/files_lib.c
libpromises/files_lib.h

Allows specifying mode (permissions) when creating a parent dir.
Especially useful now, since this PR affected more places than
intended:
https://github.com/cfengine/core/pull/5131

Added MakeParentDirectoryPerms()

---

.github/workflows/ci.yml

We will now test on master, 3.21.x and 3.18.x
3.15.x testing will stop as that series is EOL
Ticket: ENT-9433

ENT-9433: Adjust github workflows (ci) after 3.21.0 release

---

misc/systemd/cf-runalerts.service.in

The directory really needs to exist in order for the service to update time-stamps.
There is policy managing it's existence, so if we wait for it, it will appear.
Ticket: ENT-9711
together:
https://github.com/cfengine/masterfiles/pull/2564
https://github.com/cfengine/core/pull/5136

ENT-9711: Added condition to runalerts service to require stamp directory

---

misc/systemd/cf-runalerts.service.in

The directory really needs to exist in order for the service to update time-stamps. There is policy managing it's existence, so if we wait for it, it will appear.
Ticket: ENT-9711
(cherry picked from commit f9636ca357fdc9c4166c681675df91f623d30e10)
together:
https://github.com/cfengine/buildscripts/pull/1188
https://github.com/cfengine/masterfiles/pull/2569
https://github.com/cfengine/core/pull/5149

ENT-9711: Added condition to runalerts service to require stamp directory (3.18)

---

misc/systemd/cf-runalerts.service.in

The directory really needs to exist in order for the service to update time-stamps. There is policy managing it's existence, so if we wait for it, it will appear.
Ticket: ENT-9711
(cherry picked from commit f9636ca357fdc9c4166c681675df91f623d30e10) (cherry picked from commit db498ea4cca73faa106f82bf63c47e60bb30d08c)

ENT-9711: Added condition to runalerts service to require stamp directory (3.21)

---

libpromises/failsafe.cf

With this change if the agent bootstraps with debug, verbose, or info level
logging, sub-agent executions request the same log level. This can help
facilitate debugging of bootstrap issues.
Note: This change applies to failsafe as well, but as failsafe is an embedded
call, it wont currently happen unless a separate change tries to align failsafe
execution with the agent execution that failed.
Ticket: CFE-4121

CFE-4121: Changed bootstrap policy to preserve log level for debug, verbose, and info

---

libpromises/evalfunction.c

This change simply clarifies that the input to the function is a string and not
a data container.

ENT-9759: Fixed syntax description of validjson()

---

libpromises/evalfunction.c

This change simply clarifies that the input to the function is a string and not
a data container.

ENT-9759: Fixed syntax description of validjson() (3.21)

---

libpromises/evalfunction.c

This change simply clarifies that the input to the function is a string and not
a data container.

ENT-9759: Fixed syntax description of validjson() (3.18)

---

misc/selinux/Makefile.am
misc/selinux/cfengine-enterprise.te

by installing the .te and .fc files as well as the build .pp file
buildscripts repo will need install scripts changes to take advantage of this change.
Ticket: ENT-9685
https://github.com/cfengine/core/pull/5146
https://github.com/cfengine/buildscripts/pull/1187

ENT-9685: Enabled install-time selinux policy compiling

---

misc/Makefile.am

Needed to check shellcheck command differently.
Ticket: ENT-9340
(cherry picked from commit 999b930e6ba97f17a272d769a08730f05d9c4717)

ENT-9340: Fixed cf-support shellcheck check target (3.21)

---

misc/Makefile.am

Needed to check shellcheck command differently.
Ticket: ENT-9340
(cherry picked from commit 999b930e6ba97f17a272d769a08730f05d9c4717)

ENT-9340: Fixed cf-support shellcheck check target (3.18)

---

configure.ac

The CF3_WITH_LIBRARY and AC_CHECK_HEADERS were moved to outside of the check for with-libxml2=no
Ticket: CFE-4023

CFE-4023: Fixed --with-libxml2=no case in configure.ac

---

libpromises/expand.c

This naive change both removes un-necessary whitespace to align with the format
(namespace:bundle.varname) and fixes the output to include the variable name
instead of it's value.
Ticket: CFE-4122

CFE-4122: Fixed debug module expand logging for scalars

---

libpromises/expand.c

This change makes the log message less confusing as it used to look like
a variable expansion.
Ticket: CFE-4122
Co-authored-by: Nick Anderson <nick.anderson@northern.tech>
(cherry picked from commit fa903e9b03d05aa863df89be8ab5f56781b344fa)

CFE-4122: Fixed debug module expand logging for scalars (3.21)

---

libpromises/expand.c

This change makes the log message less confusing as it used to look like
a variable expansion.
Ticket: CFE-4122
Co-authored-by: Nick Anderson <nick.anderson@northern.tech>
(cherry picked from commit fa903e9b03d05aa863df89be8ab5f56781b344fa)

CFE-4122: Fixed debug module expand logging for scalars (3.18)

---

cf-agent/verify_files_utils.c
tests/acceptance/28_inform_testing/01_files/copy_from01.cf.expected
tests/acceptance/28_inform_testing/01_files/copy_from03.cf.expected
tests/acceptance/28_inform_testing/01_files/perms.cf
tests/acceptance/28_inform_testing/01_files/perms.cf.expected

Log message now says:
```
info: [Regular file|Directory|etc...] '/tmp/foo' had permissions 0600, changed it to 0700
```
instead of:
```
info: Object '/tmp/foo' had permissions 0600, changed it to 0700
```
Ticket: CFE-4109

CFE-4109: Log msg now mentions filetype when changing perms

---

configure.ac

The CF3_WITH_LIBRARY and AC_CHECK_HEADERS were moved to outside of the check for with-libxml2=no
Both in core and libntech (brought in by submodule update)
Ticket: CFE-4023

CFE-4023: Fixed --with-libxml2=no case in configure.ac (3.21)

---

.github/workflows/macos_unit_tests.yml
INSTALL
configure.ac
libenv/unix_iface.c

- Find openssl libraries in a more dynamic way.
- Fixup unix_iface.c compiler warnings.

ENT-9363: Improved MacOS Support

---

libpromises/cmdb.c

Now an error message is emitted instead, when array is empty:
```
error: Empty class specification '[]' in CMDB data not allowed, only '["any::"]'
```
Also added an error message when array contains more than one element:
```
error: Too many elements in class specification in CMDB data, only '["any::"]' allowed
```
And the old error message is now only emitted when array contains one
element that is not "any::":
```
error: Invalid class specification '["linux::"]' in CMDB data, only '["any::"]' allowed
```

CFE-4145: Fixed segfault caused by empty array in CMDB class specification

---

libpromises/mod_custom.c
libpromises/mod_custom.h
libpromises/policy.c
libpromises/signals.c
tests/acceptance/00_basics/ifelapsed_and_expireafter/expireafter.cf
tests/acceptance/00_basics/ifelapsed_and_expireafter/expireafter.cf.sub

Enable expireafter attribute for custom promise types.
Merge with:
- https://github.com/cfengine/masterfiles/pull/2526

CFE-3435: Enable expireafter attribute

---

examples/isreadable.cf
libpromises/evalfunction.c
tests/acceptance/01_vars/02_functions/isreadable.cf

Merge with:
- https://github.com/cfengine/documentation/pull/2951
TODO:

ENT-9380: Created new policy function isreadable

---

libpromises/cmdb.c

Now an error message is emitted instead, when array is empty:
```
error: Empty class specification '[]' in CMDB data not allowed, only '["any::"]'
```
Also added an error message when array contains more than one element:
```
error: Too many elements in class specification in CMDB data, only '["any::"]' allowed
```
And the old error message is now only emitted when array contains one element that is not "any::":
```
error: Invalid class specification '["linux::"]' in CMDB data, only '["any::"]' allowed
```

CFE-4145: Fixed segfault caused by empty array in CMDB class specification (3.18.x)

---

libpromises/cmdb.c

Now an error message is emitted instead, when array is empty:
```
error: Empty class specification '[]' in CMDB data not allowed, only '["any::"]'
```
Also added an error message when array contains more than one element:
```
error: Too many elements in class specification in CMDB data, only '["any::"]' allowed
```
And the old error message is now only emitted when array contains one element that is not "any::":
```
error: Invalid class specification '["linux::"]' in CMDB data, only '["any::"]' allowed
```
Cherry picked from https://github.com/cfengine/core/pull/5181

CFE-4145: Fixed segfault caused by empty array in CMDB class specification (3.21.x)

---

cf-agent/verify_files_utils.c
libpromises/files_lib.c
libpromises/files_lib.h
libpromises/files_links.c
tests/acceptance/28_inform_testing/01_files/copy_from01.cf.expected
tests/acceptance/28_inform_testing/01_files/copy_from02.cf.expected

Instead of creating the directories with the default file permissions,
then change them to the desired state; directories are now created with
the desired set of permissions.
```
info: Created file '/tmp/testfile', mode 0655
info: Created directory '/tmp/testdir/.', mode 0655
```

CFE-4114: Directories are now created with correct perms

---

libpromises/cmdb.c

Cherry picked from https://github.com/cfengine/core/pull/5188

Now prints problematic value when too many elements in CMDB class spec (3.18.x)

---

libpromises/cmdb.c

New output looks like this:
```
error: Too many elements in class specification '["any::","linux::"]' in CMDB data, only '["any::"]' allowed
```

Now prints problematic value when too many elements in CMDB class spec

---

cf-agent/verify_files_utils.c
libpromises/files_lib.c
libpromises/files_lib.h
libpromises/files_links.c
tests/acceptance/28_inform_testing/01_files/copy_from01.cf.expected
tests/acceptance/28_inform_testing/01_files/copy_from02.cf.expected

Instead of creating the directories with the default file permissions, then change them to the desired state; directories are now created with the desired set of permissions.
```
info: Created file '/tmp/testfile', mode 0655
info: Created directory '/tmp/testdir/.', mode 0655
```
Cherry picked from https://github.com/cfengine/core/pull/5193

CFE-4114: Directories are now created with correct perms (3.21.x)

---

libpromises/evalfunction.c
tests/acceptance/01_vars/02_functions/validjson_trailing_bogus_data.cf

Policy function validjson() no longer accepts trailing bogus data. I.e.
non-whitespace characters after json element termination.
Cherry picked from https://github.com/cfengine/core/pull/5191

CFE-4080: validjson() no longer accepts trailing bogus data (3.21.x)

---

misc/cf-support

Prior to this change cf-support would search for core files recursively to
infinity levels deep. This could be very expensive if a user typed in / as the
path for core files for example.
This change simply limits that recursion to a single level.
Ticket: ENT-9981

ENT-9981: Prevented cf-support from searching more than 1 level for core files

---

misc/cf-support

Prior to this change cf-support would search for core files recursively to
infinity levels deep. This could be very expensive if a user typed in / as the
path for core files for example.
This change simply limits that recursion to a single level.

ENT-9981: Prevented cf-support from searching more than 1 level for core files (3.21)

---

misc/cf-support

Prior to this change cf-support would search for core files recursively to
infinity levels deep. This could be very expensive if a user typed in / as the
path for core files for example.
This change simply limits that recursion to a single level.

ENT-9981: Prevented cf-support from searching more than 1 level for core files (3.18)

---

tests/acceptance/testall

Ticket: ENT-9891
Issue was that when "$RPMVERCMP" variable is not set, this command:
ln "$RPMVERCMP" "$WORKDIR/bin"
was printing an unhelpful error message that it can't overwrite a
directory, thus polluting logs.
So the solution is to not run this command when this variable is not
set, a.k.a. when we don't need rpmvercmp.

ENT-9891: Symlink rpmvercmp only when needed 

---

cf-agent/verify_methods.c
cf-net/cf-net.c
libcfnet/client_code.c
libpromises/evalfunction.c
libpromises/iteration.c
libpromises/sort.c

Really fixing compiler warnings from clang 14.
Ticket: ENT-9878

ENT-9878: Fixed compiler warnings for clang 14.0.3 (3.21)

---

tests/acceptance/testall

Ticket: ENT-9891
Issue was that when "$RPMVERCMP" variable is not set, this command:
ln "$RPMVERCMP" "$WORKDIR/bin"
was printing an unhelpful error message that it can't overwrite a directory, thus polluting logs.
So the solution is to not run this command when this variable is not set, a.k.a. when we don't need rpmvercmp.
(cherry picked from commit 3cec91067a300bf721610a08eb3909b41439a434)

Symlink rpmvercmp only when needed (3.21)

---

tests/acceptance/testall

Ticket: ENT-9891
Issue was that when "$RPMVERCMP" variable is not set, this command:
ln "$RPMVERCMP" "$WORKDIR/bin"
was printing an unhelpful error message that it can't overwrite a directory, thus polluting logs.
So the solution is to not run this command when this variable is not set, a.k.a. when we don't need rpmvercmp.
(cherry picked from commit 3cec91067a300bf721610a08eb3909b41439a434)

Symlink rpmvercmp only when needed (3.18)

---

.github/workflows/valgrind.yml

Ticket: ENT-10190
(cherry picked from commit ed867c06259bd3ed1d00dcd6d673316c05d9e03f)
Conflicts:
.github/workflows/job-static-check.yml
.github/workflows/job-valgrind-check.yml
.github/workflows/valgrind.yml
valgrind.yml needed and upgrade, the other two are not present in 3.21.x and so were removed

ENT-10190: Upgraded together javascript action (3.18)

---

.github/workflows/valgrind.yml

Ticket: ENT-10190
(cherry picked from commit ed867c06259bd3ed1d00dcd6d673316c05d9e03f)
Conflicts:
.github/workflows/job-static-check.yml
.github/workflows/job-valgrind-check.yml
.github/workflows/valgrind.yml
valgrind.yml needed and upgrade, the other two are not present in 3.21.x and so were removed

ENT-10190: Upgraded together javascript action (3.21)

---

.github/workflows/job-static-check.yml
.github/workflows/job-valgrind-check.yml
.github/workflows/valgrind.yml

When a PR is merged a push event occurs and workflows are triggered.
At this time an empty ref: will default to master instead of the appropriate branch.
So include github.base_ref and github.ref as fallbacks.
Ticket: ENT-10172

ENT-10172: Fixed workflow refs for push events

---

misc/selinux/cfengine-enterprise.te

Needed by rhel-9.2 linux kernel
Ticket: ENT-10206
(cherry picked from commit f3ef17c3ec2d8afb35a73ced6938750aefb84a5f)

ENT-10206: Added mctp_socket class to selinux policy (3.18)

---

misc/selinux/cfengine-enterprise.te

Needed by rhel-9.2 linux kernel
Ticket: ENT-10206
(cherry picked from commit f3ef17c3ec2d8afb35a73ced6938750aefb84a5f)

ENT-10206: Added mctp_socket class to selinux policy (3.21)

---

configure.ac

The CF3_WITH_LIBRARY and AC_CHECK_HEADERS were moved to outside of the check for with-libxml2=no
Ticket: CFE-4023
Also required earlier change that was not cherry picked to 3.18.x
configure.ac: Enabled use of pkg-config to find libxml2
Debian is taking steps towards removing xml2-config in favour of pkg-config.
This means cfengine3 will build without libxml2 support.
This patch modifies configure.ac to detect libxml2 via pkg-config, falling
back to xml2-config if pkg-config is not available.
Ticket: CFE-4014
Signed-off-by: Hugh McMaster <hugh.mcmaster@outlook.com>

CFE-4023: Fixed --with-libxml2=no case in configure.ac (3.18)

---

libpromises/evalfunction.c
tests/acceptance/08_commands/01_modules/set-tags.cf
tests/acceptance/08_commands/01_modules/vars-from-module-have-source-and-derived_from-tags.cf

According to the docs; all variables and classes will be tagged with `source=module`. This was apparently only the case when specifying tags using `^meta=Tag1,Tag2`. Now this tag is added all the time, even when you don't specify tags.
Furthermore, we added an additional meta tag `derived_from=<SOME_COMMAND>` which holds the path to the module script when using the `usemodule()` policy function or the command when using a commands promise with `module => "true"`.
Example output when using both `usemodule()` and commands promise without specifying meta tags:
```
$ sudo cf-agent -KIf ~/test.cf 
info: Executing 'no timeout' ... '/bin/echo "=bogus=Hello CFEngine!"'
info: Completed execution of '/bin/echo "=bogus=Hello CFEngine!"'
R: getvariablemetatags(doofus.doofus) => '{ "source=module", …
```

ENT-7725: Variables & Classes Modules automatically tagged

---

ChangeLog
configure.ac

I had to revert these three commits to make 3.18.x build on Solaris 10 and HP-UX. I believe they're not really necessary?
Failures were:
On Solaris 10 (both SPARC and x86):
```
00:16:20.675 xml-c14nize.c: In function ‘xmlC14nizeFile’:
00:16:21.104 xml-c14nize.c:25:37: error: ‘XML_C14N_1_0’ undeclared (first use in this function)
00:16:21.129      if (xmlC14NDocSaveTo(doc, NULL, XML_C14N_1_0, 0, true, out) < 0)
00:16:21.129                                      ^
```
on HP-UX:
```
00:10:41.199 checking for xmlFirstElementChild in -lxml2... ./configure[15954]: /var/cfengine/bin/xml2-config:  not found.
00:10:41.570 yes
00:10:41.596 checking libxml/xmlwriter.h usability... no
00:10:41.912 checking libxml/xmlwriter.h presence... no
00:10:42.147 checking for libxml/xmlwriter.h... no …
```

Fix building on solaris and hpux

---

libpromises/cmdb.c

The function that adds CMDB classes to the context, checks if the class is already there. If this is the case, it skips adding the class and returns false. The code using this function interpreted false as an error, which is not the case.
Back ported from https://github.com/cfengine/core/pull/5263

ENT-10336: Fixed misleading error message when adding CMDB classes (3.18.x)

---

libpromises/cmdb.c

The function that adds CMDB classes to the context, checks if the class is already there. If this is the case, it skips adding the class and returns false. The code using this function interpreted false as an error, which is not the case.
Back ported from https://github.com/cfengine/core/pull/5263

ENT-10336: Fixed misleading error message when adding CMDB classes (3.21.x)

---

libpromises/evalfunction.c

This function takes a string, and not a data container, it has confused people.
Ticket: ENT-9759
(cherry picked from commit c4ffbdb1e1c4b2186107f1647c4c0ae2aedf48c6)

ENT-9759: Improved syntax description for validjson() (3.21)

---

libpromises/dbm_api.c
libpromises/dbm_api.h
libpromises/evalfunction.c

If default software inventory from context is not specified, the package[update]smatching policy functions now looks for the software inventory databases in the state directory and uses them if found. This change enables the usage of these functions in standalone policy files without the demand for specifying the default package inventory attribute in body common control. However, you still need the default package inventory attribute specified in the policy framework for the software inventory databases to exist in the first place and to be maintained.

ENT-9083: package[update]smatching now looks for software inventory databases

---

README.md

(cherry picked from commit 66490d6c29fb6145e6933c46fc27f4acd95624ef)

Removed LGTM banner that no longer works (3.18)

---

.github/workflows/ci.yml

We don't have easy visibility on the results of these events which only occur after we merge pull requests.
We use /merge refs in pull requests so running the actions again on push events (after the merge) don't really provide any additional information.
Pushes/commits to pull requests are handled by the pull_request event so no change there.
See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
Ticket: ENT-10428

ENT-10428: Removed push event handling in github actions workflow

---

.github/workflows/ci.yml

We don't have easy visibility on the results of these events which only occur after we merge pull requests.
We use /merge refs in pull requests so running the actions again on push events (after the merge) don't really provide any additional information.
Pushes/commits to pull requests are handled by the pull_request event so no change there.
See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
Ticket: ENT-10428
(cherry picked from commit 81b49e7b0edec53133d16b9dbe0ac8dfba17a7b5)

ENT-10428: Removed push event handling in github actions workflow (3.21)

---

.github/workflows/ci.yml

We don't have easy visibility on the results of these events which only occur after we merge pull requests.
We use /merge refs in pull requests so running the actions again on push events (after the merge) don't really provide any additional information.
Pushes/commits to pull requests are handled by the pull_request event so no change there.
See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
Ticket: ENT-10428
(cherry picked from commit 81b49e7b0edec53133d16b9dbe0ac8dfba17a7b5)
Conflicts:
.github/workflows/ci.yml
Different branches were mentioned in push event handling but we removed it entirely so no significant conflict.

ENT-10428: Removed push event handling in github actions workflow (3.18)

---

libpromises/dbm_api.c
libpromises/dbm_api.h
libpromises/evalfunction.c

If the default software inventory from context is not specified, the package[update]smatching policy functions now looks for the software inventory databases in the state directory and uses them if found. This change enables the usage of these functions in standalone policy files without the demand for specifying the default package inventory attribute in body common control. However, you still need the default package inventory attribute specified in the policy framework for the software inventory databases to exist in the first place and to be maintained.
Cherry picked from https://github.com/cfengine/core/pull/5274

ENT-9083: package[update]smatching now looks for software inventory databases (3.21.x)

---

libpromises/dbm_api.c
libpromises/dbm_api.h
libpromises/evalfunction.c

If the default software inventory from context is not specified, the package[update]smatching policy functions now looks for the software inventory databases in the state directory and uses them if found. This change enables the usage of these functions in standalone policy files without the demand for specifying the default package inventory attribute in body common control. However, you still need the default package inventory attribute specified in the policy framework for the software inventory databases to exist in the first place and to be maintained.
https://github.com/cfengine/core/pull/5274

ENT-9083: package[update]smatching now looks for software inventory databases (3.18.x)

---

tests/unit/passopenfile_test.c

This reverts commit dbda08aec9e1590a7b841740bb22bccec11fbb84.
Ticket: CFE-4249
Turns out it is still failing even in github. Already reverted in 3.18.x and 3.21.x.

CFE-4249: Revert "Re-enabled passopenfile_test after migrating to github actions"

---

libpromises/rlist.c
tests/acceptance/01_vars/04_containers/execresult_and_as_data.cf
tests/unit/rlist_test.c

The original issue that leads to this is the fact that the caches for execresult and execresult_as_data were mixed ([CFE-4244](https://northerntech.atlassian.net/browse/CFE-4244)). This is caused by two separate issues:
* The function cache uses the args list as key and discards the function itself. This means different functions with the same args are considered identical, and cache is reused.
https://github.com/cfengine/core/blob/57745c7afbd200a26b79a3a4dd79851781ff7ff1/libpromises/eval_context.c#L2840
* The function args are passed as an Rlist, and the comparison used ignores the additional items of the longest list when comparing two lists of different lengths, leading to treating execresult and execresult_as_data as identical when using the same command and shell args.
This PR only …

CFE-4244: Fix RlistEqual comparison on lists of different lengths

---

libpromises/rlist.c
tests/acceptance/01_vars/04_containers/execresult_and_as_data.cf
tests/unit/rlist_test.c

The original issue that leads to this is the fact that the cache
for execresult and execresult_as_data were mixed. This is caused by two
separate issues:
* The function cache uses the args list as key and discards the function
itself. This means different function with the same args are considered
identical, and cache is reused.
* The args are passed as an Rlist, and the used Rlist comparison ignores the
additional items of the longest list when comparing two lists of
different lengths, leading to treating execresult and execresult_as_data
as identical when using the same command and shell args.
This PR only fixes the specific case of execresult, but leaves other
function cache issues (e.g. host2ip vs. ip2host could be confused).
(cherry picked from commit …

CFE-4244: Fix RlistEqual comparison on lists of different lengths (3.21.x)

---

libpromises/rlist.c
tests/acceptance/01_vars/04_containers/execresult_and_as_data.cf
tests/unit/rlist_test.c

The original issue that leads to this is the fact that the cache
for execresult and execresult_as_data were mixed. This is caused by two
separate issues:
* The function cache uses the args list as key and discards the function
itself. This means different function with the same args are considered
identical, and cache is reused.
* The args are passed as an Rlist, and the used Rlist comparison ignores the
additional items of the longest list when comparing two lists of
different lengths, leading to treating execresult and execresult_as_data
as identical when using the same command and shell args.
This PR only fixes the specific case of execresult, but leaves other
function cache issues (e.g. host2ip vs. ip2host could be confused).
(cherry picked from commit …

CFE-4244: Fix RlistEqual comparison on lists of different lengths (3.18.x)

---

libpromises/eval_context.c
tests/acceptance/01_vars/02_functions/cache_name.cf

The function cache only used the args values as key, which in some cases could lead to mixing results from different functions with the same arguments.
Related to #5313.

CFE-4244: Add the function name to the result cache key

---

libpromises/eval_context.c
tests/acceptance/01_vars/02_functions/cache_name.cf

The function cache only used the args values, which in some cases could
lead to mixing results from different functions with the same arguments.
Ticket: CFE-4244
Changelog: Cashed policy function results now take into account number of arguments and function name.
Co-authored-by: Alexis Mousset <alexis.mousset@rudder.io>
(cherry picked from commit 29e60a9ba05016847c3b601f469bcb5e19147960)
Backported from https://github.com/cfengine/core/pull/5317

CFE-4244: Added the function name to the result cache key (3.21.x)

---

libpromises/eval_context.c
tests/acceptance/01_vars/02_functions/cache_name.cf

The function cache only used the args values, which in some cases could
lead to mixing results from different functions with the same arguments.
Ticket: CFE-4244
Changelog: Cashed policy function results now take into account number of arguments and function name.
Co-authored-by: Alexis Mousset <alexis.mousset@rudder.io>
(cherry picked from commit 29e60a9ba05016847c3b601f469bcb5e19147960)
Back-ported from https://github.com/cfengine/core/pull/5317

CFE-4244: Added the function name to the result cache key (3.18.x)

---

tests/acceptance/08_commands/01_modules/long-module-lines.cf
tests/acceptance/09_services/custom.cf
tests/acceptance/09_services/disable.cf
tests/acceptance/09_services/enable.cf
tests/acceptance/09_services/reload.cf
tests/acceptance/09_services/restart.cf
tests/acceptance/09_services/service_cannot_be_resolved.cf
tests/acceptance/09_services/start.cf
tests/acceptance/09_services/stop.cf

Ticket: ENT-10470
Issue was that these failures were visible in Jenkins, turning build "unstable".

Change suppress fail to soft fail on known failing tests

---

libpromises/rlist.c
tests/acceptance/00_basics/03_bodies/inherit_from_with_global_var.cf

This also prevents a memory corruption when an inherited attribute contains external vars but no local vars.
https://northerntech.atlassian.net/browse/CFE-4254

CFE-4254: Allow inheriting attributes using global variables in bodies having local parameters

---

libpromises/rlist.c
tests/acceptance/00_basics/03_bodies/inherit_from_with_global_var.cf

Back-ported from https://github.com/cfengine/core/pull/5324

CFE-4254: Allow inheriting attributes using global variables in bodies having local parameters (3.21.x)

---

libpromises/rlist.c
tests/acceptance/00_basics/03_bodies/inherit_from_with_global_var.cf

Back-ported from https://github.com/cfengine/core/pull/5324

CFE-4254: Allow inheriting attributes using global variables in bodies having local parameters (3.18.x)

---

cf-key/cf-key-functions.c
cf-serverd/server_classic.c
libcfnet/client_code.c
libcfnet/client_protocol.c
libpromises/crypto.c
libpromises/generic_agent.c
libpromises/locks.c

We require OpenSSL 1.0.0 or newer so we don't need this compatibility code for older versions.
https://github.com/cfengine/core/pull/5332
https://github.com/cfengine/nova/pull/2124

Do not #include libcrypto-compat

---

misc/selinux/cfengine-enterprise.te

https://github.com/cfengine/nova/commit/8b8726e7b2896d601f05d1b4392abef705d1489a
changed cf-hub behavior for ENT-9825
This change fixes an issue with hubs that have SELinux set to enforce.
Hubs which do not have SELinux set to enforce are unaffected by this issue.
Ticket: ENT-10696

ENT-10696: Added selinux policy to allow cf-hub to initiate scheduled reports

---

misc/selinux/cfengine-enterprise.te

https://github.com/cfengine/nova/commit/8b8726e7b2896d601f05d1b4392abef705d1489a
changed cf-hub behavior for ENT-9825
This change fixes an issue with hubs that have SELinux set to enforce.
Hubs which do not have SELinux set to enforce are unaffected by this issue.
Ticket: ENT-10696
(cherry picked from commit 48ed76f8d5cb3c2cee72b456960362108a119a45)

ENT-10696: Added selinux policy to allow cf-hub to initiate scheduled reports (3.18)

---

misc/selinux/cfengine-enterprise.te

https://github.com/cfengine/nova/commit/8b8726e7b2896d601f05d1b4392abef705d1489a
changed cf-hub behavior for ENT-9825
This change fixes an issue with hubs that have SELinux set to enforce.
Hubs which do not have SELinux set to enforce are unaffected by this issue.
Ticket: ENT-10696
(cherry picked from commit 48ed76f8d5cb3c2cee72b456960362108a119a45)

ENT-10696: Added selinux policy to allow cf-hub to initiate scheduled reports (3.21)

---

.github/workflows/ci.yml

- cf-agent.exe is not always installed "in-time" ENT-10699
- job uses latest nightly instead of building the PR code ENT-10754
Ticket: none

Disable win-acceptance tests for now due to two issues

---

tests/acceptance/31_tickets/ENT-8788/1/main.cf
tests/acceptance/31_tickets/ENT-8788/2/main.cf

Their first run they change an original/source file and so on subsequent runs
the tests failed due to the original being incorrect.
Ticket: ENT-10761

ENT-10761: Fixed two acceptance tests which could only run once before failing

---

contrib/masterfiles-stage/common.sh

LANG is not sufficient to guard against odd environment vars, LC_ALL is a master override so prefer that.
Ticket: ENT-10753
together
https://github.com/cfengine/nova/pull/2129
https://github.com/cfengine/core/pull/5344

ENT-10753: Improved locale override in masterfiles stage scripts

---

tests/acceptance/31_tickets/ENT-8788/1/main.cf
tests/acceptance/31_tickets/ENT-8788/2/main.cf

Their first run they change an original/source file and so on subsequent runs the tests failed due to the original being incorrect.
Ticket: ENT-10761
(cherry picked from commit c8af66eb2b802230b92e8cb6708dfd1c7903c633)

ENT-10761: Fixed two acceptance tests which could only run once before failing  (3.21)

---

tests/acceptance/31_tickets/ENT-8788/1/main.cf
tests/acceptance/31_tickets/ENT-8788/2/main.cf

Their first run they change an original/source file and so on subsequent runs the tests failed due to the original being incorrect.
Ticket: ENT-10761
(cherry picked from commit c8af66eb2b802230b92e8cb6708dfd1c7903c633)

ENT-10761: Fixed two acceptance tests which could only run once before failing (3.18)

---

cf-agent/cf-agent.c
cf-check/cf-check.c
cf-execd/cf-execd.c
cf-key/cf-key.c
cf-monitord/cf-monitord.c
cf-net/cf-net.c
cf-promises/cf-promises.c
cf-runagent/cf-runagent.c
cf-secret/cf-secret.c
cf-serverd/cf-serverd-functions.c
cf-testd/cf-testd.c
configure.ac
tests/acceptance/mock_package_manager.c

https://github.com/cfengine/core/pull/5339
https://github.com/cfengine/nova/pull/2128

Modify all calls to `WriterWriteHelp` to adapt to API change

---

cf-check/cf-check.c

Add `COMMANDS` to the help text call, which was missing when `cf-check` was updated to use the common `libntech` formatting.
Amends commit 3de33e9a6abdb894f804a62a2441beac729c5072

fix help text for `cf-check`

---

contrib/masterfiles-stage/common.sh

LANG is not sufficient to guard against odd environment vars, LC_ALL is a master override so prefer that.
Ticket: ENT-10753
(cherry picked from commit 3cefecb184b3d0a371a22436220eae1b2dcd94f8)
together
https://github.com/cfengine/nova/pull/2141
https://github.com/cfengine/core/pull/5355

ENT-10753: Improved locale override in masterfiles stage scripts (3.21)

---

contrib/masterfiles-stage/common.sh

LANG is not sufficient to guard against odd environment vars, LC_ALL is a master override so prefer that.
Ticket: ENT-10753
(cherry picked from commit 3cefecb184b3d0a371a22436220eae1b2dcd94f8)

ENT-10753: Improved locale override in masterfiles stage scripts (3.18)

---

libenv/unix_iface.c

- https://github.com/cfengine/masterfiles/pull/2750
- https://github.com/cfengine/documentation/pull/3102
PR includes:
- Formatted InitIgnoreInterfaces() with clang-format
- Moved ignore_interfaces.rx to $(sys.workdir)
- Added error message based on errno to InitIgnoreInterfaces()
- Fixed infinite loop on error bug while reading interface exception file
Demo:
```
root@hub:/var/cfengine/inputs# /var/cfengine/bin/cf-agent -KI
warning: Found interface exception file ignore_interfaces.rx in /var/cfengine/inputs but it should be in /var/cfengine. Please consider moving it to the appropriate location.
warning: Found interface exception file ignore_interfaces.rx in /var/cfengine/inputs but it should be in /var/cfengine. Please consider moving it to the appropriate location. …
```

ENT-9402: Moved ignore_interfaces.rx to $(sys.workdir)

---

libenv/unix_iface.c

Fixed bug where the agent may enter an infinite loop while trying to read the interface exception file. The problem comes from the fact that the while loop for reading each line in the file checks for end-of-file, but not error. If an error occurs, end-of-file will never be reached, hence the loop will never break.
Back-ported from https://github.com/cfengine/core/pull/5357

Fixed infinite loop on error bug while reading interface exception file (3.21.x)

---

libenv/unix_iface.c

Fixed bug where the agent may enter an infinite loop while trying to read the interface exception file. The problem comes from the fact that the while loop for reading each line in the file checks for end-of-file, but not error. If an error occurs, end-of-file will never be reached, hence the loop will never break.
Back-ported from https://github.com/cfengine/core/pull/5357

Fixed infinite loop on error bug while reading interface exception file (3.18.x)

---

cf-check/dump.c
libpromises/locks.c
libpromises/locks.h
misc/systemd/cf-apache.service.in
misc/systemd/cf-execd.service.in
misc/systemd/cf-hub.service.in
misc/systemd/cf-monitord.service.in
misc/systemd/cf-postgres.service.in
misc/systemd/cf-reactor.service.in
misc/systemd/cf-runalerts.service.in
misc/systemd/cf-serverd.service.in

https://github.com/cfengine/core/pull/5362
https://github.com/cfengine/buildscripts/pull/1332
https://github.com/cfengine/masterfiles/pull/2760

CFE-3982: Random process killing

---

tests/acceptance/16_cf-serverd/serial/simple_copy_from_admit_localhost.cf
tests/acceptance/16_cf-serverd/serial/simple_copy_from_deny_localhost.cf

We should to investigate this, but first we should to get Debian 12 into the next release. See ticket ENT-9055.
- https://github.com/cfengine/system-testing/pull/506
- https://github.com/mendersoftware/infra/pull/382
- https://github.com/cfengine/buildscripts/pull/1313

ENT-10347: Skip failing tests on Debian 12

---

contrib/masterfiles-stage/common.sh

When policy is tagged (with cf-promises -T) cf-promises looks for .git/HEAD and
uses it's content as the policy release id in the generated
cf_promises_release_id file. If .git/HEAD does not exist the policy tree is
hashed and that value is used instead.
For traditional deployments straight from version control, this works. When
deploying from cfbs .git/HEAD needs to be copied to out/masterfiles or it won't
be part of the tagged policy. This change adjusts the target appropriately when
deploying with cfbs.
Ticket: ENT-10832
(cherry picked from commit 89ab485968e1eb420c9659395cb2f334a60935f7)

ENT-10832: Fixed inventoried policy release id when masterfiles-stage.sh deploys with cfbs (3.21)

---

contrib/masterfiles-stage/common.sh

When policy is tagged (with cf-promises -T) cf-promises looks for .git/HEAD and
uses it's content as the policy release id in the generated
cf_promises_release_id file. If .git/HEAD does not exist the policy tree is
hashed and that value is used instead.
For traditional deployments straight from version control, this works. When
deploying from cfbs .git/HEAD needs to be copied to out/masterfiles or it won't
be part of the tagged policy. This change adjusts the target appropriately when
deploying with cfbs.
Ticket: ENT-10832
(cherry picked from commit 89ab485968e1eb420c9659395cb2f334a60935f7)

ENT-10832: Fixed inventoried policy release id when masterfiles-stage.sh deploys with cfbs (3.18)

---

examples/const.cf
libenv/constants.c
tests/acceptance/00_basics/linesep.cf

- Added new platform-agnostic constant `linesep`
- Added `linesep` to constants example
- Added acceptance test for `linesep` constant
Merge together with https://github.com/cfengine/documentation/pull/3106

ENT-10432: Added new platform-agnostic constant `linesep`

---

libenv/unix_iface.c

Back-ported from https://github.com/cfengine/core/pull/5357

ENT-9402: Moved ignore_interfaces.rx to $(sys.workdir) (3.21.x)

---

tests/acceptance/02_classes/01_basic/simplistic_ipaddr_classes.cf

Merge together with https://github.com/cfengine/enterprise/pull/772

ENT-2044: Added acceptance test for IP-address classes

---

cf-check/diagnose.c
cf-check/diagnose.h
cf-check/dump.c
cf-check/repair.c
cf-check/repair.h
cf-check/validate.c
libpromises/dbm_api.c
libpromises/dbm_api.h
libpromises/dbm_lmdb.c
libpromises/dbm_priv.h
libpromises/dbm_quick.c
libpromises/dbm_tokyocab.c
libpromises/locks.c

[3.18.x] A few LMDB related fixes and improvements

---

libpromises/unix.c

https://northerntech.atlassian.net/browse/CFE-4256
~Still not tested.~ Now tested on a system where this error occurred.

CFE-4256: Fallback on /usr/bin/getent when /bin/getent does not exist

---

libpromises/unix.c

Ticket: CFE-4256
Changelog: /usr/bin/getent is now attempted to be used if
/bin/getent doesn't exist
(cherry picked from commit 08ae1d1be363bdda5629de6c719b423b2fdad8b0)

[3.18.x] Fallback to /usr/bin/getent when /bin/getent doesn't exist

---

libpromises/unix.c

Ticket: CFE-4256
Changelog: /usr/bin/getent is now attempted to be used if
/bin/getent doesn't exist
(cherry picked from commit 08ae1d1be363bdda5629de6c719b423b2fdad8b0)

[3.21.x] Fallback to /usr/bin/getent when /bin/getent doesn't exist

---

cf-execd/cf-execd.c

Happens on Debian 12:
```
info: Socket "/var/cfengine/state/./cf-execd.sockets/runagent.socket" had permissions 0700, changed it to 0600
info: Directory "/var/cfengine/state/./cf-execd.sockets" had permissions 0750, changed it to 0700
```
Merge together with:
- https://github.com/NorthernTechHQ/infra/pull/416
- https://github.com/cfengine/system-testing/pull/510
- https://github.com/cfengine/buildscripts/pull/1337

ENT-10347: Fixed changing perms noise in no-noise sequential test

---

cf-key/cf-key.c

Getting the digest needs crypto functions and finalization also
unloads crypto providers. Also, it just doesn't make sense.

Do not finalize things before printing digest in cf-key

---

tests/static-check/run.sh

Was trying to run on debian-11 which had dns issues and couldn't see the error easily.
Ticket: CFE-4295

CFE-4295: Adjusted static-check/run.sh to expose errors in create_image()

---

INSTALL

rhel needs fakeroot for make check
debian seems to include fakeroot in existing deps in INSTALL file
both need libxml2 development package to pass make check
Ticket: none
(cherry picked from commit 3c6b07059ef97efc3a42098f214a0c1f3f7fab67)

Updated source install instructions for RedHat/CentOS/Debian (3.18)

---

tests/static-check/run.sh

Was trying to run on debian-11 which had dns issues and couldn't see the error easily.
Ticket: CFE-4295
(cherry picked from commit c54801546100be7dc160aaf417f4f80206ed2a53)

CFE-4295: Adjusted static-check/run.sh to expose errors in create_image() (3.18)

---

misc/cf-support

Had a --no-lock argument which is not supported so nothing was collected.
Ticket: CFE-4300

CFE-4300: Fixed cf-support call to cf-promises to collect all classes and vars

---

misc/cf-support

Had a --no-lock argument which is not supported so nothing was collected.
Ticket: CFE-4300
(cherry picked from commit bc8a0de71e63a26fb689dab4f0011935e9c3def9)

CFE-4300: Fixed cf-support call to cf-promises to collect all classes and vars (3.18)

---

misc/cf-support

Had a --no-lock argument which is not supported so nothing was collected.
Ticket: CFE-4300
(cherry picked from commit bc8a0de71e63a26fb689dab4f0011935e9c3def9)

CFE-4300: Fixed cf-support call to cf-promises to collect all classes and vars (3.21)

---

cf-execd/cf-execd.c
tests/acceptance/16_cf-serverd/serial/simple_copy_from_admit_localhost.cf
tests/acceptance/16_cf-serverd/serial/simple_copy_from_deny_localhost.cf

* https://github.com/cfengine/buildscripts/pull/1357

ENT-11046: Skip failing tests on Debian 12 (3.21.x)

---

cf-execd/cf-execd.c
libpromises/files_lib.c
libpromises/files_lib.h
tests/acceptance/16_cf-serverd/serial/simple_copy_from_admit_localhost.cf
tests/acceptance/16_cf-serverd/serial/simple_copy_from_deny_localhost.cf

* https://github.com/cfengine/buildscripts/pull/1356

ENT-10997: Skip failing tests on Debian 12 (3.18.x)

---

cf-agent/verify_exec.c
cf-monitord/history.c
libpromises/exec_tools.c
libpromises/exec_tools.h
libpromises/pipes.h
libpromises/pipes_unix.c
libpromises/unix.c
tests/acceptance/08_commands/arglist.cf
tests/unit/arg_split_test.c

Merge together with:
- https://github.com/cfengine/enterprise/pull/775
- https://github.com/cfengine/masterfiles/pull/2804

CFE-2724: The `arglist` attribute now preserves spaces in arguments

---

ChangeLog
misc/selinux/cfengine-enterprise.te.all

Needed for httpd/php to monitor exporting large PDF reports.
Changelog: SELinux no longer breaks exporting large reports as PDF (cherry picked from commit 0229b4006c243a6dd0d7c0bdab74a637310a804f)

[3.18.x] Allow httpd to run `ps` and get info about processes

---

ChangeLog
misc/selinux/cfengine-enterprise.te.all

Needed for httpd/php to monitor exporting large PDF reports.
Changelog: SELinux no longer breaks exporting large reports as PDF (cherry picked from commit 0229b4006c243a6dd0d7c0bdab74a637310a804f)

[3.21.x] Allow httpd to run `ps` and get info about processes

---

misc/selinux/cfengine-enterprise.te.all

It needs to be able to actually execute `/bin/ps` (and `/bin/bash`, but that's already allowed) and read `/proc`.

More SELinux policy changes for httpd/php to run ps

---

misc/selinux/cfengine-enterprise.te.all

It needs to be able to actually execute `/bin/ps` (and `/bin/bash`, but that's already allowed) and read `/proc`.
(cherry picked from commit d34bdf5a52a309354a7d28274637653706ae4823)

[3.21.x] More SELinux policy changes for httpd/php to run ps

---

misc/selinux/cfengine-enterprise.te.all

It needs to be able to actually execute `/bin/ps` (and `/bin/bash`, but that's already allowed) and read `/proc`.
(cherry picked from commit d34bdf5a52a309354a7d28274637653706ae4823)

[3.18.x] More SELinux policy changes for httpd/php to run ps

---

INSTALL

rhel needs fakeroot for make check
debian seems to include fakeroot in existing deps in INSTALL file
both need libxml2 development package to pass make check
Ticket: none
(cherry picked from commit 3c6b07059ef97efc3a42098f214a0c1f3f7fab67)

Updated source install instructions for RedHat/CentOS/Debian (3.21)

---

tests/static-check/run.sh

Was trying to run on debian-11 which had dns issues and couldn't see the error easily.
Ticket: CFE-4295
(cherry picked from commit c54801546100be7dc160aaf417f4f80206ed2a53)

CFE-4295: Adjusted static-check/run.sh to expose errors in create_image() (3.21)

---

cf-agent/verify_users_pam.c
cf-check/diagnose.c
tests/static-check/run_checks.sh

Apparently config.h is not included from platform.h because HAVE_CONFIG_H is not defined or not checked as a possibility soon enough by cppcheck.
Ticket: CFE-4310

CFE-4310: Fixed static-check job by forcing inclusion of config.h

---

configure.ac

Previously --with-systemd-socket is defaulted to true always.
If a system has libsystemd-dev and configure is called with --with-systemd-service=no the build would fail.
Ticket: CFE-4274
(cherry picked from commit a12d12a0089c012a9fa2f17c094f4555b8371be4)

In configure.ac, force with-systemd-socket=no when with-systemd-service=no (3.21)

---

configure.ac

Previously --with-systemd-socket is defaulted to true always.
If a system has libsystemd-dev and configure is called with --with-systemd-service=no the build would fail.
Ticket: CFE-4274
(cherry picked from commit a12d12a0089c012a9fa2f17c094f4555b8371be4)

In configure.ac, force with-systemd-socket=no when with-systemd-service=no (3.18)

---

tests/static-check/run_checks.sh

Apparently config.h is not included from platform.h because HAVE_CONFIG_H is not defined or not checked as a possibility soon enough by cppcheck.
Ticket: CFE-4310
(cherry picked from commit d8f2a75db2ab826c80051b035f569142a663d8b9)

Fixed static-check job by forcing inclusion of config.h (3.21)

---

cf-agent/cf-agent.c
libpromises/generic_agent.c
libpromises/generic_agent.h

Ticket: ENT-10792
Changelog: cf-agent has two new options --no-augments and
--no-host-specific-data to skip loading augments (def.json)
and host-specific data (host_specific.json), respectively

Add options to skip loading augments and host-specific data to cf-agent

---

cf-agent/cf-agent.c
libpromises/generic_agent.c
libpromises/generic_agent.h

Ticket: ENT-10792
Changelog: cf-agent has two new options --no-augments and
--no-host-specific-data to skip loading augments
(def.json or def_preferred.json) and host-specific
data (host_specific.json), respectively
(cherry picked from commit 9aa4767eaa311b0558ea0f97a8420f475e877d21)

[3.21.x] Add options to skip loading augments and host-specific data to cf-agent

---

libpromises/dbm_test_api.c

Not the boolean values we use to determine if the thread values are valid.
Ticket: CFE-4281

Pass the actual simulation threads to pthread_join functions

---

cf-agent/verify_files.c
libpromises/cf3parse.y
libpromises/cf3parse_logic.h
libpromises/parser.c
libpromises/parser.h
libpromises/policy.c
tests/unit/data/benchmark.cf
tests/unit/policy_test.c

- Agent now warns on unresolved function arguments
- Agent no longer warns if there are no action in files promise
- Added warning to parser in case of promises with no action requested
```
$ cat ~/foo.cf 
{
files:
"/tmp/testfile"
comment => "No action";
}
$ sudo /var/cfengine/bin/cf-agent -KIf ~/foo.cf 
/home/vagrant/foo.cf:5:32: warning: No action requested for files promise with promiser '/tmp/testfile' in /home/vagrant/foo.cf:main close to line 4 [-Wsanity-check]
comment => "No action";
^
```
```
$ cat bar.cf 
{
files:
"/tmp/testfile"
content => concat("$(bogus)", "doofus");
}
$ sudo /var/cfengine/bin/cf-agent -KIf ~/bar.cf 
warning: Function 'concat' in promise '/home/vagrant/bar.cf' near line 4 contains unresolved arguments on last pass
$ sudo …
```

ENT-11137: Warn if no action requested when parsing

---

cf-agent/verify_files.c
tests/acceptance/10_files/10_links/owner-mismatch-link-and-target.cf
tests/acceptance/28_inform_testing/01_files/perms.cf
tests/acceptance/28_inform_testing/01_files/perms.cf.expected

If the promiser is a symlink, `lstat()` and `stat()` give different results. We need to use `lstat()` to get info about the promiser (symlink) itself.
Also, we need to call `VerifyFileLeaf()` on symlinks as well as on regular files.
Ticket: ENT-11235

Carefully handle symlinks at the last phase of VerifyFilePromise()

---

cf-agent/verify_files.c
tests/acceptance/10_files/10_links/owner-mismatch-link-and-target.cf

If the promiser is a symlink, `lstat()` and `stat()` give different results. We need to use `lstat()` to get info about the promiser (symlink) itself.
Also, we need to call `VerifyFileLeaf()` on symlinks as well as on regular files.
Ticket: ENT-11235
Changelog: Ownership of symlinks is now handled properly (cherry picked from commit 84b67836aa7dcaa2e949c8a03ea80fadac0568d7)
Conflicts:
tests/acceptance/28_inform_testing/01_files/perms.cf.expected

[3.21.x] Carefully handle symlinks at the last phase of VerifyFilePromise()

---

INSTALL
libpromises/crypto.c

- Adjusted INSTALL instructions for OpenBSD 7.4
- Adjusted openssl ifdefs to support building on OpenBSD

CFE-3152: Fix building and using core on OpenBSD

---

libpromises/evalfunction.c

Attempt to fix the following error found in todays nightlies:
```
12:56:18 dbm_api.c: In function ‘SearchExistingSubDBNames’:
12:56:18 dbm_api.c:174:33: error: implicit declaration of function ‘GlobFileList’ [-Werror=implicit-function-declaration]
12:56:18   174 |     StringSet *const db_paths = GlobFileList(glob_pattern);
12:56:18       |                                 ^~~~~~~~~~~~
12:56:18 dbm_api.c:174:33: warning: initialization of ‘StringSet * const’ {aka ‘struct <anonymous> * const’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
12:56:18 cc1: some warnings being treated as errors
12:56:18 make[3]: *** [Makefile:957: dbm_api.lo] Error 1
---snip---
12:56:19 evalfunction.c: In function ‘FnCallSysctlValue’:
12:56:19 evalfunction.c:1048:26: error: implicit …
```

ENT-11341: Fixed implicit declaration due to missing include

---

INSTALL
libpromises/crypto.c

- Adjusted INSTALL instructions for OpenBSD 7.4
- Adjusted openssl ifdefs to support building on OpenBSD

CFE-3152: Adjusted openssl ifdefs to support building on OpenBSD (3.18)

---

misc/cf-support

sed -n '/cfe/p;/cf-/p' would cause any line matching both expressions to be printed twice
Ticket: CFE-4337

Fixed incorrect sed command for cf-support filtering syslog output

---

misc/cf-support

sed -n '/cfe/p;/cf-/p' would cause any line matching both expressions to be printed twice
Ticket: CFE-4337
(cherry picked from commit 56140ba74b9025d46cbfd84ae4c96daf83d5e405)

Fixed incorrect sed command for cf-support filtering syslog output (3.18)

---

libpromises/dbm_api.c
libpromises/evalfunction.c
tests/acceptance/01_vars/02_functions/findfiles-GLOB_BRACE.cf
tests/acceptance/01_vars/02_functions/findfiles.cf
tests/acceptance/01_vars/02_functions/findfiles_glob_bracket.cf
tests/acceptance/01_vars/02_functions/findfiles_up.cf
tests/unit/getopt_test.c

* https://github.com/cfengine/enterprise/pull/786
TODO:

CFE-3292: Removed soft fail related to the use of globs

---

libenv/sysinfo.c
tests/acceptance/01_vars/01_basic/os_name_human.cf

Added `sys.os_name_human` and `sys.os_version_major`. Additionally
changed value of `sys.flavor` from `AmazonLinux` to `amazon_linux_2`, so
that it is similar to other supported Linux distros. This change was
necessary, due to the fact that the `sys.os_version_major` variable is
derived from it. However, the `AmazonLinux` class previously derived
from `sys.flavor` is still defined for backwards compatibility.

ENT-10817: Added standard OS name & version variables for Amazon Linux

---

libenv/sysinfo.c
tests/acceptance/01_vars/01_basic/os_name_human.cf

Added `sys.os_name_human` and `sys.os_version_major`. Additionally
changed value of `sys.flavor` from `AmazonLinux` to `amazon_linux_2`, so
that it is similar to other supported Linux distros. This change was
necessary, due to the fact that the `sys.os_version_major` variable is
derived from it. However, the `AmazonLinux` class previously derived
from `sys.flavor` is still defined for backwards compatibility.
Ticket: ENT-10817
Co-authored-by: Ole Herman Schumacher Elgesem <4048546+olehermanse@users.noreply.github.com>
(cherry picked from commit c3701b6c88bf947d6806d65e6c3a8b98e5b9049c)

ENT-10817: Added standard OS name & version variables for Amazon (3.21.x)

---

libenv/sysinfo.c
tests/acceptance/01_vars/01_basic/os_name_human.cf

Added `sys.os_name_human` and `sys.os_version_major`. Additionally
changed value of `sys.flavor` from `AmazonLinux` to `amazon_linux_2`, so
that it is similar to other supported Linux distros. This change was
necessary, due to the fact that the `sys.os_version_major` variable is
derived from it. However, the `AmazonLinux` class previously derived
from `sys.flavor` is still defined for backwards compatibility.
Ticket: ENT-10817
Co-authored-by: Ole Herman Schumacher Elgesem <4048546+olehermanse@users.noreply.github.com>
(cherry picked from commit c3701b6c88bf947d6806d65e6c3a8b98e5b9049c)

ENT-10817: Added standard OS name & version variables for Amazon (3.18.x)

---

libenv/sysinfo.c

Running cf-agent on my Arch produces the warning: `warning: Operating System not properly recognized, setting sys.os_name_human to "Unknown", please submit a bug report for us to fix this`.
Not really sure what's going on with this, but added Arch to the list in `SysOSNameHuman()`.

Add Arch to the list of OSes recognized by SysOSNameHuman

---

examples/files-content-if-fileexists.cf
examples/files-content-with.cf
examples/files-content.cf
examples/files-create-class-expression.cf

Intended to replace the inline examples introduced to docs here: https://github.com/cfengine/documentation/pull/2877, see comment: https://github.com/cfengine/documentation/pull/2877#pullrequestreview-1101189833

Core examples for simple small examples to files promise type docs

---

INSTALL

Also removed prefixed '$ ' lines to make it easier to copy/paste the commands in INSTALL (not an .md file)
Ticket: CFE-4344

CFE-4344: Added instructions on building for NetBSD and OpenBSD

---

cf-agent/verify_packages.c
libpromises/attributes.c

merge with https://github.com/cfengine/documentation/pull/3237

CFE-4315: Modified packages promise default to use module if present

---

cf-agent/verify_packages.c
libpromises/attributes.c

Previously if a policy that only specified the promiser:
packages:
"ed";
It will default to package_method generic in our C code.
Now it will look for package_module_knowledge.platform_default and if present make the package promise use package module instead.
Ticket: CFE-4315
Co-authored-by: Lars Erik Wik <53906608+larsewi@users.noreply.github.com>
(cherry picked from commit f23e268255b189465cf67135e9c1e77f36c92f20)

CFE-4315: Modified package promise default. If platform_default is present use that package module. (3.18)

---

cf-agent/verify_packages.c
libpromises/attributes.c

Previously if a policy that only specified the promiser:
packages:
"ed";
It will default to package_method generic in our C code.
Now it will look for package_module_knowledge.platform_default and if present make the package promise use package module instead.
Ticket: CFE-4315
Co-authored-by: Lars Erik Wik <53906608+larsewi@users.noreply.github.com>
(cherry picked from commit f23e268255b189465cf67135e9c1e77f36c92f20)

CFE-4315: Modified package promise default. If platform_default is present use that package module. (3.21)

---

cf-agent/package_module.c

On FreeBSD where package versions can have commas such as joe-4.6,1 this was causing errors with the use of packagesmatching() function.
```
error: Line from package inventory 'joe,4.6,1,amd64,pkg' did not yield correct number of elements.
```
Ticket: CFE-4341

CFE-4341: Adjusted package module inventory to include quotes around fields when needed

---

cf-agent/package_module.c

On FreeBSD where package versions can have commas such as joe-4.6,1 this was causing errors with the use of packagesmatching() function.
```
error: Line from package inventory 'joe,4.6,1,amd64,pkg' did not yield correct number of elements.
```
Used CsvWriterField to quote the field in case it includes " , \r \n. See CsvWriterField() at https://github.com/NorthernTechHQ/libntech/blob/master/libutils/csv_writer.c#L73
Had to add a workaround to convert CRLF written by csv_writer to expected LF in resulting inventory_list.
Ticket: CFE-4341
Co-authored-by: Lars Erik Wik <lars.erik.wik@northern.tech>
(cherry picked from commit 27fdfb5afd1ccd0cdefd9926a0129f0ca30563ec)

CFE-4341: Adjusted package module inventory to include quotes around fields when needed (3.21)

---

INSTALL

Also removed prefixed '$ ' lines to make it easier to copy/paste the commands in INSTALL (not an .md file)
Ticket: CFE-4344
(cherry picked from commit 0b1cb02f206ce65585e8f7618789cab69b734064)
Conflicts:
INSTALL
Needed manual edits due to pcre and not pcre2 in 3.21.x branch.

CFE-4344: Added instructions on building for NetBSD and OpenBSD (3.21)

---

INSTALL

Also removed prefixed '$ ' lines to make it easier to copy/paste the commands in INSTALL (not an .md file)
Ticket: CFE-4344
(cherry picked from commit 0b1cb02f206ce65585e8f7618789cab69b734064)
Conflicts:
INSTALL
Had to edit conflicts due to 3.18.x not having pcre2 but rather pcre

CFE-4344: Added instructions on building for NetBSD and OpenBSD (3.18)

---

misc/Makefile.am

To prevent `make install` from hanging. The rule is fault-tolerant so if the authentication is required the command will fail and things will continue just fine. Authentication required means `make install` was not run neither with `sudo` nor as root so `systemctl daemon-reload` would not work anyway because this means the systemd units were not installed into the standard locations where only the root user has access to.

Prevent systemctl from asking for password after installing unit files

---

contrib/container-chroot-agent/Dockerfile-cfengine-chroot-agent
contrib/container-chroot-agent/README
contrib/container-chroot-agent/chrootshell.sh
contrib/container-chroot-agent/clean.sh
contrib/container-chroot-agent/entrypoint-agent.sh
contrib/container-chroot-agent/run.sh
contrib/container-chroot-agent/shell.sh

Working towards providing visibility in and around containers this provides a way to bring up a container which mounts the hosting root filesystem and then installs CFEngine and runs it inside of chroot in that container.
It should not affect the host other than creating an empty /var/cfengine directory.
Ticket: ENT-11345

ENT-11345: Added container chroot agent materials to contrib

---

misc/systemd/cf-apache.service.in

apachectl graceful doesn't close currently open connections.
Ticket: ENT-11526
with https://github.com/cfengine/masterfiles/pull/2864

ENT-11526: Changed cf-apache systemd unit to reload configuration gracefully

---

misc/systemd/cf-apache.service.in

apachectl graceful doesn't close currently open connections.
Ticket: ENT-11526
(cherry picked from commit d3e0ed02ad30c61707d80d6ba93ece8b96810cfb)

Changed cf-apache systemd unit to reload configuration gracefully (3.21)

---

misc/systemd/cf-apache.service.in

apachectl graceful doesn't close currently open connections.
Ticket: ENT-11526
(cherry picked from commit d3e0ed02ad30c61707d80d6ba93ece8b96810cfb)

Changed cf-apache systemd unit to reload configuration gracefully (3.18)

---

tests/static-check/run.sh

The latest and greatest release. [1]
[1] https://fedoramagazine.org/announcing-fedora-linux-40/

Switch static checks to Fedora 40

---

libpromises/dbm_api.c

To prevent multiple processes from opening/closing the DB at the same time. From what we have seen, the *Invalid argument* issues only happen when multiple processes try to work with the DB, multiple threads inside a single process don't seem to hit the trigger.
Also, we have seen that the issues happen when LMDB tries to use a robust (shared inter-process) mutex that was already destroyed.
Ticket: ENT-11543
Changelog: CFEngine processes no longer suffer from the "Invalid
argument" issues when working with LMDB

Try to acquire file lock when closing DB

---

libpromises/dbm_api.c

To prevent multiple processes from opening/closing the DB at the same time. From what we have seen, the *Invalid argument* issues only happen when multiple processes try to work with the DB, multiple threads inside a single process don't seem to hit the trigger.
Also, we have seen that the issues happen when LMDB tries to use a robust (shared inter-process) mutex that was already destroyed.
Ticket: ENT-11543
Changelog: CFEngine processes no longer suffer from the "Invalid
argument" issues when working with LMDB

[3.21.x] Try to acquire file lock when closing DB

---

.github/workflows/ci.yml
.github/workflows/windows_acceptance_tests.yml
tests/acceptance/00_basics/macros/if_triple.cf
tests/acceptance/01_vars/02_functions/packagesmatching.cf
tests/acceptance/27_cf-secret/encrypt-decrypt-args.cf

- Improve and re-enable windows acceptance test workflow
- Adjust expectations of windows acceptance tests

ENT-10699: Fixed windows acceptance test workflow

---

.github/workflows/ci.yml
.github/workflows/windows_acceptance_tests.yml

Ticket: ENT-10699
(cherry picked from commit da214fa9593576926f11b553524958bc6680fee3)
Conflicts:
.github/workflows/ci.yml
.github/workflows/windows_acceptance_tests.yml
Added windows acceptance test to 3.21.x and changed cf-remote command from using master to latest 3.21.x nightly.

ENT-10699: Improve and re-enable windows acceptance test workflow (3.21)

---

cf-execd/cf-execd.c

This could fix issues if things are slow and agent runs end up getting skipped if cf-execd wakes up too late.
TODO:

ENT-11765: Changed cf-execd's sleep behavior so it attempts to wake up at the beginning of every minute

---

.github/workflows/valgrind.yml
configure.ac
tests/unit/files_copy_test.c

We need to take care of the newly required checks in configure.ac because we are responsible for producing config.h usable for both us and libntech.
Ticket: CFE-4380
Changelog: File copying now uses more efficient implementation on
Linux platforms
https://github.com/cfengine/core/pull/5490
https://github.com/NorthernTechHQ/libntech/pull/218

Support libntech's new efficient file/data copying

---

.github/workflows/windows_acceptance_tests.yml

There was an issue with 3.18.x version of this job which required this change.
Ticket: ENT-11771

ENT-11771: Adjust windows acceptance test job workflow to use only C: partition

---

libenv/time_classes.c
libenv/time_classes.h
libpromises/eval_context.c
libpromises/eval_context.h
tests/unit/eval_context_test.c

With the GetTimeClasses() function you can get a set of time classes
without the need for an EvalContext object.
Ticket: ENT-8890
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=10835)](https://ci.cfengine.com/job/pr-pipeline/10835/)

ENT-8890: Added utility function to get time classes

---

misc/selinux/cfengine-enterprise.te.all

This is needed for successful uploads of custom action scripts.
(cherry picked from commit b80cceed6fddbd32d77521e950fb6d91a2ed3050)

[3.21.x] Allow httpd to open tmp files

---

misc/selinux/cfengine-enterprise.te.all

This is needed for successful uploads of custom action scripts.
(cherry picked from commit b80cceed6fddbd32d77521e950fb6d91a2ed3050)

[3.18.x] Allow httpd to open tmp files

---

libpromises/expand.c
tests/acceptance/01_vars/01_basic/fqhost_domain.cf

Fixed bug where `default:sys.fqhost` contained many spaces when domain is set in body common control.
Ticket: CFE-4053
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=10893)](https://ci.cfengine.com/job/pr-pipeline/10893/)

CFE-4053: Fixed bug where default:sys.fqhost contained many spaces

---

libpromises/expand.c
tests/acceptance/01_vars/01_basic/fqhost_domain.cf

Fixed bug where `default:sys.fqhost` contained many spaces when domain is set in body common control.
Ticket: CFE-4053
(cherry picked from commit 06e3eff4b15c4ac0965def1ac1aff741c3d77a81)

[3.21.x] Fixed bug where default:sys.fqhost contained many spaces

---

libpromises/expand.c
tests/acceptance/01_vars/01_basic/fqhost_domain.cf

Fixed bug where `default:sys.fqhost` contained many spaces when domain is set in body common control.
Ticket: CFE-4053
(cherry picked from commit 06e3eff4b15c4ac0965def1ac1aff741c3d77a81)

[3.18.x] Fixed bug where default:sys.fqhost contained many spaces

---

ChangeLog

Markdown in the changelog (especially single backticks around words) cause the
doc build to break with failure to resolve automatic links. Here we simply
replaced backticks with single quotes.
Ticket: ENT-11854

ENT-11854: Fixed doc build (3.21)

---

ChangeLog

The documentation build tries and fails to resolve automatic backtick links,
this change simply switches from backticks to single quotes to allow doc builds
to function properly.
Ticket: ENT-11854

ENT-11854: Fixed doc build (3.18)

---

misc/selinux/cfengine-enterprise.te.all

Otherwise things like this happen:
postfix/sendmail[31057]: fatal: inet_addr_local[getifaddrs]: getifaddrs: Permission denied
(ported commit 5fbebdb34fc51bc5d6ce14b005674f7feaf8a403)

[3.18.x] Allow all processing using the netlink route socket to read/write

---

cf-agent/verify_files.c

So that policy using depth_search with a promiser that is a file
simply handles the file itself. A warning is issued, though.
Ticket: ENT-8996
Changelog: depth_search acting on a non-directory promiser now
handles such file as if the promise didn't use
depth_search issuing a warning

Allow depth_search on non-directory files

---

cf-agent/verify_files.c

So that policy using depth_search with a promiser that is a file simply handles the file itself. A warning is issued, though.
Ticket: ENT-8996
Changelog: depth_search acting on a non-directory promiser now
handles such file as if the promise didn't use
depth_search issuing a warning
(cherry picked from commit 139885f3e0bf7416315b61aef2407194afe9467c)

[3.21.x] Allow depth_search on non-directory files

---

contrib/masterfiles-stage/common.sh

On Debian-9 and possibly other older or minimal systems en-US.utf-8 may not be a locale which is available.
In any case, default to the first utf locale found via `locale -a` which seems to include something general first regardless.
Ticket: ENT-11885
(cherry picked from commit b99fa9a7f10b77ce31bf738b9de8883b64ff2dfc)

Adjusted local settings in masterfiles stage common script to handle more cases (3.21)

---

contrib/masterfiles-stage/common.sh

On Debian-9 and possibly other older or minimal systems en-US.utf-8 may not be a locale which is available.
In any case, default to the first utf locale found via `locale -a` which seems to include something general first regardless.
Ticket: ENT-11885
(cherry picked from commit b99fa9a7f10b77ce31bf738b9de8883b64ff2dfc)

Adjusted local settings in masterfiles stage common script to handle more cases (3.18)

---

libpromises/iteration.c
tests/acceptance/01_vars/01_basic/double_expansion_list.cf

[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=10982)](https://ci.cfengine.com/job/pr-pipeline/10982/)
Back-ported to:
- https://github.com/cfengine/core/pull/5560
- https://github.com/cfengine/core/pull/5559

ENT-9491: Fixed bug in double expansion of foreign list variables

---

libpromises/iteration.c
tests/acceptance/01_vars/01_basic/double_expansion_list.cf

Test output before fix looks like this:
```
R: /ntech/cfengine/core/tests/acceptance/01_vars/01_basic/double_expansion_list.cf FAIL
R: $($(parent_bundle).str) => EXPANDED
R: $($(parent_bundle).lst) => $(check.lst)
R: $(check.baz)            => EXPANDED
R: $($(parent_bundle)#lst) => EXPANDED
```
Ticket: ENT-9491
(cherry picked from commit ea1c92f832799ffe92376381725d3d1b53856f8d)
Back-ported from https://github.com/cfengine/core/pull/5536

ENT-9491: Fixed bug in double expansion of foreign list variables (3.21.x)

---

libpromises/iteration.c
tests/acceptance/01_vars/01_basic/double_expansion_list.cf

Test output before fix looks like this:
```
R: /ntech/cfengine/core/tests/acceptance/01_vars/01_basic/double_expansion_list.cf FAIL
R: $($(parent_bundle).str) => EXPANDED
R: $($(parent_bundle).lst) => $(check.lst)
R: $(check.baz)            => EXPANDED
R: $($(parent_bundle)#lst) => EXPANDED
```
Ticket: ENT-9491
(cherry picked from commit ea1c92f832799ffe92376381725d3d1b53856f8d)
Back-ported from https://github.com/cfengine/core/pull/5536

ENT-9491: Fixed bug in double expansion of foreign list variables (3.18.x)

---

tests/acceptance/10_files/11_xml_edits/CFE-3806.cf

libxml2-2.13.1 seems to be fixing this.
Ticket: CFE-3806
Changelog: Trailing newline on insert_tree promisers no longer removes ending tag for select_xpath
https://github.com/cfengine/buildscripts/pull/1471
https://github.com/cfengine/core/pull/5556

Enable test for trailing newline on insert_tree promisers

---

libpromises/dbm_api.c

The packagesmatching() function searches for lmdb databases with GlobFileList() which is known to segfault on absolute paths on Windows with backslashes.
The fix is only needed in 3.21.x because changes in master core+libntech improve the situation in a more thorough way.
Ticket: ENT-11900
together:
https://github.com/cfengine/core/pull/5558
https://github.com/cfengine/enterprise/pull/802

ENT-11900: Fixed packagesmatching() function segfaulting on Windows platform (3.21)

---

misc/cf-support

If something goes wrong with masterfiles-stage then /var/cfengine/outputs/dc-scripts.log will contain additional details about what happened.
This is a cumulative log so compress it.
Ticket: none

Added capture of masterfiles-stage log dc-scripts.log to cf-support

---

tests/valgrind-check/valgrind.sh

Backport of https://github.com/cfengine/core/pull/5567

[3.21.x] valgrind-checks improvements

---

libpromises/iteration.c
tests/acceptance/01_vars/01_basic/double_expansion_list_namespace.cf

Prior to fix, the added acceptance test had the following output:
```
R: /home/larsewi/ntech/cfengine/core/tests/acceptance/01_vars/01_basic/double_expansion_list_namespace.cf FAIL
R: $($(parent_namespace):$(parent_bundle).str) => EXPANDED
R: $($(parent_namespace):$(parent_bundle).lst) => $(bogus:check.lst)
R: $(default:check.lst)                        => EXPANDED
```
Ticket: ENT-11923
(cherry picked from commit 5e8ccbd6831e346b4242816df6ef90a762928975)
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=11041)](https://ci.cfengine.com/job/pr-pipeline/11041/)
Back-ported from https://github.com/cfengine/core/pull/5564

ENT-11923: Fixed bug in double expansion of foreign list variables with namespaces (3.21.x)

---

libpromises/iteration.c
tests/acceptance/01_vars/01_basic/double_expansion_list.cf
tests/acceptance/01_vars/01_basic/double_expansion_list_namespace.cf

(cherry picked from commit 7016c253863269c163f397c75ac309994da004cd)
Back-ported from https://github.com/cfengine/core/pull/5566

Fixed some typos related fixes for ENT-9491 & ENT-11923 (3.21.x)

---

cf-agent/verify_packages.c
libpromises/attributes.c
libpromises/cf3parse_logic.h
tests/acceptance/07_packages/default_package_module.cf
tests/acceptance/07_packages/default_package_module.cf.expected
tests/acceptance/07_packages/default_package_module.cf.module

CFE-4315 introduced a behavior change so that in the case of a simple package promise with only a promiser:
packages:
"ed";
Things would just work in the case where there was no default package manager defined with package_module_knowledge.platform_default.
In the case where package_module_knowledge.platform_default was defined this simple case would cause errors.
This change fixes this second case as well as modifies and adds some logging around the choosing of v1 or v2 package promise implementation.
Ticket: CFE-4408

CFE-4408: Fixed package promises with only promisers and no other attributes

---

contrib/masterfiles-stage/common.sh

https://github.com/cfengine/nova/pull/2276

masterfiles-stage: Added alternate global directory for cfbs build

---

cf-agent/verify_packages.c
libpromises/attributes.c
tests/acceptance/07_packages/default_package_module.cf
tests/acceptance/07_packages/default_package_module.cf.expected
tests/acceptance/07_packages/default_package_module.cf.module

CFE-4315 introduced a behavior change so that in the case of a simple package promise with only a promiser:
packages:
"ed";
Things would just work in the case where there was no default package manager defined with package_module_knowledge.platform_default.
In the case where package_module_knowledge.platform_default was defined this simple case would cause errors.
This change fixes this second case as well as improves logging around the choosing of v1 and v2 package promise implementations.
Some of these changes fix CFE-4398 which noted that too many INFO level messages were produced. These messages are moved to DEBUG and VERBOSE level as appropriate.
Also added "packages" promises to list of exceptions so that a bare promiser-only package promise does not cause warnings.
Ticket: CFE-4408 …

CFE-4408: Fixed package promises with only promisers and no other attributes (3.21)

---

contrib/masterfiles-stage/common.sh

We need to compare the revision in the mirror against the target deploy directory, not the temporary checkout from the mirror. And we can do this earlier in the process.
Ticket: ENT-11970
https://github.com/cfengine/core/pull/5579
https://github.com/cfengine/nova/pull/2284

Fix early git revision comparison in masterfiles-stage.sh

---

ChangeLog

The documentation website build renders changes logs from other repos, when
those files contain markdown links the docs build breaks for not knowing the
references. Here we simply replace backticks with single quotes to avoid the
problem.
Ticket: ENT-11993

ENT-11993: Stripped backticks which break doc build

---

libpromises/policy.c
libpromises/policy.h

So that CFEngine components can make sure masterfiles updates don't happen at wrong times or as multiple runs at the same times.
Ticket: ENT-9386

Add the GetMasterfilesStageLock() function

---

.github/workflows/windows_acceptance_tests.yml

```
error: externally-managed-environment
```
Since this is a container, it should be OK to potentially break system
packages.
Ticket: None

Fixed failure to install cf-remote

---

cf-agent/retcode.c

They are marked as failed with the following message:
Command related to promiser '...' returned code '1' not defined as promise kept, not kept or repaired; setting to failed
Failed promises should log errors not just info
messages. Otherwise running without `--info` or more detailed logging fails silently.
Ticket: CFE-4429
Ticket: ENT-12103
Changelog: commands promises with exit codes not matching any
_returncodes attributes from classes body now log and
error message not just an info message
(cherry picked from commit 41214f7b5de59729d8c723a4976c67d1dde5d48c)

[3.24.x] Log errors for commands promises with exit codes not matching any _returncodes

---

cf-agent/retcode.c

They are marked as failed with the following message:
Command related to promiser '...' returned code '1' not defined as promise kept, not kept or repaired; setting to failed
Failed promises should log errors not just info
messages. Otherwise running without `--info` or more detailed logging fails silently.
Ticket: CFE-4429
Ticket: ENT-12103
Changelog: commands promises with exit codes not matching any
_returncodes attributes from classes body now log and
error message not just an info message
(cherry picked from commit 41214f7b5de59729d8c723a4976c67d1dde5d48c)

[3.21.x] Log errors for commands promises with exit codes not matching any _returncodes

---

misc/cf-support

Ticket: ENT-12137
(cherry picked from commit ea77c55bbf419b7862d68b361ef54da83779d480)

Added logging CFEngine component related SELinux denials in cf-support (3.21)

---

tests/acceptance/10_files/11_xml_edits/CFE-3806.cf

libxml2-2.13.1 seems to be fixing this.
Ticket: CFE-3806
Changelog: Trailing newline on insert_tree promisers no longer removes ending tag for select_xpath
(cherry picked from commit cea0100fbac7a193c586c8b44b3b26df2d8187d1)

Enable test for trailing newline on insert_tree promisers (3.21)

---

tests/static-check/run.sh

Install extra tools in build image to get rid of errors in GH workflow
./configure: line 8045: cmp: command not found
./configure: line 8224: /usr/bin/file: No such file or directory
./configure: line 9811: diff: command not found

tests/static: Install extra tools in build image

---

tests/static-check/run_checks.sh

When running cppcheck in static checks, we use `-i libpromises/cf3lex.c` in order to make cppcheck ignore the generated cf3lex.c file. However, the new version of cppcheck ignores this option and fails on issues found in the file.
However, we don't want this file or any other generated files except for bootstrap.inc which contains the bootstrap policy. So we can run `make clean` and `make -C libpromise/ boostrap.inc` before running cppcheck to get a cleaner environment.

Workaround cppcheck ignoring `-i libpromises/cf3lex.c`

---

cf-agent/verify_files_utils.c
libcfnet/client_code.c
libcfnet/client_code.h

Changes to `files` promise in `copy_from` attribute:
- The new file (i.e., `<FILENAME>.cfnew`) is now created with correct
permission during remote copy. Previously it would be created with
default permissions.
- The destination file (i.e., `<FILENAME>`) is no longer deleted on
backup during file copy.  Previously it would be renamed to
`<FILENAME>.cfsaved`, causing the original file to dissappear. Now an
actual copy of the original file with the same permissions is created
instead.
As a result, there will no longer be a brief moment where the original
file is inaccessible.

ENT-11988: Atomic copy_from in files promise

---

libenv/unix_iface.c

Agent now also ignores interfaces listed in `ignore_interfaces.rx` when
looking for IPv6 interface info. Variables such as
`default:sys.hardware_mac[<INTERFACE>]` will no longer be defined for
ignored interfaces.

ENT-11840: Also ignore IPv6 interface info

---

.github/workflows/job-static-check.yml

libncurses5 was not available in the noble repository, but maybe
libncurses6 will work.
```
E: Unable to locate package libncurses5
```
Ticket: None

Fixed error in static checks

---

.github/workflows/job-static-check.yml
.github/workflows/windows_acceptance_tests.yml
cf-agent/verify_files_utils.c
libcfnet/client_code.c
libcfnet/client_code.h
tests/static-check/run_checks.sh

Changes to `files` promise in `copy_from` attribute:
- The new file (i.e., `<FILENAME>.cfnew`) is now created with correct
permission during remote copy. Previously it would be created with
default permissions.
- The destination file (i.e., `<FILENAME>`) is no longer deleted on
backup during file copy.  Previously it would be renamed to
`<FILENAME>.cfsaved`, causing the original file to dissappear. Now an
actual copy of the original file with the same permissions is created
instead.
As a result, there will no longer be a brief moment where the original
file is inaccessible.
Back-ported from https://github.com/cfengine/core/pull/5611/

ENT-11988: Atomic copy_from in files promise (3.24.x)

---

.github/workflows/codeql.yml
.github/workflows/job-static-check.yml
.github/workflows/windows_acceptance_tests.yml
cf-agent/verify_files_utils.c
libcfnet/client_code.c
libcfnet/client_code.h
tests/static-check/run_checks.sh

Changes to `files` promise in `copy_from` attribute:
- The new file (i.e., `<FILENAME>.cfnew`) is now created with correct
permission during remote copy. Previously it would be created with
default permissions.
- The destination file (i.e., `<FILENAME>`) is no longer deleted on
backup during file copy.  Previously it would be renamed to
`<FILENAME>.cfsaved`, causing the original file to dissappear. Now an
actual copy of the original file with the same permissions is created
instead.
As a result, there will no longer be a brief moment where the original
file is inaccessible.
Back-ported from https://github.com/cfengine/core/pull/5611/

ENT-11988: Atomic copy_from in files promise (3.21.x)

---

libenv/unix_iface.c

Agent now also ignores interfaces listed in ignore_interfaces.rx when
looking for IPv6 interface info. Variables such as
`default:sys.hardware_mac[<INTERFACE>]` will no longer be defined for
ignored interfaces.
Back-ported from https://github.com/cfengine/core/pull/5612/

ENT-11840: Also ignore IPv6 interface info (3.24.x)

---

libenv/unix_iface.c

Agent now also ignores interfaces listed in ignore_interfaces.rx when
looking for IPv6 interface info. Variables such as
`default:sys.hardware_mac[<INTERFACE>]` will no longer be defined for
ignored interfaces.
Back-ported from https://github.com/cfengine/core/pull/5612/

ENT-11840: Also ignore IPv6 interface info (3.21.x)

---

cf-check/backup.c
cf-check/db_structs.h
cf-check/dump.c
libpromises/dbm_api.c
libpromises/dbm_lmdb.c
libpromises/dbm_migration.c
libpromises/dbm_migration_lastseen.c
libpromises/lastseen.c
libpromises/lastseen.h
tests/unit/lastseen_test.c

- [Added acknowledge field to lastseen DB](https://github.com/cfengine/core/pull/5617/commits/5d148d3b9bf907b3d3c50c7f5494b46f2c417396)
- [Added acknowledge function for lastseen entries](https://github.com/cfengine/core/pull/5617/commits/80e9540c2028de3880c1672512cbf5383d2a3808)
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=11319)](https://ci.cfengine.com/job/pr-pipeline/11319/)

ENT-11838: Fixed perpetual warnings that a deleted host has checked in

---

examples/peerleader.cf
examples/peerleaders.cf
examples/peers.cf

This was breaking on some systems in a way that doesn't benefit the test.
Instead of assuming that `hostname -f` is equal to `sys.fqhost` just use `sys.fqhost` in the first place.
Ticket: ENT-12437

Adjusted peer related examples in regards to hostname -f versus sys.fqhost

---

examples/peerleader.cf
examples/peerleaders.cf
examples/peers.cf

This was breaking on some systems in a way that doesn't benefit the test.
Instead of assuming that `hostname -f` is equal to `sys.fqhost` just use `sys.fqhost` in the first place.
Ticket: ENT-12437
(cherry picked from commit 471dc0f4b5d468b989b0e42cb0cf3dd0275e7acc)

Adjusted peer related examples in regards to hostname -f versus sys.fqhost (3.21)

---

misc/selinux/cfengine-enterprise.te.all

Apparently, ps command running with SELinux kernel policy version 33 requires self:cap_userns sys_ptrace.

Adjusted CFEngine SELinux policy to allow cf-execd to run ps command with policy version 33

---

libpromises/evalfunction.c

Do not crash cf-promises if no argument is given for following functions:
* readfile
* iprange
* isipinsubnet

libpromises/evalfunction: Do not crash w/o arguments

---

misc/selinux/cfengine-enterprise.te.all

Apparently, ps command running with SELinux kernel policy version 33 requires self:cap_userns sys_ptrace.
(cherry picked from commit 45ea0fe542f73e8c4358d7c0e23049dee34056d3)

Adjusted CFEngine SELinux policy to allow cf-execd to run ps command with policy version 33 (3.21)

---

misc/selinux/cfengine-enterprise.te.all

Apparently, ps command running with SELinux kernel policy version 33 requires self:cap_userns sys_ptrace.
(cherry picked from commit 45ea0fe542f73e8c4358d7c0e23049dee34056d3)

Adjusted CFEngine SELinux policy to allow cf-execd to run ps command with policy version 33 (3.24)

---

.github/workflows/ci.yml

Disabled windows_acceptance_tests in github CI due to 6 hour time limit

---

.github/workflows/ci.yml

Ticket: ENT-12497
(cherry picked from commit 17f68d0e6b2ab39cfb7c7b9bc0999351b2d67685)

Disabled windows_acceptance_tests in github CI due to 6 hour time limit (3.21)

---

.github/workflows/ci.yml

Ticket: ENT-12497
(cherry picked from commit 17f68d0e6b2ab39cfb7c7b9bc0999351b2d67685)

Disabled windows_acceptance_tests in github CI due to 6 hour time limit (3.24)

---

misc/selinux/cfengine-enterprise.te.all

It was found in some situations that cf-monitord was attempting access to files and dirs with the user_home_dir_t type and being blocked.
cf-monitord needs full access to all filesystems and files.

Added filesystem and files unconfined access to cf-monitord in cfengine-enterprise SELinux policy

---

misc/selinux/cfengine-enterprise.te.all

- Added getattr capability for cert_t:dir as needed to CFEngine components in cfengine-enterprise SELinux policy
- Added create capability on cfengine_var_lib_t:dir to cf-hub

ENT-12466: SELinux fixes for kernel policy version 33 on rhel-9 hubs

---

misc/selinux/cfengine-enterprise.te.all

Seen on rhel-8 and rhel-9 with kernels 4.18.0 and 5.14.0 and policy version 33.
Applies to cf-monitord, cf-execd and cf-serverd.
Ticket: ENT-12466

Adjusted SELinux policy to allow components which run cf-promises to getattr everywhere and read symlinks

---

misc/selinux/cfengine-enterprise.te.all

Were found to be needed in 3.21.6a and 3.24.1a testing on rhel-9 hubs.
Policy works on rhel-8 as well.
Ticket: ENT-12466

Granted more access to certificates directory for CFEngine components in SELinux policy

---

tests/static-check/run.sh

I added some comments to explain the logic behind recreating the image in static checks.

Added comments to explain image recreation logic

---

misc/selinux/cfengine-enterprise.te.all

In order to honor some settings like def.control_server_maxconnections we must allow self:capability sys_resource.

SELinux: Allow cf-serverd to set its own limits

---

misc/selinux/cfengine-enterprise.te.all

In order to honor some settings like def.control_server_maxconnections we must allow self:capability sys_resource.
(cherry picked from commit c05f25b1e776af00205ef3d21f03926bd63b36f6)

SELinux: Allow cf-serverd to set its own limits (3.21)

---

misc/selinux/cfengine-enterprise.te.all

In order to honor some settings like def.control_server_maxconnections we must allow self:capability sys_resource.
(cherry picked from commit c05f25b1e776af00205ef3d21f03926bd63b36f6)

SELinux: Allow cf-serverd to set its own limits (3.24)

---

misc/cf-support

head -c 8 doesn't work on hpux 11.23 that we test on currently
dd count=1 bs=8 should work on all UNIX systems
tr on solaris needs LC_CTYPE=C as it can't handle binary data.
Silence not found sysctl command where it is not present.
Ticket: ENT-9786

Adjusted cf-support for exotic UNIX platforms

---

misc/cf-support

- Made cf-support use coredumpctl for core analysis only when configured in kerenl.core_pattern
- Adjusted cf-support for exotic UNIX platforms
- Adjusted cf-support to not fail if core dumps are available and gdb is missing

Adjusted cf-support for exotic UNIX platforms (3.21)

---

misc/cf-support

- Adjusted cf-support for exotic UNIX platforms
- Adjusted cf-support to not fail if core dumps are available and gdb is missing

Adjusted cf-support for exotic UNIX platforms (3.24)

---

.github/workflows/asan_unit_tests.yml
libpromises/evalfunction.c
tests/unit/Makefile.am
tests/unit/evalfunction_test.c
tests/unit/lastseen_test.c
tests/unit/rlist_test.c
tests/unit/set_domainname_test.c

- **Fixed ODR violations in ASAN Unit Tests**
- **Revert "Disabled ODR violation from ASAN Unit Tests"**

CFE-4454: Fixed ODR violations in ASAN Unit Tests

---

tests/acceptance/10_files/copy_from_convert.cf
tests/acceptance/10_files/copy_from_convert.cf.template

Added acceptance test for testing that directories should be changed
back to files on recusive copy. The test is currently set to soft fail.
Ticket: CFE-2216

Added acceptance test for CFE-2216

---

tests/unit/Makefile.am

For some reason rlist_test fails in AIX unit tests. The test seems to
`abort()` while it should trigger an assert so that
`expect_assert_failure()` can catch it. For some reason this is not
happening anymore.
```
rlist.c:135: Programming Error: Internal error: Rval contains type f instead of expected scalar
```
I created a ticket (CFE-4473) to follow-up on this.
Ticket: None

Soft fail rlist_test on AIX

---

libpromises/evalfunction.c

Do not crash cf-promises if no argument is given for following
functions:
* readfile
* iprange
* isipinsubnet
(cherry picked from commit e040d7f0526230b3a9f8d4b2780c27167184545e)

libpromises/evalfunction: Do not crash w/o arguments (3.24.x)

---

libcfnet/file_stream.c
libcfnet/protocol.c

The command `cf-net get <FILENAME>` now writes to `<FILENAME>.cfnew`
followed by replacing `<FILENAME>` with `<FILENAME>.cfnew`. Previously
it would unlink and re-create the original file.
With the new `"filestream"` protocol, we need the original file in order
to compute its signature, so that we can save bandwidth using the RSYNC
protocol. Furthermore, unlinking the original file, causes a brief
moment when it either does not exist or is incomplete. This can be
problematic if other processes depend on it.
Ticket: ENT-12511
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=11550)](https://ci.cfengine.com/job/pr-pipeline/11550/) together with …

ENT-12511: Now `cf-net get` no longer unlinks original file

---

cf-net/cf-net.c

```
$ sudo /var/cfengine/bin/cf-net -H 192.168.123.456 connect
Failed to connect to '192.168.123.456'
$ echo $?
1
$ sudo /var/cfengine/bin/cf-net -H 127.0.0.1 connect
Connected & authenticated successfully to '127.0.0.1'
$ echo $?
0
```

CFE-4414: `cf-net connect` now exits with 1 in case of error

---

tests/valgrind-check/Containerfile

Recently we've seen segmentation faults while compiling core in valgrind
checks. I'll try to upgrade the container image to Ubuntu 24 to see if
that resolves the issue.
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=11587)](https://ci.cfengine.com/job/pr-pipeline/11587/)

Upgraded valgrind check container to Ubuntu 24

---

libpromises/mod_common.c
libpromises/mod_files.c

This changes the syntax description for the protocol_version attributes to
include the new version 4/filestream protocol. This change is necessary for the
generated documentation to reflect the current state.
Ticket: CFE-4483

CFE-4483: Updated syntax description to include new protocol_version values

---

INSTALL

- **Added ARM64 to regularly build and tested CPU architectures**
- **Added librsync to install dependencies**
- **Removed x86 from regularly build and tested CPU architectures**

Updated install dependencies to include librsync

---

cf-net/cf-net.c
libcfnet/client_code.c
libcfnet/file_stream.c
libcfnet/file_stream.h
libcfnet/protocol.c
libcfnet/protocol.h

The performance stats are also logged. This way we can also study the
performance through `cf-agent`'s debug logs.
The following is an example of running `cf-net` with the `--stats` option:
```
$ sudo /var/cfengine/bin/cf-net --stats --host 192.168.56.10 get /var/cfengine/masterfiles/promises.cf
Send signature statistics:
16970 bytes in (read from 'promises.cf')
2424 bytes out (sent to server)
Receive delta statistics:
9 bytes in (received from server)
16970 bytes out (written to 'promises.cf.cfnew')
```
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=11640)](https://ci.cfengine.com/job/pr-pipeline/11640/)

Added option to print rsync performance stats in cf-net

---

cf-check/backup.c
cf-check/db_structs.h
cf-check/dump.c
libpromises/dbm_api.c
libpromises/dbm_lmdb.c
libpromises/dbm_migration.c
libpromises/dbm_migration_lastseen.c
libpromises/lastseen.c
libpromises/lastseen.h
tests/unit/lastseen_test.c

- **Fixed bug causing LMDB database corruption**
- **Re-enabled DB migration support for LMDB**
- **Added acknowledged field to lastseen DB**
- **Added acknowledge function for lastseen entries**
- **Handle LMDB migration failures**
- **Now creates backup before LMDB migration**
- **Fixed possible segfault when backing up LMDB databases**
Back-ported from https://github.com/cfengine/core/pull/5617
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=11643)](https://ci.cfengine.com/job/pr-pipeline/11643/)

ENT-11838: Fixed perpetual warnings that a deleted host has checked in (3.21.x)

---

cf-secret/cf-secret.c

localhost is the default for both `encrypt` and `decrypt`.
Also, `print-headers` doesn't require `--output`.
Ticket: none

Fix `cf-secret -h` output regarding localhost as default

---

cf-check/backup.c
cf-check/db_structs.h
cf-check/dump.c
libpromises/dbm_api.c
libpromises/dbm_lmdb.c
libpromises/dbm_migration.c
libpromises/dbm_migration_lastseen.c
libpromises/lastseen.c
libpromises/lastseen.h
tests/unit/lastseen_test.c

- **Fixed bug causing LMDB database corruption**
- **Re-enabled DB migration support for LMDB**
- **Added acknowledged field to lastseen DB**
- **Added acknowledge function for lastseen entries**
- **Handle LMDB migration failures**
- **Now creates backup before LMDB migration**
- **Fixed possible segfault when backing up LMDB databases**
Back-ported from https://github.com/cfengine/core/pull/5617/
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=11719)](https://ci.cfengine.com/job/pr-pipeline/11719/)

ENT-11838: Fixed perpetual warnings that a deleted host has checked in (3.24.x)

---

examples/is_type.cf
libpromises/evalfunction.c
tests/acceptance/01_vars/02_functions/is_type.cf

Changelog: Added is_type policy function to check type of a variable.
Ticket: CFE-3641
https://github.com/cfengine/core/pull/5691
https://github.com/cfengine/documentation/pull/3391

Added is_type policy function

---

tests/static-check/run_checks.sh

Fixed static-check to not configure when running autogen.

---

.github/workflows/job-static-check.yml
cf-check/dump.c
libpromises/locks.c
tests/static-check/run_checks.sh

- Minimized resources for static-check (package dependencies) and added cppcheck version printout
- address static-check complaints
- bump libntech to master
Back ported from https://github.com/cfengine/core/pull/5706

2025 03 06 static check fixes/3.24

---

INSTALL
libenv/unix_iface.c
libpromises/unix.c
libpromises/unix.h
tests/acceptance/00_basics/environment/proc-net-functions.cf
tests/acceptance/00_basics/environment/proc-net.cf

together
https://github.com/cfengine/masterfiles/pull/2990
https://github.com/cfengine/core/pull/5702

CFE-3429: Use current process ID to investigate proc filesystem to workaround in-container non-root owned symlinks

---

cf-check/diagnose.c
cf-check/validate.c
tests/valgrind-check/valgrind.sh

- **Added leak check for running cf-check on non-existent file**
- **Fixed memory leak when running cf-check on non-existent file**
- **Fixed conditional jump or move depends on uninitialised value**
- **Silence error from cf-check when checking for valgrind errors**

CFE-4508: Fixed valgrind errors in cf-check

---

.github/workflows/codeql.yml

Annotation in previous CodeQL runs:
> CodeQL Action major versions v1 and v2 have been deprecated. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2025-01-10-code-scanning-codeql-action-v2-is-now-deprecated/

CodeQL: bump deprecated GitHub Action

---

libpromises/matching.c

This memory issue caused segmentation faults in the
package_commands_useshell.cf acceptance test on SPARC Solaris 11 after
upgrading PCRE2 to version 10.45. The memory issue was found with the
help of valgrind.
Signed-off-by: Lars Erik Wik [lars.erik.wik@northern.tech](mailto:lars.erik.wik@northern.tech)
Back-ported to: https://github.com/cfengine/core/pull/5740

Fixed invalid read of size 8 in function FirstBackReference

---

libpromises/matching.c

This memory issue caused segmentation faults in the
package_commands_useshell.cf acceptance test on SPARC Solaris 11 after
upgrading PCRE2 to version 10.45. The memory issue was found with the
help of valgrind.
(cherry picked from commit aecb4a2403c4ddc075efdf0640e2810b4a4cf9ad)
Back-ported from: https://github.com/cfengine/core/pull/5738
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=11909)](https://ci.cfengine.com/job/pr-pipeline/11909/)

Fixed invalid read of size 8 in function FirstBackReference (3.24.x)

---

.github/workflows/macos_unit_tests.yml
configure.ac
libcfnet/Makefile.am
tests/acceptance/Makefile.am

- **Upgraded libntech**
- **CFE-4385: Fix build on macOS**
- **GH Actions: Installed libyaml on macOS to fix build errors**

Fixes to handling of brew and compiling on macOS in GH Actions

---

cf-runagent/cf-runagent.c

ChangeLog: Title
Ticket: ENT-12712
Signed-off-by: Ihor Aleksandrychiev <ihor.aleksandrychiev@northern.tech>
(cherry picked from commit 79a2165877dbda5ae1ce5b8a6d050fb10edb44af)

ENT-12712: Fixed incorrect exit code handling in cf-runagent (3.24.x)

---

cf-runagent/cf-runagent.c

ChangeLog: Title
Ticket: ENT-12712
Signed-off-by: Ihor Aleksandrychiev <ihor.aleksandrychiev@northern.tech>
(cherry picked from commit 79a2165877dbda5ae1ce5b8a6d050fb10edb44af)

ENT-12712: Fixed incorrect exit code handling in cf-runagent (3.21.x)

---

libenv/sysinfo.c
tests/static-check/cppcheck_suppressions.txt

Use platform context variable also for logging the os class description. Before this change, it were using loop counter variable, which is incremented again. This led to verbose logging message:
verbose: CFEngine detected operating system description is qnx
on Darwin/macOS.
Also use already lowercased sysname from utsname struct.
Fixes: e2c9f00c0 ("Use a proper 'bool' variable for a condition in GetNameInfo3()")

libenv/sysinfo: Fix detected os description

---

libenv/sysinfo.c

Fix sys.os_name_human warning on macOS
Operating System not properly recognized, setting sys.os_name_human to "Unknown", please submit a bug report for us to fix this due to missing "macos" hardclass.
Define expected macos hardclass and additional major, minor and patch version hardclasses obtained from sw_vers tool.
This changes sys.flavor from darwin_KERNEL_VER to macos_MACOS_MAJOR_VER.

Define macos and additional version hardclasses

---

libcfnet/file_stream.c

- **Fixed junk printed in case of internal server error**
- **Fixed some typos in filestream.c**
- **Fixed bad ordering of format string arguments**
- **Fixed bug causing internal server error on remote file copy**
- **Expanded comment to better explain relationship between in_buf, next_in and avail_in**

CFE-4507: Fixed internal server error when copying large files

---

tests/static-check/run_checks.sh

Just a wild guess at how to fix a flakey issue we see fairly often.
Ticket: ENT-11515

Adjusted static-checks test to use half the number of available processors to avoid cppcheckerror segfaults

---

tests/static-check/run_checks.sh

Just a wild guess at how to fix a flakey issue we see fairly often.
Ticket: ENT-11515
(cherry picked from commit cd4dce1adb36cd23ee775af25e7919e49f8afc13)

Adjusted static-checks test to use half the number of available processors to avoid cppcheckerror segfaults (3.21)

---

tests/static-check/run_checks.sh

Just a wild guess at how to fix a flakey issue we see fairly often.
Ticket: ENT-11515
(cherry picked from commit cd4dce1adb36cd23ee775af25e7919e49f8afc13)

Adjusted static-checks test to use half the number of available processors to avoid cppcheckerror segfaults (3.24)

---

examples/findlocalusers.cf
libpromises/evalfunction.c
tests/acceptance/01_vars/02_functions/findlocalusers.cf
tests/acceptance/01_vars/02_functions/findlocalusers.cf.expected.json
tests/acceptance/01_vars/02_functions/unsafe/findlocalusers_unsafe.cf
tests/acceptance/01_vars/02_functions/unsafe/findlocalusers_unsafe.cf.expected.json

https://github.com/cfengine/documentation/pull/3406
https://github.com/cfengine/core/pull/5714

CFE-2318: Added findlocalusers() policy function

---

cf-agent/verify_processes.c
libpromises/attributes.c
libpromises/processes_select.c
tests/acceptance/05_processes/01_matching/select_without_result.cf

Currently process_select bodies are expected to have a process_result attribute. However documentation states, that in case the process_result attribute is missing, all set attributes are AND'ed together. This commit adds necessary changes to allow process_select bodies without process_result attribute and removes all error logging too.
Ticket: CFE-4511

Support process_select bodies without process_result attribute

---

.github/workflows/acceptance_tests.yml
.github/workflows/asan_unit_tests.yml
.github/workflows/job-static-check.yml
.github/workflows/shellcheck.yml
.github/workflows/unit_tests.yml
.github/workflows/valgrind.yml

This commit was added while working on implementing the File Stream API
in ticket ENT-12414. The File Stream API utilizes librsync.  To begin
with I had `AC_CHECK_HEADERS([librsync_export.h], [],
AC_MSG_ERROR(Cannot find librsync))` in configure.ac. This file did not
exist in earlier versions of librync. Hence, I upgraded the Ubuntu
platforms in GitHub CI to make configure work. Later a realized that I
should remove that line enirely to make CFEngine compatible with earlier
versions. However, it does not hurt to upgrade the Ubuntu platforms, so
decided on keeping this commit.
Ticket: None
(cherry picked from commit 758e0657dba1646b4851f1b87064a4d5cf73e9a6)

Replaced GitHub CI platforms with Ubuntu 24 (3.24)

---

libpromises/evalfunction.c

Fixed whitespace typo in message about Cannot open software_packages.csv

---

tests/acceptance/01_vars/02_functions/findlocalusers.cf
tests/acceptance/01_vars/02_functions/unsafe/findlocalusers_unsafe.cf

User management and default shell and other details are different on AIX than on Linux.
Ticket: ENT-12767

Marked findlocalusers* tests (2) as soft fail on AIX

---

libpromises/evalfunction.c
tests/unit/Makefile.am
tests/unit/evalfunction_test.c
tests/unit/lastseen_test.c
tests/unit/rlist_test.c
tests/unit/set_domainname_test.c

Ticket: ENT-12766
(cherry picked from commit 88e6052728345daa18d9cb59478ea6b8f2771423)
Back-ported from https://github.com/cfengine/core/pull/5656

ENT-12766: Fixed ODR violations in ASAN Unit Tests (3.24.x)

---

tests/acceptance/01_vars/02_functions/findlocalusers.cf
tests/acceptance/01_vars/02_functions/unsafe/findlocalusers_unsafe.cf

The test needs work.
The expected data is not accurate for solaris as well as windows and aix.
Ticket: ENT-12767
Solaris only build: [![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=12071)](https://ci.cfengine.com/job/pr-pipeline/12071/)

Added exception for solaris platform for findlocalusers* tests

---

libenv/sysinfo.c

- **Revert "libenv/sysinfo: Check on lowercase"**
- **Fixed bug in system detection code caused by wrong assumption**

Fixed assertion triggered in OS detection code

---

tests/unit/Makefile.am

For some reason rlist_test fails in AIX unit tests. The test seems to
`abort()` while it should trigger an assert so that
`expect_assert_failure()` can catch it. For some reason this is not
happening anymore.
```
rlist.c:135: Programming Error: Internal error: Rval contains type f instead of expected scalar
```
I created a ticket (CFE-4473) to follow-up on this.
Ticket: None
(cherry picked from commit 67ebf978d4a7feaa089661dfd0f7fea119f22f6c)

Soft fail rlist_test on AIX (3.24)

---

tests/acceptance/05_processes/01_matching/select_without_result.cf

The test_soft_fail ticket was added improperly.
A meta attribute instead of a promisee.
https://docs.cfengine.com/docs/3.24/reference-language-concepts.html
Ticket: CFE-4511
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=12084)](https://ci.cfengine.com/job/pr-pipeline/12084/)

Fixed soft_fail 05_processes/01_matching/select_without_result.cf for windows meta data

---

libpromises/processes_select.c
tests/unit/Makefile.am
tests/unit/processes_select_test.c

- **Fixed bug in parsing process_select for Windows**
Back-ported from https://github.com/cfengine/core/pull/5786

ENT-12751: Fixed bug in parsing process_select for Windows (3.24.x)

---

misc/selinux/cfengine-enterprise.te.all
misc/selinux/cfengine-enterprise.te.el9

http_port is needed in el9, selinux-policy version 38.1.45, for inventory policy common bundles.
getattr for fsadm_exec_t is needed in el9 and getattr for lvm_exec_t is needed in both el8 and el9.
Ticket: ENT-12954
(cherry picked from commit 73ba3b410170f61bad3c1d5b623e8f511a7528ec)
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=12108)](https://ci.cfengine.com/job/pr-pipeline/12108/)
Packages: https://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-12108/

Added http_port and getattr selinux permissions as needed for selinux policy on rhel-8 and rhel-9 (3.21)

---

misc/selinux/cfengine-enterprise.te.all
misc/selinux/cfengine-enterprise.te.el9

http_port is needed in el9, selinux-policy version 38.1.45, for inventory policy common bundles.
getattr for fsadm_exec_t and lvm_exec_t are needed for lib/paths.cf as a common bundle for both rhel-8 selinux-policy 3.14.3 and rhel-9 38.1.45
Ticket: ENT-12954
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=12103)](https://ci.cfengine.com/job/pr-pipeline/12103/) (redhat only build)
https://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-12103/

Added http_port and getattr selinux permissions as needed for selinux policy on rhel-8 and rhel-9

---

misc/selinux/cfengine-enterprise.te.all
misc/selinux/cfengine-enterprise.te.el9

http_port is needed in el9, selinux-policy version 38.1.45, for inventory policy common bundles.
getattr for fsadm_exec_t is needed in el9 and getattr for lvm_exec_t is needed in both el8 and el9.
Ticket: ENT-12954
(cherry picked from commit 73ba3b410170f61bad3c1d5b623e8f511a7528ec)
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=12109)](https://ci.cfengine.com/job/pr-pipeline/12109/)
Packages: https://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-12109/

Added http_port and getattr selinux permissions as needed for selinux policy on rhel-8 and rhel-9 (3.24)

---

misc/changelog-generator/changelog-generator

Fixed syntax error in regex by changing it into a raw string.
```
$ misc/changelog-generator/changelog-generator --repo  3.25.0..master
/home/larsewi/ntech/cfengine/core/misc/changelog-generator/changelog-generator:192: SyntaxWarning: invalid escape sequence '\('
match = re.match("^\(cherry picked from commit ([0-9a-f]+)\)", line, re.IGNORECASE)
```

changelog-generator: Fixed syntax error in regex

---

.github/workflows/stale.yml

I'd like old and inactive PRs to be closed automatically. We have a release checklist to try to go over all open PRs before each release and there's (IMO) too much noise.

Added stale workflow to label and close stale PRs

---

tests/acceptance/testall

```
$ ./tests/acceptance/testall --gdb tests/acceptance/10_files/test.cf
======================================================================
Testsuite started at 2025-05-26 15:18:33
----------------------------------------------------------------------
Total tests: 1
COMMON_TESTS: enabled
TIMED_TESTS: enabled
SLOW_TESTS: enabled
ERROREXIT_TESTS: enabled
SERIAL_TESTS: enabled
NETWORK_TESTS: enabled
LIBXML2_TESTS: enabled
LIBCURL_TESTS: enabled
UNSAFE_TESTS: disabled
STAGING_TESTS: disabled
Test run is not parallel
./tests/acceptance/10_files/test.cf Reading symbols from /home/larsewi/ntech/core/cf-agent/.libs/cf-agent...
(gdb)
```

Don't print license when initiating gdb from testall script

---

examples/isnewerthan.cf
examples/isnewerthantime.cf
libpromises/evalfunction.c
tests/acceptance/02_classes/02_functions/isnewerthantime.cf

corresponding docs PR: https://github.com/cfengine/documentation/pull/3430

CFE-2815: Added `isnewerthantime` function

---

libenv/sysinfo.c
tests/acceptance/01_vars/02_functions/001.cf
tests/acceptance/01_vars/02_functions/002.cf
tests/acceptance/02_classes/01_basic/expected_os_classes.cf

A couple patches for allowing CFEngine to properly identify Manjaro Linux (ArchLinux family) systems.

Manjaro Linux OS proper identification

---

libenv/sysinfo.c

When running the agent on a SLED (SUSE Linux Enterprise Desktop), we get:
```
CFEngine(common)  Operating System not properly recognized, setting sys.os_name_human to "Unknown", please submit a bug report for us to fix this
```
This is caused by the OS detection skipping the `suse` alias on SLED systems.

Define the "suse" class on SLED systems

---

libpromises/evalfunction.c

Ticket: ENT-12732
(cherry picked from commit 2763daf2bc8bcc08c6e8359a98751d40eb104a74)

Fixed whitespace typo in message about Cannot open software_packages.csv (3.21)

---

libenv/sysinfo.c
tests/acceptance/01_vars/02_functions/001.cf
tests/acceptance/01_vars/02_functions/002.cf
tests/acceptance/02_classes/01_basic/expected_os_classes.cf

Back-ported from https://github.com/cfengine/core/pull/5807/

Manjaro Linux proper identification (3.24.x)

---

libenv/sysinfo.c

- **sysinfo.c: Removed trailing whitespace**
- **Define suse class on SLED systems**
Back-ported from https://github.com/cfengine/core/pull/5773/

Define the "suse" class on SLED systems (3.24.x)

---

libenv/sysinfo.c

- **sysinfo.c: Removed trailing whitespace**
- **Define suse class on SLED systems**
Back-ported from https://github.com/cfengine/core/pull/5773

Define the "suse" class on SLED systems (3.21.x)

---

libenv/sysinfo.c

CFE-4536: Fixed file descriptor leak in sys.cpusockets

---

CONTRIBUTING.md

We primarily chat on matrix so include that link.
Clarify Allman-4 and add a link.
Ticket: none

A few minor CONTRIBUTING doc edits

---

cf-agent/files_edit.c
cf-agent/files_edit.h
cf-agent/verify_files.c

- **verify_files.c: Added missing include for cf3.defs.h**
- **files_edit.c: Added missing include for cf3.defs.h**
- **verify_files.c: Removed trailing white space**
- **Properly handle promise locking with edit line**

ENT-9980: Properly handle promise locking with edit line

---

cf-agent/files_edit.c
cf-agent/files_edit.h
cf-agent/verify_files.c

- **verify_files.c: Added missing include for cf3.defs.h**
- **files_edit.c: Added missing include for cf3.defs.h**
- **verify_files.c: Removed trailing white space**
- **Properly handle promise locking with edit line**
Back-ported from https://github.com/cfengine/core/pull/5815

ENT-9980: Properly handle promise locking with edit line (3.24.x)

---

cf-agent/files_edit.c
cf-agent/files_edit.h
cf-agent/verify_files.c

- **verify_files.c: Added missing include for cf3.defs.h**
- **files_edit.c: Added missing include for cf3.defs.h**
- **verify_files.c: Removed trailing white space**
- **Properly handle promise locking with edit line**
Back-ported from https://github.com/cfengine/core/pull/5815

ENT-9980: Properly handle promise locking with edit line (3.21.x)

---

tests/valgrind-check/valgrind.sh

Some build hosts weren't finishing in 30 minutes so see if 40 is enough.
Ticket: ENT-13080

Adjusted valgrind-check auto_destruct timeout from 30m to 40m

---

libpromises/acl_tools.h
libpromises/acl_tools_posix.c
libpromises/evalfunction.c
tests/acceptance/10_files/12_acl/getacls.cf

- **Added policy function to get ACLs**
- **Added acceptance test for getacls()**

CFE-4529: Added policy function getacls()

---

examples/classfilterdata_array_of_arrays.cf
examples/classfilterdata_array_of_objects.cf
libpromises/evalfunction.c
tests/acceptance/01_vars/02_functions/classfilterdata_array_of_arrays_foo.cf
tests/acceptance/01_vars/02_functions/classfilterdata_array_of_arrays_foo_bar.cf
tests/acceptance/01_vars/02_functions/classfilterdata_array_of_objects_foo.cf
tests/acceptance/01_vars/02_functions/classfilterdata_array_of_objects_foo_bar.cf
tests/acceptance/01_vars/02_functions/classfilterdata_collecting.cf

- **evalfunction.c: Removed trailing whitespace**
- **Added policy function classfilterdata()**
- **Added acceptance tests for classfilterdata()**
- **Collecting classfilterdata policy function**
- **Added examples for classfilterdata()**

ENT-6193, CFE-3421: Added policy function classfilterdata()

---

tests/valgrind-check/Containerfile

- **valgrind-check: Fixed missing curl**
- **valgrind-check: fix missing archives**
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=12401)](https://ci.cfengine.com/job/pr-pipeline/12401/)

Fixed static checks (3.21.x)

---

tests/acceptance/plucked.cf.sub

This change simply aligns the implementation of this bundle with what we use for
testing.
CFE-4460

CFE-4460: Aligned testing with implementation of bundle edit_line set_variable_values_ini

---

libpromises/evalfunction.c

Build on Solaris
[![Build Status](https://ci.cfengine.com/buildStatus/icon?job=pr-pipeline&build=12437)](https://ci.cfengine.com/job/pr-pipeline/12437/)

ENT-13146: Fixed compilation error on Solaris 11

---

cf-agent/verify_files.c
tests/acceptance/10_files/unsafe/13_immutable.cf

Fixed a bug where a successful files content promise causes remaining
files promise attribute handling to be skipped.

CFE-4569: Fixed bug where files content promises skips remaining promises

---

libenv/sysinfo.c

On my Gentoo I got:
warning: Operating System not properly recognized, setting sys.os_name_human to "Unknown", please submit a bug report for us to fix this
This patch permit to set sys.os_name_human to Gentoo

Handle sys.os_name_human on gentoo

---

cf-agent/verify_files_utils.c

Remote file copy with the 'copy_from' attribute now only preserves
source file permissions if the 'preserve' attribute in 'body copy_from'
is true. Otherwise it will use the permissions of the destination file
if it already exists and default permissions if it does not.
Ticket: ENT-11988
(cherry picked from commit e2021b555f62197e6a112ee09e5af23ee4a68b6f)
Back ported from https://github.com/cfengine/core/pull/5837

ENT-11988: Fixed bug where remote file copy always preserves source perms (3.24.x)

---

cf-agent/verify_files_utils.c

Remote file copy with the 'copy_from' attribute now only preserves
source file permissions if the 'preserve' attribute in 'body copy_from'
is true. Otherwise it will use the permissions of the destination file
if it already exists and default permissions if it does not.
Ticket: ENT-11988
(cherry picked from commit e2021b555f62197e6a112ee09e5af23ee4a68b6f)
Back ported from https://github.com/cfengine/core/pull/5837

ENT-11988: Fixed bug where remote file copy always preserves source perms (3.21.x)

---

cf-agent/nfs.c

CFE-4494: Fixed CIFS mounts on Linux

---

cf-agent/nfs.c

CFE-4494: Fixed CIFS mounts in filesystem table (3.21)

---

cf-agent/verify_files_utils.c

Temporary file is now set to promised permissions before replacing it
with original during remote copy from.
Ticket: ENT-13163
(cherry picked from commit c1d8cd03137d8c678dbfaf92ba3dd604f4fcc65f)
Back ported from https://github.com/cfengine/core/pull/5868

ENT-13163: Atomic permissions during file copy (3.21.x)

---

cf-agent/verify_files_utils.c

Temporary file is now set to promised permissions before replacing it
with original during remote copy from.
Ticket: ENT-13163
Back ported to:
* https://github.com/cfengine/core/pull/5869
* https://github.com/cfengine/core/pull/5870

ENT-13163: Atomic permissions during file copy

---

libenv/time_classes.c
libenv/time_classes.h
tests/acceptance/01_vars/01_basic/time_based_vars.cf
tests/unit/eval_context_test.c

Merge together https://github.com/cfengine/nova/pull/2448

CFE-4000: Added time based sys variables

---

tests/valgrind-check/Containerfile

Otherwise, the update layer can be cached and have bad information for the subsequent two install command layers.
As the distribution changes package versions the install layers, if they are not cached, will fail.
Also combined the two install commands into one for brevity.
Ticket: ENT-13252

Adjusted valgrind-check Containerfile to ensure apt update and install are linked and cached together in one layer
